-- ============================================================
-- Petty Cash Module — Table DDL
-- File: database/pc/01_pc_tables.sql
-- Run order: 1st
-- ============================================================

-- ============================================================
-- 1. RR_PC_REGISTERS  (Petty Cash Register Header)
-- ============================================================
CREATE TABLE RR_PC_REGISTERS (
    REGISTER_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGISTER_NAME       VARCHAR2(200)  NOT NULL,
    START_DATE          DATE,
    END_DATE            DATE,
    COMMENTS            VARCHAR2(1000),
    CASH_ACCOUNT_CCID   NUMBER,                       -- FK → REERP_GL_CODE_COMBINATIONS
    CASH_ACCOUNT_DESC   VARCHAR2(400),                -- denormalised segment string
    CURRENCY            VARCHAR2(10)   DEFAULT 'AED',
    STATUS              VARCHAR2(50)   DEFAULT 'ACTIVE',  -- ACTIVE | CLOSED
    CREATED_BY          VARCHAR2(150),
    CREATION_DATE       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(150),
    LAST_UPDATE_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_PC_REG_STATUS_CK  CHECK (STATUS IN ('ACTIVE','CLOSED')),
    CONSTRAINT RR_PC_REG_NAME_UK    UNIQUE (REGISTER_NAME)
);

CREATE INDEX IDX_RR_PC_REG_STATUS ON RR_PC_REGISTERS(STATUS);
CREATE INDEX IDX_RR_PC_REG_DATES  ON RR_PC_REGISTERS(START_DATE, END_DATE);

COMMENT ON TABLE  RR_PC_REGISTERS                     IS 'Petty cash register headers';
COMMENT ON COLUMN RR_PC_REGISTERS.CASH_ACCOUNT_CCID   IS 'GL code combination ID for the petty cash GL account';
COMMENT ON COLUMN RR_PC_REGISTERS.STATUS               IS 'ACTIVE = open for transactions; CLOSED = read-only';

-- ============================================================
-- 2. RR_PC_TRANSACTIONS  (Petty Cash Lines)
-- ============================================================
CREATE TABLE RR_PC_TRANSACTIONS (
    TRANSACTION_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGISTER_ID         NUMBER        NOT NULL,
    LINE_NUMBER         NUMBER,                        -- sequence within register
    TRANSACTION_DATE    DATE          NOT NULL,
    TRANSACTION_TYPE      VARCHAR2(100) NOT NULL,        -- 'Balance Refill' | 'Expense' | 'Adjustment'
    EXPENSE_TYPE          VARCHAR2(200),                 -- populated for Expense lines
    CHARGE_ACCOUNT_CCID   NUMBER,                        -- GL code combination for charge account
    CHARGE_ACCOUNT_DESC   VARCHAR2(400),                 -- denormalised segment string
    ACCOUNTING_DATE       DATE,                          -- GL accounting date
    POSTING_STATUS        VARCHAR2(50) DEFAULT 'Unposted', -- Unposted | Posted | Error
    CURRENCY              VARCHAR2(10)  DEFAULT 'AED',
    DEBIT_AMOUNT          NUMBER(18,2)  DEFAULT 0,       -- money IN  (Add Money)
    CREDIT_AMOUNT         NUMBER(18,2)  DEFAULT 0,       -- money OUT (Add Expense)
    COMMENTS              VARCHAR2(1000),
    REFERENCE_NO          VARCHAR2(200),
    ATTACHMENT            VARCHAR2(1000),
    CREATED_BY            VARCHAR2(150),
    CREATION_DATE         TIMESTAMP    DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY       VARCHAR2(150),
    LAST_UPDATE_DATE      TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_PC_TXN_REG_FK      FOREIGN KEY (REGISTER_ID) REFERENCES RR_PC_REGISTERS(REGISTER_ID),
    CONSTRAINT RR_PC_TXN_TYPE_CK     CHECK (TRANSACTION_TYPE IN ('Balance Refill','Expense','Adjustment')),
    CONSTRAINT RR_PC_TXN_POSTING_CK  CHECK (POSTING_STATUS IN ('Unposted','Posted','Error')),
    CONSTRAINT RR_PC_TXN_DEBIT_CK    CHECK (DEBIT_AMOUNT  >= 0),
    CONSTRAINT RR_PC_TXN_CREDIT_CK   CHECK (CREDIT_AMOUNT >= 0)
);

CREATE INDEX IDX_RR_PC_TXN_REG    ON RR_PC_TRANSACTIONS(REGISTER_ID);
CREATE INDEX IDX_RR_PC_TXN_DATE   ON RR_PC_TRANSACTIONS(TRANSACTION_DATE);
CREATE INDEX IDX_RR_PC_TXN_TYPE   ON RR_PC_TRANSACTIONS(TRANSACTION_TYPE);

COMMENT ON TABLE  RR_PC_TRANSACTIONS                          IS 'Petty cash transaction lines — debits (money in) and credits (expenses out)';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.DEBIT_AMOUNT              IS 'Cash received into petty cash (Balance Refill / Adjustment)';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.CREDIT_AMOUNT             IS 'Cash paid out (Expense)';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.LINE_NUMBER               IS 'Auto-assigned sequential line number per register';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.CHARGE_ACCOUNT_CCID       IS 'GL code combination ID for the expense charge account';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.CHARGE_ACCOUNT_DESC       IS 'Denormalised segment string for the charge account';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.ACCOUNTING_DATE           IS 'GL accounting date — may differ from transaction date';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.POSTING_STATUS            IS 'Unposted = not yet posted to GL; Posted = transferred; Error = posting failed';

-- ============================================================
-- 3. Alter RR_EXTERNAL_CASH_TRANSACTIONS — add REGISTER_ID
--    (Add Money links an external transaction to a register)
-- ============================================================
DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count
    FROM   user_tab_columns
    WHERE  table_name  = 'RR_EXTERNAL_CASH_TRANSACTIONS'
    AND    column_name = 'REGISTER_ID';

    IF l_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE RR_EXTERNAL_CASH_TRANSACTIONS
            ADD (REGISTER_ID NUMBER)
        ';
    END IF;
END;
/

-- ============================================================
-- 4. Sequences  (safety — IDENTITY handles it, but useful for PKG)
-- ============================================================
DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_sequences WHERE sequence_name = 'RR_PC_REGISTERS_SEQ';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE RR_PC_REGISTERS_SEQ START WITH 1001 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_sequences WHERE sequence_name = 'RR_PC_TRANSACTIONS_SEQ';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE RR_PC_TRANSACTIONS_SEQ START WITH 1001 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
