-- ============================================================
-- Petty Cash Module — Table DDL  (idempotent — safe to re-run)
-- File: database/pc/01_pc_tables.sql
-- Run order: 1st
-- ============================================================

-- ============================================================
-- 1. RR_PC_REGISTERS  (Petty Cash Register Header)
-- ============================================================
DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'RR_PC_REGISTERS';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PC_REGISTERS (
    REGISTER_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGISTER_NAME       VARCHAR2(200)  NOT NULL,
    BUSINESS_UNIT       VARCHAR2(240)  NOT NULL,
    START_DATE          DATE,
    END_DATE            DATE,
    COMMENTS            VARCHAR2(1000),
    CASH_ACCOUNT_CCID   NUMBER,
    CASH_ACCOUNT_DESC   VARCHAR2(400),
    CURRENCY            VARCHAR2(10)   DEFAULT 'AED',
    STATUS              VARCHAR2(50)   DEFAULT 'DRAFT',
    CREATED_BY          VARCHAR2(150),
    CREATION_DATE       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(150),
    LAST_UPDATE_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_PC_REG_STATUS_CK  CHECK (STATUS IN ('DRAFT','ACTIVE','INACTIVE','CLOSED')),
    CONSTRAINT RR_PC_REG_NAME_UK    UNIQUE (REGISTER_NAME)
)]';
    END IF;
END;
/

-- Indexes
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'IDX_RR_PC_REG_STATUS';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_RR_PC_REG_STATUS ON RR_PC_REGISTERS(STATUS)';
    END IF;
END;
/

DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'IDX_RR_PC_REG_DATES';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_RR_PC_REG_DATES ON RR_PC_REGISTERS(START_DATE, END_DATE)';
    END IF;
END;
/

COMMENT ON TABLE  RR_PC_REGISTERS                   IS 'Petty cash register headers';
COMMENT ON COLUMN RR_PC_REGISTERS.BUSINESS_UNIT     IS 'Oracle Fusion Business Unit that owns this petty cash register';
COMMENT ON COLUMN RR_PC_REGISTERS.CASH_ACCOUNT_CCID IS 'GL code combination ID for the petty cash GL account';
COMMENT ON COLUMN RR_PC_REGISTERS.STATUS            IS 'DRAFT = setup; ACTIVE = open for transactions; INACTIVE = closed (balance must be 0); CLOSED = legacy';

-- Safe: add BUSINESS_UNIT if missing (older installs)
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_REGISTERS' AND column_name = 'BUSINESS_UNIT';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_REGISTERS ADD (BUSINESS_UNIT VARCHAR2(240))';
    END IF;
END;
/

-- Safe: add OWNED_BY if missing
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_REGISTERS' AND column_name = 'OWNED_BY';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_REGISTERS ADD (OWNED_BY VARCHAR2(240))';
    END IF;
END;
/

-- Safe: add CASH_LIMIT if missing
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_REGISTERS' AND column_name = 'CASH_LIMIT';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_REGISTERS ADD (CASH_LIMIT NUMBER(18,2))';
    END IF;
END;
/

COMMENT ON COLUMN RR_PC_REGISTERS.OWNED_BY   IS 'Person or department responsible for this petty cash register';
COMMENT ON COLUMN RR_PC_REGISTERS.CASH_LIMIT IS 'Maximum allowed balance / spending limit for this register';

-- Safe: update STATUS constraint to DRAFT | ACTIVE | INACTIVE | CLOSED
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_constraints
    WHERE  table_name = 'RR_PC_REGISTERS' AND constraint_name = 'RR_PC_REG_STATUS_CK';
    IF l_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_REGISTERS DROP CONSTRAINT RR_PC_REG_STATUS_CK';
    END IF;
    EXECUTE IMMEDIATE q'[ALTER TABLE RR_PC_REGISTERS ADD CONSTRAINT RR_PC_REG_STATUS_CK CHECK (STATUS IN ('DRAFT','ACTIVE','INACTIVE','CLOSED'))]';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================
-- 2. RR_PC_TRANSACTIONS  (Petty Cash Lines)
-- ============================================================
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tables WHERE table_name = 'RR_PC_TRANSACTIONS';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE q'[
CREATE TABLE RR_PC_TRANSACTIONS (
    TRANSACTION_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGISTER_ID         NUMBER        NOT NULL,
    LINE_NUMBER         NUMBER,
    TRANSACTION_DATE    DATE          NOT NULL,
    TRANSACTION_TYPE    VARCHAR2(100) NOT NULL,
    EXPENSE_TYPE        VARCHAR2(200),
    CHARGE_ACCOUNT_CCID NUMBER,
    CHARGE_ACCOUNT_DESC VARCHAR2(400),
    ACCOUNTING_DATE     DATE,
    POSTING_STATUS      VARCHAR2(50)  DEFAULT 'Unposted',
    CURRENCY            VARCHAR2(10)  DEFAULT 'AED',
    DEBIT_AMOUNT        NUMBER(18,2)  DEFAULT 0,
    CREDIT_AMOUNT       NUMBER(18,2)  DEFAULT 0,
    COMMENTS            VARCHAR2(1000),
    REFERENCE_NO        VARCHAR2(200),
    ATTACHMENT          VARCHAR2(1000),
    CREATED_BY          VARCHAR2(150),
    CREATION_DATE       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(150),
    LAST_UPDATE_DATE    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_PC_TXN_REG_FK      FOREIGN KEY (REGISTER_ID) REFERENCES RR_PC_REGISTERS(REGISTER_ID),
    CONSTRAINT RR_PC_TXN_TYPE_CK     CHECK (TRANSACTION_TYPE IN ('Balance Refill','Expense','Adjustment')),
    CONSTRAINT RR_PC_TXN_POSTING_CK  CHECK (POSTING_STATUS   IN ('Unposted','Posted','Error')),
    CONSTRAINT RR_PC_TXN_DEBIT_CK    CHECK (DEBIT_AMOUNT  >= 0),
    CONSTRAINT RR_PC_TXN_CREDIT_CK   CHECK (CREDIT_AMOUNT >= 0)
)]';
    END IF;
END;
/

-- Indexes
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'IDX_RR_PC_TXN_REG';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_RR_PC_TXN_REG ON RR_PC_TRANSACTIONS(REGISTER_ID)';
    END IF;
END;
/

DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'IDX_RR_PC_TXN_DATE';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_RR_PC_TXN_DATE ON RR_PC_TRANSACTIONS(TRANSACTION_DATE)';
    END IF;
END;
/

DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_indexes WHERE index_name = 'IDX_RR_PC_TXN_TYPE';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_RR_PC_TXN_TYPE ON RR_PC_TRANSACTIONS(TRANSACTION_TYPE)';
    END IF;
END;
/

COMMENT ON TABLE  RR_PC_TRANSACTIONS                         IS 'Petty cash transaction lines — debits (money in) and credits (expenses out)';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.DEBIT_AMOUNT            IS 'Cash received into petty cash (Balance Refill / Adjustment)';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.CREDIT_AMOUNT           IS 'Cash paid out (Expense)';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.LINE_NUMBER             IS 'Auto-assigned sequential line number per register';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.CHARGE_ACCOUNT_CCID    IS 'GL code combination ID for the expense charge account';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.CHARGE_ACCOUNT_DESC    IS 'Denormalised segment string for the charge account';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.ACCOUNTING_DATE        IS 'GL accounting date — may differ from transaction date';
COMMENT ON COLUMN RR_PC_TRANSACTIONS.POSTING_STATUS         IS 'Unposted = not yet posted to GL; Posted = transferred; Error = posting failed';

-- ============================================================
-- 3. Alter RR_EXTERNAL_CASH_TRANSACTIONS — add REGISTER_ID
-- ============================================================
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name  = 'RR_EXTERNAL_CASH_TRANSACTIONS'
    AND    column_name = 'REGISTER_ID';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_EXTERNAL_CASH_TRANSACTIONS ADD (REGISTER_ID NUMBER)';
    END IF;
END;
/

-- ============================================================
-- 4. Sequences
-- ============================================================
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_sequences WHERE sequence_name = 'RR_PC_REGISTERS_SEQ';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE RR_PC_REGISTERS_SEQ START WITH 1001 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_TRANSACTIONS' AND column_name = 'ACCOUNTING_PERIOD';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_TRANSACTIONS ADD (ACCOUNTING_PERIOD VARCHAR2(30))';
    END IF;
END;
/


-- ============================================================
-- Add BANK_TXN_ID to RR_PC_TRANSACTIONS (idempotent)
-- Links a Balance Refill to an external bank transaction
-- ============================================================
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_TRANSACTIONS' AND column_name = 'BANK_TXN_ID';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_TRANSACTIONS ADD (BANK_TXN_ID NUMBER)';
    END IF;
END;
/

-- ============================================================
-- Add EMPLOYEE_NAME, RECEIPT_STATUS, ATTACHMENT_DATA (idempotent)
-- ============================================================
DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_TRANSACTIONS' AND column_name = 'EMPLOYEE_NAME';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_TRANSACTIONS ADD (EMPLOYEE_NAME VARCHAR2(200))';
    END IF;
END;
/

DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_TRANSACTIONS' AND column_name = 'RECEIPT_STATUS';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_TRANSACTIONS ADD (RECEIPT_STATUS VARCHAR2(3))';
    END IF;
END;
/

DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE  table_name = 'RR_PC_TRANSACTIONS' AND column_name = 'ATTACHMENT_DATA';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_PC_TRANSACTIONS ADD (ATTACHMENT_DATA CLOB)';
    END IF;
END;
/
