-- ============================================================
-- Petty Cash Module — Attachments Table + ORDS Handlers
-- File: database/pc/07_pc_attachments.sql
-- Run order: 7th (after 06_pc_transfer.sql)
-- ============================================================
-- Changes:
--   1. Create RR_PC_ATTACHMENTS table (idempotent)
--   2. Create RR_PC_ATTACH_PKG (add / delete procedures)
--   3. Redefine GET /pc/registers/:registerId/transactions
--      to include attachmentCount subquery
--   4. New ORDS templates + handlers:
--        POST   /pc/attachments
--        GET    /pc/attachments          (?transactionId=X or ?registerId=X&referenceNo=Y)
--        GET    /pc/attachments/:attachmentId
--        DELETE /pc/attachments/:attachmentId
-- ============================================================

-- ── 1. Create RR_PC_ATTACHMENTS table ────────────────────────
DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_exists
    FROM   user_tables
    WHERE  table_name = 'RR_PC_ATTACHMENTS';

    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE RR_PC_ATTACHMENTS (
                ATTACHMENT_ID   NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                REGISTER_ID     NUMBER          NOT NULL,
                TRANSACTION_ID  NUMBER,
                REFERENCE_NO    VARCHAR2(100),
                FILE_NAME       VARCHAR2(500)   NOT NULL,
                FILE_DATA       CLOB            NOT NULL,
                MIME_TYPE       VARCHAR2(200),
                CREATED_BY      VARCHAR2(100),
                CREATION_DATE   DATE            DEFAULT SYSDATE,
                CONSTRAINT RR_PC_ATTACH_REG_FK FOREIGN KEY (REGISTER_ID)
                    REFERENCES RR_PC_REGISTERS(REGISTER_ID),
                CONSTRAINT RR_PC_ATTACH_TXN_FK FOREIGN KEY (TRANSACTION_ID)
                    REFERENCES RR_PC_TRANSACTIONS(TRANSACTION_ID) ON DELETE CASCADE
            )
        ]';

        EXECUTE IMMEDIATE 'CREATE INDEX RR_PC_ATTACH_TXN_IDX     ON RR_PC_ATTACHMENTS (TRANSACTION_ID)';
        EXECUTE IMMEDIATE 'CREATE INDEX RR_PC_ATTACH_REG_REF_IDX ON RR_PC_ATTACHMENTS (REGISTER_ID, REFERENCE_NO)';
    END IF;
END;
/

-- ── 2. RR_PC_ATTACH_PKG — package spec ───────────────────────
CREATE OR REPLACE PACKAGE RR_PC_ATTACH_PKG AS

    PROCEDURE add_attachment(
        p_json    IN  CLOB,
        p_id      OUT NUMBER,
        p_error   OUT VARCHAR2
    );

    PROCEDURE delete_attachment(
        p_attachment_id IN  NUMBER,
        p_rows          OUT NUMBER,
        p_error         OUT VARCHAR2
    );

END RR_PC_ATTACH_PKG;
/

-- ── 3. RR_PC_ATTACH_PKG — package body ───────────────────────
CREATE OR REPLACE PACKAGE BODY RR_PC_ATTACH_PKG AS

    -- ──────────────────────────────────────────────────────────
    -- add_attachment
    -- JSON body: { registerId, transactionId?, referenceNo?,
    --              fileName, fileData (base64), mimeType?, createdBy? }
    -- ──────────────────────────────────────────────────────────
    PROCEDURE add_attachment(
        p_json    IN  CLOB,
        p_id      OUT NUMBER,
        p_error   OUT VARCHAR2
    ) IS
        l_register_id  NUMBER;
        l_txn_id       NUMBER;
        l_ref_no       VARCHAR2(100);
        l_file_name    VARCHAR2(500);
        l_file_data    CLOB;
        l_mime_type    VARCHAR2(200);
        l_created_by   VARCHAR2(100);
    BEGIN
        -- Use JSON_TABLE to extract all fields including CLOB fileData
        SELECT j.register_id,
               j.txn_id,
               j.ref_no,
               j.file_name,
               j.file_data,
               j.mime_type,
               j.created_by
        INTO   l_register_id,
               l_txn_id,
               l_ref_no,
               l_file_name,
               l_file_data,
               l_mime_type,
               l_created_by
        FROM   JSON_TABLE(p_json FORMAT JSON, '$' COLUMNS (
                   register_id  NUMBER        PATH '$.registerId',
                   txn_id       NUMBER        PATH '$.transactionId',
                   ref_no       VARCHAR2(100) PATH '$.referenceNo',
                   file_name    VARCHAR2(500) PATH '$.fileName',
                   file_data    CLOB          PATH '$.fileData',
                   mime_type    VARCHAR2(200) PATH '$.mimeType',
                   created_by   VARCHAR2(100) PATH '$.createdBy'
               )) j;

        IF l_register_id IS NULL THEN
            p_error := 'BLOCKED:registerId is required';
            RETURN;
        END IF;
        IF l_file_name IS NULL OR l_file_data IS NULL THEN
            p_error := 'BLOCKED:fileName and fileData are required';
            RETURN;
        END IF;

        INSERT INTO RR_PC_ATTACHMENTS (
            REGISTER_ID, TRANSACTION_ID, REFERENCE_NO,
            FILE_NAME, FILE_DATA, MIME_TYPE, CREATED_BY, CREATION_DATE
        ) VALUES (
            l_register_id, l_txn_id, l_ref_no,
            l_file_name, l_file_data, l_mime_type,
            NVL(l_created_by, 'SYSTEM'), SYSDATE
        )
        RETURNING ATTACHMENT_ID INTO p_id;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_error := SQLERRM;
    END add_attachment;

    -- ──────────────────────────────────────────────────────────
    -- delete_attachment
    -- ──────────────────────────────────────────────────────────
    PROCEDURE delete_attachment(
        p_attachment_id IN  NUMBER,
        p_rows          OUT NUMBER,
        p_error         OUT VARCHAR2
    ) IS
    BEGIN
        DELETE FROM RR_PC_ATTACHMENTS
        WHERE  ATTACHMENT_ID = p_attachment_id;
        p_rows := SQL%ROWCOUNT;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_error := SQLERRM;
    END delete_attachment;

END RR_PC_ATTACH_PKG;
/

-- ── 4. Redefine GET /pc/registers/:registerId/transactions ───
--    Adds attachmentCount. HAS_ATTACHMENT computed (not a real column).
--    EMPLOYEE_NAME, RECEIPT_STATUS, BANK_TXN_ID included if they exist.
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name => 'pc',
        p_pattern     => 'registers/:registerId/transactions',
        p_method      => 'GET',
        p_source_type => ORDS.source_type_plsql,
        p_source      => '
DECLARE
    v_clob CLOB;
    CURSOR c IS
        SELECT t.TRANSACTION_ID,
               t.REGISTER_ID,
               t.LINE_NUMBER,
               t.TRANSACTION_DATE,
               t.TRANSACTION_TYPE,
               t.EXPENSE_TYPE,
               t.CHARGE_ACCOUNT_CCID,
               t.CHARGE_ACCOUNT_DESC,
               t.ACCOUNTING_DATE,
               t.ACCOUNTING_PERIOD,
               t.POSTING_STATUS,
               t.CURRENCY,
               t.DEBIT_AMOUNT,
               t.CREDIT_AMOUNT,
               t.COMMENTS,
               t.REFERENCE_NO,
               t.ATTACHMENT,
               CASE WHEN t.ATTACHMENT IS NOT NULL THEN ''Y'' ELSE ''N'' END AS HAS_ATTACHMENT,
               t.EMPLOYEE_NAME,
               t.RECEIPT_STATUS,
               t.BANK_TXN_ID,
               t.CREATED_BY,
               t.CREATION_DATE,
               SUM(t.DEBIT_AMOUNT - t.CREDIT_AMOUNT) OVER (
                   PARTITION BY t.REGISTER_ID
                   ORDER BY t.TRANSACTION_DATE, t.LINE_NUMBER
                   ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
               ) AS RUNNING_BALANCE,
               (SELECT COUNT(*) FROM RR_PC_ATTACHMENTS a
                WHERE  a.TRANSACTION_ID = t.TRANSACTION_ID) AS ATTACHMENT_COUNT
        FROM   RR_PC_TRANSACTIONS t
        WHERE  t.REGISTER_ID = :registerId
        ORDER BY t.TRANSACTION_DATE, t.LINE_NUMBER;
BEGIN
    :status_code := 200;
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE(''success'', TRUE);
    APEX_JSON.OPEN_ARRAY(''items'');
    FOR rec IN c LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE(''transactionId'',    rec.TRANSACTION_ID);
        APEX_JSON.WRITE(''registerId'',       rec.REGISTER_ID);
        APEX_JSON.WRITE(''lineNumber'',       rec.LINE_NUMBER);
        APEX_JSON.WRITE(''transactionDate'',  TO_CHAR(rec.TRANSACTION_DATE, ''DD-MON-YYYY''));
        APEX_JSON.WRITE(''transactionType'',  rec.TRANSACTION_TYPE);
        APEX_JSON.WRITE(''expenseType'',      rec.EXPENSE_TYPE);
        APEX_JSON.WRITE(''chargeAccountCcid'',rec.CHARGE_ACCOUNT_CCID);
        APEX_JSON.WRITE(''chargeAccountDesc'',rec.CHARGE_ACCOUNT_DESC);
        APEX_JSON.WRITE(''accountingDate'',   TO_CHAR(rec.ACCOUNTING_DATE,  ''DD-MON-YYYY''));
        APEX_JSON.WRITE(''accountingPeriod'', rec.ACCOUNTING_PERIOD);
        APEX_JSON.WRITE(''postingStatus'',    rec.POSTING_STATUS);
        APEX_JSON.WRITE(''currency'',         NVL(rec.CURRENCY, ''AED''));
        APEX_JSON.WRITE(''debitAmount'',      rec.DEBIT_AMOUNT);
        APEX_JSON.WRITE(''creditAmount'',     rec.CREDIT_AMOUNT);
        APEX_JSON.WRITE(''comments'',         rec.COMMENTS);
        APEX_JSON.WRITE(''referenceNo'',      rec.REFERENCE_NO);
        APEX_JSON.WRITE(''attachment'',       rec.ATTACHMENT);
        APEX_JSON.WRITE(''hasAttachment'',    rec.HAS_ATTACHMENT);
        APEX_JSON.WRITE(''employeeName'',     rec.EMPLOYEE_NAME);
        APEX_JSON.WRITE(''receiptStatus'',    rec.RECEIPT_STATUS);
        APEX_JSON.WRITE(''bankTxnId'',        rec.BANK_TXN_ID);
        APEX_JSON.WRITE(''createdBy'',        rec.CREATED_BY);
        APEX_JSON.WRITE(''creationDate'',     TO_CHAR(rec.CREATION_DATE, ''DD-MON-YYYY''));
        APEX_JSON.WRITE(''runningBalance'',   rec.RUNNING_BALANCE);
        APEX_JSON.WRITE(''attachmentCount'',  rec.ATTACHMENT_COUNT);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    v_clob := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    HTP.PRN(v_clob);
END;
'
    );

    -- ── 5. New template: /pc/attachments ──────────────────────
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'pc',
        p_pattern     => 'attachments'
    );

    -- POST /pc/attachments  →  RR_PC_ATTACH_PKG.add_attachment
    -- Body: { registerId, transactionId?, referenceNo?,
    --         fileName, fileData (base64), mimeType?, createdBy? }
    ORDS.DEFINE_HANDLER(
        p_module_name => 'pc',
        p_pattern     => 'attachments',
        p_method      => 'POST',
        p_source_type => ORDS.source_type_plsql,
        p_source      => '
DECLARE
    l_id  NUMBER;
    l_err VARCHAR2(4000);
BEGIN
    RR_PC_ATTACH_PKG.add_attachment(
        p_json  => :body_text,
        p_id    => l_id,
        p_error => l_err
    );
    IF l_err LIKE ''BLOCKED:%'' THEN
        :status_code := 400;
        HTP.PRN(''{"success":false,"message":'' || APEX_JSON.STRINGIFY(REPLACE(l_err,''BLOCKED:'','''')) || ''}'');
    ELSIF l_err IS NOT NULL THEN
        :status_code := 500;
        HTP.PRN(''{"success":false,"message":'' || APEX_JSON.STRINGIFY(l_err) || ''}'');
    ELSE
        :status_code := 201;
        HTP.PRN(''{"success":true,"attachmentId":'' || l_id || '',"message":"Attachment saved"}'');
    END IF;
END;
'
    );

    -- GET /pc/attachments?transactionId=X  (list, no file data)
    --   or ?registerId=X&referenceNo=Y
    ORDS.DEFINE_HANDLER(
        p_module_name => 'pc',
        p_pattern     => 'attachments',
        p_method      => 'GET',
        p_source_type => ORDS.source_type_plsql,
        p_source      => '
DECLARE
    v_clob  CLOB;
    v_count PLS_INTEGER := 0;
BEGIN
    IF :transactionId IS NULL AND :registerId IS NULL AND :referenceNo IS NULL THEN
        :status_code := 400;
        HTP.PRN(''{"success":false,"message":"At least one filter parameter required"}'');
        RETURN;
    END IF;

    :status_code := 200;
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE(''success'', TRUE);
    APEX_JSON.OPEN_ARRAY(''items'');

    FOR rec IN (
        SELECT ATTACHMENT_ID, REGISTER_ID, TRANSACTION_ID, REFERENCE_NO,
               FILE_NAME, MIME_TYPE, CREATED_BY,
               TO_CHAR(CREATION_DATE, ''YYYY-MM-DD"T"HH24:MI:SS'') AS CREATION_DATE
        FROM   RR_PC_ATTACHMENTS
        WHERE  (:transactionId IS NOT NULL AND TRANSACTION_ID = :transactionId)
           OR  (:transactionId IS NULL
                AND (:registerId  IS NULL OR REGISTER_ID  = :registerId)
                AND (:referenceNo IS NULL OR REFERENCE_NO = :referenceNo))
        ORDER BY CREATION_DATE, ATTACHMENT_ID
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE(''attachmentId'',  rec.ATTACHMENT_ID);
        APEX_JSON.WRITE(''registerId'',    rec.REGISTER_ID);
        APEX_JSON.WRITE(''transactionId'', rec.TRANSACTION_ID);
        APEX_JSON.WRITE(''referenceNo'',   rec.REFERENCE_NO);
        APEX_JSON.WRITE(''fileName'',      rec.FILE_NAME);
        APEX_JSON.WRITE(''mimeType'',      rec.MIME_TYPE);
        APEX_JSON.WRITE(''createdBy'',     rec.CREATED_BY);
        APEX_JSON.WRITE(''creationDate'',  rec.CREATION_DATE);
        APEX_JSON.CLOSE_OBJECT;
        v_count := v_count + 1;
    END LOOP;

    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.WRITE(''count'', v_count);
    APEX_JSON.CLOSE_OBJECT;

    v_clob := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    HTP.PRN(v_clob);

EXCEPTION
    WHEN OTHERS THEN
        BEGIN APEX_JSON.FREE_OUTPUT; EXCEPTION WHEN OTHERS THEN NULL; END;
        :status_code := 500;
        HTP.PRN(''{"success":false,"message":''
             || APEX_JSON.STRINGIFY(''Error: '' || SQLERRM)
             || ''}'');
END;
'
    );

    -- ── 6. New template: /pc/attachments/:attachmentId ────────
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'pc',
        p_pattern     => 'attachments/:attachmentId'
    );

    -- GET /pc/attachments/:attachmentId  (single, includes fileData)
    ORDS.DEFINE_HANDLER(
        p_module_name => 'pc',
        p_pattern     => 'attachments/:attachmentId',
        p_method      => 'GET',
        p_source_type => ORDS.source_type_plsql,
        p_source      => '
DECLARE
    v_clob          CLOB;
    l_attachment_id NUMBER;
    l_register_id   NUMBER;
    l_txn_id        NUMBER;
    l_ref_no        VARCHAR2(100);
    l_file_name     VARCHAR2(500);
    l_file_data     CLOB;
    l_mime_type     VARCHAR2(200);
    l_created_by    VARCHAR2(100);
    l_created_date  DATE;
BEGIN
    SELECT ATTACHMENT_ID, REGISTER_ID, TRANSACTION_ID, REFERENCE_NO,
           FILE_NAME, FILE_DATA, MIME_TYPE, CREATED_BY, CREATION_DATE
    INTO   l_attachment_id, l_register_id, l_txn_id, l_ref_no,
           l_file_name, l_file_data, l_mime_type, l_created_by, l_created_date
    FROM   RR_PC_ATTACHMENTS
    WHERE  ATTACHMENT_ID = :attachmentId;

    :status_code := 200;
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE(''success'',       TRUE);
    APEX_JSON.WRITE(''attachmentId'',  l_attachment_id);
    APEX_JSON.WRITE(''registerId'',    l_register_id);
    APEX_JSON.WRITE(''transactionId'', l_txn_id);
    APEX_JSON.WRITE(''referenceNo'',   l_ref_no);
    APEX_JSON.WRITE(''fileName'',      l_file_name);
    APEX_JSON.WRITE(''mimeType'',      l_mime_type);
    APEX_JSON.WRITE(''createdBy'',     l_created_by);
    APEX_JSON.WRITE(''creationDate'',  TO_CHAR(l_created_date, ''DD-MON-YYYY''));
    APEX_JSON.WRITE(''fileData'',      l_file_data);
    APEX_JSON.CLOSE_OBJECT;
    v_clob := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    HTP.PRN(v_clob);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        :status_code := 404;
        HTP.PRN(''{"success":false,"message":"Attachment not found"}'');
END;
'
    );

    -- DELETE /pc/attachments/:attachmentId
    ORDS.DEFINE_HANDLER(
        p_module_name => 'pc',
        p_pattern     => 'attachments/:attachmentId',
        p_method      => 'DELETE',
        p_source_type => ORDS.source_type_plsql,
        p_source      => '
DECLARE
    l_rows NUMBER;
    l_err  VARCHAR2(4000);
BEGIN
    RR_PC_ATTACH_PKG.delete_attachment(
        p_attachment_id => :attachmentId,
        p_rows          => l_rows,
        p_error         => l_err
    );
    IF l_err IS NOT NULL THEN
        :status_code := 500;
        HTP.PRN(''{"success":false,"message":'' || APEX_JSON.STRINGIFY(l_err) || ''}'');
    ELSIF l_rows = 0 THEN
        :status_code := 404;
        HTP.PRN(''{"success":false,"message":"Attachment not found"}'');
    ELSE
        :status_code := 200;
        HTP.PRN(''{"success":true,"message":"Attachment deleted"}'');
    END IF;
END;
'
    );

    COMMIT;
END;
/
