-- ============================================================
-- Table: RR_BANK_TRANSFER_ATTACHMENTS
-- Stores file attachments for bank account transfers
-- No FK to bank transfers table (transfers may be Oracle-sourced)
-- ============================================================

CREATE TABLE RR_BANK_TRANSFER_ATTACHMENTS (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BANK_ACCOUNT_TRANSFER_ID NUMBER NOT NULL,
    FILE_NAME               VARCHAR2(500) NOT NULL,
    FILE_TYPE               VARCHAR2(100),
    FILE_SIZE               NUMBER,
    FILE_CONTENT            CLOB,  -- Base64-encoded file content
    CREATED_BY              VARCHAR2(150),
    CREATED_DATE            TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_RR_BTA_TRF_ID ON RR_BANK_TRANSFER_ATTACHMENTS(BANK_ACCOUNT_TRANSFER_ID);

-- ============================================================
-- ORDS: GET /cash/banktransfers/:transferId/attachments
-- ============================================================
BEGIN
    ORDS.DELETE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/banktransfers/:transferId/attachments'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/banktransfers/:transferId/attachments',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => 'Attachments for a bank account transfer'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/banktransfers/:transferId/attachments',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'List attachments for a bank transfer',
        p_source         => q'[
DECLARE
    l_json CLOB := '{"items":[';
    l_first BOOLEAN := TRUE;
BEGIN
    FOR r IN (
        SELECT ID, FILE_NAME, FILE_TYPE, FILE_SIZE, CREATED_BY,
               TO_CHAR(CREATED_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS CREATED_DATE
          FROM RR_BANK_TRANSFER_ATTACHMENTS
         WHERE BANK_ACCOUNT_TRANSFER_ID = :transferId
         ORDER BY CREATED_DATE DESC
    ) LOOP
        IF NOT l_first THEN l_json := l_json || ','; END IF;
        l_first := FALSE;
        l_json := l_json
            || '{"id":' || r.ID
            || ',"fileName":' || APEX_JSON.STRINGIFY(r.FILE_NAME)
            || ',"fileType":' || APEX_JSON.STRINGIFY(NVL(r.FILE_TYPE,''))
            || ',"fileSize":' || NVL(TO_CHAR(r.FILE_SIZE),'null')
            || ',"createdBy":' || APEX_JSON.STRINGIFY(NVL(r.CREATED_BY,''))
            || ',"createdDate":' || APEX_JSON.STRINGIFY(NVL(r.CREATED_DATE,''))
            || '}';
    END LOOP;
    l_json := l_json || ']}';
    HTP.P(l_json);
EXCEPTION WHEN OTHERS THEN
    HTP.P('{"items":[],"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ============================================================
-- ORDS: POST /cash/banktransfers/:transferId/attachments
-- ============================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/banktransfers/:transferId/attachments',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Upload attachment for a bank transfer',
        p_source         => q'[
DECLARE
    v_file_name  VARCHAR2(500);
    v_file_type  VARCHAR2(100);
    v_file_size  NUMBER;
    v_content    CLOB;
    v_created_by VARCHAR2(150);
    v_new_id     NUMBER;
BEGIN
    SELECT jt.file_name, jt.file_type, jt.file_size, jt.content, jt.created_by
    INTO   v_file_name, v_file_type, v_file_size, v_content, v_created_by
    FROM   JSON_TABLE(:body_text, '$' COLUMNS (
               file_name  VARCHAR2(500)  PATH '$.fileName',
               file_type  VARCHAR2(100)  PATH '$.fileType',
               file_size  NUMBER         PATH '$.fileSize',
               content    CLOB           PATH '$.content',
               created_by VARCHAR2(150)  PATH '$.createdBy'
           )) jt;

    INSERT INTO RR_BANK_TRANSFER_ATTACHMENTS
        (BANK_ACCOUNT_TRANSFER_ID, FILE_NAME, FILE_TYPE, FILE_SIZE, FILE_CONTENT, CREATED_BY)
    VALUES
        (:transferId, v_file_name, v_file_type, v_file_size, v_content, NVL(v_created_by,'SYSTEM'))
    RETURNING ID INTO v_new_id;

    COMMIT;
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('{"status":"success","id":' || v_new_id || ',"fileName":' || APEX_JSON.STRINGIFY(v_file_name) || '}');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- OPTIONS for CORS
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/banktransfers/:transferId/attachments',
        p_method         => 'OPTIONS',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[BEGIN OWA_UTIL.MIME_HEADER('application/json', FALSE); HTP.P(''); END;]'
    );
    COMMIT;
END;
/

-- ============================================================
-- ORDS: GET /cash/banktransfers/:transferId/attachments/:attachmentId
-- Returns the attachment including FILE_CONTENT for preview
-- ============================================================
BEGIN
    ORDS.DELETE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/banktransfers/:transferId/attachments/:attachmentId'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/banktransfers/:transferId/attachments/:attachmentId',
        p_priority    => 0,
        p_etag_type   => 'HASH'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/banktransfers/:transferId/attachments/:attachmentId',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'Get single attachment with content for preview',
        p_source         => q'[
DECLARE
    r RR_BANK_TRANSFER_ATTACHMENTS%ROWTYPE;
BEGIN
    SELECT * INTO r
      FROM RR_BANK_TRANSFER_ATTACHMENTS
     WHERE ID = :attachmentId
       AND BANK_ACCOUNT_TRANSFER_ID = :transferId;

    HTP.P('{"id":' || r.ID
        || ',"fileName":' || APEX_JSON.STRINGIFY(r.FILE_NAME)
        || ',"fileType":' || APEX_JSON.STRINGIFY(NVL(r.FILE_TYPE,''))
        || ',"fileSize":' || NVL(TO_CHAR(r.FILE_SIZE),'null')
        || ',"content":' || APEX_JSON.STRINGIFY(NVL(r.FILE_CONTENT,''))
        || '}');
EXCEPTION WHEN NO_DATA_FOUND THEN
    HTP.P('{"error":"Not found"}');
WHEN OTHERS THEN
    HTP.P('{"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/banktransfers/:transferId/attachments/:attachmentId',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'Delete a bank transfer attachment',
        p_source         => q'[
BEGIN
    DELETE FROM RR_BANK_TRANSFER_ATTACHMENTS
     WHERE ID = :attachmentId
       AND BANK_ACCOUNT_TRANSFER_ID = :transferId;
    IF SQL%ROWCOUNT = 0 THEN
        OWA_UTIL.MIME_HEADER('application/json', FALSE);
        HTP.P('{"status":"error","message":"Attachment not found"}');
    ELSE
        COMMIT;
        OWA_UTIL.MIME_HEADER('application/json', FALSE);
        HTP.P('{"status":"success"}');
    END IF;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/
