-- ============================================================
-- Table: RR_BANK_STATEMENT_PDF_TEMPLATES
-- Description: User-defined templates for parsing bank statement PDFs
--              Each template maps PDF column X-positions to statement fields
-- ============================================================

CREATE TABLE RR_BANK_STATEMENT_PDF_TEMPLATES (
    TEMPLATE_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TEMPLATE_NAME       VARCHAR2(200)   NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    BUSINESS_UNIT_NAME  VARCHAR2(360),          -- NULL = applies to all BUs
    COLUMN_MAPPINGS     CLOB,                   -- JSON array: [{text,x,xMin,xMax,field}]
    HEADER_ROW_TEXT     VARCHAR2(2000),         -- concatenated header texts for auto-detection
    DATE_FORMAT         VARCHAR2(50)  DEFAULT 'DD/MM/YYYY',
    CREATED_BY          VARCHAR2(150),
    CREATION_DATE       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(150),
    LAST_UPDATE_DATE    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_RR_PDF_TPL_NAME UNIQUE (TEMPLATE_NAME)
);

CREATE INDEX IDX_RR_PDF_TPL_BU ON RR_BANK_STATEMENT_PDF_TEMPLATES(BUSINESS_UNIT_NAME);

COMMENT ON TABLE  RR_BANK_STATEMENT_PDF_TEMPLATES IS 'Templates for parsing PDF bank statements by column X-position mapping';
COMMENT ON COLUMN RR_BANK_STATEMENT_PDF_TEMPLATES.COLUMN_MAPPINGS IS 'JSON array of column objects: [{text,x,xMin,xMax,field}]';
COMMENT ON COLUMN RR_BANK_STATEMENT_PDF_TEMPLATES.HEADER_ROW_TEXT IS 'Space-joined header column texts — used for auto-template detection';
COMMENT ON COLUMN RR_BANK_STATEMENT_PDF_TEMPLATES.DATE_FORMAT     IS 'Date format string: DD/MM/YYYY | MM/DD/YYYY | DD-MMM-YYYY | YYYY-MM-DD';


-- ============================================================
-- APEX REST Handlers
-- ============================================================

-- ── Template: cash/pdf-templates ────────────────────────────
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/pdf-templates',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'PDF Statement Templates endpoint'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -20001 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ── GET cash/pdf-templates ───────────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/pdf-templates',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_items_per_page => 0,
        p_mimes_allowed  => '',
        p_comments       => 'List PDF templates; optional business_unit filter (also returns NULL-BU templates)',
        p_source         => q'[
SELECT
    TEMPLATE_ID         AS "templateId",
    TEMPLATE_NAME       AS "templateName",
    DESCRIPTION         AS "description",
    BUSINESS_UNIT_NAME  AS "businessUnitName",
    COLUMN_MAPPINGS     AS "columnMappings",
    HEADER_ROW_TEXT     AS "headerRowText",
    DATE_FORMAT         AS "dateFormat",
    CREATED_BY          AS "createdBy",
    TO_CHAR(CREATION_DATE,    'YYYY-MM-DD"T"HH24:MI:SS') AS "creationDate",
    LAST_UPDATED_BY     AS "lastUpdatedBy",
    TO_CHAR(LAST_UPDATE_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS "lastUpdateDate"
FROM RR_BANK_STATEMENT_PDF_TEMPLATES
WHERE (:business_unit IS NULL
       OR BUSINESS_UNIT_NAME = :business_unit
       OR BUSINESS_UNIT_NAME IS NULL)
ORDER BY TEMPLATE_NAME
]'
    );
    COMMIT;
END;
/

-- ── POST cash/pdf-templates (upsert) ────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/pdf-templates',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Upsert a PDF template — update if template_id provided, else insert',
        p_source         => q'[
DECLARE
    l_id        NUMBER;
    l_name      VARCHAR2(200);
    l_desc      VARCHAR2(500);
    l_bu        VARCHAR2(360);
    l_mappings  CLOB;
    l_hdr       VARCHAR2(2000);
    l_fmt       VARCHAR2(50);
    l_created   VARCHAR2(150);
    l_updated   VARCHAR2(150);
BEGIN
    APEX_JSON.PARSE(:body_text);

    l_id       := APEX_JSON.GET_NUMBER(p_path => 'template_id');
    l_name     := APEX_JSON.GET_VARCHAR2(p_path => 'template_name');
    l_desc     := APEX_JSON.GET_VARCHAR2(p_path => 'description');
    l_bu       := APEX_JSON.GET_VARCHAR2(p_path => 'business_unit_name');
    l_mappings := TO_CLOB(APEX_JSON.GET_VARCHAR2(p_path => 'column_mappings'));
    l_hdr      := APEX_JSON.GET_VARCHAR2(p_path => 'header_row_text');
    l_fmt      := NVL(APEX_JSON.GET_VARCHAR2(p_path => 'date_format'), 'DD/MM/YYYY');
    l_created  := APEX_JSON.GET_VARCHAR2(p_path => 'created_by');
    l_updated  := APEX_JSON.GET_VARCHAR2(p_path => 'last_updated_by');

    IF l_name IS NULL AND l_id IS NULL THEN
        :status_code := 400;
        HTP.PRN('{"status":"error","message":"template_name is required"}');
        RETURN;
    END IF;

    IF l_id IS NOT NULL THEN
        UPDATE RR_BANK_STATEMENT_PDF_TEMPLATES
        SET    TEMPLATE_NAME      = NVL(l_name,     TEMPLATE_NAME),
               DESCRIPTION        = l_desc,
               BUSINESS_UNIT_NAME = l_bu,
               COLUMN_MAPPINGS    = NVL(l_mappings,  COLUMN_MAPPINGS),
               HEADER_ROW_TEXT    = l_hdr,
               DATE_FORMAT        = NVL(l_fmt,       DATE_FORMAT),
               LAST_UPDATED_BY    = l_updated,
               LAST_UPDATE_DATE   = SYSTIMESTAMP
        WHERE  TEMPLATE_ID = l_id;

        IF SQL%ROWCOUNT = 0 THEN
            :status_code := 404;
            HTP.PRN('{"status":"error","message":"Template not found"}');
            RETURN;
        END IF;
        COMMIT;
        :status_code := 200;
        HTP.PRN('{"status":"success","template_id":' || l_id || ',"message":"Template updated"}');
    ELSE
        INSERT INTO RR_BANK_STATEMENT_PDF_TEMPLATES (
            TEMPLATE_NAME, DESCRIPTION, BUSINESS_UNIT_NAME,
            COLUMN_MAPPINGS, HEADER_ROW_TEXT, DATE_FORMAT,
            CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE
        ) VALUES (
            l_name, l_desc, l_bu, l_mappings, l_hdr, l_fmt,
            l_created, SYSTIMESTAMP, NVL(l_updated, l_created), SYSTIMESTAMP
        ) RETURNING TEMPLATE_ID INTO l_id;
        COMMIT;
        :status_code := 201;
        HTP.PRN('{"status":"success","template_id":' || l_id || ',"message":"Template created"}');
    END IF;

EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── Template: cash/pdf-templates/{id} ───────────────────────
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/pdf-templates/:id',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'PDF Templates single-record endpoint'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -20001 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ── DELETE cash/pdf-templates/:id ───────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/pdf-templates/:id',
        p_method         => 'DELETE',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => '',
        p_comments       => 'Delete a PDF template by TEMPLATE_ID',
        p_source         => q'[
DECLARE
    l_rows NUMBER;
BEGIN
    DELETE FROM RR_BANK_STATEMENT_PDF_TEMPLATES WHERE TEMPLATE_ID = :id;
    l_rows := SQL%ROWCOUNT;
    COMMIT;
    IF l_rows = 0 THEN
        :status_code := 404;
        HTP.PRN('{"status":"error","message":"Template not found"}');
    ELSE
        :status_code := 200;
        HTP.PRN('{"status":"success","message":"Template deleted"}');
    END IF;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/
