-- =============================================================================
-- RR_BANK_STATEMENTS.SQL
-- Bank Statement Management: Tables, Indexes, Package, ORDS Handlers
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: RR_BANK_STATEMENT_HEADER
-- ---------------------------------------------------------------------------
CREATE TABLE RR_BANK_STATEMENT_HEADER (
    STATEMENT_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STATEMENT_NUMBER    VARCHAR2(100)  NOT NULL,
    BANK_ACCOUNT_NUMBER VARCHAR2(100),
    BANK_ACCOUNT_NAME   VARCHAR2(360),
    STATEMENT_DATE      DATE,
    CURRENCY_CODE       VARCHAR2(15),
    OPENING_BALANCE     NUMBER,
    CLOSING_BALANCE     NUMBER,
    TOTAL_CREDITS       NUMBER         DEFAULT 0,
    TOTAL_DEBITS        NUMBER         DEFAULT 0,
    STATUS              VARCHAR2(30)   DEFAULT 'DRAFT',       -- DRAFT, SUBMITTED, RECONCILING, RECONCILED, CLOSED
    BUSINESS_UNIT_NAME  VARCHAR2(360),
    DESCRIPTION         VARCHAR2(1000),
    CREATED_BY          VARCHAR2(150),
    CREATION_DATE       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(150),
    LAST_UPDATE_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_BKST_HDR_UK UNIQUE (STATEMENT_NUMBER, BANK_ACCOUNT_NUMBER)
);

COMMENT ON TABLE  RR_BANK_STATEMENT_HEADER                  IS 'Bank statement header records';
COMMENT ON COLUMN RR_BANK_STATEMENT_HEADER.STATEMENT_ID     IS 'Identity primary key';
COMMENT ON COLUMN RR_BANK_STATEMENT_HEADER.STATUS           IS 'DRAFT | SUBMITTED | RECONCILING | RECONCILED | CLOSED';

-- ---------------------------------------------------------------------------
-- TABLE: RR_BANK_STATEMENT_LINES
-- ---------------------------------------------------------------------------
CREATE TABLE RR_BANK_STATEMENT_LINES (
    LINE_ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STATEMENT_ID           NUMBER        NOT NULL,
    LINE_NUMBER            NUMBER,
    TRANSACTION_DATE       DATE,
    VALUE_DATE             DATE,
    AMOUNT                 NUMBER,
    TRANSACTION_CODE       VARCHAR2(10),   -- CR, DR
    DESCRIPTION            VARCHAR2(1000),
    REFERENCE              VARCHAR2(360),
    BANK_TXN_REFERENCE     VARCHAR2(200),
    COUNTERPARTY_NAME      VARCHAR2(360),
    COUNTERPARTY_ACCOUNT   VARCHAR2(100),
    -- Reconciliation columns
    RECON_STATUS           VARCHAR2(30)  DEFAULT 'UNRECONCILED',  -- UNRECONCILED, RECONCILED, PARTIALLY_RECONCILED, EXCLUDED
    RECON_AMOUNT           NUMBER,
    RECON_DATE             TIMESTAMP,
    RECON_BY               VARCHAR2(150),
    RECON_TXN_TYPE         VARCHAR2(30),   -- AR_RECEIPT, AP_PAYMENT, CE_TXN, JOURNAL, EXTERNAL
    RECON_TXN_ID           NUMBER,
    RECON_TXN_NUMBER       VARCHAR2(200),
    RECON_REFERENCE        VARCHAR2(360),
    RECON_NOTES            VARCHAR2(1000),
    CREATED_BY             VARCHAR2(150),
    CREATION_DATE          TIMESTAMP     DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY        VARCHAR2(150),
    LAST_UPDATE_DATE       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_BKST_LN_FK FOREIGN KEY (STATEMENT_ID)
        REFERENCES RR_BANK_STATEMENT_HEADER (STATEMENT_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  RR_BANK_STATEMENT_LINES                    IS 'Bank statement line items';
COMMENT ON COLUMN RR_BANK_STATEMENT_LINES.TRANSACTION_CODE   IS 'CR = Credit, DR = Debit';

-- Add CATEGORY_CODE column for RR_TRANSACTION_CODES lookup (run once on existing DB)
ALTER TABLE RR_BANK_STATEMENT_LINES ADD CATEGORY_CODE VARCHAR2(50);
COMMENT ON COLUMN RR_BANK_STATEMENT_LINES.CATEGORY_CODE IS 'Transaction code from RR_TRANSACTION_CODES';
COMMENT ON COLUMN RR_BANK_STATEMENT_LINES.RECON_STATUS       IS 'UNRECONCILED | RECONCILED | PARTIALLY_RECONCILED | EXCLUDED';
COMMENT ON COLUMN RR_BANK_STATEMENT_LINES.RECON_TXN_TYPE     IS 'AR_RECEIPT | AP_PAYMENT | CE_TXN | JOURNAL | EXTERNAL';

-- ---------------------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------------------
CREATE INDEX RR_BKST_HDR_DATE_IDX   ON RR_BANK_STATEMENT_HEADER (STATEMENT_DATE);
CREATE INDEX RR_BKST_HDR_ACCT_IDX   ON RR_BANK_STATEMENT_HEADER (BANK_ACCOUNT_NUMBER);
CREATE INDEX RR_BKST_HDR_STAT_IDX   ON RR_BANK_STATEMENT_HEADER (STATUS);
CREATE INDEX RR_BKST_LN_STMTID_IDX  ON RR_BANK_STATEMENT_LINES  (STATEMENT_ID);
CREATE INDEX RR_BKST_LN_RECON_IDX   ON RR_BANK_STATEMENT_LINES  (RECON_STATUS);

-- ---------------------------------------------------------------------------
-- PACKAGE SPEC: RR_BANK_STMT_PKG
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE RR_BANK_STMT_PKG AS

    /**
     * Save or update a statement header.
     *   p_json    : JSON object with header fields (camelCase or UPPER_SNAKE)
     *   p_stmt_id : OUT — the statement_id of the saved record
     *   p_error   : OUT — non-null on failure
     */
    PROCEDURE save_header (
        p_json    IN  CLOB,
        p_stmt_id OUT NUMBER,
        p_error   OUT VARCHAR2
    );

    /**
     * Save or merge lines for a given statement.
     *   p_stmt_id : parent statement_id
     *   p_json    : JSON array of line objects
     *   p_count   : OUT — number of lines processed
     *   p_error   : OUT — non-null on failure
     */
    PROCEDURE save_lines (
        p_stmt_id IN  NUMBER,
        p_json    IN  CLOB,
        p_count   OUT NUMBER,
        p_error   OUT VARCHAR2
    );

    /** Delete a single statement line. */
    PROCEDURE delete_line (
        p_line_id IN  NUMBER,
        p_error   OUT VARCHAR2
    );

    /**
     * Mark a line as RECONCILED against an external transaction.
     */
    PROCEDURE reconcile_line (
        p_line_id     IN  NUMBER,
        p_txn_type    IN  VARCHAR2,
        p_txn_id      IN  NUMBER,
        p_txn_number  IN  VARCHAR2,
        p_recon_amount IN NUMBER,
        p_notes       IN  VARCHAR2,
        p_user        IN  VARCHAR2,
        p_error       OUT VARCHAR2
    );

    /**
     * Clear reconciliation data from a line (reset to UNRECONCILED).
     */
    PROCEDURE unreconcile_line (
        p_line_id IN  NUMBER,
        p_user    IN  VARCHAR2,
        p_error   OUT VARCHAR2
    );

    /**
     * Recalculate TOTAL_CREDITS and TOTAL_DEBITS on the header
     * by summing lines for the given statement.
     */
    PROCEDURE recalc_totals (
        p_stmt_id IN NUMBER
    );

END RR_BANK_STMT_PKG;
/

-- ---------------------------------------------------------------------------
-- PACKAGE BODY: RR_BANK_STMT_PKG
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY RR_BANK_STMT_PKG AS

    -- -------------------------------------------------------------------------
    -- save_header
    -- -------------------------------------------------------------------------
    PROCEDURE save_header (
        p_json    IN  CLOB,
        p_stmt_id OUT NUMBER,
        p_error   OUT VARCHAR2
    ) IS
        v_statement_id      NUMBER;
        v_statement_number  VARCHAR2(100);
        v_bank_acct_num     VARCHAR2(100);
        v_bank_acct_name    VARCHAR2(360);
        v_stmt_date         DATE;
        v_currency          VARCHAR2(15);
        v_opening_bal       NUMBER;
        v_closing_bal       NUMBER;
        v_status            VARCHAR2(30);
        v_bu_name           VARCHAR2(360);
        v_description       VARCHAR2(1000);
        v_created_by        VARCHAR2(150);
        v_updated_by        VARCHAR2(150);
        v_exists            NUMBER := 0;
    BEGIN
        p_error := NULL;

        -- Parse incoming JSON
        SELECT jt.statement_id,
               jt.statement_number,
               jt.bank_account_number,
               jt.bank_account_name,
               TO_DATE(jt.statement_date, 'YYYY-MM-DD'),
               jt.currency_code,
               jt.opening_balance,
               jt.closing_balance,
               jt.status,
               jt.business_unit_name,
               jt.description,
               jt.created_by,
               jt.last_updated_by
        INTO   v_statement_id,
               v_statement_number,
               v_bank_acct_num,
               v_bank_acct_name,
               v_stmt_date,
               v_currency,
               v_opening_bal,
               v_closing_bal,
               v_status,
               v_bu_name,
               v_description,
               v_created_by,
               v_updated_by
        FROM   JSON_TABLE(p_json, '$'
                 COLUMNS (
                   statement_id       NUMBER       PATH '$.statementId',
                   statement_number   VARCHAR2(100) PATH '$.statementNumber',
                   bank_account_number VARCHAR2(100) PATH '$.bankAccountNumber',
                   bank_account_name  VARCHAR2(360) PATH '$.bankAccountName',
                   statement_date     VARCHAR2(20)  PATH '$.statementDate',
                   currency_code      VARCHAR2(15)  PATH '$.currencyCode',
                   opening_balance    NUMBER        PATH '$.openingBalance',
                   closing_balance    NUMBER        PATH '$.closingBalance',
                   status             VARCHAR2(30)  PATH '$.status',
                   business_unit_name VARCHAR2(360) PATH '$.businessUnitName',
                   description        VARCHAR2(1000) PATH '$.description',
                   created_by         VARCHAR2(150) PATH '$.createdBy',
                   last_updated_by    VARCHAR2(150) PATH '$.lastUpdatedBy'
                 )
               ) jt;

        -- Default fallbacks
        v_status     := NVL(v_status,     'DRAFT');
        v_created_by := NVL(v_created_by, 'ERP_USER');
        v_updated_by := NVL(v_updated_by, 'ERP_USER');

        -- Resolve existing record: by ID first, then by natural key
        IF v_statement_id IS NOT NULL THEN
            SELECT COUNT(1) INTO v_exists
            FROM   RR_BANK_STATEMENT_HEADER
            WHERE  STATEMENT_ID = v_statement_id;
        END IF;

        IF v_exists = 0 AND v_statement_number IS NOT NULL AND v_bank_acct_num IS NOT NULL THEN
            BEGIN
                SELECT STATEMENT_ID INTO v_statement_id
                FROM   RR_BANK_STATEMENT_HEADER
                WHERE  STATEMENT_NUMBER    = v_statement_number
                AND    BANK_ACCOUNT_NUMBER = v_bank_acct_num;
                v_exists := 1;
            EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
            END;
        END IF;

        IF v_exists > 0 THEN
            -- UPDATE
            UPDATE RR_BANK_STATEMENT_HEADER
            SET    STATEMENT_NUMBER    = NVL(v_statement_number, STATEMENT_NUMBER),
                   BANK_ACCOUNT_NUMBER = NVL(v_bank_acct_num,    BANK_ACCOUNT_NUMBER),
                   BANK_ACCOUNT_NAME   = NVL(v_bank_acct_name,   BANK_ACCOUNT_NAME),
                   STATEMENT_DATE      = NVL(v_stmt_date,         STATEMENT_DATE),
                   CURRENCY_CODE       = NVL(v_currency,          CURRENCY_CODE),
                   OPENING_BALANCE     = NVL(v_opening_bal,       OPENING_BALANCE),
                   CLOSING_BALANCE     = NVL(v_closing_bal,       CLOSING_BALANCE),
                   STATUS              = NVL(v_status,            STATUS),
                   BUSINESS_UNIT_NAME  = NVL(v_bu_name,           BUSINESS_UNIT_NAME),
                   DESCRIPTION         = NVL(v_description,       DESCRIPTION),
                   LAST_UPDATED_BY     = v_updated_by,
                   LAST_UPDATE_DATE    = SYSTIMESTAMP
            WHERE  STATEMENT_ID = v_statement_id;
        ELSE
            -- INSERT
            INSERT INTO RR_BANK_STATEMENT_HEADER (
                STATEMENT_NUMBER, BANK_ACCOUNT_NUMBER, BANK_ACCOUNT_NAME,
                STATEMENT_DATE, CURRENCY_CODE, OPENING_BALANCE, CLOSING_BALANCE,
                STATUS, BUSINESS_UNIT_NAME, DESCRIPTION,
                CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE
            ) VALUES (
                v_statement_number, v_bank_acct_num, v_bank_acct_name,
                v_stmt_date, v_currency, v_opening_bal, v_closing_bal,
                v_status, v_bu_name, v_description,
                v_created_by, SYSTIMESTAMP, v_updated_by, SYSTIMESTAMP
            ) RETURNING STATEMENT_ID INTO v_statement_id;
        END IF;

        p_stmt_id := v_statement_id;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_error := SQLERRM;
    END save_header;

    -- -------------------------------------------------------------------------
    -- save_lines
    -- -------------------------------------------------------------------------
    PROCEDURE save_lines (
        p_stmt_id IN  NUMBER,
        p_json    IN  CLOB,
        p_count   OUT NUMBER,
        p_error   OUT VARCHAR2
    ) IS
        v_count  NUMBER := 0;
        v_max_ln NUMBER := 0;
        v_exists NUMBER := 0;
        v_new_id NUMBER;
    BEGIN
        p_error := NULL;

        -- Determine current max line_number for auto-assign
        SELECT NVL(MAX(LINE_NUMBER), 0)
        INTO   v_max_ln
        FROM   RR_BANK_STATEMENT_LINES
        WHERE  STATEMENT_ID = p_stmt_id;

        -- MERGE each line
        FOR rec IN (
            SELECT jt.line_id,
                   jt.line_number,
                   TO_DATE(jt.transaction_date, 'YYYY-MM-DD') AS transaction_date,
                   TO_DATE(jt.value_date,       'YYYY-MM-DD') AS value_date,
                   jt.amount,
                   jt.transaction_code,
                   jt.description,
                   jt.reference,
                   jt.bank_txn_reference,
                   jt.counterparty_name,
                   jt.counterparty_account,
                   jt.recon_status,
                   jt.created_by,
                   jt.last_updated_by
            FROM   JSON_TABLE(p_json, '$[*]'
                     COLUMNS (
                       line_id              NUMBER        PATH '$.lineId',
                       line_number          NUMBER        PATH '$.lineNumber',
                       transaction_date     VARCHAR2(20)  PATH '$.transactionDate',
                       value_date           VARCHAR2(20)  PATH '$.valueDate',
                       amount               NUMBER        PATH '$.amount',
                       transaction_code     VARCHAR2(10)  PATH '$.transactionCode',
                       description          VARCHAR2(1000) PATH '$.description',
                       reference            VARCHAR2(360) PATH '$.reference',
                       bank_txn_reference   VARCHAR2(200) PATH '$.bankTxnReference',
                       counterparty_name    VARCHAR2(360) PATH '$.counterpartyName',
                       counterparty_account VARCHAR2(100) PATH '$.counterpartyAccount',
                       recon_status         VARCHAR2(30)  PATH '$.reconStatus',
                       created_by           VARCHAR2(150) PATH '$.createdBy',
                       last_updated_by      VARCHAR2(150) PATH '$.lastUpdatedBy'
                     )
                   ) jt
        )
        LOOP
            v_exists := 0;
            IF rec.line_id IS NOT NULL THEN
                SELECT COUNT(1) INTO v_exists
                FROM   RR_BANK_STATEMENT_LINES
                WHERE  LINE_ID = rec.line_id AND STATEMENT_ID = p_stmt_id;
            END IF;

            IF v_exists > 0 THEN
                UPDATE RR_BANK_STATEMENT_LINES
                SET    LINE_NUMBER          = NVL(rec.line_number,        LINE_NUMBER),
                       TRANSACTION_DATE     = NVL(rec.transaction_date,   TRANSACTION_DATE),
                       VALUE_DATE           = NVL(rec.value_date,         VALUE_DATE),
                       AMOUNT               = NVL(rec.amount,             AMOUNT),
                       TRANSACTION_CODE     = NVL(rec.transaction_code,   TRANSACTION_CODE),
                       DESCRIPTION          = NVL(rec.description,        DESCRIPTION),
                       REFERENCE            = NVL(rec.reference,          REFERENCE),
                       BANK_TXN_REFERENCE   = NVL(rec.bank_txn_reference, BANK_TXN_REFERENCE),
                       COUNTERPARTY_NAME    = NVL(rec.counterparty_name,  COUNTERPARTY_NAME),
                       COUNTERPARTY_ACCOUNT = NVL(rec.counterparty_account, COUNTERPARTY_ACCOUNT),
                       LAST_UPDATED_BY      = NVL(rec.last_updated_by,    'ERP_USER'),
                       LAST_UPDATE_DATE     = SYSTIMESTAMP
                WHERE  LINE_ID = rec.line_id;
            ELSE
                -- Auto-assign line number if not provided
                v_max_ln := v_max_ln + 1;
                INSERT INTO RR_BANK_STATEMENT_LINES (
                    STATEMENT_ID, LINE_NUMBER,
                    TRANSACTION_DATE, VALUE_DATE,
                    AMOUNT, TRANSACTION_CODE,
                    DESCRIPTION, REFERENCE,
                    BANK_TXN_REFERENCE, COUNTERPARTY_NAME, COUNTERPARTY_ACCOUNT,
                    RECON_STATUS,
                    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE
                ) VALUES (
                    p_stmt_id, NVL(rec.line_number, v_max_ln),
                    rec.transaction_date, rec.value_date,
                    rec.amount, rec.transaction_code,
                    rec.description, rec.reference,
                    rec.bank_txn_reference, rec.counterparty_name, rec.counterparty_account,
                    NVL(rec.recon_status, 'UNRECONCILED'),
                    NVL(rec.created_by, 'ERP_USER'), SYSTIMESTAMP,
                    NVL(rec.last_updated_by, 'ERP_USER'), SYSTIMESTAMP
                ) RETURNING LINE_ID INTO v_new_id;
            END IF;

            v_count := v_count + 1;
        END LOOP;

        p_count := v_count;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_error := SQLERRM;
    END save_lines;

    -- -------------------------------------------------------------------------
    -- delete_line
    -- -------------------------------------------------------------------------
    PROCEDURE delete_line (
        p_line_id IN  NUMBER,
        p_error   OUT VARCHAR2
    ) IS
    BEGIN
        p_error := NULL;
        DELETE FROM RR_BANK_STATEMENT_LINES WHERE LINE_ID = p_line_id;
        IF SQL%ROWCOUNT = 0 THEN
            p_error := 'Line ID ' || p_line_id || ' not found.';
        ELSE
            COMMIT;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_error := SQLERRM;
    END delete_line;

    -- -------------------------------------------------------------------------
    -- reconcile_line
    -- -------------------------------------------------------------------------
    PROCEDURE reconcile_line (
        p_line_id      IN  NUMBER,
        p_txn_type     IN  VARCHAR2,
        p_txn_id       IN  NUMBER,
        p_txn_number   IN  VARCHAR2,
        p_recon_amount IN  NUMBER,
        p_notes        IN  VARCHAR2,
        p_user         IN  VARCHAR2,
        p_error        OUT VARCHAR2
    ) IS
        v_line_amount NUMBER;
    BEGIN
        p_error := NULL;

        SELECT AMOUNT INTO v_line_amount
        FROM   RR_BANK_STATEMENT_LINES
        WHERE  LINE_ID = p_line_id;

        UPDATE RR_BANK_STATEMENT_LINES
        SET    RECON_STATUS     = 'RECONCILED',
               RECON_AMOUNT     = p_recon_amount,
               RECON_DATE       = SYSTIMESTAMP,
               RECON_BY         = p_user,
               RECON_TXN_TYPE   = p_txn_type,
               RECON_TXN_ID     = p_txn_id,
               RECON_TXN_NUMBER = p_txn_number,
               RECON_NOTES      = p_notes,
               LAST_UPDATED_BY  = p_user,
               LAST_UPDATE_DATE = SYSTIMESTAMP
        WHERE  LINE_ID = p_line_id;

        IF SQL%ROWCOUNT = 0 THEN
            p_error := 'Line ID ' || p_line_id || ' not found.';
            RETURN;
        END IF;
        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_error := 'Line ID ' || p_line_id || ' not found.';
        WHEN OTHERS THEN
            ROLLBACK;
            p_error := SQLERRM;
    END reconcile_line;

    -- -------------------------------------------------------------------------
    -- unreconcile_line
    -- -------------------------------------------------------------------------
    PROCEDURE unreconcile_line (
        p_line_id IN  NUMBER,
        p_user    IN  VARCHAR2,
        p_error   OUT VARCHAR2
    ) IS
    BEGIN
        p_error := NULL;
        UPDATE RR_BANK_STATEMENT_LINES
        SET    RECON_STATUS     = 'UNRECONCILED',
               RECON_AMOUNT     = NULL,
               RECON_DATE       = NULL,
               RECON_BY         = NULL,
               RECON_TXN_TYPE   = NULL,
               RECON_TXN_ID     = NULL,
               RECON_TXN_NUMBER = NULL,
               RECON_REFERENCE  = NULL,
               RECON_NOTES      = NULL,
               LAST_UPDATED_BY  = p_user,
               LAST_UPDATE_DATE = SYSTIMESTAMP
        WHERE  LINE_ID = p_line_id;

        IF SQL%ROWCOUNT = 0 THEN
            p_error := 'Line ID ' || p_line_id || ' not found.';
        ELSE
            COMMIT;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_error := SQLERRM;
    END unreconcile_line;

    -- -------------------------------------------------------------------------
    -- recalc_totals
    -- -------------------------------------------------------------------------
    PROCEDURE recalc_totals (
        p_stmt_id IN NUMBER
    ) IS
        v_credits NUMBER := 0;
        v_debits  NUMBER := 0;
    BEGIN
        SELECT NVL(SUM(CASE WHEN TRANSACTION_CODE = 'CR' THEN AMOUNT ELSE 0 END), 0),
               NVL(SUM(CASE WHEN TRANSACTION_CODE = 'DR' THEN AMOUNT ELSE 0 END), 0)
        INTO   v_credits, v_debits
        FROM   RR_BANK_STATEMENT_LINES
        WHERE  STATEMENT_ID  = p_stmt_id
        AND    RECON_STATUS  <> 'EXCLUDED';

        UPDATE RR_BANK_STATEMENT_HEADER
        SET    TOTAL_CREDITS     = v_credits,
               TOTAL_DEBITS      = v_debits,
               LAST_UPDATE_DATE  = SYSTIMESTAMP
        WHERE  STATEMENT_ID = p_stmt_id;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END recalc_totals;

END RR_BANK_STMT_PKG;
/

-- =============================================================================
-- ORDS HANDLERS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Helper: numeric-safe TO_CHAR wrapper (used inline in queries)
-- Wrap every numeric output with:
--   REGEXP_REPLACE(TO_CHAR(col,'FM99999999999999990.9999999999'),'\.$','')
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1. GET cash/bankstatements  — Search headers
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/bankstatements',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_clob  CLOB;
    v_buf   VARCHAR2(32767);
    v_first BOOLEAN := TRUE;
    v_limit NUMBER  := NVL(:row_limit, 500);

    CURSOR c_stmt IS
        SELECT
            h.STATEMENT_ID,
            h.STATEMENT_NUMBER,
            h.BANK_ACCOUNT_NUMBER,
            h.BANK_ACCOUNT_NAME,
            TO_CHAR(h.STATEMENT_DATE, 'YYYY-MM-DD')          AS STATEMENT_DATE,
            h.CURRENCY_CODE,
            REGEXP_REPLACE(TO_CHAR(NVL(h.OPENING_BALANCE,0),'FM99999999999999990.9999999999'),'\.$','')  AS OPENING_BALANCE,
            REGEXP_REPLACE(TO_CHAR(NVL(h.CLOSING_BALANCE,0),'FM99999999999999990.9999999999'),'\.$','')  AS CLOSING_BALANCE,
            REGEXP_REPLACE(TO_CHAR(NVL(h.TOTAL_CREDITS,0),  'FM99999999999999990.9999999999'),'\.$','')  AS TOTAL_CREDITS,
            REGEXP_REPLACE(TO_CHAR(NVL(h.TOTAL_DEBITS,0),   'FM99999999999999990.9999999999'),'\.$','')  AS TOTAL_DEBITS,
            h.STATUS,
            h.BUSINESS_UNIT_NAME,
            h.DESCRIPTION,
            h.CREATED_BY,
            TO_CHAR(h.CREATION_DATE,    'YYYY-MM-DD"T"HH24:MI:SS') AS CREATION_DATE,
            h.LAST_UPDATED_BY,
            TO_CHAR(h.LAST_UPDATE_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS LAST_UPDATE_DATE
        FROM   RR_BANK_STATEMENT_HEADER h
        WHERE  (:statement_number IS NULL OR UPPER(h.STATEMENT_NUMBER)    LIKE '%' || UPPER(:statement_number) || '%')
        AND    (:bank_account     IS NULL OR UPPER(h.BANK_ACCOUNT_NUMBER) LIKE '%' || UPPER(:bank_account)     || '%'
                                         OR UPPER(h.BANK_ACCOUNT_NAME)   LIKE '%' || UPPER(:bank_account)     || '%')
        AND    (:business_unit    IS NULL OR UPPER(h.BUSINESS_UNIT_NAME)  LIKE '%' || UPPER(:business_unit)    || '%')
        AND    (:status           IS NULL OR h.STATUS = :status)
        AND    (:date_from        IS NULL OR h.STATEMENT_DATE >= TO_DATE(:date_from, 'YYYY-MM-DD'))
        AND    (:date_to          IS NULL OR h.STATEMENT_DATE <= TO_DATE(:date_to,   'YYYY-MM-DD'))
        ORDER  BY h.STATEMENT_DATE DESC, h.STATEMENT_ID DESC
        FETCH  FIRST v_limit ROWS ONLY;
BEGIN
    DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
    DBMS_LOB.APPEND(v_clob, '{"status":"success","items":[');

    FOR r IN c_stmt LOOP
        IF NOT v_first THEN
            DBMS_LOB.APPEND(v_clob, ',');
        END IF;
        v_first := FALSE;

        v_buf :=
            '{"statementId":'          || r.STATEMENT_ID                                       ||
            ',"statementNumber":'      || APEX_JSON.STRINGIFY(r.STATEMENT_NUMBER)              ||
            ',"bankAccountNumber":'    || APEX_JSON.STRINGIFY(NVL(r.BANK_ACCOUNT_NUMBER,''))   ||
            ',"bankAccountName":'      || APEX_JSON.STRINGIFY(NVL(r.BANK_ACCOUNT_NAME,''))     ||
            ',"statementDate":'        || APEX_JSON.STRINGIFY(NVL(r.STATEMENT_DATE,''))        ||
            ',"currencyCode":'         || APEX_JSON.STRINGIFY(NVL(r.CURRENCY_CODE,''))         ||
            ',"openingBalance":'       || r.OPENING_BALANCE                                    ||
            ',"closingBalance":'       || r.CLOSING_BALANCE                                    ||
            ',"totalCredits":'         || r.TOTAL_CREDITS                                      ||
            ',"totalDebits":'          || r.TOTAL_DEBITS                                       ||
            ',"status":'               || APEX_JSON.STRINGIFY(NVL(r.STATUS,''))                ||
            ',"businessUnitName":'     || APEX_JSON.STRINGIFY(NVL(r.BUSINESS_UNIT_NAME,''))    ||
            ',"description":'          || APEX_JSON.STRINGIFY(NVL(r.DESCRIPTION,''))           ||
            ',"createdBy":'            || APEX_JSON.STRINGIFY(NVL(r.CREATED_BY,''))            ||
            ',"creationDate":'         || APEX_JSON.STRINGIFY(NVL(r.CREATION_DATE,''))         ||
            ',"lastUpdatedBy":'        || APEX_JSON.STRINGIFY(NVL(r.LAST_UPDATED_BY,''))       ||
            ',"lastUpdateDate":'       || APEX_JSON.STRINGIFY(NVL(r.LAST_UPDATE_DATE,''))      ||
            '}';
        DBMS_LOB.APPEND(v_clob, v_buf);
    END LOOP;

    DBMS_LOB.APPEND(v_clob, ']}');
    HTP.P(v_clob);
    DBMS_LOB.FREETEMPORARY(v_clob);
EXCEPTION
    WHEN OTHERS THEN
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 2. POST cash/bankstatements  — Create / update header + lines
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/bankstatements',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_body        CLOB;
    v_header_json CLOB;
    v_lines_json  CLOB;
    v_stmt_id     NUMBER;
    v_count       NUMBER := 0;
    v_error       VARCHAR2(4000);
    v_dest_off    INTEGER := 1;
    v_src_off     INTEGER := 1;
    v_lang        INTEGER := DBMS_LOB.DEFAULT_LANG_CTX;
    v_warn        INTEGER;
BEGIN
    -- Convert BLOB body to CLOB (reads :body once, types match)
    DBMS_LOB.CREATETEMPORARY(v_body, TRUE);
    DBMS_LOB.CONVERTTOCLOB(
        dest_lob     => v_body,
        src_blob     => :body,
        amount       => DBMS_LOB.LOBMAXSIZE,
        dest_offset  => v_dest_off,
        src_offset   => v_src_off,
        blob_csid    => NLS_CHARSET_ID('AL32UTF8'),
        lang_context => v_lang,
        warning      => v_warn
    );

    -- Extract header and lines sub-objects
    SELECT JSON_QUERY(v_body, '$.header'),
           JSON_QUERY(v_body, '$.lines')
    INTO   v_header_json, v_lines_json
    FROM   DUAL;

    -- Save header
    RR_BANK_STMT_PKG.save_header(
        p_json    => v_header_json,
        p_stmt_id => v_stmt_id,
        p_error   => v_error
    );
    IF v_error IS NOT NULL THEN
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(v_error) || '}');
        RETURN;
    END IF;

    -- Save lines if provided
    IF v_lines_json IS NOT NULL AND v_lines_json != 'null' THEN
        RR_BANK_STMT_PKG.save_lines(
            p_stmt_id => v_stmt_id,
            p_json    => v_lines_json,
            p_count   => v_count,
            p_error   => v_error
        );
        IF v_error IS NOT NULL THEN
            HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(v_error) || '}');
            RETURN;
        END IF;
    END IF;

    -- Recalculate totals
    RR_BANK_STMT_PKG.recalc_totals(p_stmt_id => v_stmt_id);

    HTP.P('{"status":"success","statementId":' || v_stmt_id ||
          ',"linesProcessed":'                 || v_count   || '}');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_LOB.FREETEMPORARY(v_body);
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 3. GET cash/bankstatements/{stmt_id}  — Get single statement with lines
--    Uses APEX_JSON output API — zero manual string concatenation,
--    so VARCHAR2 size limits cannot cause ORA-06502.
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/bankstatements/:stmt_id',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_clob   CLOB;
    v_exists NUMBER := 0;

    CURSOR c_hdr IS
        SELECT
            h.STATEMENT_ID,
            h.STATEMENT_NUMBER,
            h.BANK_ACCOUNT_NUMBER,
            h.BANK_ACCOUNT_NAME,
            TO_CHAR(h.STATEMENT_DATE, 'YYYY-MM-DD')                     AS STATEMENT_DATE,
            h.CURRENCY_CODE,
            NVL(h.OPENING_BALANCE, 0)                                    AS OPENING_BALANCE,
            NVL(h.CLOSING_BALANCE, 0)                                    AS CLOSING_BALANCE,
            NVL(h.TOTAL_CREDITS,   0)                                    AS TOTAL_CREDITS,
            NVL(h.TOTAL_DEBITS,    0)                                    AS TOTAL_DEBITS,
            h.STATUS,
            h.BUSINESS_UNIT_NAME,
            h.DESCRIPTION,
            h.CREATED_BY,
            TO_CHAR(h.CREATION_DATE,    'YYYY-MM-DD"T"HH24:MI:SS')      AS CREATION_DATE,
            h.LAST_UPDATED_BY,
            TO_CHAR(h.LAST_UPDATE_DATE, 'YYYY-MM-DD"T"HH24:MI:SS')      AS LAST_UPDATE_DATE
        FROM   RR_BANK_STATEMENT_HEADER h
        WHERE  h.STATEMENT_ID = :stmt_id;

    CURSOR c_lines IS
        SELECT
            l.LINE_ID,
            l.STATEMENT_ID,
            l.LINE_NUMBER,
            TO_CHAR(l.TRANSACTION_DATE, 'YYYY-MM-DD')                   AS TRANSACTION_DATE,
            TO_CHAR(l.VALUE_DATE,       'YYYY-MM-DD')                   AS VALUE_DATE,
            NVL(l.AMOUNT, 0)                                             AS AMOUNT,
            l.TRANSACTION_CODE,
            l.DESCRIPTION,
            l.REFERENCE,
            l.BANK_TXN_REFERENCE,
            l.COUNTERPARTY_NAME,
            l.COUNTERPARTY_ACCOUNT,
            NVL(l.RECON_STATUS, 'UNRECONCILED')                          AS RECON_STATUS,
            l.RECON_AMOUNT,
            TO_CHAR(l.RECON_DATE,       'YYYY-MM-DD"T"HH24:MI:SS')      AS RECON_DATE,
            l.RECON_BY,
            l.RECON_TXN_TYPE,
            l.RECON_TXN_ID,
            l.RECON_TXN_NUMBER,
            l.RECON_REFERENCE,
            l.RECON_NOTES,
            l.CREATED_BY,
            TO_CHAR(l.CREATION_DATE,    'YYYY-MM-DD"T"HH24:MI:SS')      AS CREATION_DATE,
            l.LAST_UPDATED_BY,
            TO_CHAR(l.LAST_UPDATE_DATE, 'YYYY-MM-DD"T"HH24:MI:SS')      AS LAST_UPDATE_DATE
        FROM   RR_BANK_STATEMENT_LINES l
        WHERE  l.STATEMENT_ID = :stmt_id
        ORDER  BY l.LINE_NUMBER, l.LINE_ID;
BEGIN
    SELECT COUNT(1) INTO v_exists
    FROM   RR_BANK_STATEMENT_HEADER
    WHERE  STATEMENT_ID = :stmt_id;

    IF v_exists = 0 THEN
        HTP.P('{"status":"error","message":"Statement ' || :stmt_id || ' not found"}');
        RETURN;
    END IF;

    -- Use APEX_JSON output API — all JSON building is done internally by Oracle
    -- using CLOBs, so no VARCHAR2 buffers can overflow.
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;

    APEX_JSON.OPEN_OBJECT;                             -- {
    APEX_JSON.WRITE('status', 'success');

    -- ---- header ----
    APEX_JSON.OPEN_OBJECT('header');                   --   "header":{
    FOR r IN c_hdr LOOP
        APEX_JSON.WRITE('statementId',       r.STATEMENT_ID);
        APEX_JSON.WRITE('statementNumber',   r.STATEMENT_NUMBER);
        APEX_JSON.WRITE('bankAccountNumber', r.BANK_ACCOUNT_NUMBER);
        APEX_JSON.WRITE('bankAccountName',   r.BANK_ACCOUNT_NAME);
        APEX_JSON.WRITE('statementDate',     r.STATEMENT_DATE);
        APEX_JSON.WRITE('currencyCode',      r.CURRENCY_CODE);
        APEX_JSON.WRITE('openingBalance',    r.OPENING_BALANCE);
        APEX_JSON.WRITE('closingBalance',    r.CLOSING_BALANCE);
        APEX_JSON.WRITE('totalCredits',      r.TOTAL_CREDITS);
        APEX_JSON.WRITE('totalDebits',       r.TOTAL_DEBITS);
        APEX_JSON.WRITE('status',            r.STATUS);
        APEX_JSON.WRITE('businessUnitName',  r.BUSINESS_UNIT_NAME);
        APEX_JSON.WRITE('description',       r.DESCRIPTION);
        APEX_JSON.WRITE('createdBy',         r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',      r.CREATION_DATE);
        APEX_JSON.WRITE('lastUpdatedBy',     r.LAST_UPDATED_BY);
        APEX_JSON.WRITE('lastUpdateDate',    r.LAST_UPDATE_DATE);
    END LOOP;
    APEX_JSON.CLOSE_OBJECT;                            --   }

    -- ---- lines ----
    APEX_JSON.OPEN_ARRAY('lines');                     --   "lines":[
    FOR r IN c_lines LOOP
        APEX_JSON.OPEN_OBJECT;                         --     {
        APEX_JSON.WRITE('lineId',              r.LINE_ID);
        APEX_JSON.WRITE('statementId',         r.STATEMENT_ID);
        APEX_JSON.WRITE('lineNumber',          r.LINE_NUMBER);
        APEX_JSON.WRITE('transactionDate',     r.TRANSACTION_DATE);
        APEX_JSON.WRITE('valueDate',           r.VALUE_DATE);
        APEX_JSON.WRITE('amount',              r.AMOUNT);
        APEX_JSON.WRITE('transactionCode',     r.TRANSACTION_CODE);
        APEX_JSON.WRITE('description',         r.DESCRIPTION);
        APEX_JSON.WRITE('reference',           r.REFERENCE);
        APEX_JSON.WRITE('bankTxnReference',    r.BANK_TXN_REFERENCE);
        APEX_JSON.WRITE('counterpartyName',    r.COUNTERPARTY_NAME);
        APEX_JSON.WRITE('counterpartyAccount', r.COUNTERPARTY_ACCOUNT);
        APEX_JSON.WRITE('reconStatus',         r.RECON_STATUS);
        APEX_JSON.WRITE('reconAmount',         r.RECON_AMOUNT);
        APEX_JSON.WRITE('reconDate',           r.RECON_DATE);
        APEX_JSON.WRITE('reconBy',             r.RECON_BY);
        APEX_JSON.WRITE('reconTxnType',        r.RECON_TXN_TYPE);
        APEX_JSON.WRITE('reconTxnId',          r.RECON_TXN_ID);
        APEX_JSON.WRITE('reconTxnNumber',      r.RECON_TXN_NUMBER);
        APEX_JSON.WRITE('reconReference',      r.RECON_REFERENCE);
        APEX_JSON.WRITE('reconNotes',          r.RECON_NOTES);
        APEX_JSON.WRITE('createdBy',           r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',        r.CREATION_DATE);
        APEX_JSON.WRITE('lastUpdatedBy',       r.LAST_UPDATED_BY);
        APEX_JSON.WRITE('lastUpdateDate',      r.LAST_UPDATE_DATE);
        APEX_JSON.CLOSE_OBJECT;                        --     }
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;                             --   ]

    APEX_JSON.CLOSE_OBJECT;                            -- }

    v_clob := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    HTP.P(v_clob);
EXCEPTION
    WHEN OTHERS THEN
        APEX_JSON.FREE_OUTPUT;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 4. POST cash/bankstatements/{stmt_id}/lines/delete  — Delete a line
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/bankstatements/:stmt_id/lines/delete',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_line_id NUMBER;
    v_error   VARCHAR2(4000);
BEGIN
    SELECT jt.line_id
    INTO   v_line_id
    FROM   JSON_TABLE(:body_text, '$'
             COLUMNS (line_id NUMBER PATH '$.lineId')
           ) jt;

    RR_BANK_STMT_PKG.delete_line(
        p_line_id => v_line_id,
        p_error   => v_error
    );

    IF v_error IS NOT NULL THEN
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(v_error) || '}');
    ELSE
        -- Recalculate statement totals after deletion
        RR_BANK_STMT_PKG.recalc_totals(p_stmt_id => :stmt_id);
        HTP.P('{"status":"success","lineId":' || v_line_id || '}');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 5. POST cash/bankstatements/{stmt_id}/reconcile  — Reconcile a line
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/bankstatements/:stmt_id/reconcile',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_line_id     NUMBER;
    v_txn_type    VARCHAR2(30);
    v_txn_id      NUMBER;
    v_txn_number  VARCHAR2(200);
    v_recon_amt   NUMBER;
    v_notes       VARCHAR2(1000);
    v_user        VARCHAR2(150) := 'ERP_USER';
    v_error       VARCHAR2(4000);
BEGIN
    SELECT jt.line_id,
           jt.txn_type,
           jt.txn_id,
           jt.txn_number,
           jt.recon_amount,
           jt.notes
    INTO   v_line_id, v_txn_type, v_txn_id, v_txn_number, v_recon_amt, v_notes
    FROM   JSON_TABLE(:body_text, '$'
             COLUMNS (
               line_id     NUMBER        PATH '$.lineId',
               txn_type    VARCHAR2(30)  PATH '$.txnType',
               txn_id      NUMBER        PATH '$.txnId',
               txn_number  VARCHAR2(200) PATH '$.txnNumber',
               recon_amount NUMBER       PATH '$.reconAmount',
               notes       VARCHAR2(1000) PATH '$.notes'
             )
           ) jt;

    RR_BANK_STMT_PKG.reconcile_line(
        p_line_id      => v_line_id,
        p_txn_type     => v_txn_type,
        p_txn_id       => v_txn_id,
        p_txn_number   => v_txn_number,
        p_recon_amount => v_recon_amt,
        p_notes        => v_notes,
        p_user         => v_user,
        p_error        => v_error
    );

    IF v_error IS NOT NULL THEN
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(v_error) || '}');
    ELSE
        HTP.P('{"status":"success","lineId":' || v_line_id || '}');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/
