-- ============================================
-- Table: RR_BANK_ACCOUNTS
-- Description: Stores bank account information from Oracle Fusion
-- ============================================

CREATE TABLE RR_BANK_ACCOUNTS (
    ID                                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BANK_ACCOUNT_ID                         NUMBER NOT NULL,
    BANK_ACCOUNT_NAME                       VARCHAR2(360) NOT NULL,
    BANK_ACCOUNT_NAME_ALT                   VARCHAR2(360),
    BANK_ACCOUNT_NUMBER                     VARCHAR2(100),
    BANK_ACCOUNT_NUMBER_ELECTRONIC          VARCHAR2(100),
    IBAN_NUMBER                             VARCHAR2(100),
    MASKED_ACCOUNT_NUMBER                   VARCHAR2(100),
    MASKED_IBAN                             VARCHAR2(100),
    ACCOUNT_HOLDER_NAME                     VARCHAR2(360),
    ACCOUNT_HOLDER_NAME_ALT                 VARCHAR2(360),
    ACCOUNT_SUFFIX                          VARCHAR2(30),
    ACCOUNT_TYPE                            VARCHAR2(60),
    CURRENCY_CODE                           VARCHAR2(15),
    DESCRIPTION                             VARCHAR2(240),
    CHECK_DIGITS                            VARCHAR2(30),
    -- Bank and Branch Info
    BANK_NUMBER                             VARCHAR2(60),
    BRANCH_NUMBER                           VARCHAR2(60),
    BANK_NAME                               VARCHAR2(360),
    BANK_BRANCH_NAME                        VARCHAR2(360),
    COUNTRY_NAME                            VARCHAR2(100),
    -- Legal Entity
    LEGAL_ENTITY_NAME                       VARCHAR2(360),
    -- Flags
    AP_USE_ALLOWED_FLAG                     VARCHAR2(5),
    AR_USE_ALLOWED_FLAG                     VARCHAR2(5),
    PAY_USE_ALLOWED_FLAG                    VARCHAR2(5),
    DATA_SECURITY_FLAG                      VARCHAR2(5),
    MULTI_CURRENCY_ALLOWED_FLAG             VARCHAR2(5),
    NETTING_ACCOUNT_FLAG                    VARCHAR2(5),
    POOLED_FLAG                             VARCHAR2(5),
    ZERO_AMOUNT_ALLOWED                     VARCHAR2(5),
    MULTI_CASH_RECON_ENABLED_FLAG           VARCHAR2(5),
    -- Amounts
    MINIMUM_CHECK_AMOUNT                    NUMBER,
    MAXIMUM_CHECK_AMOUNT                    NUMBER,
    MAXIMUM_OUTLAY                          NUMBER,
    TARGET_BALANCE                          NUMBER,
    -- Account Combinations
    CASH_ACCOUNT_COMBINATION                VARCHAR2(500),
    CASH_CLEARING_ACCOUNT_COMBINATION       VARCHAR2(500),
    RECON_DIFFERENCE_ACCOUNT_COMBINATION    VARCHAR2(500),
    PDC_ACCOUNT_COMBINATION                 VARCHAR2(500),
    CASH_CCID_FIXED_SEGMENTS                VARCHAR2(500),
    -- Dates
    END_DATE                                DATE,
    RECON_START_DATE                        DATE,
    GL_RECON_START_DATE                     DATE,
    -- Other fields
    AGENCY_LOCATION_CODE                    VARCHAR2(60),
    EFT_USER_NUMBER                         VARCHAR2(60),
    SECONDARY_ACCOUNT_REFERENCE             VARCHAR2(100),
    REVERSAL_PROCESSING_METHOD              VARCHAR2(60),
    RULESET_NAME                            VARCHAR2(100),
    TOLERANCE_RULE_NAME                     VARCHAR2(100),
    PARSING_RULE_SET_NAME                   VARCHAR2(100),
    BANK_EXCHANGE_RATE_TYPE                 VARCHAR2(60),
    ACCOUNTING_CONVERSION_RATE_TYPE         VARCHAR2(60),
    TRANSACTION_CALENDAR                    VARCHAR2(100),
    BANK_COMPANY_IDENTIFIER                 VARCHAR2(100),
    -- Audit fields
    CREATED_BY                              VARCHAR2(150),
    CREATION_DATE                           TIMESTAMP,
    LAST_UPDATE_DATE                        TIMESTAMP,
    LAST_UPDATE_LOGIN                       VARCHAR2(100),
    LAST_UPDATED_BY                         VARCHAR2(150),
    SYNC_DATE                               TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_RR_BANK_ACCOUNTS_ID UNIQUE (BANK_ACCOUNT_ID)
);

-- Indexes
CREATE INDEX IDX_RR_BANK_ACCT_NAME ON RR_BANK_ACCOUNTS(BANK_ACCOUNT_NAME);
CREATE INDEX IDX_RR_BANK_ACCT_NUMBER ON RR_BANK_ACCOUNTS(BANK_ACCOUNT_NUMBER);
CREATE INDEX IDX_RR_BANK_ACCT_IBAN ON RR_BANK_ACCOUNTS(IBAN_NUMBER);
CREATE INDEX IDX_RR_BANK_ACCT_BANK ON RR_BANK_ACCOUNTS(BANK_NAME);
CREATE INDEX IDX_RR_BANK_ACCT_CURRENCY ON RR_BANK_ACCOUNTS(CURRENCY_CODE);
CREATE INDEX IDX_RR_BANK_ACCT_LE ON RR_BANK_ACCOUNTS(LEGAL_ENTITY_NAME);

-- Comments
COMMENT ON TABLE RR_BANK_ACCOUNTS IS 'Bank accounts master data synced from Oracle Fusion';
COMMENT ON COLUMN RR_BANK_ACCOUNTS.BANK_ACCOUNT_ID IS 'Unique bank account identifier from Fusion';
COMMENT ON COLUMN RR_BANK_ACCOUNTS.IBAN_NUMBER IS 'International Bank Account Number';
COMMENT ON COLUMN RR_BANK_ACCOUNTS.CASH_ACCOUNT_COMBINATION IS 'GL cash account code combination';
COMMENT ON COLUMN RR_BANK_ACCOUNTS.PDC_ACCOUNT_COMBINATION IS 'GL PDC (Post-Dated Cheque) account code combination';
COMMENT ON COLUMN RR_BANK_ACCOUNTS.SYNC_DATE IS 'Timestamp when record was synced';

-- ============================================
-- Migration: Add PDC_ACCOUNT_COMBINATION column (run once on existing DBs)
-- ============================================
ALTER TABLE RR_BANK_ACCOUNTS ADD (PDC_ACCOUNT_COMBINATION VARCHAR2(500));
/

-- ============================================
-- Procedure: RR_SYNC_BANK_ACCOUNTS
-- Description: Upsert bank accounts from JSON payload
-- ============================================

CREATE OR REPLACE PROCEDURE RR_SYNC_BANK_ACCOUNTS (
    p_json IN CLOB,
    p_count OUT NUMBER,
    p_error OUT VARCHAR2
) AS
BEGIN
    p_count := 0;
    p_error := NULL;

    FOR rec IN (
        SELECT *
        FROM JSON_TABLE(p_json, '$.items[*]'
            COLUMNS (
                bank_account_id                     NUMBER          PATH '$.BankAccountId',
                bank_account_name                   VARCHAR2(360)   PATH '$.BankAccountName',
                bank_account_name_alt               VARCHAR2(360)   PATH '$.BankAccountNameAlt',
                bank_account_number                 VARCHAR2(100)   PATH '$.BankAccountNumber',
                bank_account_number_electronic      VARCHAR2(100)   PATH '$.BankAccountNumberElectronic',
                iban_number                         VARCHAR2(100)   PATH '$.IBANNumber',
                masked_account_number               VARCHAR2(100)   PATH '$.MaskedAccountNumber',
                masked_iban                         VARCHAR2(100)   PATH '$.MaskedIBAN',
                account_holder_name                 VARCHAR2(360)   PATH '$.AccountHolderName',
                account_holder_name_alt             VARCHAR2(360)   PATH '$.AccountHolderNameAlt',
                account_suffix                      VARCHAR2(30)    PATH '$.AccountSuffix',
                account_type                        VARCHAR2(60)    PATH '$.AccountType',
                currency_code                       VARCHAR2(15)    PATH '$.CurrencyCode',
                description                         VARCHAR2(240)   PATH '$.Description',
                check_digits                        VARCHAR2(30)    PATH '$.CheckDigits',
                bank_number                         VARCHAR2(60)    PATH '$.BankNumber',
                branch_number                       VARCHAR2(60)    PATH '$.BranchNumber',
                bank_name                           VARCHAR2(360)   PATH '$.BankName',
                bank_branch_name                    VARCHAR2(360)   PATH '$.BankBranchName',
                country_name                        VARCHAR2(100)   PATH '$.CountryName',
                legal_entity_name                   VARCHAR2(360)   PATH '$.LegalEntityName',
                ap_use_allowed_flag                 VARCHAR2(5)     PATH '$.ApUseAllowedFlag',
                ar_use_allowed_flag                 VARCHAR2(5)     PATH '$.ArUseAllowedFlag',
                pay_use_allowed_flag                VARCHAR2(5)     PATH '$.PayUseAllowedFlag',
                data_security_flag                  VARCHAR2(5)     PATH '$.DataSecurityFlag',
                multi_currency_allowed_flag         VARCHAR2(5)     PATH '$.MultiCurrencyAllowedFlag',
                netting_account_flag                VARCHAR2(5)     PATH '$.NettingAccountFlag',
                pooled_flag                         VARCHAR2(5)     PATH '$.PooledFlag',
                zero_amount_allowed                 VARCHAR2(5)     PATH '$.ZeroAmountAllowed',
                multi_cash_recon_enabled_flag       VARCHAR2(5)     PATH '$.MultiCashReconEnabledFlag',
                minimum_check_amount                NUMBER          PATH '$.MinimumCheckAmount',
                maximum_check_amount                NUMBER          PATH '$.MaximumCheckAmount',
                maximum_outlay                      NUMBER          PATH '$.MaximumOutlay',
                target_balance                      NUMBER          PATH '$.TargetBalance',
                cash_account_combination            VARCHAR2(500)   PATH '$.CashAccountCombination',
                cash_clearing_account_combination   VARCHAR2(500)   PATH '$.CashClearingAccountCombination',
                recon_diff_account_combination      VARCHAR2(500)   PATH '$.ReconciliationDifferenceAccountCombination',
                cash_ccid_fixed_segments            VARCHAR2(500)   PATH '$.CashCcidFixedSegments',
                end_date                            VARCHAR2(30)    PATH '$.EndDate',
                recon_start_date                    VARCHAR2(30)    PATH '$.ReconStartDate',
                gl_recon_start_date                 VARCHAR2(30)    PATH '$.GlReconStartDate',
                agency_location_code                VARCHAR2(60)    PATH '$.AgencyLocationCode',
                eft_user_number                     VARCHAR2(60)    PATH '$.EFTUserNumber',
                secondary_account_reference         VARCHAR2(100)   PATH '$.SecondaryAccountReference',
                reversal_processing_method          VARCHAR2(60)    PATH '$.ReversalProcessingMethod',
                ruleset_name                        VARCHAR2(100)   PATH '$.RulesetName',
                tolerance_rule_name                 VARCHAR2(100)   PATH '$.ToleranceRuleName',
                parsing_rule_set_name               VARCHAR2(100)   PATH '$.ParsingRuleSetName',
                bank_exchange_rate_type             VARCHAR2(60)    PATH '$.BankExchangeRateType',
                accounting_conversion_rate_type     VARCHAR2(60)    PATH '$.AccountingConversionRateType',
                transaction_calendar                VARCHAR2(100)   PATH '$.TransactionCalendar',
                bank_company_identifier             VARCHAR2(100)   PATH '$.BankCompanyIdentifier',
                created_by                          VARCHAR2(150)   PATH '$.CreatedBy',
                creation_date                       TIMESTAMP       PATH '$.CreationDate',
                last_update_date                    TIMESTAMP       PATH '$.LastUpdateDate',
                last_update_login                   VARCHAR2(100)   PATH '$.LastUpdateLogin',
                last_updated_by                     VARCHAR2(150)   PATH '$.LastUpdatedBy'
            )
        )
    ) LOOP
        -- Merge (upsert) the record
        MERGE INTO RR_BANK_ACCOUNTS tgt
        USING (
            SELECT
                rec.bank_account_id                     AS bank_account_id,
                rec.bank_account_name                   AS bank_account_name,
                rec.bank_account_name_alt               AS bank_account_name_alt,
                rec.bank_account_number                 AS bank_account_number,
                rec.bank_account_number_electronic      AS bank_account_number_electronic,
                rec.iban_number                         AS iban_number,
                rec.masked_account_number               AS masked_account_number,
                rec.masked_iban                         AS masked_iban,
                rec.account_holder_name                 AS account_holder_name,
                rec.account_holder_name_alt             AS account_holder_name_alt,
                rec.account_suffix                      AS account_suffix,
                rec.account_type                        AS account_type,
                rec.currency_code                       AS currency_code,
                rec.description                         AS description,
                rec.check_digits                        AS check_digits,
                rec.bank_number                         AS bank_number,
                rec.branch_number                       AS branch_number,
                rec.bank_name                           AS bank_name,
                rec.bank_branch_name                    AS bank_branch_name,
                rec.country_name                        AS country_name,
                rec.legal_entity_name                   AS legal_entity_name,
                rec.ap_use_allowed_flag                 AS ap_use_allowed_flag,
                rec.ar_use_allowed_flag                 AS ar_use_allowed_flag,
                rec.pay_use_allowed_flag                AS pay_use_allowed_flag,
                rec.data_security_flag                  AS data_security_flag,
                rec.multi_currency_allowed_flag         AS multi_currency_allowed_flag,
                rec.netting_account_flag                AS netting_account_flag,
                rec.pooled_flag                         AS pooled_flag,
                rec.zero_amount_allowed                 AS zero_amount_allowed,
                rec.multi_cash_recon_enabled_flag       AS multi_cash_recon_enabled_flag,
                rec.minimum_check_amount                AS minimum_check_amount,
                rec.maximum_check_amount                AS maximum_check_amount,
                rec.maximum_outlay                      AS maximum_outlay,
                rec.target_balance                      AS target_balance,
                rec.cash_account_combination            AS cash_account_combination,
                rec.cash_clearing_account_combination   AS cash_clearing_account_combination,
                rec.recon_diff_account_combination      AS recon_diff_account_combination,
                rec.cash_ccid_fixed_segments            AS cash_ccid_fixed_segments,
                TO_DATE(rec.end_date, 'YYYY-MM-DD')     AS end_date,
                TO_DATE(rec.recon_start_date, 'YYYY-MM-DD') AS recon_start_date,
                TO_DATE(rec.gl_recon_start_date, 'YYYY-MM-DD') AS gl_recon_start_date,
                rec.agency_location_code                AS agency_location_code,
                rec.eft_user_number                     AS eft_user_number,
                rec.secondary_account_reference         AS secondary_account_reference,
                rec.reversal_processing_method          AS reversal_processing_method,
                rec.ruleset_name                        AS ruleset_name,
                rec.tolerance_rule_name                 AS tolerance_rule_name,
                rec.parsing_rule_set_name               AS parsing_rule_set_name,
                rec.bank_exchange_rate_type             AS bank_exchange_rate_type,
                rec.accounting_conversion_rate_type     AS accounting_conversion_rate_type,
                rec.transaction_calendar                AS transaction_calendar,
                rec.bank_company_identifier             AS bank_company_identifier,
                rec.created_by                          AS created_by,
                rec.creation_date                       AS creation_date,
                rec.last_update_date                    AS last_update_date,
                rec.last_update_login                   AS last_update_login,
                rec.last_updated_by                     AS last_updated_by
            FROM DUAL
        ) src
        ON (tgt.BANK_ACCOUNT_ID = src.bank_account_id)
        WHEN MATCHED THEN
            UPDATE SET
                tgt.BANK_ACCOUNT_NAME                   = src.bank_account_name,
                tgt.BANK_ACCOUNT_NAME_ALT               = src.bank_account_name_alt,
                tgt.BANK_ACCOUNT_NUMBER                 = src.bank_account_number,
                tgt.BANK_ACCOUNT_NUMBER_ELECTRONIC      = src.bank_account_number_electronic,
                tgt.IBAN_NUMBER                         = src.iban_number,
                tgt.MASKED_ACCOUNT_NUMBER               = src.masked_account_number,
                tgt.MASKED_IBAN                         = src.masked_iban,
                tgt.ACCOUNT_HOLDER_NAME                 = src.account_holder_name,
                tgt.ACCOUNT_HOLDER_NAME_ALT             = src.account_holder_name_alt,
                tgt.ACCOUNT_SUFFIX                      = src.account_suffix,
                tgt.ACCOUNT_TYPE                        = src.account_type,
                tgt.CURRENCY_CODE                       = src.currency_code,
                tgt.DESCRIPTION                         = src.description,
                tgt.CHECK_DIGITS                        = src.check_digits,
                tgt.BANK_NUMBER                         = src.bank_number,
                tgt.BRANCH_NUMBER                       = src.branch_number,
                tgt.BANK_NAME                           = src.bank_name,
                tgt.BANK_BRANCH_NAME                    = src.bank_branch_name,
                tgt.COUNTRY_NAME                        = src.country_name,
                tgt.LEGAL_ENTITY_NAME                   = src.legal_entity_name,
                tgt.AP_USE_ALLOWED_FLAG                 = src.ap_use_allowed_flag,
                tgt.AR_USE_ALLOWED_FLAG                 = src.ar_use_allowed_flag,
                tgt.PAY_USE_ALLOWED_FLAG                = src.pay_use_allowed_flag,
                tgt.DATA_SECURITY_FLAG                  = src.data_security_flag,
                tgt.MULTI_CURRENCY_ALLOWED_FLAG         = src.multi_currency_allowed_flag,
                tgt.NETTING_ACCOUNT_FLAG                = src.netting_account_flag,
                tgt.POOLED_FLAG                         = src.pooled_flag,
                tgt.ZERO_AMOUNT_ALLOWED                 = src.zero_amount_allowed,
                tgt.MULTI_CASH_RECON_ENABLED_FLAG       = src.multi_cash_recon_enabled_flag,
                tgt.MINIMUM_CHECK_AMOUNT                = src.minimum_check_amount,
                tgt.MAXIMUM_CHECK_AMOUNT                = src.maximum_check_amount,
                tgt.MAXIMUM_OUTLAY                      = src.maximum_outlay,
                tgt.TARGET_BALANCE                      = src.target_balance,
                tgt.CASH_ACCOUNT_COMBINATION            = src.cash_account_combination,
                tgt.CASH_CLEARING_ACCOUNT_COMBINATION   = src.cash_clearing_account_combination,
                tgt.RECON_DIFFERENCE_ACCOUNT_COMBINATION = src.recon_diff_account_combination,
                tgt.CASH_CCID_FIXED_SEGMENTS            = src.cash_ccid_fixed_segments,
                tgt.END_DATE                            = src.end_date,
                tgt.RECON_START_DATE                    = src.recon_start_date,
                tgt.GL_RECON_START_DATE                 = src.gl_recon_start_date,
                tgt.AGENCY_LOCATION_CODE                = src.agency_location_code,
                tgt.EFT_USER_NUMBER                     = src.eft_user_number,
                tgt.SECONDARY_ACCOUNT_REFERENCE         = src.secondary_account_reference,
                tgt.REVERSAL_PROCESSING_METHOD          = src.reversal_processing_method,
                tgt.RULESET_NAME                        = src.ruleset_name,
                tgt.TOLERANCE_RULE_NAME                 = src.tolerance_rule_name,
                tgt.PARSING_RULE_SET_NAME               = src.parsing_rule_set_name,
                tgt.BANK_EXCHANGE_RATE_TYPE             = src.bank_exchange_rate_type,
                tgt.ACCOUNTING_CONVERSION_RATE_TYPE     = src.accounting_conversion_rate_type,
                tgt.TRANSACTION_CALENDAR                = src.transaction_calendar,
                tgt.BANK_COMPANY_IDENTIFIER             = src.bank_company_identifier,
                tgt.CREATED_BY                          = src.created_by,
                tgt.CREATION_DATE                       = src.creation_date,
                tgt.LAST_UPDATE_DATE                    = src.last_update_date,
                tgt.LAST_UPDATE_LOGIN                   = src.last_update_login,
                tgt.LAST_UPDATED_BY                     = src.last_updated_by,
                tgt.SYNC_DATE                           = SYSTIMESTAMP
        WHEN NOT MATCHED THEN
            INSERT (
                BANK_ACCOUNT_ID, BANK_ACCOUNT_NAME, BANK_ACCOUNT_NAME_ALT,
                BANK_ACCOUNT_NUMBER, BANK_ACCOUNT_NUMBER_ELECTRONIC, IBAN_NUMBER,
                MASKED_ACCOUNT_NUMBER, MASKED_IBAN, ACCOUNT_HOLDER_NAME,
                ACCOUNT_HOLDER_NAME_ALT, ACCOUNT_SUFFIX, ACCOUNT_TYPE,
                CURRENCY_CODE, DESCRIPTION, CHECK_DIGITS,
                BANK_NUMBER, BRANCH_NUMBER, BANK_NAME, BANK_BRANCH_NAME, COUNTRY_NAME,
                LEGAL_ENTITY_NAME, AP_USE_ALLOWED_FLAG, AR_USE_ALLOWED_FLAG,
                PAY_USE_ALLOWED_FLAG, DATA_SECURITY_FLAG, MULTI_CURRENCY_ALLOWED_FLAG,
                NETTING_ACCOUNT_FLAG, POOLED_FLAG, ZERO_AMOUNT_ALLOWED,
                MULTI_CASH_RECON_ENABLED_FLAG, MINIMUM_CHECK_AMOUNT, MAXIMUM_CHECK_AMOUNT,
                MAXIMUM_OUTLAY, TARGET_BALANCE, CASH_ACCOUNT_COMBINATION,
                CASH_CLEARING_ACCOUNT_COMBINATION, RECON_DIFFERENCE_ACCOUNT_COMBINATION,
                CASH_CCID_FIXED_SEGMENTS, END_DATE, RECON_START_DATE, GL_RECON_START_DATE,
                AGENCY_LOCATION_CODE, EFT_USER_NUMBER, SECONDARY_ACCOUNT_REFERENCE,
                REVERSAL_PROCESSING_METHOD, RULESET_NAME, TOLERANCE_RULE_NAME,
                PARSING_RULE_SET_NAME, BANK_EXCHANGE_RATE_TYPE, ACCOUNTING_CONVERSION_RATE_TYPE,
                TRANSACTION_CALENDAR, BANK_COMPANY_IDENTIFIER,
                CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LAST_UPDATED_BY,
                SYNC_DATE
            ) VALUES (
                src.bank_account_id, src.bank_account_name, src.bank_account_name_alt,
                src.bank_account_number, src.bank_account_number_electronic, src.iban_number,
                src.masked_account_number, src.masked_iban, src.account_holder_name,
                src.account_holder_name_alt, src.account_suffix, src.account_type,
                src.currency_code, src.description, src.check_digits,
                src.bank_number, src.branch_number, src.bank_name, src.bank_branch_name, src.country_name,
                src.legal_entity_name, src.ap_use_allowed_flag, src.ar_use_allowed_flag,
                src.pay_use_allowed_flag, src.data_security_flag, src.multi_currency_allowed_flag,
                src.netting_account_flag, src.pooled_flag, src.zero_amount_allowed,
                src.multi_cash_recon_enabled_flag, src.minimum_check_amount, src.maximum_check_amount,
                src.maximum_outlay, src.target_balance, src.cash_account_combination,
                src.cash_clearing_account_combination, src.recon_diff_account_combination,
                src.cash_ccid_fixed_segments, src.end_date, src.recon_start_date, src.gl_recon_start_date,
                src.agency_location_code, src.eft_user_number, src.secondary_account_reference,
                src.reversal_processing_method, src.ruleset_name, src.tolerance_rule_name,
                src.parsing_rule_set_name, src.bank_exchange_rate_type, src.accounting_conversion_rate_type,
                src.transaction_calendar, src.bank_company_identifier,
                src.created_by, src.creation_date, src.last_update_date, src.last_update_login, src.last_updated_by,
                SYSTIMESTAMP
            );

        p_count := p_count + 1;
    END LOOP;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        p_error := SQLERRM;
        ROLLBACK;
END RR_SYNC_BANK_ACCOUNTS;
/

-- ============================================
-- APEX REST Handler for POST /banks/bankaccounts
-- ============================================

DECLARE
    l_module_id     NUMBER;
    l_template_id   NUMBER;
BEGIN
    -- Use existing reerp module (already created)
    -- The endpoint will be: /ords/bcldifc/reerp/banks/bankaccounts
    NULL;

    -- Define template
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'reerp',
        p_pattern        => 'banks/bankaccounts',
        p_priority       => 0,
        p_etag_type      => 'HASH',
        p_etag_query     => NULL,
        p_comments       => 'Bank accounts sync endpoint'
    );

    -- Define GET handler (LOV) — collection feed; ORDS serialises column names as lowercase snake_case
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'banks/bankaccounts',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_collection_feed,
        p_items_per_page => 0,
        p_mimes_allowed  => '',
        p_comments       => 'Get bank accounts list for LOV',
        p_source         => q'[
SELECT BANK_ACCOUNT_ID,
       BANK_ACCOUNT_NAME,
       BANK_ACCOUNT_NUMBER,
       CURRENCY_CODE,
       DESCRIPTION,
       BANK_NUMBER,
       BRANCH_NUMBER,
       LEGAL_ENTITY_NAME,
       CASH_ACCOUNT_COMBINATION,
       CASH_CLEARING_ACCOUNT_COMBINATION,
       PDC_ACCOUNT_COMBINATION
  FROM RR_BANK_ACCOUNTS
 ORDER BY BANK_ACCOUNT_NAME
]'
    );

    -- Define POST handler
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'banks/bankaccounts',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Sync bank accounts from Oracle Fusion',
        p_source         => q'[
DECLARE
    l_json   CLOB;
    l_count  NUMBER;
    l_error  VARCHAR2(4000);
BEGIN
    l_json := :body_text;

    RR_SYNC_BANK_ACCOUNTS(
        p_json  => l_json,
        p_count => l_count,
        p_error => l_error
    );

    IF l_error IS NOT NULL THEN
        :status_code := 500;
        HTP.P('{"status": "error", "message": "' || l_error || '"}');
    ELSE
        :status_code := 200;
        HTP.P('{"status": "success", "count": ' || l_count || '}');
    END IF;
END;
]'
    );

    COMMIT;
END;
/

-- ============================================
-- ORDS REST Handler: PUT /banks/bankaccounts/:bank_account_id
-- Updates editable account fields (account combinations, description).
-- ============================================

BEGIN
    ORDS.DELETE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'banks/bankaccounts/:bank_account_id'
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'banks/bankaccounts/:bank_account_id',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => 'Single bank account update endpoint'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'banks/bankaccounts/:bank_account_id',
        p_method         => 'PUT',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'Update bank account combinations and description',
        p_source         => q'[
DECLARE
    v_bank_account_id   NUMBER;
    v_cash_acct         VARCHAR2(500);
    v_clearing_acct     VARCHAR2(500);
    v_recon_acct        VARCHAR2(500);
    v_pdc_acct          VARCHAR2(500);
    v_description       VARCHAR2(240);
    v_rows              NUMBER;
BEGIN
    v_bank_account_id := TO_NUMBER(:bank_account_id);

    SELECT jt.cash_account_combination,
           jt.cash_clearing_account_combination,
           jt.reconciliation_difference_account_combination,
           jt.pdc_account_combination,
           jt.description
    INTO   v_cash_acct,
           v_clearing_acct,
           v_recon_acct,
           v_pdc_acct,
           v_description
    FROM   JSON_TABLE(:body_text, '$'
             COLUMNS (
               cash_account_combination                     VARCHAR2(500) PATH '$.cashAccountCombination',
               cash_clearing_account_combination            VARCHAR2(500) PATH '$.cashClearingAccountCombination',
               reconciliation_difference_account_combination VARCHAR2(500) PATH '$.reconciliationDifferenceAccountCombination',
               pdc_account_combination                      VARCHAR2(500) PATH '$.pdcAccountCombination',
               description                                  VARCHAR2(240) PATH '$.description'
             )
           ) jt;

    UPDATE RR_BANK_ACCOUNTS
    SET    CASH_ACCOUNT_COMBINATION              = NVL(v_cash_acct,     CASH_ACCOUNT_COMBINATION),
           CASH_CLEARING_ACCOUNT_COMBINATION     = NVL(v_clearing_acct, CASH_CLEARING_ACCOUNT_COMBINATION),
           RECON_DIFFERENCE_ACCOUNT_COMBINATION  = NVL(v_recon_acct,    RECON_DIFFERENCE_ACCOUNT_COMBINATION),
           PDC_ACCOUNT_COMBINATION               = v_pdc_acct,
           DESCRIPTION                           = NVL(v_description,   DESCRIPTION),
           SYNC_DATE                             = SYSTIMESTAMP
    WHERE  BANK_ACCOUNT_ID = v_bank_account_id;

    v_rows := SQL%ROWCOUNT;
    COMMIT;

    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    IF v_rows = 0 THEN
        HTP.P('{"status":"error","message":"No bank account found for id ' || v_bank_account_id || '"}');
    ELSE
        HTP.P('{"status":"success","bankAccountId":' || v_bank_account_id || ',"rowsUpdated":' || v_rows || '}');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        OWA_UTIL.MIME_HEADER('application/json', FALSE);
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'banks/bankaccounts/:bank_account_id',
        p_method         => 'OPTIONS',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'CORS preflight',
        p_source         => q'[BEGIN OWA_UTIL.MIME_HEADER('application/json', FALSE); HTP.P(''); END;]'
    );
    COMMIT;
END;
/
