-- ============================================================
-- Table: RR_CLAUDE_KEY
-- Description: Stores the Claude (Anthropic) API key for AI agents
-- All active users can read the key via the ORDS endpoint.
-- Only DBAs / admins should INSERT/UPDATE rows directly.
-- ============================================================

CREATE TABLE RR_CLAUDE_KEY (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    API_KEY          VARCHAR2(300) NOT NULL,
    DESCRIPTION      VARCHAR2(200),
    IS_ACTIVE        VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY       VARCHAR2(150),
    CREATION_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY  VARCHAR2(150),
    LAST_UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_RR_CLAUDE_KEY_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

COMMENT ON TABLE  RR_CLAUDE_KEY            IS 'Stores Anthropic Claude API keys for ERP AI agents';
COMMENT ON COLUMN RR_CLAUDE_KEY.API_KEY    IS 'Claude API key — sk-ant-api03-...';
COMMENT ON COLUMN RR_CLAUDE_KEY.IS_ACTIVE  IS 'Y = in use, N = disabled';

-- ============================================================
-- INSERT the key (run once — replace the placeholder value)
-- ============================================================
-- INSERT INTO RR_CLAUDE_KEY (API_KEY, DESCRIPTION, IS_ACTIVE, CREATED_BY)
-- VALUES ('sk-ant-api03-YOUR-KEY-HERE', 'Claude Sonnet — Production', 'Y', 'ADMIN');
-- COMMIT;

-- ============================================================
-- ORDS: GET /settings/claudekey
-- Returns the active API key so the Electron main process can
-- call Claude API without embedding the key in the app bundle.
-- ============================================================
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'settings/claudekey',
            p_method      => 'GET'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    BEGIN
        ORDS.DEFINE_TEMPLATE(
            p_module_name => 'reerp',
            p_pattern     => 'settings/claudekey'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'settings/claudekey',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_comments       => 'Return active Claude API key for Electron AI agents',
        p_source         => '
DECLARE
    l_key VARCHAR2(300);
BEGIN
    BEGIN
        SELECT API_KEY INTO l_key
        FROM   RR_CLAUDE_KEY
        WHERE  IS_ACTIVE = ''Y''
        ORDER BY ID DESC
        FETCH FIRST 1 ROWS ONLY;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        l_key := NULL;
    END;

    IF l_key IS NULL THEN
        :status_code := 404;
        HTP.PRN(''{"status":"error","message":"No active Claude API key found in RR_CLAUDE_KEY"}'');
    ELSE
        :status_code := 200;
        HTP.PRN(''{"status":"success","apiKey":"'' || l_key || ''"}'');
    END IF;
END;
'
    );

    COMMIT;
END;
/
