-- ============================================================
-- Table: RR_CLAUDE_KEY
-- Description: Stores the Claude (Anthropic) API key for AI agents
-- All active users can read the key via the ORDS endpoint.
-- Only DBAs / admins should INSERT/UPDATE rows directly.
-- ============================================================

CREATE TABLE RR_CLAUDE_KEY (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    API_KEY          VARCHAR2(300) NOT NULL,
    DESCRIPTION      VARCHAR2(200),
    IS_ACTIVE        VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY       VARCHAR2(150),
    CREATION_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY  VARCHAR2(150),
    LAST_UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_RR_CLAUDE_KEY_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

COMMENT ON TABLE  RR_CLAUDE_KEY            IS 'Stores Anthropic Claude API keys for ERP AI agents';
COMMENT ON COLUMN RR_CLAUDE_KEY.API_KEY    IS 'Claude API key — sk-ant-api03-...';
COMMENT ON COLUMN RR_CLAUDE_KEY.IS_ACTIVE  IS 'Y = in use, N = disabled';

-- ============================================================
-- INSERT the key (run once — replace the placeholder value)
-- ============================================================
-- INSERT INTO RR_CLAUDE_KEY (API_KEY, DESCRIPTION, IS_ACTIVE, CREATED_BY)
-- VALUES ('sk-ant-api03-YOUR-KEY-HERE', 'Claude Sonnet — Production', 'Y', 'ADMIN');
-- COMMIT;

-- ============================================================
-- ORDS: GET /settings/claudekey
-- Returns the active API key so the Electron main process can
-- call Claude API without embedding the key in the app bundle.
-- ============================================================
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'settings/claudekey',
            p_method      => 'GET'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    BEGIN
        ORDS.DEFINE_TEMPLATE(
            p_module_name => 'reerp',
            p_pattern     => 'settings/claudekey'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'settings/claudekey',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_comments       => 'Return active Claude API key for Electron AI agents',
        p_source         => q'[
DECLARE
    l_key VARCHAR2(300);
BEGIN
    BEGIN
        SELECT TRIM(API_KEY) INTO l_key
        FROM   RR_CLAUDE_KEY
        WHERE  IS_ACTIVE = 'Y'
        ORDER BY ID DESC
        FETCH FIRST 1 ROWS ONLY;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        l_key := NULL;
    END;

    IF l_key IS NULL THEN
        :status_code := 404;
        HTP.PRN('{"status":"error","message":"No active Claude API key found in RR_CLAUDE_KEY"}');
    ELSE
        :status_code := 200;
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('status', 'success');
        APEX_JSON.WRITE('apiKey', l_key);
        APEX_JSON.CLOSE_OBJECT;
    END IF;
END;
]'
    );

    COMMIT;
END;
/

-- ============================================================
-- ORDS Admin CRUD handlers for RR_CLAUDE_KEY
-- GET    /admin/claudekeys        — list all keys (admin)
-- POST   /admin/claudekeys        — insert new key
-- PUT    /admin/claudekeys/:id    — update description / isActive
-- DELETE /admin/claudekeys/:id    — delete key
-- ============================================================

BEGIN
    BEGIN
        ORDS.DEFINE_TEMPLATE(
            p_module_name => 'reerp',
            p_pattern     => 'admin/claudekeys'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    BEGIN
        ORDS.DEFINE_TEMPLATE(
            p_module_name => 'reerp',
            p_pattern     => 'admin/claudekeys/:id'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    -- ── GET /admin/claudekeys ─────────────────────────────────────────────────
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/claudekeys',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_comments       => 'List all Claude API keys',
        p_source         => q'[
DECLARE
    CURSOR c IS
        SELECT ID, API_KEY, DESCRIPTION, IS_ACTIVE,
               CREATED_BY,
               TO_CHAR(CREATION_DATE,    'YYYY-MM-DD"T"HH24:MI:SS') AS CREATION_DATE,
               LAST_UPDATED_BY,
               TO_CHAR(LAST_UPDATE_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS LAST_UPDATE_DATE
          FROM RR_CLAUDE_KEY
         ORDER BY ID DESC;
    r c%ROWTYPE;
BEGIN
    :status_code := 200;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.OPEN_ARRAY('items');
    OPEN c;
    LOOP
        FETCH c INTO r;
        EXIT WHEN c%NOTFOUND;
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('id',             r.ID);
        APEX_JSON.WRITE('apiKey',         r.API_KEY);
        APEX_JSON.WRITE('description',    r.DESCRIPTION);
        APEX_JSON.WRITE('isActive',       r.IS_ACTIVE);
        APEX_JSON.WRITE('createdBy',      r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',   r.CREATION_DATE);
        APEX_JSON.WRITE('lastUpdatedBy',  r.LAST_UPDATED_BY);
        APEX_JSON.WRITE('lastUpdateDate', r.LAST_UPDATE_DATE);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    CLOSE c;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 500;
        HTP.PRN('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );

    -- ── POST /admin/claudekeys ────────────────────────────────────────────────
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/claudekeys',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Insert new Claude API key',
        p_source         => q'[
DECLARE
    l_body        CLOB    := :body_text;
    l_api_key     VARCHAR2(300);
    l_description VARCHAR2(200);
    l_is_active   VARCHAR2(1);
    l_created_by  VARCHAR2(150);
    l_new_id      NUMBER;
BEGIN
    SELECT JSON_VALUE(l_body, '$.apiKey')      INTO l_api_key     FROM DUAL;
    SELECT JSON_VALUE(l_body, '$.description') INTO l_description FROM DUAL;
    SELECT NVL(JSON_VALUE(l_body, '$.isActive'), 'Y') INTO l_is_active FROM DUAL;
    SELECT JSON_VALUE(l_body, '$.createdBy')   INTO l_created_by  FROM DUAL;

    IF l_api_key IS NULL THEN
        :status_code := 400;
        HTP.PRN('{"status":"error","message":"apiKey is required"}');
        RETURN;
    END IF;

    INSERT INTO RR_CLAUDE_KEY (API_KEY, DESCRIPTION, IS_ACTIVE, CREATED_BY, LAST_UPDATED_BY, LAST_UPDATE_DATE)
    VALUES (l_api_key, l_description, l_is_active, l_created_by, l_created_by, SYSTIMESTAMP)
    RETURNING ID INTO l_new_id;
    COMMIT;

    :status_code := 200;
    HTP.PRN('{"status":"success","id":' || l_new_id || '}');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.PRN('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );

    -- ── PUT /admin/claudekeys/:id ─────────────────────────────────────────────
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/claudekeys/:id',
        p_method         => 'PUT',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Update Claude API key description / active flag',
        p_source         => q'[
DECLARE
    l_body           CLOB    := :body_text;
    l_id             NUMBER  := TO_NUMBER(:id);
    l_description    VARCHAR2(200);
    l_is_active      VARCHAR2(1);
    l_last_updated   VARCHAR2(150);
    l_rows           NUMBER;
BEGIN
    SELECT JSON_VALUE(l_body, '$.description')  INTO l_description  FROM DUAL;
    SELECT JSON_VALUE(l_body, '$.isActive')     INTO l_is_active    FROM DUAL;
    SELECT JSON_VALUE(l_body, '$.lastUpdatedBy') INTO l_last_updated FROM DUAL;

    UPDATE RR_CLAUDE_KEY
       SET DESCRIPTION      = NVL(l_description, DESCRIPTION),
           IS_ACTIVE        = NVL(l_is_active,   IS_ACTIVE),
           LAST_UPDATED_BY  = l_last_updated,
           LAST_UPDATE_DATE = SYSTIMESTAMP
     WHERE ID = l_id;

    l_rows := SQL%ROWCOUNT;
    COMMIT;

    IF l_rows = 0 THEN
        :status_code := 404;
        HTP.PRN('{"status":"error","message":"Key not found"}');
    ELSE
        :status_code := 200;
        HTP.PRN('{"status":"success"}');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.PRN('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );

    -- ── DELETE /admin/claudekeys/:id ──────────────────────────────────────────
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/claudekeys/:id',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_comments       => 'Delete Claude API key',
        p_source         => q'[
DECLARE
    l_id   NUMBER := TO_NUMBER(:id);
    l_rows NUMBER;
BEGIN
    DELETE FROM RR_CLAUDE_KEY WHERE ID = l_id;
    l_rows := SQL%ROWCOUNT;
    COMMIT;

    IF l_rows = 0 THEN
        :status_code := 404;
        HTP.PRN('{"status":"error","message":"Key not found"}');
    ELSE
        :status_code := 200;
        HTP.PRN('{"status":"success"}');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.PRN('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );

    COMMIT;
END;
/
