-- ============================================================
-- Table: RR_EXTERNAL_CASH_TRANSACTIONS
-- Description: External Cash Transactions synced from Oracle Fusion
-- Oracle Endpoint: fscmRestApi/resources/11.13.18.05/cashExternalTransactions
-- ============================================================

CREATE TABLE RR_EXTERNAL_CASH_TRANSACTIONS (
    ID                              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EXTERNAL_TRANSACTION_ID         NUMBER NOT NULL,
    TRANSACTION_ID                  NUMBER,
    TRANSACTION_DATE                DATE,
    VALUE_DATE                      DATE,
    CLEARED_DATE                    DATE,
    AMOUNT                          NUMBER,
    CURRENCY_CODE                   VARCHAR2(15),
    DESCRIPTION                     VARCHAR2(1000),
    REFERENCE_TEXT                  VARCHAR2(360),
    SOURCE                          VARCHAR2(60),
    STATUS                          VARCHAR2(30),
    TRANSACTION_TYPE                VARCHAR2(60),
    ACCOUNTING_FLAG                 VARCHAR2(1),
    BANK_ACCOUNT_NAME               VARCHAR2(360),
    BUSINESS_UNIT_NAME              VARCHAR2(360),
    LEGAL_ENTITY_NAME               VARCHAR2(360),
    ASSET_ACCOUNT_COMBINATION       VARCHAR2(200),
    OFFSET_ACCOUNT_COMBINATION      VARCHAR2(200),
    BANK_CONVERSION_RATE            NUMBER,
    BANK_CONVERSION_RATE_TYPE       VARCHAR2(60),
    TRANSFER_ID                     NUMBER,
    ACCNT_SERVICER_REFERENCE        VARCHAR2(200),
    ADDENDA_TXT                     VARCHAR2(1000),
    CHECK_NUMBER                    VARCHAR2(100),
    CLEARING_SYSTEM_REFERENCE       VARCHAR2(200),
    CUSTOMER_REFERENCE              VARCHAR2(200),
    END_TO_END_ID                   VARCHAR2(200),
    INSTRUCTION_IDENTIFICATION      VARCHAR2(200),
    RECON_REFERENCE                 VARCHAR2(200),
    STRUCTURED_PAYMENT_REFERENCE    VARCHAR2(200),
    BANK_TRANSACTION_ID             NUMBER,
    CREATED_BY                      VARCHAR2(150),
    CREATION_DATE                   TIMESTAMP,
    LAST_UPDATED_BY                 VARCHAR2(150),
    LAST_UPDATE_DATE                TIMESTAMP,
    LAST_UPDATE_LOGIN               VARCHAR2(200),
    SYNC_DATE                       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_RR_ECT_ID UNIQUE (EXTERNAL_TRANSACTION_ID)
);

CREATE INDEX IDX_RR_ECT_TXN_DATE   ON RR_EXTERNAL_CASH_TRANSACTIONS(TRANSACTION_DATE);
CREATE INDEX IDX_RR_ECT_VALUE_DATE  ON RR_EXTERNAL_CASH_TRANSACTIONS(VALUE_DATE);
CREATE INDEX IDX_RR_ECT_BANK_ACCT  ON RR_EXTERNAL_CASH_TRANSACTIONS(BANK_ACCOUNT_NAME);
CREATE INDEX IDX_RR_ECT_STATUS     ON RR_EXTERNAL_CASH_TRANSACTIONS(STATUS);
CREATE INDEX IDX_RR_ECT_BU         ON RR_EXTERNAL_CASH_TRANSACTIONS(BUSINESS_UNIT_NAME);
CREATE INDEX IDX_RR_ECT_TXN_TYPE   ON RR_EXTERNAL_CASH_TRANSACTIONS(TRANSACTION_TYPE);
CREATE INDEX IDX_RR_ECT_SOURCE     ON RR_EXTERNAL_CASH_TRANSACTIONS(SOURCE);
CREATE INDEX IDX_RR_ECT_TXN_ID     ON RR_EXTERNAL_CASH_TRANSACTIONS(TRANSACTION_ID);

COMMENT ON TABLE RR_EXTERNAL_CASH_TRANSACTIONS IS 'External cash transactions synced from Oracle Fusion cashExternalTransactions';
COMMENT ON COLUMN RR_EXTERNAL_CASH_TRANSACTIONS.EXTERNAL_TRANSACTION_ID IS 'Unique identifier from Fusion';
COMMENT ON COLUMN RR_EXTERNAL_CASH_TRANSACTIONS.STATUS IS 'REC=Reconciled, UNR=Unreconciled, etc.';
COMMENT ON COLUMN RR_EXTERNAL_CASH_TRANSACTIONS.ACCOUNTING_FLAG IS 'Y=Accounted, N=Not Accounted';

-- Sequence for manually-created transactions (no Fusion ExternalTransactionId)
CREATE SEQUENCE RR_ECT_MANUAL_SEQ START WITH 1000000000 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- Procedure: RR_SYNC_EXTERNAL_CASH_TRANSACTIONS
-- Description: Upsert external cash transactions from JSON payload
-- ============================================================

CREATE OR REPLACE PROCEDURE RR_SYNC_EXTERNAL_CASH_TRANSACTIONS (
    p_json  IN  CLOB,
    p_count OUT NUMBER,
    p_error OUT VARCHAR2
) AS
    l_ext_id  NUMBER;   -- resolved ExternalTransactionId (sequence fallback for manual)
BEGIN
    p_count := 0;
    p_error := NULL;

    FOR rec IN (
        SELECT *
        FROM JSON_TABLE(p_json, '$.items[*]'
            COLUMNS (
                external_transaction_id      NUMBER          PATH '$.ExternalTransactionId',
                transaction_id               NUMBER          PATH '$.TransactionId',
                transaction_date             VARCHAR2(30)    PATH '$.TransactionDate',
                value_date                   VARCHAR2(30)    PATH '$.ValueDate',
                cleared_date                 VARCHAR2(30)    PATH '$.ClearedDate',
                amount                       NUMBER          PATH '$.Amount',
                currency_code                VARCHAR2(15)    PATH '$.CurrencyCode',
                description                  VARCHAR2(1000)  PATH '$.Description',
                reference_text               VARCHAR2(360)   PATH '$.ReferenceText',
                source                       VARCHAR2(60)    PATH '$.Source',
                status                       VARCHAR2(30)    PATH '$.Status',
                transaction_type             VARCHAR2(60)    PATH '$.TransactionType',
                accounting_flag              VARCHAR2(10)    PATH '$.AccountingFlag',
                bank_account_name            VARCHAR2(360)   PATH '$.BankAccountName',
                business_unit_name           VARCHAR2(360)   PATH '$.BusinessUnitName',
                legal_entity_name            VARCHAR2(360)   PATH '$.LegalEntityName',
                asset_account_combination    VARCHAR2(200)   PATH '$.AssetAccountCombination',
                offset_account_combination   VARCHAR2(200)   PATH '$.OffsetAccountCombination',
                bank_conversion_rate         NUMBER          PATH '$.BankConversionRate',
                bank_conversion_rate_type    VARCHAR2(60)    PATH '$.BankConversionRateType',
                transfer_id                  NUMBER          PATH '$.TransferId',
                accnt_servicer_reference     VARCHAR2(200)   PATH '$.AccntServicerReference',
                addenda_txt                  VARCHAR2(1000)  PATH '$.AddendaTxt',
                check_number                 VARCHAR2(100)   PATH '$.CheckNumber',
                clearing_system_reference    VARCHAR2(200)   PATH '$.ClearingSystemReference',
                customer_reference           VARCHAR2(200)   PATH '$.CustomerReference',
                end_to_end_id                VARCHAR2(200)   PATH '$.EndToEndId',
                instruction_identification   VARCHAR2(200)   PATH '$.InstructionIdentification',
                recon_reference              VARCHAR2(200)   PATH '$.ReconReference',
                structured_payment_reference VARCHAR2(200)   PATH '$.StructuredPaymentReference',
                bank_transaction_id          NUMBER          PATH '$.BankTransactionId',
                created_by                   VARCHAR2(150)   PATH '$.CreatedBy',
                creation_date                VARCHAR2(50)    PATH '$.CreationDate',
                last_updated_by              VARCHAR2(150)   PATH '$.LastUpdatedBy',
                last_update_date             VARCHAR2(50)    PATH '$.LastUpdateDate',
                last_update_login            VARCHAR2(200)   PATH '$.LastUpdateLogin'
            )
        )
    ) LOOP
        -- Resolve ExternalTransactionId outside MERGE (NEXTVAL not allowed in USING subquery)
        IF rec.external_transaction_id IS NULL THEN
            SELECT RR_ECT_MANUAL_SEQ.NEXTVAL INTO l_ext_id FROM DUAL;
        ELSE
            l_ext_id := rec.external_transaction_id;
        END IF;

        MERGE INTO RR_EXTERNAL_CASH_TRANSACTIONS tgt
        USING (
            SELECT
                l_ext_id                                        AS external_transaction_id,
                rec.transaction_id                              AS transaction_id,
                -- SUBSTR(,1,10) safely handles both 'YYYY-MM-DD' and 'YYYY-MM-DDTHH:...' from Fusion
                TO_DATE(SUBSTR(rec.transaction_date, 1, 10), 'YYYY-MM-DD')  AS transaction_date,
                TO_DATE(SUBSTR(rec.value_date,        1, 10), 'YYYY-MM-DD') AS value_date,
                TO_DATE(SUBSTR(rec.cleared_date,      1, 10), 'YYYY-MM-DD') AS cleared_date,
                rec.amount                                      AS amount,
                rec.currency_code                               AS currency_code,
                rec.description                                 AS description,
                rec.reference_text                              AS reference_text,
                rec.source                                      AS source,
                rec.status                                      AS status,
                rec.transaction_type                            AS transaction_type,
                CASE WHEN LOWER(rec.accounting_flag) = 'true' THEN 'Y' ELSE 'N' END AS accounting_flag,
                rec.bank_account_name                           AS bank_account_name,
                rec.business_unit_name                          AS business_unit_name,
                rec.legal_entity_name                           AS legal_entity_name,
                rec.asset_account_combination                   AS asset_account_combination,
                rec.offset_account_combination                  AS offset_account_combination,
                rec.bank_conversion_rate                        AS bank_conversion_rate,
                rec.bank_conversion_rate_type                   AS bank_conversion_rate_type,
                rec.transfer_id                                 AS transfer_id,
                rec.accnt_servicer_reference                    AS accnt_servicer_reference,
                rec.addenda_txt                                 AS addenda_txt,
                rec.check_number                                AS check_number,
                rec.clearing_system_reference                   AS clearing_system_reference,
                rec.customer_reference                          AS customer_reference,
                rec.end_to_end_id                               AS end_to_end_id,
                rec.instruction_identification                  AS instruction_identification,
                rec.recon_reference                             AS recon_reference,
                rec.structured_payment_reference                AS structured_payment_reference,
                rec.bank_transaction_id                         AS bank_transaction_id,
                rec.created_by                                  AS created_by,
                -- Strip Z or ±HH:MI timezone suffix before TO_TIMESTAMP parse
                TO_TIMESTAMP(
                    REGEXP_REPLACE(rec.creation_date,  '(Z|[+-]\d{2}:\d{2})$', ''),
                    'YYYY-MM-DD"T"HH24:MI:SS.FF3'
                ) AS creation_date,
                rec.last_updated_by                             AS last_updated_by,
                TO_TIMESTAMP(
                    REGEXP_REPLACE(rec.last_update_date, '(Z|[+-]\d{2}:\d{2})$', ''),
                    'YYYY-MM-DD"T"HH24:MI:SS.FF3'
                ) AS last_update_date,
                rec.last_update_login                           AS last_update_login
            FROM DUAL
        ) src
        ON (tgt.EXTERNAL_TRANSACTION_ID = src.external_transaction_id)
        WHEN MATCHED THEN
            UPDATE SET
                tgt.TRANSACTION_ID               = src.transaction_id,
                tgt.TRANSACTION_DATE             = src.transaction_date,
                tgt.VALUE_DATE                   = src.value_date,
                tgt.CLEARED_DATE                 = src.cleared_date,
                tgt.AMOUNT                       = src.amount,
                tgt.CURRENCY_CODE                = src.currency_code,
                tgt.DESCRIPTION                  = src.description,
                tgt.REFERENCE_TEXT               = src.reference_text,
                tgt.SOURCE                       = src.source,
                tgt.STATUS                       = src.status,
                tgt.TRANSACTION_TYPE             = src.transaction_type,
                tgt.ACCOUNTING_FLAG              = src.accounting_flag,
                tgt.BANK_ACCOUNT_NAME            = src.bank_account_name,
                tgt.BUSINESS_UNIT_NAME           = src.business_unit_name,
                tgt.LEGAL_ENTITY_NAME            = src.legal_entity_name,
                tgt.ASSET_ACCOUNT_COMBINATION    = src.asset_account_combination,
                tgt.OFFSET_ACCOUNT_COMBINATION   = src.offset_account_combination,
                tgt.BANK_CONVERSION_RATE         = src.bank_conversion_rate,
                tgt.BANK_CONVERSION_RATE_TYPE    = src.bank_conversion_rate_type,
                tgt.TRANSFER_ID                  = src.transfer_id,
                tgt.ACCNT_SERVICER_REFERENCE     = src.accnt_servicer_reference,
                tgt.ADDENDA_TXT                  = src.addenda_txt,
                tgt.CHECK_NUMBER                 = src.check_number,
                tgt.CLEARING_SYSTEM_REFERENCE    = src.clearing_system_reference,
                tgt.CUSTOMER_REFERENCE           = src.customer_reference,
                tgt.END_TO_END_ID               = src.end_to_end_id,
                tgt.INSTRUCTION_IDENTIFICATION   = src.instruction_identification,
                tgt.RECON_REFERENCE              = src.recon_reference,
                tgt.STRUCTURED_PAYMENT_REFERENCE = src.structured_payment_reference,
                tgt.BANK_TRANSACTION_ID          = src.bank_transaction_id,
                tgt.CREATED_BY                   = src.created_by,
                tgt.CREATION_DATE                = src.creation_date,
                tgt.LAST_UPDATED_BY              = src.last_updated_by,
                tgt.LAST_UPDATE_DATE             = src.last_update_date,
                tgt.LAST_UPDATE_LOGIN            = src.last_update_login,
                tgt.SYNC_DATE                    = SYSTIMESTAMP
        WHEN NOT MATCHED THEN
            INSERT (
                EXTERNAL_TRANSACTION_ID, TRANSACTION_ID,
                TRANSACTION_DATE, VALUE_DATE, CLEARED_DATE,
                AMOUNT, CURRENCY_CODE, DESCRIPTION, REFERENCE_TEXT,
                SOURCE, STATUS, TRANSACTION_TYPE, ACCOUNTING_FLAG,
                BANK_ACCOUNT_NAME, BUSINESS_UNIT_NAME, LEGAL_ENTITY_NAME,
                ASSET_ACCOUNT_COMBINATION, OFFSET_ACCOUNT_COMBINATION,
                BANK_CONVERSION_RATE, BANK_CONVERSION_RATE_TYPE,
                TRANSFER_ID, ACCNT_SERVICER_REFERENCE, ADDENDA_TXT,
                CHECK_NUMBER, CLEARING_SYSTEM_REFERENCE, CUSTOMER_REFERENCE,
                END_TO_END_ID, INSTRUCTION_IDENTIFICATION, RECON_REFERENCE,
                STRUCTURED_PAYMENT_REFERENCE, BANK_TRANSACTION_ID,
                CREATED_BY, CREATION_DATE, LAST_UPDATED_BY,
                LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, SYNC_DATE
            ) VALUES (
                src.external_transaction_id, src.transaction_id,
                src.transaction_date, src.value_date, src.cleared_date,
                src.amount, src.currency_code, src.description, src.reference_text,
                src.source, src.status, src.transaction_type, src.accounting_flag,
                src.bank_account_name, src.business_unit_name, src.legal_entity_name,
                src.asset_account_combination, src.offset_account_combination,
                src.bank_conversion_rate, src.bank_conversion_rate_type,
                src.transfer_id, src.accnt_servicer_reference, src.addenda_txt,
                src.check_number, src.clearing_system_reference, src.customer_reference,
                src.end_to_end_id, src.instruction_identification, src.recon_reference,
                src.structured_payment_reference, src.bank_transaction_id,
                src.created_by, src.creation_date, src.last_updated_by,
                src.last_update_date, src.last_update_login, SYSTIMESTAMP
            );

        p_count := p_count + 1;
    END LOOP;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        p_error := SQLERRM;
        ROLLBACK;
END RR_SYNC_EXTERNAL_CASH_TRANSACTIONS;
/


-- ============================================================
-- APEX REST Handlers
-- ============================================================

BEGIN
    -- ── POST /cash/externaltransactions  (sync from Oracle Fusion) ──
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/externaltransactions',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'External Cash Transactions sync endpoint'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/externaltransactions',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Sync external cash transactions from Oracle Fusion',
        p_source         => q'[
DECLARE
    l_json   CLOB;
    l_count  NUMBER;
    l_error  VARCHAR2(4000);
BEGIN
    l_json := :body_text;

    RR_SYNC_EXTERNAL_CASH_TRANSACTIONS(
        p_json  => l_json,
        p_count => l_count,
        p_error => l_error
    );

    IF l_error IS NOT NULL THEN
        :status_code := 500;
        HTP.P('{"status":"error","message":"' || REPLACE(l_error, '"', '\"') || '"}');
    ELSE
        :status_code := 200;
        HTP.P('{"status":"success","count":' || l_count || '}');
    END IF;
END;
]'
    );

    -- ── GET /cash/externaltransactions  (query with filters) ──
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/externaltransactions',
        p_method         => 'GET',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => '',
        p_comments       => 'Query external cash transactions with optional filters',
        p_source         => q'[
DECLARE
    l_txn_number  VARCHAR2(100)  := :transaction_number;
    l_bank_acct   VARCHAR2(360)  := :bank_account;
    l_currency    VARCHAR2(15)   := :currency_code;
    l_bu          VARCHAR2(360)  := :business_unit;
    l_txn_type    VARCHAR2(60)   := :transaction_type;
    l_source      VARCHAR2(60)   := :source;
    l_status      VARCHAR2(30)   := :status;
    l_reference   VARCHAR2(360)  := :reference;
    l_date_from   VARCHAR2(30)   := :date_from;
    l_date_to     VARCHAR2(30)   := :date_to;
    l_amt_from    VARCHAR2(30)   := :amount_from;
    l_amt_to      VARCHAR2(30)   := :amount_to;
    l_limit       NUMBER         := NVL(TO_NUMBER(:row_limit),  500);
    l_offset      NUMBER         := NVL(TO_NUMBER(:row_offset), 0);
    v_total       NUMBER         := 0;

    CURSOR c_txns IS
        SELECT EXTERNAL_TRANSACTION_ID,
               TRANSACTION_ID,
               TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD')  AS TRANSACTION_DATE,
               TO_CHAR(VALUE_DATE,       'YYYY-MM-DD')  AS VALUE_DATE,
               TO_CHAR(CLEARED_DATE,     'YYYY-MM-DD')  AS CLEARED_DATE,
               AMOUNT,
               CURRENCY_CODE,
               DESCRIPTION,
               REFERENCE_TEXT,
               SOURCE,
               STATUS,
               TRANSACTION_TYPE,
               NVL(ACCOUNTING_FLAG, 'N')                AS ACCOUNTING_FLAG,
               BANK_ACCOUNT_NAME,
               BUSINESS_UNIT_NAME,
               LEGAL_ENTITY_NAME,
               ASSET_ACCOUNT_COMBINATION,
               OFFSET_ACCOUNT_COMBINATION,
               BANK_CONVERSION_RATE,
               BANK_CONVERSION_RATE_TYPE,
               TRANSFER_ID,
               CHECK_NUMBER,
               RECON_REFERENCE,
               CREATED_BY,
               TO_CHAR(CREATION_DATE,   'YYYY-MM-DD"T"HH24:MI:SS') AS CREATION_DATE,
               LAST_UPDATED_BY,
               TO_CHAR(LAST_UPDATE_DATE,'YYYY-MM-DD"T"HH24:MI:SS') AS LAST_UPDATE_DATE,
               TO_CHAR(SYNC_DATE,       'YYYY-MM-DD"T"HH24:MI:SS') AS SYNC_DATE
          FROM RR_EXTERNAL_CASH_TRANSACTIONS
         WHERE (l_txn_number IS NULL OR TO_CHAR(TRANSACTION_ID) LIKE '%' || l_txn_number || '%')
           AND (l_bank_acct  IS NULL OR UPPER(BANK_ACCOUNT_NAME)   LIKE '%' || UPPER(l_bank_acct)  || '%')
           AND (l_currency   IS NULL OR CURRENCY_CODE              = l_currency)
           AND (l_bu         IS NULL OR BUSINESS_UNIT_NAME         = l_bu)
           AND (l_txn_type   IS NULL OR TRANSACTION_TYPE           = l_txn_type)
           AND (l_source     IS NULL OR SOURCE                     = l_source)
           AND (l_status     IS NULL OR STATUS                     = l_status)
           AND (l_reference  IS NULL OR UPPER(REFERENCE_TEXT)      LIKE '%' || UPPER(l_reference)  || '%')
           AND (l_date_from  IS NULL OR TRANSACTION_DATE >= TO_DATE(l_date_from, 'YYYY-MM-DD'))
           AND (l_date_to    IS NULL OR TRANSACTION_DATE <= TO_DATE(l_date_to,   'YYYY-MM-DD'))
           AND (l_amt_from   IS NULL OR AMOUNT >= TO_NUMBER(l_amt_from))
           AND (l_amt_to     IS NULL OR AMOUNT <= TO_NUMBER(l_amt_to))
         ORDER BY TRANSACTION_DATE DESC, EXTERNAL_TRANSACTION_ID DESC
         OFFSET l_offset ROWS FETCH NEXT l_limit ROWS ONLY;

    r c_txns%ROWTYPE;
BEGIN
    SELECT COUNT(*)
      INTO v_total
      FROM RR_EXTERNAL_CASH_TRANSACTIONS
     WHERE (l_txn_number IS NULL OR TO_CHAR(TRANSACTION_ID) LIKE '%' || l_txn_number || '%')
       AND (l_bank_acct  IS NULL OR UPPER(BANK_ACCOUNT_NAME)   LIKE '%' || UPPER(l_bank_acct)  || '%')
       AND (l_currency   IS NULL OR CURRENCY_CODE              = l_currency)
       AND (l_bu         IS NULL OR BUSINESS_UNIT_NAME         = l_bu)
       AND (l_txn_type   IS NULL OR TRANSACTION_TYPE           = l_txn_type)
       AND (l_source     IS NULL OR SOURCE                     = l_source)
       AND (l_status     IS NULL OR STATUS                     = l_status)
       AND (l_reference  IS NULL OR UPPER(REFERENCE_TEXT)      LIKE '%' || UPPER(l_reference)  || '%')
       AND (l_date_from  IS NULL OR TRANSACTION_DATE >= TO_DATE(l_date_from, 'YYYY-MM-DD'))
       AND (l_date_to    IS NULL OR TRANSACTION_DATE <= TO_DATE(l_date_to,   'YYYY-MM-DD'))
       AND (l_amt_from   IS NULL OR AMOUNT >= TO_NUMBER(l_amt_from))
       AND (l_amt_to     IS NULL OR AMOUNT <= TO_NUMBER(l_amt_to));

    :status_code := 200;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.WRITE('total',  v_total);
    APEX_JSON.OPEN_ARRAY('items');

    OPEN c_txns;
    LOOP
        FETCH c_txns INTO r;
        EXIT WHEN c_txns%NOTFOUND;

        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('externalTransactionId',    r.EXTERNAL_TRANSACTION_ID);
        APEX_JSON.WRITE('transactionId',            r.TRANSACTION_ID);
        APEX_JSON.WRITE('transactionDate',          r.TRANSACTION_DATE);
        APEX_JSON.WRITE('valueDate',                r.VALUE_DATE);
        APEX_JSON.WRITE('clearedDate',              r.CLEARED_DATE);
        APEX_JSON.WRITE('amount',                   r.AMOUNT);
        APEX_JSON.WRITE('currencyCode',             r.CURRENCY_CODE);
        APEX_JSON.WRITE('description',              r.DESCRIPTION);
        APEX_JSON.WRITE('referenceText',            r.REFERENCE_TEXT);
        APEX_JSON.WRITE('source',                   r.SOURCE);
        APEX_JSON.WRITE('status',                   r.STATUS);
        APEX_JSON.WRITE('transactionType',          r.TRANSACTION_TYPE);
        APEX_JSON.WRITE('accountingFlag',           r.ACCOUNTING_FLAG);
        APEX_JSON.WRITE('bankAccountName',          r.BANK_ACCOUNT_NAME);
        APEX_JSON.WRITE('businessUnitName',         r.BUSINESS_UNIT_NAME);
        APEX_JSON.WRITE('legalEntityName',          r.LEGAL_ENTITY_NAME);
        APEX_JSON.WRITE('assetAccountCombination',  r.ASSET_ACCOUNT_COMBINATION);
        APEX_JSON.WRITE('offsetAccountCombination', r.OFFSET_ACCOUNT_COMBINATION);
        APEX_JSON.WRITE('bankConversionRate',       r.BANK_CONVERSION_RATE);
        APEX_JSON.WRITE('bankConversionRateType',   r.BANK_CONVERSION_RATE_TYPE);
        APEX_JSON.WRITE('transferId',               r.TRANSFER_ID);
        APEX_JSON.WRITE('checkNumber',              r.CHECK_NUMBER);
        APEX_JSON.WRITE('reconReference',           r.RECON_REFERENCE);
        APEX_JSON.WRITE('createdBy',                r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',             r.CREATION_DATE);
        APEX_JSON.WRITE('lastUpdateDate',           r.LAST_UPDATE_DATE);
        APEX_JSON.WRITE('syncDate',                 r.SYNC_DATE);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    CLOSE c_txns;

    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 500;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );

    COMMIT;
END;
/
