-- ============================================================
-- Table: RR_EXTERNAL_TRX_ATTACHMENTS
-- Stores file attachments for external cash transactions
-- ============================================================

CREATE TABLE RR_EXTERNAL_TRX_ATTACHMENTS (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EXTERNAL_TRANSACTION_ID NUMBER NOT NULL,
    FILE_NAME               VARCHAR2(500) NOT NULL,
    FILE_TYPE               VARCHAR2(100),
    FILE_SIZE               NUMBER,
    FILE_CONTENT            CLOB,  -- Base64-encoded file content
    CREATED_BY              VARCHAR2(150),
    CREATED_DATE            TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EXT_TRX_ATT FOREIGN KEY (EXTERNAL_TRANSACTION_ID)
        REFERENCES RR_EXTERNAL_CASH_TRANSACTIONS(EXTERNAL_TRANSACTION_ID)
);

CREATE INDEX IDX_RR_ETA_TRX_ID ON RR_EXTERNAL_TRX_ATTACHMENTS(EXTERNAL_TRANSACTION_ID);

-- ============================================================
-- ORDS: GET /cash/externaltransactions/:externalTransactionId/attachments
-- ============================================================
BEGIN
    ORDS.DELETE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/externaltransactions/:externalTransactionId/attachments'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/externaltransactions/:externalTransactionId/attachments',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_comments    => 'Attachments for an external transaction'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/externaltransactions/:externalTransactionId/attachments',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'List attachments for a transaction',
        p_source         => q'[
DECLARE
    l_json CLOB := '{"items":[';
    l_first BOOLEAN := TRUE;
BEGIN
    FOR r IN (
        SELECT ID, FILE_NAME, FILE_TYPE, FILE_SIZE, CREATED_BY,
               TO_CHAR(CREATED_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS CREATED_DATE
          FROM RR_EXTERNAL_TRX_ATTACHMENTS
         WHERE EXTERNAL_TRANSACTION_ID = :externalTransactionId
         ORDER BY CREATED_DATE DESC
    ) LOOP
        IF NOT l_first THEN l_json := l_json || ','; END IF;
        l_first := FALSE;
        l_json := l_json
            || '{"id":' || r.ID
            || ',"fileName":' || APEX_JSON.STRINGIFY(r.FILE_NAME)
            || ',"fileType":' || APEX_JSON.STRINGIFY(NVL(r.FILE_TYPE,''))
            || ',"fileSize":' || NVL(TO_CHAR(r.FILE_SIZE),'null')
            || ',"createdBy":' || APEX_JSON.STRINGIFY(NVL(r.CREATED_BY,''))
            || ',"createdDate":' || APEX_JSON.STRINGIFY(NVL(r.CREATED_DATE,''))
            || '}';
    END LOOP;
    l_json := l_json || ']}';
    HTP.P(l_json);
EXCEPTION WHEN OTHERS THEN
    HTP.P('{"items":[],"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- POST handler — upload attachment
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/externaltransactions/:externalTransactionId/attachments',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Upload attachment for a transaction',
        p_source         => q'[
DECLARE
    v_file_name  VARCHAR2(500);
    v_file_type  VARCHAR2(100);
    v_file_size  NUMBER;
    v_content    CLOB;
    v_created_by VARCHAR2(150);
    v_new_id     NUMBER;
BEGIN
    SELECT jt.file_name, jt.file_type, jt.file_size, jt.content, jt.created_by
    INTO   v_file_name, v_file_type, v_file_size, v_content, v_created_by
    FROM   JSON_TABLE(:body_text, '$' COLUMNS (
               file_name  VARCHAR2(500)  PATH '$.fileName',
               file_type  VARCHAR2(100)  PATH '$.fileType',
               file_size  NUMBER         PATH '$.fileSize',
               content    CLOB           PATH '$.content',
               created_by VARCHAR2(150)  PATH '$.createdBy'
           )) jt;

    INSERT INTO RR_EXTERNAL_TRX_ATTACHMENTS
        (EXTERNAL_TRANSACTION_ID, FILE_NAME, FILE_TYPE, FILE_SIZE, FILE_CONTENT, CREATED_BY)
    VALUES
        (:externalTransactionId, v_file_name, v_file_type, v_file_size, v_content, NVL(v_created_by,'SYSTEM'))
    RETURNING ID INTO v_new_id;

    COMMIT;
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('{"status":"success","id":' || v_new_id || ',"fileName":' || APEX_JSON.STRINGIFY(v_file_name) || '}');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ============================================================
-- ORDS: DELETE /cash/externaltransactions/:externalTransactionId/attachments/:attachmentId
-- ============================================================
BEGIN
    ORDS.DELETE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/externaltransactions/:externalTransactionId/attachments/:attachmentId'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/externaltransactions/:externalTransactionId/attachments/:attachmentId',
        p_priority    => 0,
        p_etag_type   => 'HASH'
    );
    COMMIT;
END;
/

BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/externaltransactions/:externalTransactionId/attachments/:attachmentId',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'Delete an attachment',
        p_source         => q'[
BEGIN
    DELETE FROM RR_EXTERNAL_TRX_ATTACHMENTS
     WHERE ID = :attachmentId
       AND EXTERNAL_TRANSACTION_ID = :externalTransactionId;
    IF SQL%ROWCOUNT = 0 THEN
        OWA_UTIL.MIME_HEADER('application/json', FALSE);
        HTP.P('{"status":"error","message":"Attachment not found"}');
    ELSE
        COMMIT;
        OWA_UTIL.MIME_HEADER('application/json', FALSE);
        HTP.P('{"status":"success"}');
    END IF;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- OPTIONS handler for CORS
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/externaltransactions/:externalTransactionId/attachments',
        p_method         => 'OPTIONS',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[BEGIN OWA_UTIL.MIME_HEADER('application/json', FALSE); HTP.P(''); END;]'
    );
    COMMIT;
END;
/
