-- ============================================================
-- Table: RR_TRANSACTION_CODES
-- Description: Cash transaction codes for classifying cash transactions
-- ============================================================

CREATE TABLE RR_TRANSACTION_CODES (
    TC_ID                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BUSINESS_UNIT_NAME          VARCHAR2(360)   NOT NULL,
    TRANSACTION_CODE            VARCHAR2(50)    NOT NULL,
    DESCRIPTION                 VARCHAR2(500),
    DEFAULT_ACCOUNT_COMBINATION VARCHAR2(360),
    END_TRANSACTION             VARCHAR2(100),  -- e.g. 'External Transaction', 'Manual Journal', 'Bank Transfer'
    CREATED_BY                  VARCHAR2(150),
    CREATION_DATE               TIMESTAMP       DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY             VARCHAR2(150),
    LAST_UPDATE_DATE            TIMESTAMP       DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_RR_TC_BU_CODE UNIQUE (BUSINESS_UNIT_NAME, TRANSACTION_CODE)
);

-- Indexes
CREATE INDEX IDX_RR_TC_BU   ON RR_TRANSACTION_CODES(BUSINESS_UNIT_NAME);
CREATE INDEX IDX_RR_TC_CODE ON RR_TRANSACTION_CODES(TRANSACTION_CODE);

-- Comments
COMMENT ON TABLE  RR_TRANSACTION_CODES                              IS 'Cash transaction codes used to classify cash transactions by business unit';
COMMENT ON COLUMN RR_TRANSACTION_CODES.TC_ID                        IS 'Surrogate primary key';
COMMENT ON COLUMN RR_TRANSACTION_CODES.BUSINESS_UNIT_NAME           IS 'Business unit this transaction code belongs to';
COMMENT ON COLUMN RR_TRANSACTION_CODES.TRANSACTION_CODE             IS 'Short code identifying the transaction type';
COMMENT ON COLUMN RR_TRANSACTION_CODES.DESCRIPTION                  IS 'Human-readable description of the transaction code';
COMMENT ON COLUMN RR_TRANSACTION_CODES.DEFAULT_ACCOUNT_COMBINATION  IS 'Default GL account combination for this transaction code';
COMMENT ON COLUMN RR_TRANSACTION_CODES.END_TRANSACTION              IS 'End transaction type, e.g. External Transaction, Manual Journal, Bank Transfer';


-- ============================================================
-- APEX REST Handlers
-- ============================================================

-- ── Template: cash/transaction-codes ────────────────────────
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/transaction-codes',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'Cash Transaction Codes endpoint'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -20001 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ── GET cash/transaction-codes ───────────────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/transaction-codes',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_items_per_page => 0,
        p_mimes_allowed  => '',
        p_comments       => 'Query transaction codes with optional business_unit and transaction_code filters',
        p_source         => q'[
SELECT
    TC_ID                       AS "tcId",
    BUSINESS_UNIT_NAME          AS "businessUnitName",
    TRANSACTION_CODE            AS "transactionCode",
    DESCRIPTION                 AS "description",
    DEFAULT_ACCOUNT_COMBINATION AS "defaultAccountCombination",
    END_TRANSACTION             AS "endTransaction",
    CREATED_BY                  AS "createdBy",
    TO_CHAR(CREATION_DATE,    'YYYY-MM-DD"T"HH24:MI:SS') AS "creationDate",
    LAST_UPDATED_BY             AS "lastUpdatedBy",
    TO_CHAR(LAST_UPDATE_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS "lastUpdateDate"
FROM RR_TRANSACTION_CODES
WHERE (:business_unit    IS NULL OR BUSINESS_UNIT_NAME = :business_unit)
  AND (:transaction_code IS NULL OR TRANSACTION_CODE   = :transaction_code)
ORDER BY BUSINESS_UNIT_NAME, TRANSACTION_CODE
]'
    );
    COMMIT;
END;
/

-- ── POST cash/transaction-codes (upsert) ─────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/transaction-codes',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Upsert a transaction code — update if TC_ID provided, else insert',
        p_source         => q'[
DECLARE
    l_tc_id     NUMBER;
    l_bu        VARCHAR2(360);
    l_code      VARCHAR2(50);
    l_desc      VARCHAR2(500);
    l_acct      VARCHAR2(360);
    l_end_txn   VARCHAR2(100);
    l_created   VARCHAR2(150);
    l_updated   VARCHAR2(150);
BEGIN
    APEX_JSON.PARSE(:body_text);

    l_tc_id   := APEX_JSON.GET_NUMBER(p_path => 'tc_id');
    l_bu      := APEX_JSON.GET_VARCHAR2(p_path => 'business_unit_name');
    l_code    := APEX_JSON.GET_VARCHAR2(p_path => 'transaction_code');
    l_desc    := APEX_JSON.GET_VARCHAR2(p_path => 'description');
    l_acct    := APEX_JSON.GET_VARCHAR2(p_path => 'default_account_combination');
    l_end_txn := APEX_JSON.GET_VARCHAR2(p_path => 'end_transaction');
    l_created := APEX_JSON.GET_VARCHAR2(p_path => 'created_by');
    l_updated := APEX_JSON.GET_VARCHAR2(p_path => 'last_updated_by');

    IF l_tc_id IS NOT NULL THEN
        -- Update existing record
        UPDATE RR_TRANSACTION_CODES
        SET    BUSINESS_UNIT_NAME          = NVL(l_bu,      BUSINESS_UNIT_NAME),
               TRANSACTION_CODE            = NVL(l_code,    TRANSACTION_CODE),
               DESCRIPTION                 = l_desc,
               DEFAULT_ACCOUNT_COMBINATION = l_acct,
               END_TRANSACTION             = l_end_txn,
               LAST_UPDATED_BY             = l_updated,
               LAST_UPDATE_DATE            = SYSTIMESTAMP
        WHERE  TC_ID = l_tc_id;

        IF SQL%ROWCOUNT = 0 THEN
            :status_code := 404;
            HTP.PRN('{"status":"error","tc_id":null,"message":"Transaction code not found"}');
            RETURN;
        END IF;

        COMMIT;
        :status_code := 200;
        HTP.PRN('{"status":"success","tc_id":' || l_tc_id || ',"message":"Transaction code updated"}');

    ELSE
        -- Insert new record
        INSERT INTO RR_TRANSACTION_CODES (
            BUSINESS_UNIT_NAME,
            TRANSACTION_CODE,
            DESCRIPTION,
            DEFAULT_ACCOUNT_COMBINATION,
            END_TRANSACTION,
            CREATED_BY,
            CREATION_DATE,
            LAST_UPDATED_BY,
            LAST_UPDATE_DATE
        ) VALUES (
            l_bu,
            l_code,
            l_desc,
            l_acct,
            l_end_txn,
            l_created,
            SYSTIMESTAMP,
            NVL(l_updated, l_created),
            SYSTIMESTAMP
        ) RETURNING TC_ID INTO l_tc_id;

        COMMIT;
        :status_code := 201;
        HTP.PRN('{"status":"success","tc_id":' || l_tc_id || ',"message":"Transaction code created"}');
    END IF;

EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","tc_id":null,"message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── Template: cash/transaction-codes/{id} ───────────────────
BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'cash/transaction-codes/:id',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'Cash Transaction Codes single-record endpoint'
    );
    COMMIT;
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -20001 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ── DELETE cash/transaction-codes/:id ───────────────────────
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'cash/transaction-codes/:id',
        p_method         => 'DELETE',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => '',
        p_comments       => 'Delete a transaction code by TC_ID',
        p_source         => q'[
DECLARE
    l_rows NUMBER;
BEGIN
    DELETE FROM RR_TRANSACTION_CODES
    WHERE  TC_ID = :id;

    l_rows := SQL%ROWCOUNT;
    COMMIT;

    IF l_rows = 0 THEN
        :status_code := 404;
        HTP.PRN('{"status":"error","message":"Transaction code not found"}');
    ELSE
        :status_code := 200;
        HTP.PRN('{"status":"success","message":"Transaction code deleted"}');
    END IF;

EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/
