-- ============================================================
-- RR SUPPORT / TICKETING MODULE — TABLE DDL
-- ============================================================

-- ── Ticket header ─────────────────────────────────────────
CREATE TABLE RR_SUPPORT_TICKETS (
    TICKET_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TICKET_NUMBER      VARCHAR2(20),
    TITLE              VARCHAR2(500)  NOT NULL,
    DESCRIPTION        CLOB,
    MODULE             VARCHAR2(100),
    PAGE_NAME          VARCHAR2(200),
    PAGE_URL           VARCHAR2(500),
    FEATURE            VARCHAR2(200),
    PRIORITY           VARCHAR2(20)   DEFAULT 'MEDIUM'
                           CONSTRAINT CHK_TICKET_PRI CHECK (PRIORITY IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    STATUS             VARCHAR2(20)   DEFAULT 'OPEN'
                           CONSTRAINT CHK_TICKET_STS CHECK (STATUS IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
    ASSIGNED_TO        VARCHAR2(100),
    RESOLUTION_NOTES   CLOB,
    RESOLVED_BY        VARCHAR2(100),
    RESOLUTION_DATE    VARCHAR2(30),
    CREATED_BY         VARCHAR2(100)  NOT NULL,
    CREATION_DATE      VARCHAR2(30),
    LAST_UPDATED_BY    VARCHAR2(100),
    LAST_UPDATE_DATE   VARCHAR2(30)
);

-- Sequence for human-readable ticket numbers
CREATE SEQUENCE RR_SUPPORT_TICKET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER RR_SUPPORT_TICKETS_BIR
BEFORE INSERT ON RR_SUPPORT_TICKETS
FOR EACH ROW
BEGIN
    :NEW.TICKET_NUMBER  := 'TKT-' || TO_CHAR(SYSDATE, 'YYYY') || '-'
                           || LPAD(RR_SUPPORT_TICKET_SEQ.NEXTVAL, 6, '0');
    :NEW.CREATION_DATE  := TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS');
    :NEW.LAST_UPDATE_DATE := :NEW.CREATION_DATE;
    IF :NEW.LAST_UPDATED_BY IS NULL THEN
        :NEW.LAST_UPDATED_BY := :NEW.CREATED_BY;
    END IF;
END;
/

-- ── Ticket lines (multiple issues / comments per ticket) ──
CREATE TABLE RR_SUPPORT_TICKET_LINES (
    LINE_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TICKET_ID      NUMBER NOT NULL
                       CONSTRAINT FK_STL_TICKET REFERENCES RR_SUPPORT_TICKETS(TICKET_ID),
    LINE_NUMBER    NUMBER NOT NULL,
    LINE_TYPE      VARCHAR2(20) DEFAULT 'ISSUE'
                       CONSTRAINT CHK_LINE_TYPE CHECK (LINE_TYPE IN ('ISSUE','COMMENT','RESOLUTION')),
    DESCRIPTION    CLOB  NOT NULL,
    CREATED_BY     VARCHAR2(100) NOT NULL,
    CREATION_DATE  VARCHAR2(30)
);

-- Global sequence for line numbers — avoids mutating-table error
-- (ORA-04091) that occurs when trigger queries its own table during
-- a multi-row INSERT such as INSERT...SELECT from JSON_TABLE.
CREATE SEQUENCE RR_SUPPORT_LINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER RR_SUPPORT_LINES_BIR
BEFORE INSERT ON RR_SUPPORT_TICKET_LINES
FOR EACH ROW
BEGIN
    IF :NEW.LINE_NUMBER IS NULL THEN
        :NEW.LINE_NUMBER := RR_SUPPORT_LINE_SEQ.NEXTVAL;
    END IF;
    :NEW.CREATION_DATE := TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS');
END;
/

-- ── Attachments (screenshots / uploaded files) ────────────
CREATE TABLE RR_SUPPORT_TICKET_ATTACHMENTS (
    ATTACHMENT_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TICKET_ID       NUMBER NOT NULL
                        CONSTRAINT FK_STA_TICKET REFERENCES RR_SUPPORT_TICKETS(TICKET_ID),
    LINE_ID         NUMBER
                        CONSTRAINT FK_STA_LINE REFERENCES RR_SUPPORT_TICKET_LINES(LINE_ID),
    FILE_NAME       VARCHAR2(500) NOT NULL,
    FILE_TYPE       VARCHAR2(100),
    FILE_SIZE       NUMBER,
    ATTACHMENT_DATA CLOB,           -- base64-encoded content
    CREATED_BY      VARCHAR2(100) NOT NULL,
    CREATION_DATE   VARCHAR2(30)
);

CREATE OR REPLACE TRIGGER RR_SUPPORT_ATTACH_BIR
BEFORE INSERT ON RR_SUPPORT_TICKET_ATTACHMENTS
FOR EACH ROW
BEGIN
    :NEW.CREATION_DATE := TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS');
END;
/

-- ── Indexes ───────────────────────────────────────────────
CREATE INDEX IDX_SUPP_TKT_STATUS   ON RR_SUPPORT_TICKETS(STATUS);
CREATE INDEX IDX_SUPP_TKT_MODULE   ON RR_SUPPORT_TICKETS(MODULE);
CREATE INDEX IDX_SUPP_TKT_PRIORITY ON RR_SUPPORT_TICKETS(PRIORITY);
CREATE INDEX IDX_SUPP_TKT_CREATED  ON RR_SUPPORT_TICKETS(CREATION_DATE);
CREATE INDEX IDX_SUPP_LINE_TKT     ON RR_SUPPORT_TICKET_LINES(TICKET_ID);
CREATE INDEX IDX_SUPP_ATT_TKT      ON RR_SUPPORT_TICKET_ATTACHMENTS(TICKET_ID);
