-- ============================================================
-- RENTAL MANAGEMENT MODULE — LOOKUP / SEED DATA
-- Run after 01_tables.sql
-- ============================================================

-- ============================================================
-- RR_RM_LOOKUP_CODES
-- ============================================================

-- Agreement Status
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_STATUS','DRAFT',      'Draft',      10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_STATUS','ACTIVE',     'Active',     20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_STATUS','EXPIRED',    'Expired',    30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_STATUS','TERMINATED', 'Terminated', 40);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_STATUS','CANCELLED',  'Cancelled',  50);

-- Agreement Type
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_TYPE','NEW',      'New',     10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_TYPE','RENEWAL',  'Renewal', 20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('AGR_TYPE','TRANSFER', 'Transfer',30);

-- Payment Frequency
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_FREQUENCY','MONTHLY',     'Monthly (12 cheques)',         10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_FREQUENCY','QUARTERLY',   'Quarterly (4 cheques)',        20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_FREQUENCY','HALF_YEARLY', 'Half-Yearly (2 cheques)',      30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_FREQUENCY','YEARLY',      'Yearly (1 cheque)',            40);

-- Installment Status
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('INST_STATUS','PENDING',   'Pending (PDC)',  10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('INST_STATUS','PRESENTED', 'Presented',     20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('INST_STATUS','CLEARED',   'Cleared',       30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('INST_STATUS','BOUNCED',   'Bounced',       40);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('INST_STATUS','CANCELLED', 'Cancelled',     50);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('INST_STATUS','REPLACED',  'Replaced',      60);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('INST_STATUS','WAIVED',    'Waived',        70);

-- Payment Method
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_METHOD','CHEQUE',        'Cheque (PDC)',      10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_METHOD','BANK_TRANSFER', 'Bank Transfer',     20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_METHOD','CASH',          'Cash',              30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_METHOD','CARD',          'Card',              40);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PAY_METHOD','ONLINE',        'Online Transfer',   50);

-- Property Type
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','APARTMENT',  'Apartment',    10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','VILLA',      'Villa',         20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','STUDIO',     'Studio',        30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','TOWNHOUSE',  'Townhouse',     40);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','OFFICE',     'Office',        50);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','SHOP',       'Shop / Retail', 60);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','WAREHOUSE',  'Warehouse',     70);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_TYPE','LAND',       'Land / Plot',   80);

-- Property Status
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_STATUS','AVAILABLE',    'Available',    10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_STATUS','RENTED',       'Rented',       20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_STATUS','MAINTENANCE',  'Maintenance',  30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_STATUS','RESERVED',     'Reserved',     40);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('PROP_STATUS','SOLD',         'Sold',         50);

-- Customer Type
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('CUST_TYPE','INDIVIDUAL', 'Individual / Person', 10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('CUST_TYPE','COMPANY',    'Company',             20);

-- Customer Status
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('CUST_STATUS','ACTIVE',      'Active',      10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('CUST_STATUS','INACTIVE',    'Inactive',    20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('CUST_STATUS','BLACKLISTED', 'Blacklisted', 30);

-- Deposit Status
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('DEPOSIT_STATUS','HELD',      'Held',      10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('DEPOSIT_STATUS','RETURNED',  'Returned',  20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('DEPOSIT_STATUS','FORFEITED', 'Forfeited', 30);

-- Expense Status
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('EXP_STATUS','PENDING',   'Pending',   10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('EXP_STATUS','APPROVED',  'Approved',  20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('EXP_STATUS','PAID',      'Paid',      30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('EXP_STATUS','CANCELLED', 'Cancelled', 40);

-- Dubai Emirates
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('UAE_EMIRATE','DUBAI',         'Dubai',          10);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('UAE_EMIRATE','ABU_DHABI',     'Abu Dhabi',      20);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('UAE_EMIRATE','SHARJAH',       'Sharjah',        30);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('UAE_EMIRATE','AJMAN',         'Ajman',          40);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('UAE_EMIRATE','RAS_AL_KHAIMAH','Ras Al Khaimah', 50);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('UAE_EMIRATE','FUJAIRAH',      'Fujairah',       60);
INSERT INTO RR_RM_LOOKUP_CODES (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DISPLAY_ORDER) VALUES ('UAE_EMIRATE','UMM_AL_QUWAIN', 'Umm Al Quwain',  70);

COMMIT;

-- ============================================================
-- RR_RM_DOCUMENT_TYPES  — standard checklist
-- ============================================================
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'PASSPORT',      'Passport Copy',                       'INDIVIDUAL', 'Y', 10);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'EMIRATES_ID',   'Emirates ID Copy',                    'INDIVIDUAL', 'Y', 20);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'VISA',          'UAE Residence Visa',                  'INDIVIDUAL', 'Y', 30);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'TRADE_LICENSE', 'Trade License',                       'COMPANY',    'Y', 10);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'MOA',           'Memorandum of Association',           'COMPANY',    'Y', 20);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'POA',           'Power of Attorney (if applicable)',   'ALL',        'N', 40);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'SIGNED_AGREEMENT','Signed Rental Agreement',           'ALL',        'Y', 50);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'EJARI',         'Ejari Registration Certificate',      'ALL',        'Y', 60);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'DEWA',          'DEWA Connection / NOC',               'ALL',        'N', 70);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'CHEQUES',       'Post-Dated Cheques',                  'ALL',        'Y', 80);
INSERT INTO RR_RM_DOCUMENT_TYPES (DOCUMENT_TYPE_ID, DOC_TYPE_CODE, DOC_TYPE_NAME, CUSTOMER_TYPE, MANDATORY_FLAG, DISPLAY_ORDER)
VALUES (RR_RM_DOC_TYPES_S.NEXTVAL, 'SECURITY_CHEQUE','Security Deposit Cheque',            'ALL',        'Y', 90);

COMMIT;

-- ============================================================
-- RR_RM_EXPENSE_TYPES  — standard expense categories
-- ============================================================
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'AC_MAINTENANCE',  'AC Maintenance & Service',    'MAINTENANCE', 'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'PLUMBING',        'Plumbing Repair',             'MAINTENANCE', 'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'ELECTRICAL',      'Electrical Repair',           'MAINTENANCE', 'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'PAINTING',        'Painting & Decoration',       'MAINTENANCE', 'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'GENERAL_MAINT',   'General Maintenance',         'MAINTENANCE', 'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'DEWA',            'DEWA (Electricity & Water)',  'UTILITY',     'Y');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'DISTRICT_COOL',   'District Cooling',            'UTILITY',     'Y');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'INTERNET',        'Internet / Telecom',          'UTILITY',     'Y');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'EJARI_FEE',       'Ejari Registration Fee',      'LEGAL',       'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'MUNICIPALITY',    'Municipality Fees (5%)',      'ADMIN',       'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'BROKER_FEE',      'Broker Commission',           'ADMIN',       'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'SERVICE_CHARGE',  'Building Service Charge',     'ADMIN',       'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'INSURANCE',       'Property Insurance',          'INSURANCE',   'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'RENOVATION',      'Renovation / Fit-out',        'CAPITAL',     'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'LEGAL_FEES',      'Legal / Notary Fees',         'LEGAL',       'N');
INSERT INTO RR_RM_EXPENSE_TYPES (EXPENSE_TYPE_ID, EXPENSE_TYPE_CODE, EXPENSE_TYPE_NAME, CATEGORY, RECOVERABLE_FLAG)
VALUES (RR_RM_EXP_TYPES_S.NEXTVAL, 'OTHER',           'Other Expense',               'OTHER',       'N');

COMMIT;

-- Verify counts
SELECT 'LOOKUP_CODES' AS tbl, COUNT(*) AS cnt FROM RR_RM_LOOKUP_CODES
UNION ALL SELECT 'DOCUMENT_TYPES', COUNT(*) FROM RR_RM_DOCUMENT_TYPES
UNION ALL SELECT 'EXPENSE_TYPES',  COUNT(*) FROM RR_RM_EXPENSE_TYPES;
