-- ============================================================
-- 05_MCP_TOOL_REGISTRY.SQL   (v1)
--
-- Table: RR_MCP_TOOL_REGISTRY
-- Data-driven tool definitions for the generic MCP server
-- (electron/mcp-registry-server.cjs). Each active row becomes
-- an MCP tool exposed to Claude Desktop — adding a tool is an
-- INSERT, no code change or redeploy.
--
-- Endpoints:
--   GET    reerp/settings/mcptools      — active tools (used by the MCP server)
--   GET    reerp/admin/mcptools         — list all (admin screen)
--   POST   reerp/admin/mcptools         — create
--   PUT    reerp/admin/mcptools/:id     — update
--   DELETE reerp/admin/mcptools/:id     — delete
--
-- HOW TO RUN: APEX SQL Workshop -> SQL Commands -> run whole file.
-- ============================================================

CREATE TABLE RR_MCP_TOOL_REGISTRY (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TOOL_NAME        VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION      VARCHAR2(1000) NOT NULL,
    PARAMS_SCHEMA    CLOB,                      -- JSON: {"properties":{...},"required":[...]}
    HTTP_METHOD      VARCHAR2(10) DEFAULT 'GET' NOT NULL,
    URL_TEMPLATE     VARCHAR2(2000) NOT NULL,   -- full URL, {param} placeholders
    AUTH_TYPE        VARCHAR2(20) DEFAULT 'NONE' NOT NULL, -- NONE | BASIC_ORDS | BASIC_FUSION
    RESULT_FILTER    CLOB,                      -- JSON: {"path":"items[].child","where":{"field":"F","op":"!=","value":0}}
    IS_ACTIVE        VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CREATED_BY       VARCHAR2(150),
    CREATION_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY  VARCHAR2(150),
    LAST_UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_RR_MCP_TOOL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_RR_MCP_TOOL_METHOD CHECK (HTTP_METHOD IN ('GET','POST','PUT','DELETE')),
    CONSTRAINT CHK_RR_MCP_TOOL_AUTH   CHECK (AUTH_TYPE IN ('NONE','BASIC_ORDS','BASIC_FUSION'))
);

COMMENT ON TABLE  RR_MCP_TOOL_REGISTRY IS 'Data-driven MCP tool definitions for the generic MCP server';
COMMENT ON COLUMN RR_MCP_TOOL_REGISTRY.URL_TEMPLATE  IS 'Full URL with {param} placeholders substituted from tool arguments';
COMMENT ON COLUMN RR_MCP_TOOL_REGISTRY.RESULT_FILTER IS 'Optional declarative filter applied to the JSON response';

-- ============================================================
-- Seed: AR open installments (Oracle Fusion Cloud, Option 1 —
-- single expand call, TotalBalanceAmount != 0 filtered in server)
-- ============================================================
INSERT INTO RR_MCP_TOOL_REGISTRY
  (TOOL_NAME, DESCRIPTION, PARAMS_SCHEMA, HTTP_METHOD, URL_TEMPLATE, AUTH_TYPE, RESULT_FILTER, CREATED_BY)
VALUES (
  'ar_getOpenInstallments',
  'Get OPEN (unpaid) receivables installments for a customer from Oracle Fusion Cloud. Returns customer site totals and only installments with a remaining balance.',
  '{"properties":{"customer_name":{"type":"string","description":"Customer name, e.g. PICK AND BUY TRIBECA LTD"}},"required":["customer_name"]}',
  'GET',
  'https://efmh.fa.em3.oraclecloud.com/fscmRestApi/resources/11.13.18.05/receivablesCustomerAccountSiteActivities?q=CustomerName LIKE ''{customer_name}%''&expand=transactionPaymentSchedules&onlyData=true&limit=200',
  'BASIC_FUSION',
  '{"path":"items[].transactionPaymentSchedules","where":{"field":"TotalBalanceAmount","op":"!=","value":0}}',
  'ADMIN'
);
COMMIT;

-- Inventory: on-hand balances (served by the standalone inv-onhand-server.cjs;
-- this row is registry inventory so admins can see the tool exists).
INSERT INTO RR_MCP_TOOL_REGISTRY
  (TOOL_NAME, DESCRIPTION, PARAMS_SCHEMA, HTTP_METHOD, URL_TEMPLATE, AUTH_TYPE, RESULT_FILTER, CREATED_BY)
VALUES (
  'inv_getOnhandBalances',
  'On-hand inventory balances from Oracle Fusion Cloud with full pagination; detail_level=full also walks every child link (lots, serials, consigned) of each row. Served by inv-onhand-server.',
  '{"properties":{"item_number":{"type":"string","description":"Item number (exact or % for LIKE)"},"organization_code":{"type":"string","description":"Inventory organization code"},"subinventory_code":{"type":"string","description":"Subinventory code"},"detail_level":{"type":"string","description":"summary (default) or full"}},"required":[]}',
  'GET',
  'https://efmh.fa.em3.oraclecloud.com/fscmRestApi/resources/11.13.18.05/inventoryOnhandBalances?q=ItemNumber LIKE ''{item_number}%''&expand=lots&onlyData=true&limit=500',
  'BASIC_FUSION',
  NULL,
  'ADMIN'
);

INSERT INTO RR_MCP_TOOL_REGISTRY
  (TOOL_NAME, DESCRIPTION, PARAMS_SCHEMA, HTTP_METHOD, URL_TEMPLATE, AUTH_TYPE, RESULT_FILTER, CREATED_BY)
VALUES (
  'inv_getItemAvailability',
  'Quick availability for one item across all inventory organizations - total primary quantity, per-organization totals, subinventories holding stock. Served by inv-onhand-server.',
  '{"properties":{"item_number":{"type":"string","description":"Item number (exact or % for LIKE)"}},"required":["item_number"]}',
  'GET',
  'https://efmh.fa.em3.oraclecloud.com/fscmRestApi/resources/11.13.18.05/inventoryOnhandBalances?q=ItemNumber LIKE ''{item_number}%''&onlyData=true&limit=500',
  'BASIC_FUSION',
  NULL,
  'ADMIN'
);
COMMIT;

-- ============================================================
-- ORDS: GET /settings/mcptools — active tools for the MCP server
-- ============================================================
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'settings/mcptools', p_method => 'GET');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN
        ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'settings/mcptools');
    EXCEPTION WHEN OTHERS THEN NULL; END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'settings/mcptools',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_comments       => 'Active MCP tool definitions for the generic MCP server',
        p_source         => q'[
BEGIN
    :status_code := 200;
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.OPEN_ARRAY('tools');
    FOR r IN (
        SELECT ID, TOOL_NAME, DESCRIPTION, PARAMS_SCHEMA, HTTP_METHOD,
               URL_TEMPLATE, AUTH_TYPE, RESULT_FILTER
        FROM   RR_MCP_TOOL_REGISTRY
        WHERE  IS_ACTIVE = 'Y'
        ORDER BY TOOL_NAME
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('id',           r.ID);
        APEX_JSON.WRITE('toolName',     r.TOOL_NAME);
        APEX_JSON.WRITE('description',  r.DESCRIPTION);
        APEX_JSON.WRITE('paramsSchema', r.PARAMS_SCHEMA);
        APEX_JSON.WRITE('httpMethod',   r.HTTP_METHOD);
        APEX_JSON.WRITE('urlTemplate',  r.URL_TEMPLATE);
        APEX_JSON.WRITE('authType',     r.AUTH_TYPE);
        APEX_JSON.WRITE('resultFilter', r.RESULT_FILTER);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    HTP.P(APEX_JSON.GET_CLOB_OUTPUT);
    APEX_JSON.FREE_OUTPUT;
EXCEPTION WHEN OTHERS THEN
    :status_code := 500;
    HTP.PRN('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );
    COMMIT;
END;
/

-- ============================================================
-- ORDS Admin CRUD handlers
-- ============================================================
BEGIN
    BEGIN
        ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'admin/mcptools');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN
        ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'admin/mcptools/:id');
    EXCEPTION WHEN OTHERS THEN NULL; END;

    -- ── GET /admin/mcptools — list all ───────────────────────────────────────
    BEGIN
        ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'admin/mcptools', p_method => 'GET');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/mcptools',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_source         => q'[
BEGIN
    :status_code := 200;
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.OPEN_ARRAY('items');
    FOR r IN (
        SELECT ID, TOOL_NAME, DESCRIPTION, PARAMS_SCHEMA, HTTP_METHOD,
               URL_TEMPLATE, AUTH_TYPE, RESULT_FILTER, IS_ACTIVE,
               CREATED_BY, TO_CHAR(CREATION_DATE,'YYYY-MM-DD HH24:MI') CREATION_DATE,
               LAST_UPDATED_BY, TO_CHAR(LAST_UPDATE_DATE,'YYYY-MM-DD HH24:MI') LAST_UPDATE_DATE
        FROM   RR_MCP_TOOL_REGISTRY
        ORDER BY TOOL_NAME
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('id',             r.ID);
        APEX_JSON.WRITE('toolName',       r.TOOL_NAME);
        APEX_JSON.WRITE('description',    r.DESCRIPTION);
        APEX_JSON.WRITE('paramsSchema',   r.PARAMS_SCHEMA);
        APEX_JSON.WRITE('httpMethod',     r.HTTP_METHOD);
        APEX_JSON.WRITE('urlTemplate',    r.URL_TEMPLATE);
        APEX_JSON.WRITE('authType',       r.AUTH_TYPE);
        APEX_JSON.WRITE('resultFilter',   r.RESULT_FILTER);
        APEX_JSON.WRITE('isActive',       r.IS_ACTIVE);
        APEX_JSON.WRITE('createdBy',      r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',   r.CREATION_DATE);
        APEX_JSON.WRITE('lastUpdatedBy',  r.LAST_UPDATED_BY);
        APEX_JSON.WRITE('lastUpdateDate', r.LAST_UPDATE_DATE);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    HTP.P(APEX_JSON.GET_CLOB_OUTPUT);
    APEX_JSON.FREE_OUTPUT;
EXCEPTION WHEN OTHERS THEN
    :status_code := 500;
    HTP.PRN('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );

    -- ── POST /admin/mcptools — create ────────────────────────────────────────
    BEGIN
        ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'admin/mcptools', p_method => 'POST');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/mcptools',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => 'application/json',
        p_source         => q'[
DECLARE
    l_body   CLOB := :body_text;
    l_id     NUMBER;
BEGIN
    APEX_JSON.PARSE(l_body);
    INSERT INTO RR_MCP_TOOL_REGISTRY
      (TOOL_NAME, DESCRIPTION, PARAMS_SCHEMA, HTTP_METHOD, URL_TEMPLATE,
       AUTH_TYPE, RESULT_FILTER, IS_ACTIVE, CREATED_BY, LAST_UPDATED_BY)
    VALUES (
      APEX_JSON.GET_VARCHAR2(p_path => 'toolName'),
      APEX_JSON.GET_VARCHAR2(p_path => 'description'),
      APEX_JSON.GET_VARCHAR2(p_path => 'paramsSchema'),
      NVL(APEX_JSON.GET_VARCHAR2(p_path => 'httpMethod'), 'GET'),
      APEX_JSON.GET_VARCHAR2(p_path => 'urlTemplate'),
      NVL(APEX_JSON.GET_VARCHAR2(p_path => 'authType'), 'NONE'),
      APEX_JSON.GET_VARCHAR2(p_path => 'resultFilter'),
      NVL(APEX_JSON.GET_VARCHAR2(p_path => 'isActive'), 'Y'),
      NVL(APEX_JSON.GET_VARCHAR2(p_path => 'createdBy'), 'ADMIN'),
      NVL(APEX_JSON.GET_VARCHAR2(p_path => 'createdBy'), 'ADMIN')
    ) RETURNING ID INTO l_id;
    COMMIT;
    :status_code := 201;
    HTP.PRN('{"status":"success","id":' || l_id || '}');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );

    -- ── PUT /admin/mcptools/:id — update ─────────────────────────────────────
    BEGIN
        ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'admin/mcptools/:id', p_method => 'PUT');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/mcptools/:id',
        p_method         => 'PUT',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => 'application/json',
        p_source         => q'[
DECLARE
    l_body CLOB := :body_text;
    l_cnt  NUMBER;
BEGIN
    APEX_JSON.PARSE(l_body);
    UPDATE RR_MCP_TOOL_REGISTRY SET
      TOOL_NAME        = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'toolName'), TOOL_NAME),
      DESCRIPTION      = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'description'), DESCRIPTION),
      PARAMS_SCHEMA    = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'paramsSchema'), PARAMS_SCHEMA),
      HTTP_METHOD      = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'httpMethod'), HTTP_METHOD),
      URL_TEMPLATE     = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'urlTemplate'), URL_TEMPLATE),
      AUTH_TYPE        = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'authType'), AUTH_TYPE),
      RESULT_FILTER    = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'resultFilter'), RESULT_FILTER),
      IS_ACTIVE        = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'isActive'), IS_ACTIVE),
      LAST_UPDATED_BY  = NVL(APEX_JSON.GET_VARCHAR2(p_path => 'updatedBy'), 'ADMIN'),
      LAST_UPDATE_DATE = SYSTIMESTAMP
    WHERE ID = TO_NUMBER(:id);
    l_cnt := SQL%ROWCOUNT;
    COMMIT;
    IF l_cnt = 0 THEN
        :status_code := 404;
        HTP.PRN('{"status":"error","message":"Tool not found"}');
    ELSE
        :status_code := 200;
        HTP.PRN('{"status":"success","rowsUpdated":' || l_cnt || '}');
    END IF;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );

    -- ── DELETE /admin/mcptools/:id ───────────────────────────────────────────
    BEGIN
        ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'admin/mcptools/:id', p_method => 'DELETE');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/mcptools/:id',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_source         => q'[
DECLARE
    l_cnt NUMBER;
BEGIN
    DELETE FROM RR_MCP_TOOL_REGISTRY WHERE ID = TO_NUMBER(:id);
    l_cnt := SQL%ROWCOUNT;
    COMMIT;
    IF l_cnt = 0 THEN
        :status_code := 404;
        HTP.PRN('{"status":"error","message":"Tool not found"}');
    ELSE
        :status_code := 200;
        HTP.PRN('{"status":"success"}');
    END IF;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );

    COMMIT;
END;
/
