-- ============================================================
-- 06_MCP_CALL_LOG.SQL   (v1)
--
-- Table: RR_MCP_CALL_LOG
-- Central record of every MCP tool call and every agent run,
-- inserted by the MCP servers (mcp-call-logger.cjs) so Claude
-- activity — interactive and scheduled — is monitorable in the DB.
--
-- Endpoints:
--   POST reerp/settings/mcplog   — insert one log row (called by servers)
--   GET  reerp/admin/mcplogs     — query logs (filters: server, tool, ok, limit)
--
-- Monitoring examples:
--   -- did the morning agent run today?
--   SELECT * FROM RR_MCP_CALL_LOG
--    WHERE SERVER_NAME='agent-run' AND TRUNC(LOG_TIME)=TRUNC(SYSDATE);
--   -- failures in the last 24h
--   SELECT * FROM RR_MCP_CALL_LOG
--    WHERE OK='N' AND LOG_TIME > SYSTIMESTAMP - INTERVAL '1' DAY;
--
-- HOW TO RUN: APEX SQL Workshop -> SQL Commands -> run whole file.
-- ============================================================

CREATE TABLE RR_MCP_CALL_LOG (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LOG_TIME        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SERVER_NAME     VARCHAR2(100) NOT NULL,   -- gl-server / ar-server / ar-customer-balance / archive-server / agent-run
    TOOL_NAME       VARCHAR2(200) NOT NULL,   -- tool called, or task name for agent-run rows
    ARGS            CLOB,                     -- JSON arguments
    OK              VARCHAR2(1) DEFAULT 'Y' NOT NULL,  -- Y success / N failed
    DURATION_MS     NUMBER,
    RESULT_PREVIEW  CLOB,                     -- first ~2000 chars of the result / run output
    ERROR_MSG       VARCHAR2(2000),
    HOST_NAME       VARCHAR2(200),            -- machine the MCP server ran on
    OS_USER         VARCHAR2(200),            -- OS user who owns the process
    IP_ADDR         VARCHAR2(64),             -- machine local IPv4
    PLATFORM        VARCHAR2(60),             -- e.g. win32 10.0.22631
    CONSTRAINT CHK_RR_MCP_LOG_OK CHECK (OK IN ('Y','N'))
);

CREATE INDEX IDX_RR_MCP_LOG_TIME   ON RR_MCP_CALL_LOG (LOG_TIME);
CREATE INDEX IDX_RR_MCP_LOG_SERVER ON RR_MCP_CALL_LOG (SERVER_NAME, LOG_TIME);

COMMENT ON TABLE RR_MCP_CALL_LOG IS 'Every MCP tool call and agent run, inserted by the MCP servers for monitoring';

-- ============================================================
-- ORDS: POST /settings/mcplog — insert one row (called by servers)
-- ============================================================
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'settings/mcplog', p_method => 'POST');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN
        ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'settings/mcplog');
    EXCEPTION WHEN OTHERS THEN NULL; END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'settings/mcplog',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Insert one MCP call/agent-run log row',
        p_source         => q'[
DECLARE
    l_body CLOB := :body_text;
    l_id   NUMBER;
BEGIN
    APEX_JSON.PARSE(l_body);
    INSERT INTO RR_MCP_CALL_LOG
      (SERVER_NAME, TOOL_NAME, ARGS, OK, DURATION_MS, RESULT_PREVIEW, ERROR_MSG,
       HOST_NAME, OS_USER, IP_ADDR, PLATFORM)
    VALUES (
      NVL(APEX_JSON.GET_VARCHAR2(p_path => 'server'), 'unknown'),
      NVL(APEX_JSON.GET_VARCHAR2(p_path => 'tool'), 'unknown'),
      APEX_JSON.GET_VARCHAR2(p_path => 'args'),
      CASE WHEN NVL(APEX_JSON.GET_VARCHAR2(p_path => 'ok'), 'Y') IN ('Y','true') THEN 'Y' ELSE 'N' END,
      APEX_JSON.GET_NUMBER(p_path => 'ms'),
      APEX_JSON.GET_VARCHAR2(p_path => 'resultPreview'),
      APEX_JSON.GET_VARCHAR2(p_path => 'error'),
      APEX_JSON.GET_VARCHAR2(p_path => 'host'),
      APEX_JSON.GET_VARCHAR2(p_path => 'osUser'),
      APEX_JSON.GET_VARCHAR2(p_path => 'ip'),
      APEX_JSON.GET_VARCHAR2(p_path => 'platform')
    ) RETURNING ID INTO l_id;
    COMMIT;
    :status_code := 201;
    HTP.PRN('{"status":"success","id":' || l_id || '}');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.PRN('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );
    COMMIT;
END;
/

-- ============================================================
-- ORDS: GET /admin/mcplogs — query logs for monitoring
-- Params: server, tool, ok (Y/N), hours (default 168 = 7 days), limit
-- ============================================================
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'admin/mcplogs', p_method => 'GET');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN
        ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'admin/mcplogs');
    EXCEPTION WHEN OTHERS THEN NULL; END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'admin/mcplogs',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => '',
        p_source         => q'[
DECLARE
    v_hours NUMBER := NVL(TO_NUMBER(:hours), 168);
    v_limit NUMBER := NVL(TO_NUMBER(:limit), 200);
BEGIN
    :status_code := 200;
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.OPEN_ARRAY('items');
    FOR r IN (
        SELECT ID, TO_CHAR(LOG_TIME,'YYYY-MM-DD HH24:MI:SS') LOG_TIME,
               SERVER_NAME, TOOL_NAME, ARGS, OK, DURATION_MS,
               DBMS_LOB.SUBSTR(RESULT_PREVIEW, 2000, 1) RESULT_PREVIEW, ERROR_MSG,
               HOST_NAME, OS_USER, IP_ADDR, PLATFORM
        FROM   RR_MCP_CALL_LOG
        WHERE  LOG_TIME > SYSTIMESTAMP - NUMTODSINTERVAL(v_hours, 'HOUR')
          AND (:server IS NULL OR SERVER_NAME = :server)
          AND (:tool   IS NULL OR TOOL_NAME   = :tool)
          AND (:ok     IS NULL OR OK          = :ok)
        ORDER BY LOG_TIME DESC
        FETCH FIRST v_limit ROWS ONLY
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('id',            r.ID);
        APEX_JSON.WRITE('logTime',       r.LOG_TIME);
        APEX_JSON.WRITE('server',        r.SERVER_NAME);
        APEX_JSON.WRITE('tool',          r.TOOL_NAME);
        APEX_JSON.WRITE('args',          r.ARGS);
        APEX_JSON.WRITE('ok',            r.OK);
        APEX_JSON.WRITE('durationMs',    r.DURATION_MS);
        APEX_JSON.WRITE('resultPreview', r.RESULT_PREVIEW);
        APEX_JSON.WRITE('errorMsg',      r.ERROR_MSG);
        APEX_JSON.WRITE('host',          r.HOST_NAME);
        APEX_JSON.WRITE('osUser',        r.OS_USER);
        APEX_JSON.WRITE('ipAddr',        r.IP_ADDR);
        APEX_JSON.WRITE('platform',      r.PLATFORM);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    HTP.P(APEX_JSON.GET_CLOB_OUTPUT);
    APEX_JSON.FREE_OUTPUT;
EXCEPTION WHEN OTHERS THEN
    :status_code := 500;
    HTP.PRN('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );
    COMMIT;
END;
/
