-- =============================================================================
-- RR_TAX_SETUP.SQL
-- Input/Output Tax Master, BU Assignments, and ORDS Handlers
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: RR_INPUT_OUTPUT_TAX  — master tax definitions
-- ---------------------------------------------------------------------------
CREATE TABLE RR_INPUT_OUTPUT_TAX (
    TAX_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TAX_NAME        VARCHAR2(200)  NOT NULL,
    TAX_CODE        VARCHAR2(50)   NOT NULL,
    TAX_RATE        NUMBER(10,4)   NOT NULL,           -- percentage, e.g. 5 for 5%
    TAX_TYPE        VARCHAR2(20)   DEFAULT 'BOTH',     -- INPUT | OUTPUT | BOTH
    APPLICABILITY   VARCHAR2(10)   DEFAULT 'BOTH',     -- AP | AR | BOTH
    DESCRIPTION     VARCHAR2(500),
    STATUS          VARCHAR2(20)   DEFAULT 'ACTIVE',   -- ACTIVE | INACTIVE
    CREATED_BY      VARCHAR2(150),
    CREATION_DATE   TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(150),
    LAST_UPDATE_DATE TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_TAX_CODE_UK UNIQUE (TAX_CODE)
);

COMMENT ON TABLE  RR_INPUT_OUTPUT_TAX               IS 'Master input/output tax definitions';
COMMENT ON COLUMN RR_INPUT_OUTPUT_TAX.TAX_RATE      IS 'Percentage rate, e.g. 5 = 5%';
COMMENT ON COLUMN RR_INPUT_OUTPUT_TAX.TAX_TYPE      IS 'INPUT | OUTPUT | BOTH';
COMMENT ON COLUMN RR_INPUT_OUTPUT_TAX.APPLICABILITY IS 'AP | AR | BOTH';
COMMENT ON COLUMN RR_INPUT_OUTPUT_TAX.STATUS        IS 'ACTIVE | INACTIVE';

-- ---------------------------------------------------------------------------
-- TABLE: RR_TAX_ASSIGNMENTS  — tax-to-BU assignments with GL account
-- ---------------------------------------------------------------------------
CREATE TABLE RR_TAX_ASSIGNMENTS (
    ASSIGNMENT_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TAX_ID           NUMBER        NOT NULL,
    BUSINESS_UNIT_NAME VARCHAR2(360) NOT NULL,
    TAX_ACCOUNT      VARCHAR2(200),                   -- GL account combination
    EFFECTIVE_FROM   DATE,
    EFFECTIVE_TO     DATE,
    STATUS           VARCHAR2(20)  DEFAULT 'ACTIVE',  -- ACTIVE | INACTIVE
    CREATED_BY       VARCHAR2(150),
    CREATION_DATE    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY  VARCHAR2(150),
    LAST_UPDATE_DATE TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_TAX_ASGN_FK  FOREIGN KEY (TAX_ID) REFERENCES RR_INPUT_OUTPUT_TAX(TAX_ID) ON DELETE CASCADE,
    CONSTRAINT RR_TAX_ASGN_UK  UNIQUE (TAX_ID, BUSINESS_UNIT_NAME)
);

COMMENT ON TABLE  RR_TAX_ASSIGNMENTS                    IS 'Tax-to-Business-Unit assignments';
COMMENT ON COLUMN RR_TAX_ASSIGNMENTS.TAX_ACCOUNT        IS 'GL account combination for posting tax';
COMMENT ON COLUMN RR_TAX_ASSIGNMENTS.EFFECTIVE_FROM     IS 'Assignment effective start date';
COMMENT ON COLUMN RR_TAX_ASSIGNMENTS.EFFECTIVE_TO       IS 'Assignment effective end date (NULL = open-ended)';

CREATE INDEX RR_TAX_ASGN_TAXID_IDX ON RR_TAX_ASSIGNMENTS (TAX_ID);
CREATE INDEX RR_TAX_ASGN_BU_IDX    ON RR_TAX_ASSIGNMENTS (BUSINESS_UNIT_NAME);

-- =============================================================================
-- ORDS HANDLERS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. GET  tax/taxes  — search/list taxes
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'tax/taxes',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_clob  CLOB;
BEGIN
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.OPEN_ARRAY('items');

    FOR r IN (
        SELECT TAX_ID, TAX_NAME, TAX_CODE, TAX_RATE, TAX_TYPE,
               APPLICABILITY, DESCRIPTION, STATUS,
               CREATED_BY, TO_CHAR(CREATION_DATE,'YYYY-MM-DD"T"HH24:MI:SS') AS CREATION_DATE,
               LAST_UPDATED_BY, TO_CHAR(LAST_UPDATE_DATE,'YYYY-MM-DD"T"HH24:MI:SS') AS LAST_UPDATE_DATE
        FROM   RR_INPUT_OUTPUT_TAX
        WHERE  (:tax_code       IS NULL OR UPPER(TAX_CODE)  LIKE '%'||UPPER(:tax_code)||'%')
        AND    (:tax_name       IS NULL OR UPPER(TAX_NAME)  LIKE '%'||UPPER(:tax_name)||'%')
        AND    (:applicability  IS NULL OR APPLICABILITY    = :applicability)
        AND    (:status         IS NULL OR STATUS           = :status)
        ORDER  BY TAX_NAME
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('taxId',          r.TAX_ID);
        APEX_JSON.WRITE('taxName',        r.TAX_NAME);
        APEX_JSON.WRITE('taxCode',        r.TAX_CODE);
        APEX_JSON.WRITE('taxRate',        r.TAX_RATE);
        APEX_JSON.WRITE('taxType',        r.TAX_TYPE);
        APEX_JSON.WRITE('applicability',  r.APPLICABILITY);
        APEX_JSON.WRITE('description',    r.DESCRIPTION);
        APEX_JSON.WRITE('status',         r.STATUS);
        APEX_JSON.WRITE('createdBy',      r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',   r.CREATION_DATE);
        APEX_JSON.WRITE('lastUpdatedBy',  r.LAST_UPDATED_BY);
        APEX_JSON.WRITE('lastUpdateDate', r.LAST_UPDATE_DATE);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;

    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    v_clob := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    HTP.P(v_clob);
EXCEPTION
    WHEN OTHERS THEN
        APEX_JSON.FREE_OUTPUT;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 2. POST  tax/taxes  — create or update a tax
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'tax/taxes',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_body    CLOB;
    v_dest    INTEGER := 1; v_src INTEGER := 1;
    v_lang    INTEGER := DBMS_LOB.DEFAULT_LANG_CTX; v_warn INTEGER;
    v_tax_id      NUMBER;
    v_tax_name    VARCHAR2(200);
    v_tax_code    VARCHAR2(50);
    v_tax_rate    NUMBER;
    v_tax_type    VARCHAR2(20);
    v_applicability VARCHAR2(10);
    v_description VARCHAR2(500);
    v_status      VARCHAR2(20);
    v_user        VARCHAR2(150);
    v_exists      NUMBER := 0;
BEGIN
    DBMS_LOB.CREATETEMPORARY(v_body, TRUE);
    DBMS_LOB.CONVERTTOCLOB(v_body, :body, DBMS_LOB.LOBMAXSIZE, v_dest, v_src,
                           NLS_CHARSET_ID('AL32UTF8'), v_lang, v_warn);

    SELECT jt.tax_id, jt.tax_name, jt.tax_code, jt.tax_rate, jt.tax_type,
           jt.applicability, jt.description, jt.status, jt.user_name
    INTO   v_tax_id, v_tax_name, v_tax_code, v_tax_rate, v_tax_type,
           v_applicability, v_description, v_status, v_user
    FROM   JSON_TABLE(v_body, '$' COLUMNS (
               tax_id       NUMBER        PATH '$.taxId',
               tax_name     VARCHAR2(200) PATH '$.taxName',
               tax_code     VARCHAR2(50)  PATH '$.taxCode',
               tax_rate     NUMBER        PATH '$.taxRate',
               tax_type     VARCHAR2(20)  PATH '$.taxType',
               applicability VARCHAR2(10) PATH '$.applicability',
               description  VARCHAR2(500) PATH '$.description',
               status       VARCHAR2(20)  PATH '$.status',
               user_name    VARCHAR2(150) PATH '$.lastUpdatedBy'
           )) jt;

    v_status := NVL(v_status, 'ACTIVE');
    v_user   := NVL(v_user,   'ERP_USER');

    IF v_tax_id IS NOT NULL THEN
        SELECT COUNT(1) INTO v_exists FROM RR_INPUT_OUTPUT_TAX WHERE TAX_ID = v_tax_id;
    END IF;

    IF v_exists > 0 THEN
        UPDATE RR_INPUT_OUTPUT_TAX SET
            TAX_NAME         = NVL(v_tax_name,      TAX_NAME),
            TAX_CODE         = NVL(v_tax_code,      TAX_CODE),
            TAX_RATE         = NVL(v_tax_rate,      TAX_RATE),
            TAX_TYPE         = NVL(v_tax_type,      TAX_TYPE),
            APPLICABILITY    = NVL(v_applicability, APPLICABILITY),
            DESCRIPTION      = v_description,
            STATUS           = NVL(v_status,        STATUS),
            LAST_UPDATED_BY  = v_user,
            LAST_UPDATE_DATE = SYSTIMESTAMP
        WHERE TAX_ID = v_tax_id;
    ELSE
        INSERT INTO RR_INPUT_OUTPUT_TAX (
            TAX_NAME, TAX_CODE, TAX_RATE, TAX_TYPE, APPLICABILITY,
            DESCRIPTION, STATUS, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE
        ) VALUES (
            v_tax_name, v_tax_code, v_tax_rate,
            NVL(v_tax_type, 'BOTH'), NVL(v_applicability, 'BOTH'),
            v_description, v_status, v_user, SYSTIMESTAMP, v_user, SYSTIMESTAMP
        ) RETURNING TAX_ID INTO v_tax_id;
    END IF;

    COMMIT;
    HTP.P('{"status":"success","taxId":' || v_tax_id || '}');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        HTP.P('{"status":"error","message":"Tax code already exists"}');
    WHEN OTHERS THEN
        ROLLBACK;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 3. POST  tax/taxes/delete  — delete a tax (cascades to assignments)
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'tax/taxes/delete',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_tax_id NUMBER;
BEGIN
    SELECT jt.tax_id INTO v_tax_id
    FROM   JSON_TABLE(:body_text, '$' COLUMNS (tax_id NUMBER PATH '$.taxId')) jt;

    DELETE FROM RR_INPUT_OUTPUT_TAX WHERE TAX_ID = v_tax_id;
    IF SQL%ROWCOUNT = 0 THEN
        HTP.P('{"status":"error","message":"Tax not found"}');
    ELSE
        COMMIT;
        HTP.P('{"status":"success","taxId":' || v_tax_id || '}');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 4. GET  tax/assignments  — list assignments, filterable by BU / tax
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'tax/assignments',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_clob CLOB;
BEGIN
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.OPEN_ARRAY('items');

    FOR r IN (
        SELECT a.ASSIGNMENT_ID, a.TAX_ID, a.BUSINESS_UNIT_NAME,
               a.TAX_ACCOUNT, a.STATUS,
               TO_CHAR(a.EFFECTIVE_FROM, 'YYYY-MM-DD') AS EFFECTIVE_FROM,
               TO_CHAR(a.EFFECTIVE_TO,   'YYYY-MM-DD') AS EFFECTIVE_TO,
               a.CREATED_BY, TO_CHAR(a.CREATION_DATE,'YYYY-MM-DD"T"HH24:MI:SS') AS CREATION_DATE,
               a.LAST_UPDATED_BY, TO_CHAR(a.LAST_UPDATE_DATE,'YYYY-MM-DD"T"HH24:MI:SS') AS LAST_UPDATE_DATE,
               t.TAX_NAME, t.TAX_CODE, t.TAX_RATE, t.TAX_TYPE, t.APPLICABILITY
        FROM   RR_TAX_ASSIGNMENTS a
        JOIN   RR_INPUT_OUTPUT_TAX t ON t.TAX_ID = a.TAX_ID
        WHERE  (:business_unit IS NULL OR UPPER(a.BUSINESS_UNIT_NAME) LIKE '%'||UPPER(:business_unit)||'%')
        AND    (:tax_id        IS NULL OR a.TAX_ID = :tax_id)
        AND    (:status        IS NULL OR a.STATUS = :status)
        ORDER  BY a.BUSINESS_UNIT_NAME, t.TAX_CODE
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('assignmentId',    r.ASSIGNMENT_ID);
        APEX_JSON.WRITE('taxId',           r.TAX_ID);
        APEX_JSON.WRITE('taxName',         r.TAX_NAME);
        APEX_JSON.WRITE('taxCode',         r.TAX_CODE);
        APEX_JSON.WRITE('taxRate',         r.TAX_RATE);
        APEX_JSON.WRITE('taxType',         r.TAX_TYPE);
        APEX_JSON.WRITE('applicability',   r.APPLICABILITY);
        APEX_JSON.WRITE('businessUnitName',r.BUSINESS_UNIT_NAME);
        APEX_JSON.WRITE('taxAccount',      r.TAX_ACCOUNT);
        APEX_JSON.WRITE('effectiveFrom',   r.EFFECTIVE_FROM);
        APEX_JSON.WRITE('effectiveTo',     r.EFFECTIVE_TO);
        APEX_JSON.WRITE('status',          r.STATUS);
        APEX_JSON.WRITE('createdBy',       r.CREATED_BY);
        APEX_JSON.WRITE('creationDate',    r.CREATION_DATE);
        APEX_JSON.WRITE('lastUpdatedBy',   r.LAST_UPDATED_BY);
        APEX_JSON.WRITE('lastUpdateDate',  r.LAST_UPDATE_DATE);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;

    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    v_clob := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    HTP.P(v_clob);
EXCEPTION
    WHEN OTHERS THEN
        APEX_JSON.FREE_OUTPUT;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 5. POST  tax/assignments  — create or update an assignment
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'tax/assignments',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_body          CLOB;
    v_dest INTEGER := 1; v_src INTEGER := 1;
    v_lang INTEGER := DBMS_LOB.DEFAULT_LANG_CTX; v_warn INTEGER;
    v_assignment_id NUMBER;
    v_tax_id        NUMBER;
    v_bu_name       VARCHAR2(360);
    v_tax_account   VARCHAR2(200);
    v_eff_from      DATE;
    v_eff_to        DATE;
    v_status        VARCHAR2(20);
    v_user          VARCHAR2(150);
    v_exists        NUMBER := 0;
BEGIN
    DBMS_LOB.CREATETEMPORARY(v_body, TRUE);
    DBMS_LOB.CONVERTTOCLOB(v_body, :body, DBMS_LOB.LOBMAXSIZE, v_dest, v_src,
                           NLS_CHARSET_ID('AL32UTF8'), v_lang, v_warn);

    SELECT jt.assignment_id, jt.tax_id, jt.bu_name, jt.tax_account,
           TO_DATE(jt.eff_from, 'YYYY-MM-DD'), TO_DATE(jt.eff_to, 'YYYY-MM-DD'),
           jt.status, jt.user_name
    INTO   v_assignment_id, v_tax_id, v_bu_name, v_tax_account,
           v_eff_from, v_eff_to, v_status, v_user
    FROM   JSON_TABLE(v_body, '$' COLUMNS (
               assignment_id NUMBER        PATH '$.assignmentId',
               tax_id        NUMBER        PATH '$.taxId',
               bu_name       VARCHAR2(360) PATH '$.businessUnitName',
               tax_account   VARCHAR2(200) PATH '$.taxAccount',
               eff_from      VARCHAR2(20)  PATH '$.effectiveFrom',
               eff_to        VARCHAR2(20)  PATH '$.effectiveTo',
               status        VARCHAR2(20)  PATH '$.status',
               user_name     VARCHAR2(150) PATH '$.lastUpdatedBy'
           )) jt;

    v_status := NVL(v_status, 'ACTIVE');
    v_user   := NVL(v_user,   'ERP_USER');

    IF v_assignment_id IS NOT NULL THEN
        SELECT COUNT(1) INTO v_exists FROM RR_TAX_ASSIGNMENTS WHERE ASSIGNMENT_ID = v_assignment_id;
    END IF;

    IF v_exists > 0 THEN
        UPDATE RR_TAX_ASSIGNMENTS SET
            TAX_ID           = NVL(v_tax_id,      TAX_ID),
            BUSINESS_UNIT_NAME = NVL(v_bu_name,   BUSINESS_UNIT_NAME),
            TAX_ACCOUNT      = v_tax_account,
            EFFECTIVE_FROM   = v_eff_from,
            EFFECTIVE_TO     = v_eff_to,
            STATUS           = NVL(v_status,      STATUS),
            LAST_UPDATED_BY  = v_user,
            LAST_UPDATE_DATE = SYSTIMESTAMP
        WHERE ASSIGNMENT_ID = v_assignment_id;
    ELSE
        INSERT INTO RR_TAX_ASSIGNMENTS (
            TAX_ID, BUSINESS_UNIT_NAME, TAX_ACCOUNT,
            EFFECTIVE_FROM, EFFECTIVE_TO, STATUS,
            CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE
        ) VALUES (
            v_tax_id, v_bu_name, v_tax_account,
            v_eff_from, v_eff_to, v_status,
            v_user, SYSTIMESTAMP, v_user, SYSTIMESTAMP
        ) RETURNING ASSIGNMENT_ID INTO v_assignment_id;
    END IF;

    COMMIT;
    HTP.P('{"status":"success","assignmentId":' || v_assignment_id || '}');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        HTP.P('{"status":"error","message":"This tax is already assigned to that business unit"}');
    WHEN OTHERS THEN
        ROLLBACK;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 6. POST  tax/assignments/delete  — delete an assignment
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'tax/assignments/delete',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_id NUMBER;
BEGIN
    SELECT jt.id INTO v_id
    FROM   JSON_TABLE(:body_text, '$' COLUMNS (id NUMBER PATH '$.assignmentId')) jt;

    DELETE FROM RR_TAX_ASSIGNMENTS WHERE ASSIGNMENT_ID = v_id;
    IF SQL%ROWCOUNT = 0 THEN
        HTP.P('{"status":"error","message":"Assignment not found"}');
    ELSE
        COMMIT;
        HTP.P('{"status":"success","assignmentId":' || v_id || '}');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/

-- ---------------------------------------------------------------------------
-- 7. GET  tax/taxes/bybu  — active taxes for a BU (for use in invoice/AR dropdowns)
--    ?business_unit=X   returns taxes assigned to that BU that are currently active
-- ---------------------------------------------------------------------------
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'tax/taxes/bybu',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => q'[
DECLARE
    v_clob CLOB;
BEGIN
    APEX_JSON.INITIALIZE_CLOB_OUTPUT;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('status', 'success');
    APEX_JSON.OPEN_ARRAY('items');

    FOR r IN (
        SELECT t.TAX_ID, t.TAX_NAME, t.TAX_CODE, t.TAX_RATE,
               t.TAX_TYPE, t.APPLICABILITY,
               a.TAX_ACCOUNT, a.ASSIGNMENT_ID
        FROM   RR_INPUT_OUTPUT_TAX  t
        JOIN   RR_TAX_ASSIGNMENTS   a ON a.TAX_ID = t.TAX_ID
        WHERE  UPPER(a.BUSINESS_UNIT_NAME) = UPPER(:business_unit)
        AND    t.STATUS = 'ACTIVE'
        AND    a.STATUS = 'ACTIVE'
        AND    (a.EFFECTIVE_FROM IS NULL OR a.EFFECTIVE_FROM <= SYSDATE)
        AND    (a.EFFECTIVE_TO   IS NULL OR a.EFFECTIVE_TO   >= SYSDATE)
        AND    (:applicability IS NULL OR t.APPLICABILITY IN (:applicability, 'BOTH'))
        ORDER  BY t.TAX_CODE
    ) LOOP
        APEX_JSON.OPEN_OBJECT;
        APEX_JSON.WRITE('taxId',          r.TAX_ID);
        APEX_JSON.WRITE('taxName',        r.TAX_NAME);
        APEX_JSON.WRITE('taxCode',        r.TAX_CODE);
        APEX_JSON.WRITE('taxRate',        r.TAX_RATE);
        APEX_JSON.WRITE('taxType',        r.TAX_TYPE);
        APEX_JSON.WRITE('applicability',  r.APPLICABILITY);
        APEX_JSON.WRITE('taxAccount',     r.TAX_ACCOUNT);
        APEX_JSON.WRITE('assignmentId',   r.ASSIGNMENT_ID);
        APEX_JSON.CLOSE_OBJECT;
    END LOOP;

    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
    v_clob := APEX_JSON.GET_CLOB_OUTPUT;
    APEX_JSON.FREE_OUTPUT;
    HTP.P(v_clob);
EXCEPTION
    WHEN OTHERS THEN
        APEX_JSON.FREE_OUTPUT;
        HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]',
        p_items_per_page => 0
    );
    COMMIT;
END;
/
