-- =============================================================================
-- AP Payment Attachments  (mirror of 19_ap_invoice_attachments.sql)
-- Table : RR_AP_PAYMENT_ATTACHMENTS
-- Package : RR_AP_PAY_ATTACH_PKG
-- Handlers:
--   POST   reerp/ap/payments/:check_id/attachments                  (upload)
--   GET    reerp/ap/payments/:check_id/attachments                  (list)
--   GET    reerp/ap/payments/:check_id/attachments/:attachment_id   (download binary)
--   DELETE reerp/ap/payments/:check_id/attachments/:attachment_id   (soft delete)
--
-- Files are stored as BLOBs.  Upload accepts JSON with base64-encoded content.
-- Download streams the raw binary back with the original Content-Type.
--
-- Run each block separately in SQL Workshop > SQL Commands (as schema owner)
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1.  Table
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE RR_AP_PAYMENT_ATTACHMENTS (
      ATTACHMENT_ID  NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      CHECK_ID       NUMBER          NOT NULL,
      FILE_NAME      VARCHAR2(500)   NOT NULL,
      FILE_SIZE      NUMBER,
      MIME_TYPE      VARCHAR2(200),
      FILE_CONTENT   BLOB,
      DESCRIPTION    VARCHAR2(1000),
      STATUS         VARCHAR2(20)    DEFAULT ''ACTIVE'' NOT NULL,
      UPLOADED_BY    VARCHAR2(200),
      UPLOAD_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT RR_AP_PAY_ATTACH_STATUS_CK CHECK (STATUS IN (''ACTIVE'',''DELETED''))
    )
  ';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX RR_AP_PAY_ATTACH_CHK_IX ON RR_AP_PAYMENT_ATTACHMENTS (CHECK_ID, STATUS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/


-- ---------------------------------------------------------------------------
-- 2.  Package spec
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE RR_AP_PAY_ATTACH_PKG AS

  PROCEDURE base64_to_blob (
    p_base64  IN  CLOB,
    p_blob    OUT BLOB
  );

  PROCEDURE upload_attachment (
    p_check_id      IN  NUMBER,
    p_file_name     IN  VARCHAR2,
    p_mime_type     IN  VARCHAR2,
    p_file_size     IN  NUMBER,
    p_file_content  IN  BLOB,
    p_description   IN  VARCHAR2,
    p_uploaded_by   IN  VARCHAR2,
    p_attach_id     OUT NUMBER
  );

  FUNCTION list_attachments (
    p_check_id IN NUMBER
  ) RETURN CLOB;

  PROCEDURE get_attachment (
    p_attach_id   IN  NUMBER,
    p_file_name   OUT VARCHAR2,
    p_mime_type   OUT VARCHAR2,
    p_file_size   OUT NUMBER,
    p_content     OUT BLOB
  );

  PROCEDURE delete_attachment (
    p_attach_id   IN NUMBER,
    p_deleted_by  IN VARCHAR2
  );

END RR_AP_PAY_ATTACH_PKG;
/


-- ---------------------------------------------------------------------------
-- 3.  Package body
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY RR_AP_PAY_ATTACH_PKG AS

  -- ── JSON helpers ────────────────────────────────────────────────────────
  FUNCTION esc(p IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN REPLACE(REPLACE(p, CHR(92), CHR(92)||CHR(92)), '"', CHR(92)||'"');
  END;
  FUNCTION jstr(p IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE WHEN p IS NULL THEN 'null' ELSE '"'||esc(p)||'"' END;
  END;
  FUNCTION jnum(p IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE WHEN p IS NULL THEN 'null' ELSE TO_CHAR(p) END;
  END;
  FUNCTION jts(p IN TIMESTAMP) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE WHEN p IS NULL THEN 'null'
           ELSE '"'||TO_CHAR(p,'YYYY-MM-DD"T"HH24:MI:SS')||'"' END;
  END;

  -- ── base64 → BLOB ────────────────────────────────────────────────────────
  PROCEDURE base64_to_blob (
    p_base64  IN  CLOB,
    p_blob    OUT BLOB
  ) IS
    v_chunk  VARCHAR2(32767);
    v_raw    RAW(24576);
    v_offset PLS_INTEGER := 1;
    v_total  PLS_INTEGER;
    c_amt    CONSTANT PLS_INTEGER := 24576;  -- multiple of 4 → clean base64 boundary
  BEGIN
    DBMS_LOB.CREATETEMPORARY(p_blob, TRUE, DBMS_LOB.SESSION);
    v_total := DBMS_LOB.GETLENGTH(p_base64);
    WHILE v_offset <= v_total LOOP
      v_chunk := DBMS_LOB.SUBSTR(p_base64, c_amt, v_offset);
      EXIT WHEN v_chunk IS NULL OR LENGTH(v_chunk) = 0;
      v_raw := UTL_ENCODE.BASE64_DECODE(UTL_RAW.CAST_TO_RAW(v_chunk));
      DBMS_LOB.WRITEAPPEND(p_blob, UTL_RAW.LENGTH(v_raw), v_raw);
      v_offset := v_offset + c_amt;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      IF DBMS_LOB.ISTEMPORARY(p_blob) = 1 THEN
        DBMS_LOB.FREETEMPORARY(p_blob);
      END IF;
      RAISE;
  END base64_to_blob;

  -- ── Upload ───────────────────────────────────────────────────────────────
  PROCEDURE upload_attachment (
    p_check_id      IN  NUMBER,
    p_file_name     IN  VARCHAR2,
    p_mime_type     IN  VARCHAR2,
    p_file_size     IN  NUMBER,
    p_file_content  IN  BLOB,
    p_description   IN  VARCHAR2,
    p_uploaded_by   IN  VARCHAR2,
    p_attach_id     OUT NUMBER
  ) IS
  BEGIN
    INSERT INTO RR_AP_PAYMENT_ATTACHMENTS (
      CHECK_ID, FILE_NAME, FILE_SIZE, MIME_TYPE,
      FILE_CONTENT, DESCRIPTION, STATUS, UPLOADED_BY, UPLOAD_DATE
    ) VALUES (
      p_check_id, p_file_name, p_file_size, p_mime_type,
      p_file_content, p_description, 'ACTIVE', p_uploaded_by, SYSTIMESTAMP
    )
    RETURNING ATTACHMENT_ID INTO p_attach_id;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
  END upload_attachment;

  -- ── List ─────────────────────────────────────────────────────────────────
  FUNCTION list_attachments (
    p_check_id IN NUMBER
  ) RETURN CLOB IS
    v_buf   CLOB    := '{"attachments":[';
    v_first BOOLEAN := TRUE;
  BEGIN
    FOR r IN (
      SELECT ATTACHMENT_ID, FILE_NAME, FILE_SIZE, MIME_TYPE,
             DESCRIPTION, UPLOADED_BY, UPLOAD_DATE
        FROM RR_AP_PAYMENT_ATTACHMENTS
       WHERE CHECK_ID = p_check_id
         AND STATUS   = 'ACTIVE'
       ORDER BY UPLOAD_DATE DESC
    ) LOOP
      IF NOT v_first THEN v_buf := v_buf || ','; END IF;
      v_first := FALSE;
      v_buf := v_buf || '{'
        || '"attachmentId":'  || jnum(r.ATTACHMENT_ID) || ','
        || '"fileName":'      || jstr(r.FILE_NAME)     || ','
        || '"fileSize":'      || jnum(r.FILE_SIZE)     || ','
        || '"mimeType":'      || jstr(r.MIME_TYPE)     || ','
        || '"description":'   || jstr(r.DESCRIPTION)   || ','
        || '"uploadedBy":'    || jstr(r.UPLOADED_BY)   || ','
        || '"uploadDate":'    || jts(r.UPLOAD_DATE)
      || '}';
    END LOOP;
    RETURN v_buf || ']}';
  END list_attachments;

  -- ── Get one (for download) ────────────────────────────────────────────────
  PROCEDURE get_attachment (
    p_attach_id   IN  NUMBER,
    p_file_name   OUT VARCHAR2,
    p_mime_type   OUT VARCHAR2,
    p_file_size   OUT NUMBER,
    p_content     OUT BLOB
  ) IS
  BEGIN
    SELECT FILE_NAME, MIME_TYPE, FILE_SIZE, FILE_CONTENT
      INTO p_file_name, p_mime_type, p_file_size, p_content
      FROM RR_AP_PAYMENT_ATTACHMENTS
     WHERE ATTACHMENT_ID = p_attach_id
       AND STATUS        = 'ACTIVE';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      p_file_name := NULL; p_mime_type := NULL;
      p_file_size := NULL; p_content   := NULL;
  END get_attachment;

  -- ── Soft delete ──────────────────────────────────────────────────────────
  PROCEDURE delete_attachment (
    p_attach_id  IN NUMBER,
    p_deleted_by IN VARCHAR2
  ) IS
  BEGIN
    UPDATE RR_AP_PAYMENT_ATTACHMENTS
       SET STATUS = 'DELETED'
     WHERE ATTACHMENT_ID = p_attach_id;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
  END delete_attachment;

END RR_AP_PAY_ATTACH_PKG;
/


-- ---------------------------------------------------------------------------
-- 4.  Drop & recreate the two URL templates
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ap/payments/:check_id/attachments');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ap/payments/:check_id/attachments/:attachment_id');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- ---------------------------------------------------------------------------
-- 5a.  GET ap/payments/:check_id/attachments  — list
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/payments/:check_id/attachments',
    p_method        => 'GET',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => '',
    p_comments      => 'List attachments for a payment',
    p_source        => q'[
DECLARE
  v_result CLOB;
BEGIN
  v_result     := RR_AP_PAY_ATTACH_PKG.list_attachments(p_check_id => :check_id);
  :status_code := 200;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.PRN(v_result);
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/


-- ---------------------------------------------------------------------------
-- 5b.  POST ap/payments/:check_id/attachments  — upload
--      Body: JSON { fileName, mimeType, fileSize, fileContent (base64), description, uploadedBy }
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/payments/:check_id/attachments',
    p_method        => 'POST',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => 'application/json',
    p_comments      => 'Upload a file attachment for a payment',
    p_source        => q'[
DECLARE
  v_body       CLOB := :body_text;
  v_json       JSON_OBJECT_T;
  v_check_id   NUMBER  := :check_id;
  v_file_name  VARCHAR2(500);
  v_mime_type  VARCHAR2(200);
  v_file_size  NUMBER;
  v_desc       VARCHAR2(1000);
  v_up_by      VARCHAR2(200);
  v_b64        CLOB;
  v_blob       BLOB;
  v_attach_id  NUMBER;
BEGIN
  v_json := JSON_OBJECT_T.PARSE(v_body);

  v_file_name  := v_json.GET_STRING('fileName');
  v_mime_type  := NVL(v_json.GET_STRING('mimeType'), 'application/octet-stream');
  v_file_size  := v_json.GET_NUMBER('fileSize');
  v_desc       := v_json.GET_STRING('description');
  v_up_by      := v_json.GET_STRING('uploadedBy');
  v_b64        := v_json.GET_CLOB('fileContent');

  RR_AP_PAY_ATTACH_PKG.base64_to_blob(p_base64 => v_b64, p_blob => v_blob);

  RR_AP_PAY_ATTACH_PKG.upload_attachment(
    p_check_id     => v_check_id,
    p_file_name    => v_file_name,
    p_mime_type    => v_mime_type,
    p_file_size    => v_file_size,
    p_file_content => v_blob,
    p_description  => v_desc,
    p_uploaded_by  => v_up_by,
    p_attach_id    => v_attach_id
  );

  :status_code := 201;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.PRN('{"success":true,"attachmentId":' || v_attach_id || '}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"success":false,"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/


-- ---------------------------------------------------------------------------
-- 6a.  GET ap/payments/:check_id/attachments/:attachment_id  — download binary
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/payments/:check_id/attachments/:attachment_id',
    p_method        => 'GET',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => '',
    p_comments      => 'Download a specific payment attachment as binary',
    p_source        => q'[
DECLARE
  v_file_name VARCHAR2(500);
  v_mime_type VARCHAR2(200);
  v_file_size NUMBER;
  v_content   BLOB;
BEGIN
  RR_AP_PAY_ATTACH_PKG.get_attachment(
    p_attach_id  => :attachment_id,
    p_file_name  => v_file_name,
    p_mime_type  => v_mime_type,
    p_file_size  => v_file_size,
    p_content    => v_content
  );

  IF v_file_name IS NULL THEN
    :status_code := 404;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"error":"Attachment not found"}');
    RETURN;
  END IF;

  OWA_UTIL.MIME_HEADER(NVL(v_mime_type, 'application/octet-stream'), FALSE);
  HTP.P('Content-Disposition: attachment; filename="' || v_file_name || '"');
  HTP.P('Content-Length: ' || DBMS_LOB.GETLENGTH(v_content));
  OWA_UTIL.HTTP_HEADER_CLOSE;
  WPG_DOCLOAD.DOWNLOAD_FILE(v_content);
  :status_code := 200;
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/


-- ---------------------------------------------------------------------------
-- 6b.  DELETE ap/payments/:check_id/attachments/:attachment_id  — soft delete
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/payments/:check_id/attachments/:attachment_id',
    p_method        => 'DELETE',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => '',
    p_comments      => 'Soft-delete a payment attachment',
    p_source        => q'[
DECLARE
  v_deleted_by VARCHAR2(200) := :deleted_by;
BEGIN
  RR_AP_PAY_ATTACH_PKG.delete_attachment(
    p_attach_id  => :attachment_id,
    p_deleted_by => v_deleted_by
  );
  :status_code := 200;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.PRN('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"success":false,"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/
