-- =============================================================================
-- AP Multiperiod Accounting
-- Table   : RR_AP_INVOICE_MULTIPERIOD_SCHEDULE
-- Package : RR_AP_MPA_PKG
-- Handlers:
--   GET  reerp/ap/multiperiod                  (list / search schedules)
--   GET  reerp/ap/multiperiod/:invoice_id       (detail for one invoice)
--   POST reerp/ap/multiperiod/generate          (generate / refresh schedule)
--   POST reerp/ap/multiperiod/mark-posted       (stamp lines as posted)
--
-- Run each block separately in SQL Workshop > SQL Commands (as schema owner)
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1.  Table
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE RR_AP_INVOICE_MULTIPERIOD_SCHEDULE (
      SCHEDULE_ID          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      INVOICE_ID           NUMBER          NOT NULL,
      INVOICE_NUMBER       VARCHAR2(50),
      INVOICE_LINE_ID      NUMBER,
      LINE_NUMBER          NUMBER,
      BUSINESS_UNIT        VARCHAR2(200),
      SUPPLIER             VARCHAR2(500),
      SUPPLIER_NUMBER      VARCHAR2(30),
      SUPPLIER_ID          NUMBER,
      INVOICE_DATE         DATE,
      PERIOD_DATE          DATE            NOT NULL,
      PERIOD_NAME          VARCHAR2(20),
      ORIGINAL_AMOUNT      NUMBER,
      PERIOD_AMOUNT        NUMBER          NOT NULL,
      ACCRUAL_ACCOUNT      VARCHAR2(240),
      CHARGE_ACCOUNT       VARCHAR2(240),
      DESCRIPTION          VARCHAR2(1000),
      CURRENCY_CODE        VARCHAR2(15)    DEFAULT ''AED'',
      POSTING_STATUS       VARCHAR2(20)    DEFAULT ''Not Posted''
                             CONSTRAINT RR_AP_MPA_POST_CK
                             CHECK (POSTING_STATUS IN (''Not Posted'',''Posted'',''Error'')),
      TRANSACTION_STATUS   VARCHAR2(20)    DEFAULT ''Active''
                             CONSTRAINT RR_AP_MPA_TXN_CK
                             CHECK (TRANSACTION_STATUS IN (''Active'',''Cancelled'')),
      SLA_HEADER_ID        NUMBER,
      POSTED_DATE          DATE,
      POSTED_BY            VARCHAR2(200),
      CREATED_BY           VARCHAR2(200),
      CREATION_DATE        TIMESTAMP       DEFAULT SYSTIMESTAMP,
      LAST_UPDATED_BY      VARCHAR2(200),
      LAST_UPDATE_DATE     TIMESTAMP       DEFAULT SYSTIMESTAMP
    )
  ';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE INDEX RR_AP_MPA_INV_STATUS_IX
      ON RR_AP_INVOICE_MULTIPERIOD_SCHEDULE (INVOICE_ID, POSTING_STATUS)
  ';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/


-- ---------------------------------------------------------------------------
-- 2.  Package spec
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE RR_AP_MPA_PKG AS

  -- Generate (or refresh) the multiperiod schedule for an invoice
  PROCEDURE generate_schedule (
    p_invoice_id IN NUMBER
  );

  -- List / search schedules (grouped by invoice)
  FUNCTION list_schedules (
    p_invoice_number  IN VARCHAR2,
    p_supplier        IN VARCHAR2,
    p_business_unit   IN VARCHAR2,
    p_posting_status  IN VARCHAR2
  ) RETURN CLOB;

  -- Full schedule detail for one invoice
  FUNCTION get_invoice_schedule (
    p_invoice_id IN NUMBER
  ) RETURN CLOB;

  -- Mark all Not-Posted lines for a given invoice + period as Posted
  PROCEDURE mark_posted (
    p_invoice_id    IN NUMBER,
    p_period_name   IN VARCHAR2,
    p_sla_header_id IN NUMBER,
    p_posted_by     IN VARCHAR2
  );

END RR_AP_MPA_PKG;
/


-- ---------------------------------------------------------------------------
-- 3.  Package body
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY RR_AP_MPA_PKG AS

  -- ── JSON helpers ────────────────────────────────────────────────────────
  FUNCTION esc(p IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN REPLACE(REPLACE(p, CHR(92), CHR(92)||CHR(92)), '"', CHR(92)||'"');
  END;

  FUNCTION jstr(p IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE WHEN p IS NULL THEN 'null' ELSE '"'||esc(p)||'"' END;
  END;

  FUNCTION jnum(p IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE WHEN p IS NULL THEN 'null' ELSE TO_CHAR(p) END;
  END;

  FUNCTION jdate(p IN DATE) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE WHEN p IS NULL THEN 'null'
           ELSE '"'||TO_CHAR(p,'YYYY-MM-DD')||'"' END;
  END;

  -- ── generate_schedule ────────────────────────────────────────────────────
  PROCEDURE generate_schedule (
    p_invoice_id IN NUMBER
  ) IS
    -- Header fields
    v_invoice_number  VARCHAR2(50);
    v_supplier        VARCHAR2(500);
    v_supplier_number VARCHAR2(30);
    v_business_unit   VARCHAR2(200);
    v_invoice_date    DATE;
    v_currency        VARCHAR2(15);

    -- Per-line working variables
    v_total_days      NUMBER;
    v_cur_month       DATE;
    v_period_start    DATE;
    v_period_end      DATE;
    v_period_days     NUMBER;
    v_period_amount   NUMBER;
    v_running_sum     NUMBER;
    v_last_month      DATE;
    v_period_name     VARCHAR2(20);
  BEGIN
    -- 1. Delete existing Not-Posted entries for this invoice
    DELETE FROM RR_AP_INVOICE_MULTIPERIOD_SCHEDULE
     WHERE INVOICE_ID     = p_invoice_id
       AND POSTING_STATUS = 'Not Posted';

    -- 2. Look up invoice header
    BEGIN
      SELECT INV.INVOICE_NUMBER,
             INV.SUPPLIER,
             INV.SUPPLIER_NUMBER,
             INV.BUSINESS_UNIT,
             INV.INVOICE_DATE,
             INV.INVOICE_CURRENCY
        INTO v_invoice_number, v_supplier, v_supplier_number,
             v_business_unit, v_invoice_date, v_currency
        FROM RR_AP_INVOICES_ALL INV
       WHERE INV.INVOICE_ID = p_invoice_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invoice not found: ' || p_invoice_id);
    END;

    -- 3. Loop over qualifying lines
    FOR ln IN (
      SELECT LINE_NUMBER,
             LINE_AMOUNT,
             DESCRIPTION,
             DISTRIBUTION_COMBINATION,
             MULTIPERIOD_START_DATE,
             MULTIPERIOD_END_DATE,
             MULTIPERIOD_ACCRUAL_ACCOUNT
        FROM RR_AP_INVOICE_LINES_ALL
       WHERE INVOICE_ID             = p_invoice_id
         AND MULTIPERIOD_START_DATE IS NOT NULL
         AND MULTIPERIOD_END_DATE   IS NOT NULL
       ORDER BY LINE_NUMBER
    ) LOOP

      v_total_days  := TRUNC(ln.MULTIPERIOD_END_DATE) - TRUNC(ln.MULTIPERIOD_START_DATE) + 1;
      v_running_sum := 0;
      v_last_month  := TRUNC(ln.MULTIPERIOD_END_DATE, 'MM');
      v_cur_month   := TRUNC(ln.MULTIPERIOD_START_DATE, 'MM');

      WHILE v_cur_month <= v_last_month LOOP

        v_period_start  := GREATEST(ln.MULTIPERIOD_START_DATE, v_cur_month);
        v_period_end    := LEAST(ln.MULTIPERIOD_END_DATE, LAST_DAY(v_cur_month));
        v_period_days   := TRUNC(v_period_end) - TRUNC(v_period_start) + 1;
        v_period_name   := TO_CHAR(v_cur_month, 'Mon-YYYY');

        -- Last month gets the remainder to avoid rounding drift
        IF v_cur_month = v_last_month THEN
          v_period_amount := ROUND(ln.LINE_AMOUNT - v_running_sum, 2);
        ELSE
          v_period_amount := ROUND(ln.LINE_AMOUNT * v_period_days / v_total_days, 2);
        END IF;

        v_running_sum := v_running_sum + v_period_amount;

        INSERT INTO RR_AP_INVOICE_MULTIPERIOD_SCHEDULE (
          INVOICE_ID,
          INVOICE_NUMBER,
          LINE_NUMBER,
          BUSINESS_UNIT,
          SUPPLIER,
          SUPPLIER_NUMBER,
          INVOICE_DATE,
          PERIOD_DATE,
          PERIOD_NAME,
          ORIGINAL_AMOUNT,
          PERIOD_AMOUNT,
          ACCRUAL_ACCOUNT,
          CHARGE_ACCOUNT,
          DESCRIPTION,
          CURRENCY_CODE,
          POSTING_STATUS,
          TRANSACTION_STATUS,
          CREATED_BY,
          CREATION_DATE,
          LAST_UPDATED_BY,
          LAST_UPDATE_DATE
        ) VALUES (
          p_invoice_id,
          v_invoice_number,
          ln.LINE_NUMBER,
          v_business_unit,
          v_supplier,
          v_supplier_number,
          v_invoice_date,
          v_cur_month,
          v_period_name,
          ln.LINE_AMOUNT,
          v_period_amount,
          ln.MULTIPERIOD_ACCRUAL_ACCOUNT,
          ln.DISTRIBUTION_COMBINATION,
          ln.DESCRIPTION,
          NVL(v_currency, 'AED'),
          'Not Posted',
          'Active',
          USER,
          SYSTIMESTAMP,
          USER,
          SYSTIMESTAMP
        );

        v_cur_month := ADD_MONTHS(v_cur_month, 1);
      END LOOP;

    END LOOP;

    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END generate_schedule;


  -- ── list_schedules ───────────────────────────────────────────────────────
  FUNCTION list_schedules (
    p_invoice_number  IN VARCHAR2,
    p_supplier        IN VARCHAR2,
    p_business_unit   IN VARCHAR2,
    p_posting_status  IN VARCHAR2
  ) RETURN CLOB IS
    v_buf   CLOB    := '{"schedules":[';
    v_first BOOLEAN := TRUE;
  BEGIN
    FOR r IN (
      SELECT
        s.INVOICE_ID,
        s.INVOICE_NUMBER,
        s.SUPPLIER,
        s.SUPPLIER_NUMBER,
        s.BUSINESS_UNIT,
        s.INVOICE_DATE,
        s.CURRENCY_CODE,
        COUNT(*)                                         AS TOTAL_LINES,
        SUM(s.PERIOD_AMOUNT)                             AS TOTAL_AMOUNT,
        SUM(CASE WHEN s.POSTING_STATUS = 'Posted'     THEN s.PERIOD_AMOUNT ELSE 0 END) AS POSTED_AMOUNT,
        SUM(CASE WHEN s.POSTING_STATUS = 'Not Posted' THEN s.PERIOD_AMOUNT ELSE 0 END) AS NOT_POSTED_AMOUNT,
        MIN(s.PERIOD_DATE)                               AS MIN_PERIOD_DATE,
        MAX(s.PERIOD_DATE)                               AS MAX_PERIOD_DATE
      FROM RR_AP_INVOICE_MULTIPERIOD_SCHEDULE s
     WHERE (p_invoice_number IS NULL OR UPPER(s.INVOICE_NUMBER) LIKE '%'||UPPER(p_invoice_number)||'%')
       AND (p_supplier       IS NULL OR UPPER(s.SUPPLIER)       LIKE '%'||UPPER(p_supplier)||'%')
       AND (p_business_unit  IS NULL OR s.BUSINESS_UNIT = p_business_unit)
       AND (p_posting_status IS NULL OR s.POSTING_STATUS = p_posting_status)
       AND s.TRANSACTION_STATUS = 'Active'
     GROUP BY
        s.INVOICE_ID, s.INVOICE_NUMBER, s.SUPPLIER, s.SUPPLIER_NUMBER,
        s.BUSINESS_UNIT, s.INVOICE_DATE, s.CURRENCY_CODE
     ORDER BY s.INVOICE_NUMBER
    ) LOOP
      IF NOT v_first THEN v_buf := v_buf || ','; END IF;
      v_first := FALSE;
      v_buf := v_buf || '{'
        || '"invoiceId":'          || jnum(r.INVOICE_ID)          || ','
        || '"invoiceNumber":'      || jstr(r.INVOICE_NUMBER)      || ','
        || '"supplier":'           || jstr(r.SUPPLIER)            || ','
        || '"supplierNumber":'     || jstr(r.SUPPLIER_NUMBER)     || ','
        || '"businessUnit":'       || jstr(r.BUSINESS_UNIT)       || ','
        || '"invoiceDate":'        || jdate(r.INVOICE_DATE)       || ','
        || '"currencyCode":'       || jstr(r.CURRENCY_CODE)       || ','
        || '"totalLines":'         || jnum(r.TOTAL_LINES)         || ','
        || '"totalAmount":'        || jnum(r.TOTAL_AMOUNT)        || ','
        || '"postedAmount":'       || jnum(r.POSTED_AMOUNT)       || ','
        || '"notPostedAmount":'    || jnum(r.NOT_POSTED_AMOUNT)   || ','
        || '"minPeriodDate":'      || jdate(r.MIN_PERIOD_DATE)    || ','
        || '"maxPeriodDate":'      || jdate(r.MAX_PERIOD_DATE)
      || '}';
    END LOOP;
    RETURN v_buf || ']}';
  END list_schedules;


  -- ── get_invoice_schedule ─────────────────────────────────────────────────
  FUNCTION get_invoice_schedule (
    p_invoice_id IN NUMBER
  ) RETURN CLOB IS
    v_buf          CLOB;
    v_first        BOOLEAN := TRUE;
    v_inv_number   VARCHAR2(50)  := '';
    v_supplier     VARCHAR2(500) := '';
    v_bus_unit     VARCHAR2(200) := '';
    v_inv_date     DATE;
    v_currency     VARCHAR2(15)  := 'AED';
    v_acct_status  VARCHAR2(30)  := NULL;
  BEGIN
    -- Fetch header fields from first schedule row
    BEGIN
      SELECT INVOICE_NUMBER, SUPPLIER, BUSINESS_UNIT, INVOICE_DATE, CURRENCY_CODE
        INTO v_inv_number, v_supplier, v_bus_unit, v_inv_date, v_currency
        FROM RR_AP_INVOICE_MULTIPERIOD_SCHEDULE
       WHERE INVOICE_ID = p_invoice_id
         AND ROWNUM     = 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN NULL;
    END;

    -- Fetch invoice accounting status from SLA headers
    BEGIN
      SELECT h.ACCOUNTING_STATUS
        INTO v_acct_status
        FROM RR_SLA_ACCOUNTING_HEADERS h
       WHERE h.SOURCE_TABLE = 'AP_INVOICES'
         AND h.SOURCE_ID    = p_invoice_id
       ORDER BY h.HEADER_ID DESC
       FETCH FIRST 1 ROWS ONLY;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN NULL;
    END;

    v_buf := '{'
      || '"invoiceId":'                || jnum(p_invoice_id) || ','
      || '"invoiceNumber":'            || jstr(v_inv_number)  || ','
      || '"supplier":'                 || jstr(v_supplier)    || ','
      || '"businessUnit":'             || jstr(v_bus_unit)    || ','
      || '"invoiceDate":'              || jdate(v_inv_date)   || ','
      || '"currencyCode":'             || jstr(v_currency)    || ','
      || '"invoiceAccountingStatus":'  || jstr(v_acct_status) || ','
      || '"lines":[';

    FOR r IN (
      SELECT
        SCHEDULE_ID,
        LINE_NUMBER,
        PERIOD_DATE,
        PERIOD_NAME,
        ORIGINAL_AMOUNT,
        PERIOD_AMOUNT,
        ACCRUAL_ACCOUNT,
        CHARGE_ACCOUNT,
        DESCRIPTION,
        POSTING_STATUS,
        POSTED_DATE,
        POSTED_BY,
        SLA_HEADER_ID
      FROM RR_AP_INVOICE_MULTIPERIOD_SCHEDULE
      WHERE INVOICE_ID         = p_invoice_id
        AND TRANSACTION_STATUS = 'Active'
      ORDER BY LINE_NUMBER, PERIOD_DATE
    ) LOOP
      IF NOT v_first THEN v_buf := v_buf || ','; END IF;
      v_first := FALSE;
      v_buf := v_buf || '{'
        || '"scheduleId":'     || jnum(r.SCHEDULE_ID)     || ','
        || '"lineNumber":'     || jnum(r.LINE_NUMBER)     || ','
        || '"periodDate":'     || jdate(r.PERIOD_DATE)    || ','
        || '"periodName":'     || jstr(r.PERIOD_NAME)     || ','
        || '"originalAmount":' || jnum(r.ORIGINAL_AMOUNT) || ','
        || '"periodAmount":'   || jnum(r.PERIOD_AMOUNT)   || ','
        || '"accrualAccount":' || jstr(r.ACCRUAL_ACCOUNT) || ','
        || '"chargeAccount":'  || jstr(r.CHARGE_ACCOUNT)  || ','
        || '"description":'    || jstr(r.DESCRIPTION)     || ','
        || '"postingStatus":'  || jstr(r.POSTING_STATUS)  || ','
        || '"postedDate":'     || jdate(r.POSTED_DATE)    || ','
        || '"postedBy":'       || jstr(r.POSTED_BY)       || ','
        || '"slaHeaderId":'    || jnum(r.SLA_HEADER_ID)
      || '}';
    END LOOP;

    RETURN v_buf || ']}';
  END get_invoice_schedule;


  -- ── mark_posted ──────────────────────────────────────────────────────────
  PROCEDURE mark_posted (
    p_invoice_id    IN NUMBER,
    p_period_name   IN VARCHAR2,
    p_sla_header_id IN NUMBER,
    p_posted_by     IN VARCHAR2
  ) IS
  BEGIN
    UPDATE RR_AP_INVOICE_MULTIPERIOD_SCHEDULE
       SET POSTING_STATUS    = 'Posted',
           SLA_HEADER_ID     = p_sla_header_id,
           POSTED_DATE       = SYSDATE,
           POSTED_BY         = p_posted_by,
           LAST_UPDATE_DATE  = SYSTIMESTAMP,
           LAST_UPDATED_BY   = p_posted_by
     WHERE INVOICE_ID        = p_invoice_id
       AND PERIOD_NAME        = p_period_name
       AND POSTING_STATUS     = 'Not Posted';
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN ROLLBACK; RAISE;
  END mark_posted;

END RR_AP_MPA_PKG;
/


-- ---------------------------------------------------------------------------
-- 4.  Drop existing ORDS templates (idempotent)
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ap/multiperiod');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ap/multiperiod/:invoice_id');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ap/multiperiod/generate');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  ORDS.DELETE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ap/multiperiod/mark-posted');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- ---------------------------------------------------------------------------
-- 5a.  GET ap/multiperiod  — list schedules (search)
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/multiperiod',
    p_method        => 'GET',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => '',
    p_comments      => 'List multiperiod schedules with optional filters',
    p_source        => q'[
DECLARE
  v_result CLOB;
  v_inv_number  VARCHAR2(200) := NULLIF(TRIM(:invoice_number), '');
  v_supplier    VARCHAR2(500) := NULLIF(TRIM(:supplier),       '');
  v_bus_unit    VARCHAR2(200) := NULLIF(TRIM(:business_unit),  '');
  v_post_status VARCHAR2(50)  := NULLIF(TRIM(:posting_status), '');
BEGIN
  v_result     := RR_AP_MPA_PKG.list_schedules(
                    p_invoice_number => v_inv_number,
                    p_supplier       => v_supplier,
                    p_business_unit  => v_bus_unit,
                    p_posting_status => v_post_status
                  );
  :status_code := 200;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.PRN(v_result);
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/


-- ---------------------------------------------------------------------------
-- 5b.  GET ap/multiperiod/:invoice_id  — detail for one invoice
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/multiperiod/:invoice_id',
    p_method        => 'GET',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => '',
    p_comments      => 'Get full multiperiod schedule for a single invoice',
    p_source        => q'[
DECLARE
  v_result CLOB;
BEGIN
  v_result     := RR_AP_MPA_PKG.get_invoice_schedule(p_invoice_id => :invoice_id);
  :status_code := 200;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.PRN(v_result);
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/


-- ---------------------------------------------------------------------------
-- 5c.  POST ap/multiperiod/generate  — generate / refresh schedule
--      Body: {"invoiceId": N}
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/multiperiod/generate',
    p_method        => 'POST',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => 'application/json',
    p_comments      => 'Generate or refresh multiperiod schedule for an invoice',
    p_source        => q'[
DECLARE
  v_body       CLOB := :body_text;
  v_json       JSON_OBJECT_T;
  v_invoice_id NUMBER;
BEGIN
  v_json       := JSON_OBJECT_T.PARSE(v_body);
  v_invoice_id := v_json.GET_NUMBER('invoiceId');

  RR_AP_MPA_PKG.generate_schedule(p_invoice_id => v_invoice_id);

  :status_code := 200;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.PRN('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"success":false,"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/


-- ---------------------------------------------------------------------------
-- 5d.  POST ap/multiperiod/mark-posted  — mark period lines as posted
--      Body: {"invoiceId":N,"periodName":"Apr-2026","slaHeaderId":N,"postedBy":"..."}
-- ---------------------------------------------------------------------------
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name   => 'reerp',
    p_pattern       => 'ap/multiperiod/mark-posted',
    p_method        => 'POST',
    p_source_type   => 'plsql/block',
    p_mimes_allowed => 'application/json',
    p_comments      => 'Mark multiperiod schedule lines as posted for a given period',
    p_source        => q'[
DECLARE
  v_body          CLOB := :body_text;
  v_json          JSON_OBJECT_T;
  v_invoice_id    NUMBER;
  v_period_name   VARCHAR2(20);
  v_sla_header_id NUMBER;
  v_posted_by     VARCHAR2(200);
BEGIN
  v_json          := JSON_OBJECT_T.PARSE(v_body);
  v_invoice_id    := v_json.GET_NUMBER('invoiceId');
  v_period_name   := v_json.GET_STRING('periodName');
  v_sla_header_id := v_json.GET_NUMBER('slaHeaderId');
  v_posted_by     := v_json.GET_STRING('postedBy');

  RR_AP_MPA_PKG.mark_posted(
    p_invoice_id    => v_invoice_id,
    p_period_name   => v_period_name,
    p_sla_header_id => v_sla_header_id,
    p_posted_by     => v_posted_by
  );

  :status_code := 200;
  OWA_UTIL.MIME_HEADER('application/json', TRUE);
  HTP.PRN('{"success":true}');
EXCEPTION
  WHEN OTHERS THEN
    :status_code := 500;
    OWA_UTIL.MIME_HEADER('application/json', TRUE);
    HTP.PRN('{"success":false,"error":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;]'
  );
  COMMIT;
END;
/
