-- ============================================================
-- PATCH 92: Fusion Invoice Attachments Download Tracking
--
-- Creates:
--   1. TABLE  RR_FUSION_AP_INVOICE_ATTACHMENTS
--      Tracks every Fusion attachment download attempt:
--        invoice_id, invoice_number, file_name, saved_as,
--        fusion_href, download_status, file_size, mime_type,
--        WHO columns
--
--   2. ORDS handler  ap/fusion-invoice-attachments  GET
--      Returns download history, filterable by invoice_number,
--      download_status, date_from, date_to.
--
--   3. ORDS handler  ap/fusion-invoice-attachments  POST
--      Upserts a download record (insert or update by
--      invoice_number + file_name).
--
-- HOW TO RUN:
--   APEX SQL Workshop -> SQL Commands
--   Run each block (Step 1 / Step 2 / Step 3) separately.
-- ============================================================


-- ---------------------------------------------------------------------------
-- Step 1: Table
-- ---------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE RR_FUSION_AP_INVOICE_ATTACHMENTS (
      ATTACHMENT_DL_ID   NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      INVOICE_ID         NUMBER,
      INVOICE_NUMBER     VARCHAR2(100)   NOT NULL,
      FILE_NAME          VARCHAR2(500)   NOT NULL,
      SAVED_AS           VARCHAR2(600),
      FUSION_HREF        VARCHAR2(2000),
      DOWNLOAD_STATUS    VARCHAR2(30)    DEFAULT ''PENDING'' NOT NULL,
      FILE_SIZE          NUMBER,
      MIME_TYPE          VARCHAR2(200),
      ERROR_MESSAGE      VARCHAR2(2000),
      DOWNLOADED_AT      DATE,
      CREATED_BY         VARCHAR2(200),
      CREATION_DATE      DATE            DEFAULT SYSDATE NOT NULL,
      LAST_UPDATED_BY    VARCHAR2(200),
      LAST_UPDATE_DATE   DATE            DEFAULT SYSDATE NOT NULL
    )';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX RR_FAIA_INV_NUM_IDX ON RR_FUSION_AP_INVOICE_ATTACHMENTS(INVOICE_NUMBER)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX RR_FAIA_STATUS_IDX  ON RR_FUSION_AP_INVOICE_ATTACHMENTS(DOWNLOAD_STATUS)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
COMMIT;


-- ---------------------------------------------------------------------------
-- Step 2: GET handler
-- ---------------------------------------------------------------------------
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'ap/fusion-invoice-attachments',
            p_method      => 'GET'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'ap/fusion-invoice-attachments',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_inv_num   VARCHAR2(200) := :invoice_number;
    v_status    VARCHAR2(30)  := :download_status;
    v_date_from VARCHAR2(20)  := :date_from;
    v_date_to   VARCHAR2(20)  := :date_to;
    v_limit     NUMBER        := NVL(TO_NUMBER(:row_limit), 1000);

    v_clob  CLOB;
    v_first BOOLEAN := TRUE;
    l_pos   INTEGER;
    l_len   INTEGER;
    l_chunk VARCHAR2(32767);

    CURSOR c_data IS
        SELECT
            ATTACHMENT_DL_ID,
            INVOICE_ID,
            INVOICE_NUMBER,
            FILE_NAME,
            SAVED_AS,
            FUSION_HREF,
            DOWNLOAD_STATUS,
            FILE_SIZE,
            MIME_TYPE,
            ERROR_MESSAGE,
            TO_CHAR(DOWNLOADED_AT,    'YYYY-MM-DD"T"HH24:MI:SS') AS DOWNLOADED_AT,
            CREATED_BY,
            TO_CHAR(CREATION_DATE,    'YYYY-MM-DD"T"HH24:MI:SS') AS CREATION_DATE,
            LAST_UPDATED_BY,
            TO_CHAR(LAST_UPDATE_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS LAST_UPDATE_DATE
        FROM RR_FUSION_AP_INVOICE_ATTACHMENTS
        WHERE (v_inv_num  IS NULL OR UPPER(INVOICE_NUMBER) LIKE '%' || UPPER(v_inv_num) || '%')
          AND (v_status   IS NULL OR DOWNLOAD_STATUS = v_status)
          AND (v_date_from IS NULL OR TRUNC(CREATION_DATE) >= TO_DATE(v_date_from, 'YYYY-MM-DD'))
          AND (v_date_to   IS NULL OR TRUNC(CREATION_DATE) <= TO_DATE(v_date_to,   'YYYY-MM-DD'))
        ORDER BY CREATION_DATE DESC, ATTACHMENT_DL_ID DESC
        FETCH FIRST v_limit ROWS ONLY;

    FUNCTION jstr(p IN VARCHAR2) RETURN VARCHAR2 IS
        v VARCHAR2(32767) := p;
    BEGIN
        IF v IS NULL THEN RETURN 'null'; END IF;
        v := REPLACE(v, '\', '\\');
        v := REPLACE(v, '"', '\"');
        v := REPLACE(v, CHR(10), '\n');
        v := REPLACE(v, CHR(13), '\r');
        RETURN '"' || v || '"';
    END;
BEGIN
    DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
    DBMS_LOB.APPEND(v_clob, '{"status":"success","items":[');

    FOR r IN c_data LOOP
        IF NOT v_first THEN DBMS_LOB.APPEND(v_clob, ','); END IF;
        v_first := FALSE;
        DBMS_LOB.APPEND(v_clob,
            '{"attachmentDlId":'   || r.ATTACHMENT_DL_ID                        ||
            ',"invoiceId":'        || NVL(TO_CHAR(r.INVOICE_ID),'null')          ||
            ',"invoiceNumber":'    || jstr(r.INVOICE_NUMBER)                     ||
            ',"fileName":'         || jstr(r.FILE_NAME)                          ||
            ',"savedAs":'          || jstr(r.SAVED_AS)                           ||
            ',"fusionHref":'       || jstr(r.FUSION_HREF)                        ||
            ',"downloadStatus":'   || jstr(r.DOWNLOAD_STATUS)                   ||
            ',"fileSize":'         || NVL(TO_CHAR(r.FILE_SIZE),'null')           ||
            ',"mimeType":'         || jstr(r.MIME_TYPE)                          ||
            ',"errorMessage":'     || jstr(r.ERROR_MESSAGE)                      ||
            ',"downloadedAt":'     || jstr(r.DOWNLOADED_AT)                      ||
            ',"createdBy":'        || jstr(r.CREATED_BY)                         ||
            ',"creationDate":'     || jstr(r.CREATION_DATE)                      ||
            ',"lastUpdatedBy":'    || jstr(r.LAST_UPDATED_BY)                    ||
            ',"lastUpdateDate":'   || jstr(r.LAST_UPDATE_DATE)                   ||
            '}'
        );
    END LOOP;

    DBMS_LOB.APPEND(v_clob, ']}');
    :status_code := 200;
    l_len := DBMS_LOB.GETLENGTH(v_clob);
    l_pos := 1;
    LOOP
        EXIT WHEN l_pos > l_len;
        l_chunk := DBMS_LOB.SUBSTR(v_clob, 32767, l_pos);
        HTP.PRN(l_chunk);
        l_pos := l_pos + 32767;
    END LOOP;
    DBMS_LOB.FREETEMPORARY(v_clob);
EXCEPTION
    WHEN OTHERS THEN
        :status_code := 500;
        HTP.P('{"status":"error","message":"' || REPLACE(SQLERRM, '"', '\"') || '"}');
END;
]'
    );
    COMMIT;
END;
/


-- ---------------------------------------------------------------------------
-- Step 3: POST handler (upsert)
-- ---------------------------------------------------------------------------
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'ap/fusion-invoice-attachments',
            p_method      => 'POST'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'ap/fusion-invoice-attachments',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_body       CLOB;
    v_inv_id     NUMBER;
    v_inv_num    VARCHAR2(100);
    v_file_name  VARCHAR2(500);
    v_saved_as   VARCHAR2(600);
    v_href       VARCHAR2(2000);
    v_status     VARCHAR2(30);
    v_file_size  NUMBER;
    v_mime_type  VARCHAR2(200);
    v_err_msg    VARCHAR2(2000);
    v_user       VARCHAR2(200);
    v_existing   NUMBER;
BEGIN
    v_body := :body;
    APEX_JSON.PARSE(v_body);

    v_inv_id    := APEX_JSON.get_number(p_path => 'invoiceId');
    v_inv_num   := APEX_JSON.get_varchar2(p_path => 'invoiceNumber');
    v_file_name := APEX_JSON.get_varchar2(p_path => 'fileName');
    v_saved_as  := APEX_JSON.get_varchar2(p_path => 'savedAs');
    v_href      := APEX_JSON.get_varchar2(p_path => 'fusionHref');
    v_status    := NVL(APEX_JSON.get_varchar2(p_path => 'downloadStatus'), 'DOWNLOADED');
    v_file_size := APEX_JSON.get_number(p_path => 'fileSize');
    v_mime_type := APEX_JSON.get_varchar2(p_path => 'mimeType');
    v_err_msg   := APEX_JSON.get_varchar2(p_path => 'errorMessage');
    v_user      := NVL(APEX_JSON.get_varchar2(p_path => 'createdBy'), 'SYSTEM');

    -- Upsert: if same invoice_number + file_name already exists, update it
    SELECT COUNT(*) INTO v_existing
    FROM RR_FUSION_AP_INVOICE_ATTACHMENTS
    WHERE INVOICE_NUMBER = v_inv_num AND FILE_NAME = v_file_name;

    IF v_existing > 0 THEN
        UPDATE RR_FUSION_AP_INVOICE_ATTACHMENTS
        SET  DOWNLOAD_STATUS  = v_status,
             SAVED_AS         = NVL(v_saved_as, SAVED_AS),
             FUSION_HREF      = NVL(v_href, FUSION_HREF),
             FILE_SIZE        = NVL(v_file_size, FILE_SIZE),
             MIME_TYPE        = NVL(v_mime_type, MIME_TYPE),
             ERROR_MESSAGE    = v_err_msg,
             DOWNLOADED_AT    = CASE WHEN v_status IN ('DOWNLOADED','SUCCESS') THEN SYSDATE ELSE DOWNLOADED_AT END,
             LAST_UPDATED_BY  = v_user,
             LAST_UPDATE_DATE = SYSDATE
        WHERE INVOICE_NUMBER = v_inv_num AND FILE_NAME = v_file_name;
    ELSE
        INSERT INTO RR_FUSION_AP_INVOICE_ATTACHMENTS (
            INVOICE_ID, INVOICE_NUMBER, FILE_NAME, SAVED_AS,
            FUSION_HREF, DOWNLOAD_STATUS, FILE_SIZE, MIME_TYPE,
            ERROR_MESSAGE, DOWNLOADED_AT,
            CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE
        ) VALUES (
            v_inv_id, v_inv_num, v_file_name, v_saved_as,
            v_href, v_status, v_file_size, v_mime_type,
            v_err_msg, CASE WHEN v_status IN ('DOWNLOADED','SUCCESS') THEN SYSDATE ELSE NULL END,
            v_user, SYSDATE, v_user, SYSDATE
        );
    END IF;

    COMMIT;
    :status_code := 200;
    HTP.P('{"status":"success","message":"Record saved"}');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P('{"status":"error","message":"' || REPLACE(SQLERRM, '"', '\"') || '"}');
END;
]'
    );
    COMMIT;
END;
/
