-- ============================================================
-- Distribution Combinations — Table DDL
-- File: database/ap/rr_dist_combinations_tables.sql
-- Run order: 1st
-- ============================================================

CREATE TABLE RR_DIST_COMBINATIONS (
    COMBINATION_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    COMBINATION_NAME    VARCHAR2(300)  NOT NULL,
    BUSINESS_UNIT       VARCHAR2(240),
    GL_ACCOUNT_CCID     NUMBER,
    GL_ACCOUNT_DESC     VARCHAR2(400),
    MODULE              VARCHAR2(50)   NOT NULL,
    DESCRIPTION         VARCHAR2(1000),
    STATUS              VARCHAR2(20)   DEFAULT 'ACTIVE',
    CREATED_BY          VARCHAR2(150),
    CREATION_DATE       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY     VARCHAR2(150),
    LAST_UPDATE_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT RR_DIST_CMB_STATUS_CK CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT RR_DIST_CMB_MODULE_CK CHECK (MODULE IN ('AP','PC','GL','FA','AR','CASH','ALL','GL Revaluation')),
    CONSTRAINT RR_DIST_CMB_NAME_UK   UNIQUE (COMBINATION_NAME, MODULE)
);

CREATE INDEX IDX_RR_DIST_CMB_MODULE ON RR_DIST_COMBINATIONS(MODULE);
CREATE INDEX IDX_RR_DIST_CMB_STATUS ON RR_DIST_COMBINATIONS(STATUS);

COMMENT ON TABLE  RR_DIST_COMBINATIONS                         IS 'Distribution combinations master — links a name to a GL account for use as an expense type LOV';
COMMENT ON COLUMN RR_DIST_COMBINATIONS.BUSINESS_UNIT           IS 'Business unit that owns this combination (NULL = available to all BUs)';
COMMENT ON COLUMN RR_DIST_COMBINATIONS.MODULE                  IS 'AP | PC | GL | FA | AR | CASH | ALL | GL Revaluation — which module this combination belongs to';
COMMENT ON COLUMN RR_DIST_COMBINATIONS.GL_ACCOUNT_CCID         IS 'GL code combination ID (FK to REERP_GL_CODE_COMBINATIONS)';
COMMENT ON COLUMN RR_DIST_COMBINATIONS.GL_ACCOUNT_DESC         IS 'Denormalised segment string, e.g. 01-100-6010-000';
COMMENT ON COLUMN RR_DIST_COMBINATIONS.STATUS                  IS 'ACTIVE = visible in LOVs; INACTIVE = hidden from LOVs';

-- Safe ALTER for existing installations (adds BUSINESS_UNIT if missing)
DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_tab_columns
    WHERE table_name = 'RR_DIST_COMBINATIONS' AND column_name = 'BUSINESS_UNIT';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RR_DIST_COMBINATIONS ADD (BUSINESS_UNIT VARCHAR2(240))';
    END IF;
END;
/

DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM user_sequences WHERE sequence_name = 'RR_DIST_CMB_SEQ';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE RR_DIST_CMB_SEQ START WITH 1001 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/
