-- =============================================================================
-- RR_RAW_AP_INVOICES_ALL
-- Raw Oracle Fusion AP Invoices table
--
-- Columns mapped directly from the Fusion AP_INVOICES_ALL XML/REST response.
-- INVOICE_ID is the Fusion primary key and natural key for MERGE upserts.
-- Additional audit columns track local sync metadata.
-- =============================================================================

-- DROP TABLE RR_RAW_AP_INVOICES_ALL CASCADE CONSTRAINTS;

CREATE TABLE RR_RAW_AP_INVOICES_ALL (

    -- ── Surrogate PK (local only) ─────────────────────────────────────────────
    ID                              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ── Fusion natural key ────────────────────────────────────────────────────
    INVOICE_ID                      NUMBER          NOT NULL,

    -- ── Vendor / Supplier ─────────────────────────────────────────────────────
    VENDOR_ID                       NUMBER,
    VENDOR_SITE_ID                  NUMBER,
    PARTY_ID                        NUMBER,
    PARTY_SITE_ID                   NUMBER,

    -- ── Invoice Header ────────────────────────────────────────────────────────
    INVOICE_NUM                     VARCHAR2(50),
    INVOICE_AMOUNT                  NUMBER(18,2),
    INVOICE_DATE                    DATE,
    INVOICE_CURRENCY_CODE           VARCHAR2(15),
    INVOICE_TYPE_LOOKUP_CODE        VARCHAR2(30),
    SOURCE                          VARCHAR2(80),
    DESCRIPTION                     VARCHAR2(4000),
    BATCH_ID                        NUMBER,

    -- ── Payment ───────────────────────────────────────────────────────────────
    PAYMENT_CURRENCY_CODE           VARCHAR2(15),
    PAYMENT_CROSS_RATE              NUMBER,
    PAYMENT_CROSS_RATE_DATE         DATE,
    PAY_CURR_INVOICE_AMOUNT         NUMBER(18,2),
    AMOUNT_PAID                     NUMBER(18,2),
    DISCOUNT_AMOUNT_TAKEN           NUMBER(18,2),
    AMOUNT_APPLICABLE_TO_DISCOUNT   NUMBER(18,2),
    PAYMENT_STATUS_FLAG             VARCHAR2(1),
    PAYMENT_METHOD_CODE             VARCHAR2(30),
    PAYMENT_FUNCTION                VARCHAR2(30),
    PAY_PROC_TRXN_TYPE_CODE         VARCHAR2(30),
    EXCLUSIVE_PAYMENT_FLAG          VARCHAR2(1),
    PAY_GROUP_LOOKUP_CODE           VARCHAR2(30),

    -- ── Accounting / GL ───────────────────────────────────────────────────────
    SET_OF_BOOKS_ID                 NUMBER,
    ORG_ID                          NUMBER,
    LEGAL_ENTITY_ID                 NUMBER,
    ACCTS_PAY_CODE_COMBINATION_ID   NUMBER,
    GL_DATE                         DATE,
    BUDGET_DATE                     DATE,

    -- ── Terms ─────────────────────────────────────────────────────────────────
    TERMS_ID                        NUMBER,
    TERMS_DATE                      DATE,

    -- ── Document Sequencing ───────────────────────────────────────────────────
    DOC_SEQUENCE_ID                 NUMBER,
    DOC_SEQUENCE_VALUE              NUMBER,
    DOC_CATEGORY_CODE               VARCHAR2(30),

    -- ── Approval / Workflow ───────────────────────────────────────────────────
    APPROVAL_STATUS                 VARCHAR2(30),
    APPROVAL_READY_FLAG             VARCHAR2(1),
    WFAPPROVAL_STATUS               VARCHAR2(50),
    ROUTING_STATUS_LOOKUP_CODE      VARCHAR2(80),
    FORCE_REVALIDATION_FLAG         VARCHAR2(1),

    -- ── Tax / Registration ────────────────────────────────────────────────────
    TAXATION_COUNTRY                VARCHAR2(2),
    CUST_REGISTRATION_NUMBER        VARCHAR2(50),
    CHECK_VAT_AMOUNT_PAID           VARCHAR2(1),
    DISC_IS_INV_LESS_TAX_FLAG       VARCHAR2(1),
    EXCLUDE_FREIGHT_FROM_DISCOUNT   VARCHAR2(1),

    -- ── Miscellaneous ─────────────────────────────────────────────────────────
    INTERCOMPANY_FLAG               VARCHAR2(1),
    IMPORT_DOCUMENT_DATE            DATE,
    REFERENCE_KEY2                  VARCHAR2(240),
    REQUEST_ID                      NUMBER,
    OBJECT_VERSION_NUMBER           NUMBER,

    -- ── Fusion audit columns ──────────────────────────────────────────────────
    CREATION_DATE                   TIMESTAMP WITH TIME ZONE,
    CREATED_BY                      VARCHAR2(240),
    LAST_UPDATE_DATE                TIMESTAMP WITH TIME ZONE,
    LAST_UPDATED_BY                 VARCHAR2(240),
    LAST_UPDATE_LOGIN               VARCHAR2(100),

    -- ── Local sync metadata ───────────────────────────────────────────────────
    SYNC_DATE                       TIMESTAMP DEFAULT SYSTIMESTAMP,
    SYNC_STATUS                     VARCHAR2(20)  DEFAULT 'SYNCED',

    -- ── Natural key constraint ────────────────────────────────────────────────
    CONSTRAINT RR_RAW_AP_INV_UK UNIQUE (INVOICE_ID)
);

-- Indexes
CREATE INDEX RR_RAW_AP_INV_N1 ON RR_RAW_AP_INVOICES_ALL (VENDOR_ID);
CREATE INDEX RR_RAW_AP_INV_N2 ON RR_RAW_AP_INVOICES_ALL (INVOICE_DATE);
CREATE INDEX RR_RAW_AP_INV_N3 ON RR_RAW_AP_INVOICES_ALL (GL_DATE);
CREATE INDEX RR_RAW_AP_INV_N4 ON RR_RAW_AP_INVOICES_ALL (ORG_ID);
CREATE INDEX RR_RAW_AP_INV_N5 ON RR_RAW_AP_INVOICES_ALL (APPROVAL_STATUS);
CREATE INDEX RR_RAW_AP_INV_N6 ON RR_RAW_AP_INVOICES_ALL (SYNC_DATE);
CREATE INDEX RR_RAW_AP_INV_N7 ON RR_RAW_AP_INVOICES_ALL (INVOICE_NUM);

COMMENT ON TABLE  RR_RAW_AP_INVOICES_ALL IS 'Raw Oracle Fusion AP_INVOICES_ALL sync — one row per Fusion invoice';
COMMENT ON COLUMN RR_RAW_AP_INVOICES_ALL.INVOICE_ID            IS 'Fusion primary key (AP_INVOICES_ALL.INVOICE_ID)';
COMMENT ON COLUMN RR_RAW_AP_INVOICES_ALL.INVOICE_NUM           IS 'Invoice number (Fusion INVOICE_NUM)';
COMMENT ON COLUMN RR_RAW_AP_INVOICES_ALL.OBJECT_VERSION_NUMBER IS 'Fusion OVN — increment each sync to detect stale updates';
COMMENT ON COLUMN RR_RAW_AP_INVOICES_ALL.SYNC_STATUS           IS 'SYNCED = up to date, ERROR = last sync failed';
