-- ============================================
-- RR_AP_PAYMENTS_RELATED_INVOICES Table
-- Stores related invoices for AP Payments
-- ============================================

CREATE TABLE RR_AP_PAYMENTS_RELATED_INVOICES (
    -- Primary Key
    ID                              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Key References
    INVOICE_PAYMENT_ID              NUMBER NOT NULL,
    CHECK_ID                        NUMBER NOT NULL,
    INVOICE_ID                      NUMBER,

    -- Invoice Details
    INVOICE_BUSINESS_UNIT           VARCHAR2(240),
    INVOICE_NUMBER                  VARCHAR2(100),
    INSTALLMENT_NUMBER              NUMBER,

    -- Amounts in Payment Currency
    AMOUNT_PAID_PAYMENT_CURRENCY    NUMBER(18,2),
    AMOUNT_PAID_INVOICE_CURRENCY    NUMBER(18,2),
    INVOICE_PAYMENT_AMOUNT          NUMBER(18,2),
    INVOICE_AMOUNT                  NUMBER(18,2),
    INVOICE_BASE_AMOUNT             NUMBER(18,2),
    PAYMENT_BASE_AMOUNT             NUMBER(18,2),

    -- Discount
    DISCOUNT_LOST                   NUMBER(18,2),
    DISCOUNT_TAKEN                  NUMBER(18,2),

    -- Currency
    INVOICE_CURRENCY                VARCHAR2(15),
    CROSS_CURRENCY_RATE             NUMBER(18,6),

    -- Status
    INVOICE_PAYMENT_STATUS          VARCHAR2(50),

    -- Audit Columns from Fusion
    CREATED_BY                      VARCHAR2(100),
    CREATION_DATE                   TIMESTAMP WITH TIME ZONE,
    LAST_UPDATED_BY                 VARCHAR2(100),
    LAST_UPDATE_DATE                TIMESTAMP WITH TIME ZONE,
    LAST_UPDATE_LOGIN               VARCHAR2(100),

    -- Local Audit Columns
    LOCAL_CREATED_DATE              TIMESTAMP DEFAULT SYSTIMESTAMP,
    LOCAL_UPDATED_DATE              TIMESTAMP DEFAULT SYSTIMESTAMP,
    SYNC_STATUS                     VARCHAR2(20) DEFAULT 'SYNCED',

    -- Constraints
    CONSTRAINT RR_AP_PAY_REL_INV_UK1 UNIQUE (INVOICE_PAYMENT_ID)
);

-- Sequence for local (non-Fusion) invoice payment IDs (negative = local, never collides with Fusion)
CREATE SEQUENCE RR_AP_PAY_REL_INV_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Create indexes for better query performance
CREATE INDEX RR_AP_PAY_REL_INV_N1 ON RR_AP_PAYMENTS_RELATED_INVOICES (CHECK_ID);
CREATE INDEX RR_AP_PAY_REL_INV_N2 ON RR_AP_PAYMENTS_RELATED_INVOICES (INVOICE_ID);
CREATE INDEX RR_AP_PAY_REL_INV_N3 ON RR_AP_PAYMENTS_RELATED_INVOICES (INVOICE_NUMBER);
CREATE INDEX RR_AP_PAY_REL_INV_N4 ON RR_AP_PAYMENTS_RELATED_INVOICES (INVOICE_BUSINESS_UNIT);

-- Foreign key to payments table (optional - uncomment if needed)
-- ALTER TABLE RR_AP_PAYMENTS_RELATED_INVOICES
--     ADD CONSTRAINT RR_AP_PAY_REL_INV_FK1
--     FOREIGN KEY (CHECK_ID) REFERENCES RR_AP_PAYMENTS_ALL(CHECK_ID);

-- Add comments
COMMENT ON TABLE RR_AP_PAYMENTS_RELATED_INVOICES IS 'Stores related invoices for AP Payments from Oracle Fusion';
COMMENT ON COLUMN RR_AP_PAYMENTS_RELATED_INVOICES.INVOICE_PAYMENT_ID IS 'Unique identifier for invoice payment relationship';
COMMENT ON COLUMN RR_AP_PAYMENTS_RELATED_INVOICES.CHECK_ID IS 'Reference to parent payment (RR_AP_PAYMENTS_ALL.CHECK_ID)';
COMMENT ON COLUMN RR_AP_PAYMENTS_RELATED_INVOICES.INVOICE_ID IS 'Invoice ID from Fusion';
COMMENT ON COLUMN RR_AP_PAYMENTS_RELATED_INVOICES.AMOUNT_PAID_PAYMENT_CURRENCY IS 'Amount paid in payment currency';
