-- ============================================================
-- Table: RR_EMAIL_CONFIG
-- Description: SMTP email configuration stored in DB so credentials
--              can be updated without rebuilding the Electron exe.
-- ============================================================

CREATE TABLE RR_EMAIL_CONFIG (
    ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SMTP_HOST    VARCHAR2(200)  NOT NULL,
    SMTP_PORT    NUMBER         DEFAULT 587,
    SMTP_SECURE  VARCHAR2(5)   DEFAULT 'false',
    SMTP_USER    VARCHAR2(200)  NOT NULL,
    SMTP_PASS    VARCHAR2(1000) NOT NULL,
    FROM_NAME    VARCHAR2(200)  DEFAULT 'ReactERP',
    UPDATED_DATE TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_BY   VARCHAR2(150)
);

-- Insert SMTP credentials (replace placeholders with actual values before running)
INSERT INTO RR_EMAIL_CONFIG (SMTP_HOST, SMTP_PORT, SMTP_SECURE, SMTP_USER, SMTP_PASS, FROM_NAME, UPDATED_BY)
VALUES (
    'smtp-relay.brevo.com',
    587,
    'false',
    'your-smtp-user@example.com',
    'your-smtp-api-key-here',
    'ReactERP',
    'SYSTEM'
);

COMMIT;

-- ============================================================
-- APEX REST Handler: GET /config/emailsettings
-- Returns the active SMTP config (latest row by ID)
-- ============================================================

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'config/emailsettings',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'Email SMTP configuration'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'config/emailsettings',
        p_method         => 'GET',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => '',
        p_comments       => 'Return active SMTP config',
        p_source         => q'[
DECLARE
    l_host    VARCHAR2(200);
    l_port    NUMBER;
    l_secure  VARCHAR2(5);
    l_user    VARCHAR2(200);
    l_pass    VARCHAR2(1000);
    l_name    VARCHAR2(200);
BEGIN
    SELECT SMTP_HOST, SMTP_PORT, SMTP_SECURE, SMTP_USER, SMTP_PASS, FROM_NAME
      INTO l_host, l_port, l_secure, l_user, l_pass, l_name
      FROM RR_EMAIL_CONFIG
     ORDER BY ID DESC
     FETCH FIRST 1 ROWS ONLY;

    :status_code := 200;
    HTP.P('{'
       || '"status":"success",'
       || '"host":"'    || l_host   || '",'
       || '"port":'     || l_port   || ','
       || '"secure":'   || l_secure || ','
       || '"user":"'    || l_user   || '",'
       || '"pass":"'    || l_pass   || '",'
       || '"fromName":"'|| l_name   || '"'
       || '}');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        :status_code := 404;
        HTP.P('{"status":"error","message":"Email config not found in database"}');
    WHEN OTHERS THEN
        :status_code := 500;
        HTP.P('{"status":"error","message":"' || REPLACE(SQLERRM,'"','\"') || '"}');
END;
]'
    );

    COMMIT;
END;
/

-- ============================================================
-- To update SMTP credentials later, just run:
-- ============================================================
--
-- UPDATE RR_EMAIL_CONFIG
--    SET SMTP_PASS    = 'new-api-key-here',
--        SMTP_USER    = 'new-user@example.com',
--        UPDATED_DATE = SYSTIMESTAMP,
--        UPDATED_BY   = 'ADMIN'
--  WHERE ID = (SELECT MAX(ID) FROM RR_EMAIL_CONFIG);
-- COMMIT;
