-- ============================================================
-- RR_GL_LINES_ALL Table
-- Created for ReactERP - Oracle Fusion Data Sync
-- ============================================================

CREATE TABLE RR_GL_LINES_ALL (
    -- Primary Key
    LINE_ID                         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Foreign Keys
    BATCH_ID                        NUMBER,
    JE_HEADER_ID                    NUMBER NOT NULL,
    JE_LINE_NUMBER                  NUMBER NOT NULL,

    -- Amounts - Entered Currency
    ENTERED_DR                      NUMBER,
    ENTERED_CR                      NUMBER,

    -- Amounts - Accounted (Ledger Currency)
    ACCOUNTED_DR                    NUMBER,
    ACCOUNTED_CR                    NUMBER,

    -- Statistical
    STAT_AMOUNT                     NUMBER,

    -- Description
    DESCRIPTION                     VARCHAR2(4000),

    -- Currency Information
    CURRENCY_CODE                   VARCHAR2(15),
    CURRENCY_CONVERSION_DATE        DATE,
    CURRENCY_CONVERSION_RATE        NUMBER,
    USER_CURRENCY_CONVERSION_TYPE   VARCHAR2(30),

    -- Account Information
    ACCOUNT_COMBINATION             VARCHAR2(750),
    CHART_OF_ACCOUNTS_NAME          VARCHAR2(240),

    -- Reference Fields
    REFERENCE1                      VARCHAR2(240),
    REFERENCE2                      VARCHAR2(240),
    REFERENCE3                      VARCHAR2(240),
    REFERENCE4                      VARCHAR2(240),
    REFERENCE5                      VARCHAR2(240),
    REFERENCE6                      VARCHAR2(240),
    REFERENCE7                      VARCHAR2(240),
    REFERENCE8                      VARCHAR2(240),
    REFERENCE9                      VARCHAR2(240),
    REFERENCE10                     VARCHAR2(240),

    -- JGZZ Reconciliation Fields
    JGZZ_RECON_REFERENCE            VARCHAR2(240),
    JGZZ_RECON_DATE                 DATE,
    JGZZ_RECON_ID                   NUMBER,
    JGZZ_RECON_STATUS_MEANING       VARCHAR2(80),

    -- Reconciliation
    RECONCILIATION_REFERENCE        VARCHAR2(240),

    -- Local Audit Columns
    CREATED_BY                      VARCHAR2(100) DEFAULT USER,
    CREATION_DATE                   TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY                 VARCHAR2(100),
    LAST_UPDATE_DATE                TIMESTAMP,
    SYNC_DATE                       TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Create indexes
CREATE INDEX IDX_RR_LINE_BATCH_ID ON RR_GL_LINES_ALL(BATCH_ID);
CREATE INDEX IDX_RR_LINE_HEADER_ID ON RR_GL_LINES_ALL(JE_HEADER_ID);
CREATE INDEX IDX_RR_LINE_NUMBER ON RR_GL_LINES_ALL(JE_LINE_NUMBER);
CREATE INDEX IDX_RR_LINE_ACCOUNT ON RR_GL_LINES_ALL(ACCOUNT_COMBINATION);
CREATE INDEX IDX_RR_LINE_SYNC_DATE ON RR_GL_LINES_ALL(SYNC_DATE);

COMMENT ON TABLE RR_GL_LINES_ALL IS 'GL Journal Lines synced from Oracle Fusion';
