-- ============================================================
-- Block Direct SQL DELETE on Journal Tables + Audit Archive
-- Column names verified from ALL_TAB_COLUMNS output.
-- Run AFTER 102_create_journal_delete_audit.sql
-- ============================================================


-- ─────────────────────────────────────────────────────────────
-- 1. SECURITY PACKAGE
-- ─────────────────────────────────────────────────────────────

CREATE OR REPLACE PACKAGE reerp_security AS
  FUNCTION is_ords_call RETURN BOOLEAN;
END reerp_security;
/

CREATE OR REPLACE PACKAGE BODY reerp_security AS
  FUNCTION is_ords_call RETURN BOOLEAN IS
    v_module      VARCHAR2(200) := SYS_CONTEXT('USERENV', 'MODULE');
    v_client_info VARCHAR2(200) := SYS_CONTEXT('USERENV', 'CLIENT_INFO');
  BEGIN
    IF v_module      IS NOT NULL AND UPPER(v_module)      LIKE '%ORDS%' THEN RETURN TRUE; END IF;
    IF v_client_info IS NOT NULL AND UPPER(v_client_info) LIKE '%ORDS%' THEN RETURN TRUE; END IF;
    RETURN FALSE;
  END;
END reerp_security;
/


-- ─────────────────────────────────────────────────────────────
-- 2. TRIGGERS
-- ─────────────────────────────────────────────────────────────

-- ── BATCHES (RR_GL_JOURNAL_BATCHES — 45 columns) ─────────────
CREATE OR REPLACE TRIGGER trg_del_audit_je_batches
BEFORE DELETE ON rr_gl_journal_batches
FOR EACH ROW
BEGIN
  BEGIN
    INSERT INTO rr_gl_journal_batches_del (
      BATCH_SYNC_ID, JE_BATCH_ID, ACCOUNTED_PERIOD_TYPE, DEFAULT_PERIOD_NAME,
      BATCH_NAME, STATUS, CONTROL_TOTAL, BATCH_DESCRIPTION, ERROR_MESSAGE,
      POSTED_DATE, POSTING_RUN_ID, REQUEST_ID,
      RUNNING_TOTAL_ACCT_CR, RUNNING_TOTAL_ACCT_DR, RUNNING_TOTAL_CR, RUNNING_TOTAL_DR,
      ORACLE_CREATED_BY, ORACLE_CREATION_DATE, ORACLE_LAST_UPDATE_DATE, ORACLE_LAST_UPDATED_BY,
      ACTUAL_FLAG_MEANING, APPROVAL_STATUS_MEANING, APPROVER_EMPLOYEE_NAME,
      FUNDS_STATUS_MEANING, PARENT_JE_BATCH_NAME, CHART_OF_ACCOUNTS_NAME,
      STATUS_MEANING, COMPLETION_STATUS_MEANING, USER_PERIOD_SET_NAME, USER_JE_SOURCE_NAME,
      REVERSAL_DATE, REVERSAL_PERIOD, REVERSAL_FLAG, REVERSAL_METHOD_MEANING,
      SYNC_STATUS, SYNC_DATE, SYNC_ERROR_MESSAGE, LAST_SYNC_DATE, SYNC_COUNT,
      CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE,
      LEDGER_ID, LEDGER_NAME,
      DELETED_BY, DELETED_DATE, DELETED_FROM_MODULE
    ) VALUES (
      :OLD.BATCH_SYNC_ID, :OLD.JE_BATCH_ID, :OLD.ACCOUNTED_PERIOD_TYPE, :OLD.DEFAULT_PERIOD_NAME,
      :OLD.BATCH_NAME, :OLD.STATUS, :OLD.CONTROL_TOTAL, :OLD.BATCH_DESCRIPTION, :OLD.ERROR_MESSAGE,
      :OLD.POSTED_DATE, :OLD.POSTING_RUN_ID, :OLD.REQUEST_ID,
      :OLD.RUNNING_TOTAL_ACCT_CR, :OLD.RUNNING_TOTAL_ACCT_DR, :OLD.RUNNING_TOTAL_CR, :OLD.RUNNING_TOTAL_DR,
      :OLD.ORACLE_CREATED_BY, :OLD.ORACLE_CREATION_DATE, :OLD.ORACLE_LAST_UPDATE_DATE, :OLD.ORACLE_LAST_UPDATED_BY,
      :OLD.ACTUAL_FLAG_MEANING, :OLD.APPROVAL_STATUS_MEANING, :OLD.APPROVER_EMPLOYEE_NAME,
      :OLD.FUNDS_STATUS_MEANING, :OLD.PARENT_JE_BATCH_NAME, :OLD.CHART_OF_ACCOUNTS_NAME,
      :OLD.STATUS_MEANING, :OLD.COMPLETION_STATUS_MEANING, :OLD.USER_PERIOD_SET_NAME, :OLD.USER_JE_SOURCE_NAME,
      :OLD.REVERSAL_DATE, :OLD.REVERSAL_PERIOD, :OLD.REVERSAL_FLAG, :OLD.REVERSAL_METHOD_MEANING,
      :OLD.SYNC_STATUS, :OLD.SYNC_DATE, :OLD.SYNC_ERROR_MESSAGE, :OLD.LAST_SYNC_DATE, :OLD.SYNC_COUNT,
      :OLD.CREATED_BY, :OLD.CREATION_DATE, :OLD.LAST_UPDATED_BY, :OLD.LAST_UPDATE_DATE,
      :OLD.LEDGER_ID, :OLD.LEDGER_NAME,
      SYS_CONTEXT('USERENV','SESSION_USER'), SYSTIMESTAMP, SYS_CONTEXT('USERENV','MODULE')
    );
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  IF NOT reerp_security.is_ords_call() THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Direct DELETE on RR_GL_JOURNAL_BATCHES is not permitted. Use the ReERP UI. '
      || '(Module=' || NVL(SYS_CONTEXT('USERENV','MODULE'),'NULL') || ')');
  END IF;
END;
/


-- ── HEADERS (RR_GL_JE_HEADERS — 48 columns) ──────────────────
CREATE OR REPLACE TRIGGER trg_del_audit_je_headers
BEFORE DELETE ON rr_gl_je_headers
FOR EACH ROW
BEGIN
  BEGIN
    INSERT INTO rr_gl_je_headers_del (
      HEADER_ID, BATCH_ID, JE_HEADER_ID,
      JOURNAL_NAME, JOURNAL_DESCRIPTION, PERIOD_NAME,
      DEFAULT_EFFECTIVE_DATE, REFERENCE_DATE,
      CURRENCY_CODE, LEDGER_CURRENCY_CODE,
      CURRENCY_CONVERSION_DATE, CURRENCY_CONVERSION_RATE, INV_CURRENCY_CONVERSION_RATE,
      USER_CURRENCY_CONVERSION_TYPE,
      CONTROL_TOTAL, RUNNING_TOTAL_DR, RUNNING_TOTAL_CR,
      RUNNING_TOTAL_ACCOUNTED_DR, RUNNING_TOTAL_ACCOUNTED_CR,
      LEDGER_NAME, LEGAL_ENTITY_NAME, USER_JE_CATEGORY_NAME, ENCUMBRANCE_TYPE,
      ACCRUAL_REVERSAL_EFFECTIVE_DATE, ACCRUAL_REVERSAL_PERIOD_NAME,
      ACCRUAL_REVERSAL_STATUS, ACCRUAL_REVERSAL_JE_HEADER_NAME,
      CLOSE_ACCOUNT_SEQUENCE_VALUE, CLOSE_ACCOUNT_SEQ_ASSIGN_NAME,
      POSTING_ACCOUNT_SEQUENCE_VALUE, POSTING_ACCOUNT_SEQ_ASSIGN_NAME,
      EXTERNAL_REFERENCE, ORIGINATING_BAL_SEG_VALUE,
      REVERSED_JE_HEADER_NAME, JE_FROM_SLA_FLAG_MEANING,
      FUSION_CREATED_BY, FUSION_CREATION_DATE, FUSION_LAST_UPDATE_DATE, FUSION_LAST_UPDATED_BY,
      CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, SYNC_DATE,
      LEDGER_ID, POSTING_STATUS, DESCRIPTION, USER_JE_SOURCE_NAME,
      DELETED_BY, DELETED_DATE, DELETED_FROM_MODULE
    ) VALUES (
      :OLD.HEADER_ID, :OLD.BATCH_ID, :OLD.JE_HEADER_ID,
      :OLD.JOURNAL_NAME, :OLD.JOURNAL_DESCRIPTION, :OLD.PERIOD_NAME,
      :OLD.DEFAULT_EFFECTIVE_DATE, :OLD.REFERENCE_DATE,
      :OLD.CURRENCY_CODE, :OLD.LEDGER_CURRENCY_CODE,
      :OLD.CURRENCY_CONVERSION_DATE, :OLD.CURRENCY_CONVERSION_RATE, :OLD.INV_CURRENCY_CONVERSION_RATE,
      :OLD.USER_CURRENCY_CONVERSION_TYPE,
      :OLD.CONTROL_TOTAL, :OLD.RUNNING_TOTAL_DR, :OLD.RUNNING_TOTAL_CR,
      :OLD.RUNNING_TOTAL_ACCOUNTED_DR, :OLD.RUNNING_TOTAL_ACCOUNTED_CR,
      :OLD.LEDGER_NAME, :OLD.LEGAL_ENTITY_NAME, :OLD.USER_JE_CATEGORY_NAME, :OLD.ENCUMBRANCE_TYPE,
      :OLD.ACCRUAL_REVERSAL_EFFECTIVE_DATE, :OLD.ACCRUAL_REVERSAL_PERIOD_NAME,
      :OLD.ACCRUAL_REVERSAL_STATUS, :OLD.ACCRUAL_REVERSAL_JE_HEADER_NAME,
      :OLD.CLOSE_ACCOUNT_SEQUENCE_VALUE, :OLD.CLOSE_ACCOUNT_SEQ_ASSIGN_NAME,
      :OLD.POSTING_ACCOUNT_SEQUENCE_VALUE, :OLD.POSTING_ACCOUNT_SEQ_ASSIGN_NAME,
      :OLD.EXTERNAL_REFERENCE, :OLD.ORIGINATING_BAL_SEG_VALUE,
      :OLD.REVERSED_JE_HEADER_NAME, :OLD.JE_FROM_SLA_FLAG_MEANING,
      :OLD.FUSION_CREATED_BY, :OLD.FUSION_CREATION_DATE, :OLD.FUSION_LAST_UPDATE_DATE, :OLD.FUSION_LAST_UPDATED_BY,
      :OLD.CREATED_BY, :OLD.CREATION_DATE, :OLD.LAST_UPDATED_BY, :OLD.LAST_UPDATE_DATE, :OLD.SYNC_DATE,
      :OLD.LEDGER_ID, :OLD.POSTING_STATUS, :OLD.DESCRIPTION, :OLD.USER_JE_SOURCE_NAME,
      SYS_CONTEXT('USERENV','SESSION_USER'), SYSTIMESTAMP, SYS_CONTEXT('USERENV','MODULE')
    );
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  IF NOT reerp_security.is_ords_call() THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Direct DELETE on RR_GL_JE_HEADERS is not permitted. Use the ReERP UI. '
      || '(Module=' || NVL(SYS_CONTEXT('USERENV','MODULE'),'NULL') || ')');
  END IF;
END;
/


-- ── LINES (RR_GL_JE_LINES_ALL — 41 columns) ──────────────────
CREATE OR REPLACE TRIGGER trg_del_audit_je_lines
BEFORE DELETE ON rr_gl_je_lines_all
FOR EACH ROW
BEGIN
  BEGIN
    INSERT INTO rr_gl_je_lines_all_del (
      LINE_ID, BATCH_ID, JE_HEADER_ID, JE_LINE_NUMBER,
      ENTERED_DR, ENTERED_CR, ACCOUNTED_DR, ACCOUNTED_CR, STAT_AMOUNT,
      DESCRIPTION, CURRENCY_CODE, CURRENCY_CONVERSION_DATE,
      CURRENCY_CONVERSION_RATE, USER_CURRENCY_CONVERSION_TYPE,
      ACCOUNT_COMBINATION, CHART_OF_ACCOUNTS_NAME,
      REFERENCE1, REFERENCE2, REFERENCE3, REFERENCE4, REFERENCE5,
      REFERENCE6, REFERENCE7, REFERENCE8, REFERENCE9, REFERENCE10,
      JGZZ_RECON_REFERENCE, JGZZ_RECON_DATE, JGZZ_RECON_ID, JGZZ_RECON_STATUS_MEANING,
      RECONCILIATION_REFERENCE,
      FUSION_CREATED_BY, FUSION_CREATION_DATE, FUSION_LAST_UPDATE_DATE, FUSION_LAST_UPDATED_BY,
      CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, SYNC_DATE,
      RECONCILED_FLAG,
      DELETED_BY, DELETED_DATE, DELETED_FROM_MODULE
    ) VALUES (
      :OLD.LINE_ID, :OLD.BATCH_ID, :OLD.JE_HEADER_ID, :OLD.JE_LINE_NUMBER,
      :OLD.ENTERED_DR, :OLD.ENTERED_CR, :OLD.ACCOUNTED_DR, :OLD.ACCOUNTED_CR, :OLD.STAT_AMOUNT,
      :OLD.DESCRIPTION, :OLD.CURRENCY_CODE, :OLD.CURRENCY_CONVERSION_DATE,
      :OLD.CURRENCY_CONVERSION_RATE, :OLD.USER_CURRENCY_CONVERSION_TYPE,
      :OLD.ACCOUNT_COMBINATION, :OLD.CHART_OF_ACCOUNTS_NAME,
      :OLD.REFERENCE1, :OLD.REFERENCE2, :OLD.REFERENCE3, :OLD.REFERENCE4, :OLD.REFERENCE5,
      :OLD.REFERENCE6, :OLD.REFERENCE7, :OLD.REFERENCE8, :OLD.REFERENCE9, :OLD.REFERENCE10,
      :OLD.JGZZ_RECON_REFERENCE, :OLD.JGZZ_RECON_DATE, :OLD.JGZZ_RECON_ID, :OLD.JGZZ_RECON_STATUS_MEANING,
      :OLD.RECONCILIATION_REFERENCE,
      :OLD.FUSION_CREATED_BY, :OLD.FUSION_CREATION_DATE, :OLD.FUSION_LAST_UPDATE_DATE, :OLD.FUSION_LAST_UPDATED_BY,
      :OLD.CREATED_BY, :OLD.CREATION_DATE, :OLD.LAST_UPDATED_BY, :OLD.LAST_UPDATE_DATE, :OLD.SYNC_DATE,
      :OLD.RECONCILED_FLAG,
      SYS_CONTEXT('USERENV','SESSION_USER'), SYSTIMESTAMP, SYS_CONTEXT('USERENV','MODULE')
    );
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  IF NOT reerp_security.is_ords_call() THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Direct DELETE on RR_GL_JE_LINES_ALL is not permitted. Use the ReERP UI. '
      || '(Module=' || NVL(SYS_CONTEXT('USERENV','MODULE'),'NULL') || ')');
  END IF;
END;
/


-- ─────────────────────────────────────────────────────────────
-- 3. TEST
-- Run from APEX SQL Workshop — should be blocked:
--   DELETE FROM rr_gl_journal_batches WHERE 1=2;
--
-- Check your session MODULE:
--   SELECT SYS_CONTEXT('USERENV','MODULE') FROM dual;
-- ─────────────────────────────────────────────────────────────
