-- ============================================================
-- DEBUG: Remove silent exception to expose actual error
-- Run this, then do a UI update, check what error appears
-- ============================================================

-- First check if archive tables exist and have correct columns
SELECT table_name, COUNT(*) AS col_count
FROM all_tab_columns
WHERE owner = 'BCLDIFC'
  AND table_name IN ('RR_GL_JOURNAL_BATCHES_UPD','RR_GL_JE_HEADERS_UPD','RR_GL_JE_LINES_ALL_UPD')
GROUP BY table_name
ORDER BY table_name;

-- Check source table col counts too
SELECT table_name, COUNT(*) AS col_count
FROM all_tab_columns
WHERE owner = 'BCLDIFC'
  AND table_name IN ('RR_GL_JOURNAL_BATCHES','RR_GL_JE_HEADERS','RR_GL_JE_LINES_ALL')
GROUP BY table_name
ORDER BY table_name;


-- ── DEBUG TRIGGER (no silent exception — will show real error) ──
CREATE OR REPLACE TRIGGER trg_upd_audit_je_batches
BEFORE UPDATE ON rr_gl_journal_batches
FOR EACH ROW
BEGIN
  INSERT INTO rr_gl_journal_batches_upd (
    BATCH_SYNC_ID, JE_BATCH_ID, ACCOUNTED_PERIOD_TYPE, DEFAULT_PERIOD_NAME,
    BATCH_NAME, STATUS, CONTROL_TOTAL, BATCH_DESCRIPTION, ERROR_MESSAGE,
    POSTED_DATE, POSTING_RUN_ID, REQUEST_ID,
    RUNNING_TOTAL_ACCT_CR, RUNNING_TOTAL_ACCT_DR, RUNNING_TOTAL_CR, RUNNING_TOTAL_DR,
    ORACLE_CREATED_BY, ORACLE_CREATION_DATE, ORACLE_LAST_UPDATE_DATE, ORACLE_LAST_UPDATED_BY,
    ACTUAL_FLAG_MEANING, APPROVAL_STATUS_MEANING, APPROVER_EMPLOYEE_NAME,
    FUNDS_STATUS_MEANING, PARENT_JE_BATCH_NAME, CHART_OF_ACCOUNTS_NAME,
    STATUS_MEANING, COMPLETION_STATUS_MEANING, USER_PERIOD_SET_NAME, USER_JE_SOURCE_NAME,
    REVERSAL_DATE, REVERSAL_PERIOD, REVERSAL_FLAG, REVERSAL_METHOD_MEANING,
    SYNC_STATUS, SYNC_DATE, SYNC_ERROR_MESSAGE, LAST_SYNC_DATE, SYNC_COUNT,
    CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE,
    LEDGER_ID, LEDGER_NAME,
    CHANGED_BY, CHANGED_DATE, CHANGED_FROM_MODULE
  ) VALUES (
    :OLD.BATCH_SYNC_ID, :OLD.JE_BATCH_ID, :OLD.ACCOUNTED_PERIOD_TYPE, :OLD.DEFAULT_PERIOD_NAME,
    :OLD.BATCH_NAME, :OLD.STATUS, :OLD.CONTROL_TOTAL, :OLD.BATCH_DESCRIPTION, :OLD.ERROR_MESSAGE,
    :OLD.POSTED_DATE, :OLD.POSTING_RUN_ID, :OLD.REQUEST_ID,
    :OLD.RUNNING_TOTAL_ACCT_CR, :OLD.RUNNING_TOTAL_ACCT_DR, :OLD.RUNNING_TOTAL_CR, :OLD.RUNNING_TOTAL_DR,
    :OLD.ORACLE_CREATED_BY, :OLD.ORACLE_CREATION_DATE, :OLD.ORACLE_LAST_UPDATE_DATE, :OLD.ORACLE_LAST_UPDATED_BY,
    :OLD.ACTUAL_FLAG_MEANING, :OLD.APPROVAL_STATUS_MEANING, :OLD.APPROVER_EMPLOYEE_NAME,
    :OLD.FUNDS_STATUS_MEANING, :OLD.PARENT_JE_BATCH_NAME, :OLD.CHART_OF_ACCOUNTS_NAME,
    :OLD.STATUS_MEANING, :OLD.COMPLETION_STATUS_MEANING, :OLD.USER_PERIOD_SET_NAME, :OLD.USER_JE_SOURCE_NAME,
    :OLD.REVERSAL_DATE, :OLD.REVERSAL_PERIOD, :OLD.REVERSAL_FLAG, :OLD.REVERSAL_METHOD_MEANING,
    :OLD.SYNC_STATUS, :OLD.SYNC_DATE, :OLD.SYNC_ERROR_MESSAGE, :OLD.LAST_SYNC_DATE, :OLD.SYNC_COUNT,
    :OLD.CREATED_BY, :OLD.CREATION_DATE, :OLD.LAST_UPDATED_BY, :OLD.LAST_UPDATE_DATE,
    :OLD.LEDGER_ID, :OLD.LEDGER_NAME,
    SYS_CONTEXT('USERENV','SESSION_USER'), SYSTIMESTAMP, SYS_CONTEXT('USERENV','MODULE')
  );
  IF NOT reerp_security.is_ords_call() THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Direct UPDATE on RR_GL_JOURNAL_BATCHES is not permitted. Use the ReERP UI. '
      || '(Module=' || NVL(SYS_CONTEXT('USERENV','MODULE'),'NULL') || ')');
  END IF;
END;
/
