-- =============================================================================
-- Fix: Restart GL identity sequences to prevent collision with Fusion-synced IDs
-- =============================================================================
-- Root cause:
--   GENERATED BY DEFAULT AS IDENTITY starts at 1 for all three GL tables.
--   The journals/create ORDS handler uses HEADER_ID as JE_HEADER_ID for
--   locally-created journals → IDs 1, 2, 3 …
--   Oracle Fusion sync also stores JE_HEADER_ID values from Fusion (e.g. 500091).
--   If a Fusion journal happens to share a low JE_HEADER_ID, the lines query
--   (which joins on JE_HEADER_ID) returns lines from BOTH the local journal
--   AND the Fusion-synced journal → extra unwanted GL lines appear.
--
-- Fix:
--   Restart each identity column at 500,000,000.
--   Fusion IDs are in the hundreds-of-thousands range (e.g. 500,091).
--   Adding three zeros → 500,000,000 guarantees no overlap even if Fusion
--   continues generating new journals for years.
--
--   Each block uses GREATEST(current_max, 500000000) + 1 so the patch is
--   idempotent and safe regardless of how many local journals already exist.
--
-- Tables affected:
--   RR_GL_JOURNAL_BATCHES  — BATCH_SYNC_ID  (local PK, used as JE_BATCH_ID)
--   RR_GL_HEADERS          — HEADER_ID      (local PK, used as JE_HEADER_ID)
--   RR_GL_LINES_ALL        — LINE_ID        (local PK)
--
-- Run in: SQL Workshop > SQL Commands (as schema owner)
-- Run each block separately
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. RR_GL_JOURNAL_BATCHES.BATCH_SYNC_ID
-- ---------------------------------------------------------------------------
DECLARE
  v_start NUMBER;
BEGIN
  SELECT GREATEST(NVL(MAX(BATCH_SYNC_ID), 0), 500000000) + 1
    INTO v_start
    FROM RR_GL_JOURNAL_BATCHES;

  EXECUTE IMMEDIATE
    'ALTER TABLE RR_GL_JOURNAL_BATCHES MODIFY BATCH_SYNC_ID '
    || 'GENERATED BY DEFAULT AS IDENTITY '
    || '(START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE)';

  DBMS_OUTPUT.PUT_LINE('RR_GL_JOURNAL_BATCHES.BATCH_SYNC_ID restarted at ' || v_start);
END;
/


-- ---------------------------------------------------------------------------
-- 2. RR_GL_HEADERS.HEADER_ID
-- ---------------------------------------------------------------------------
DECLARE
  v_start NUMBER;
BEGIN
  SELECT GREATEST(NVL(MAX(HEADER_ID), 0), 500000000) + 1
    INTO v_start
    FROM RR_GL_HEADERS;

  EXECUTE IMMEDIATE
    'ALTER TABLE RR_GL_HEADERS MODIFY HEADER_ID '
    || 'GENERATED BY DEFAULT AS IDENTITY '
    || '(START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE)';

  DBMS_OUTPUT.PUT_LINE('RR_GL_HEADERS.HEADER_ID restarted at ' || v_start);
END;
/


-- ---------------------------------------------------------------------------
-- 3. RR_GL_LINES_ALL.LINE_ID
-- ---------------------------------------------------------------------------
DECLARE
  v_start NUMBER;
BEGIN
  SELECT GREATEST(NVL(MAX(LINE_ID), 0), 500000000) + 1
    INTO v_start
    FROM RR_GL_LINES_ALL;

  EXECUTE IMMEDIATE
    'ALTER TABLE RR_GL_LINES_ALL MODIFY LINE_ID '
    || 'GENERATED BY DEFAULT AS IDENTITY '
    || '(START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE)';

  DBMS_OUTPUT.PUT_LINE('RR_GL_LINES_ALL.LINE_ID restarted at ' || v_start);
END;
/


-- ---------------------------------------------------------------------------
-- 4. Verification query — run after the three blocks above
--    Confirms current identity state and max existing IDs
-- ---------------------------------------------------------------------------
SELECT
  'RR_GL_JOURNAL_BATCHES' AS table_name,
  'BATCH_SYNC_ID'         AS column_name,
  NVL(MAX(BATCH_SYNC_ID), 0) AS current_max
FROM RR_GL_JOURNAL_BATCHES
UNION ALL
SELECT
  'RR_GL_HEADERS',
  'HEADER_ID',
  NVL(MAX(HEADER_ID), 0)
FROM RR_GL_HEADERS
UNION ALL
SELECT
  'RR_GL_LINES_ALL',
  'LINE_ID',
  NVL(MAX(LINE_ID), 0)
FROM RR_GL_LINES_ALL;
