-- =============================================================================
-- 21_CREATE_JE_HEADER_ID_SEQUENCE.SQL
--
-- Problem
-- -------
-- Locally-created GL journals (from the journals/create ORDS handler) are
-- stored in RR_GL_HEADERS.  The handler previously used HEADER_ID (the table's
-- GENERATED BY DEFAULT AS IDENTITY PK) as the JE_HEADER_ID value.
-- The identity column started at 1 and counted up → it eventually reached
-- numbers like 500102 which already exist as Fusion-synced JE_HEADER_IDs.
-- When the drill-down hits /gl/journals/500102/lines it gets lines from BOTH
-- the local journal AND the Fusion-synced journal with the same ID.
--
-- Fix
-- ---
-- Create a standalone Oracle SEQUENCE for JE_HEADER_ID assignment.
-- Start value = GREATEST(max existing JE_HEADER_ID in RR_GL_HEADERS,
--                         max existing HEADER_ID    in RR_GL_HEADERS,
--                         1,000,000,000)   + 1
--
-- 1,000,000,000 is the hard floor — it is ~2,000× above the 500K-range Fusion
-- IDs currently in the system, so no Fusion sync can ever catch up even if
-- syncing runs for years.
--
-- Usage in the journals/create ORDS handler
-- -----------------------------------------
-- Replace the line that assigns JE_HEADER_ID with:
--
--     v_je_header_id := SEQ_RR_GL_JE_HEADER_ID.NEXTVAL;
--
-- Then INSERT INTO RR_GL_HEADERS with JE_HEADER_ID = v_je_header_id.
--
-- Run in: APEX SQL Workshop > SQL Commands (as schema owner)
-- Run each block individually.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- STEP 1 — Create the sequence (safe: skips if it already exists)
-- ---------------------------------------------------------------------------
DECLARE
  v_max   NUMBER;
  v_start NUMBER;
BEGIN
  -- Find the highest ID already in use from both columns
  SELECT GREATEST(
           NVL(MAX(JE_HEADER_ID), 0),
           NVL(MAX(HEADER_ID),    0),
           1000000000              -- hard floor: 1 billion
         ) + 1
    INTO v_max
    FROM RR_GL_HEADERS;

  v_start := v_max;

  -- Drop existing sequence if present so we can recreate cleanly
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RR_GL_JE_HEADER_ID';
    DBMS_OUTPUT.PUT_LINE('Dropped existing SEQ_RR_GL_JE_HEADER_ID');
  EXCEPTION
    WHEN OTHERS THEN NULL; -- sequence did not exist
  END;

  EXECUTE IMMEDIATE
    'CREATE SEQUENCE SEQ_RR_GL_JE_HEADER_ID'
    || ' START WITH '  || v_start
    || ' INCREMENT BY 1'
    || ' NOCACHE'
    || ' NOCYCLE'
    || ' NOORDER';

  DBMS_OUTPUT.PUT_LINE('SEQ_RR_GL_JE_HEADER_ID created. First NEXTVAL = ' || v_start);
END;
/


-- ---------------------------------------------------------------------------
-- STEP 2 — Verify: peek at what NEXTVAL will return
-- (This increments the sequence by 1 — run only once for verification)
-- ---------------------------------------------------------------------------
SELECT SEQ_RR_GL_JE_HEADER_ID.NEXTVAL AS first_local_je_header_id FROM DUAL;


-- ---------------------------------------------------------------------------
-- STEP 3 — Check current high-water marks
-- ---------------------------------------------------------------------------
SELECT 'RR_GL_HEADERS.JE_HEADER_ID (max)'   AS item, MAX(JE_HEADER_ID) AS value FROM RR_GL_HEADERS
UNION ALL
SELECT 'RR_GL_HEADERS.HEADER_ID (max)',               MAX(HEADER_ID)    FROM RR_GL_HEADERS
UNION ALL
SELECT 'SEQ_RR_GL_JE_HEADER_ID (last_number)',
       last_number
  FROM user_sequences
 WHERE sequence_name = 'SEQ_RR_GL_JE_HEADER_ID';


-- =============================================================================
-- STEP 4 — Update the journals/create ORDS handler to use the sequence
-- =============================================================================
-- Replace your existing handler body with this one.
-- The ONLY change from the original is: JE_HEADER_ID is now assigned via
-- SEQ_RR_GL_JE_HEADER_ID.NEXTVAL instead of relying on HEADER_ID from
-- the identity column.
--
-- Paste this into ORDS.DEFINE_HANDLER p_source for the 'journals/create'
-- POST handler in the 'reerp' module.
-- =============================================================================

BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name    => 'reerp',
    p_pattern        => 'journals/create',
    p_method         => 'POST',
    p_source_type    => 'plsql/block',
    p_items_per_page => 0,
    p_mimes_allowed  => 'application/json',
    p_comments       => 'Create GL journal batch + header + lines (sequence-based JE_HEADER_ID)',
    p_source         => q'[
DECLARE
  v_body          CLOB;
  v_batch         JSON_OBJECT_T;
  v_header        JSON_OBJECT_T;
  v_lines         JSON_ARRAY_T;
  v_line          JSON_OBJECT_T;

  v_je_batch_id   NUMBER;
  v_je_header_id  NUMBER;   -- assigned from SEQ_RR_GL_JE_HEADER_ID
  v_batch_name    VARCHAR2(240);
  v_header_name   VARCHAR2(240);
  v_period        VARCHAR2(15);
  v_ledger        VARCHAR2(240);
  v_ledger_id     NUMBER;
  v_currency      VARCHAR2(15);
  v_category      VARCHAR2(80);
  v_source        VARCHAR2(80);
  v_eff_date      DATE;
  v_total_dr      NUMBER := 0;
  v_total_cr      NUMBER := 0;
  v_ctrl_total    NUMBER;
  v_line_num      NUMBER := 0;
  v_created_by    VARCHAR2(100);
  v_description   VARCHAR2(4000);
  v_acct_period   VARCHAR2(15);
  v_status        VARCHAR2(30);
  v_batch_desc    VARCHAR2(4000);
  v_batch_source  VARCHAR2(240);
BEGIN
  v_body := :body_text;

  -- ── Parse top-level JSON ──────────────────────────────────────────────────
  DECLARE v_root JSON_OBJECT_T; BEGIN
    v_root   := JSON_OBJECT_T.parse(v_body);
    v_batch  := v_root.get_object('batch');
    v_header := v_root.get_object('header');
    v_lines  := v_root.get_array('lines');
  END;

  -- ── Batch fields ──────────────────────────────────────────────────────────
  v_batch_name   := v_batch.get_string('batchName');
  v_batch_desc   := v_batch.get_string('batchDescription');
  v_ledger       := v_batch.get_string('ledgerName');
  v_ledger_id    := v_batch.get_number('ledgerId');
  v_acct_period  := v_batch.get_string('accountingPeriod');
  v_ctrl_total   := NVL(v_batch.get_number('controlTotal'), 0);
  v_status       := NVL(v_batch.get_string('status'), 'NEW');
  v_batch_source := v_batch.get_string('batchSource');
  v_created_by   := NVL(v_batch.get_string('createdBy'), USER);

  -- ── Insert batch — identity PK auto-assigned ──────────────────────────────
  INSERT INTO RR_GL_JOURNAL_BATCHES (
    BATCH_NAME, BATCH_DESCRIPTION, LEDGER_NAME, LEDGER_ID,
    ACCOUNTING_PERIOD, CONTROL_TOTAL, STATUS, STATUS_MEANING,
    RUNNING_TOTAL_DR, RUNNING_TOTAL_CR, USER_JE_SOURCE_NAME, CREATED_BY
  ) VALUES (
    v_batch_name, v_batch_desc, v_ledger, v_ledger_id,
    v_acct_period, v_ctrl_total, v_status,
    CASE v_status WHEN 'P' THEN 'Posted' WHEN 'NEW' THEN 'Unposted' ELSE v_status END,
    NVL(v_batch.get_number('runningTotalDr'), 0),
    NVL(v_batch.get_number('runningTotalCr'), 0),
    NVL(v_batch_source, 'Manual'),
    v_created_by
  )
  RETURNING JE_BATCH_ID INTO v_je_batch_id;

  -- ── Header fields ─────────────────────────────────────────────────────────
  v_header_name := v_header.get_string('journalName');
  v_description := v_header.get_string('description');
  v_period      := v_header.get_string('periodName');
  v_currency    := v_header.get_string('currencyCode');
  v_category    := v_header.get_string('jeCategory');
  v_source      := v_header.get_string('jeSource');
  v_eff_date    := TO_DATE(SUBSTR(NVL(v_header.get_string('currencyConversionDate'), v_acct_period), 1, 10), 'YYYY-MM-DD');
  v_total_dr    := NVL(v_header.get_number('runningTotalDr'), 0);
  v_total_cr    := NVL(v_header.get_number('runningTotalCr'), 0);

  -- ── Assign JE_HEADER_ID from dedicated sequence ───────────────────────────
  -- This guarantees the ID is above 1,000,000,000 and never collides
  -- with Fusion-synced JE_HEADER_IDs (which are in the sub-million range
  -- for this environment).
  v_je_header_id := SEQ_RR_GL_JE_HEADER_ID.NEXTVAL;

  INSERT INTO RR_GL_HEADERS (
    JE_HEADER_ID, BATCH_ID, JOURNAL_NAME, JOURNAL_DESCRIPTION,
    PERIOD_NAME, DEFAULT_EFFECTIVE_DATE, CURRENCY_CODE,
    USER_JE_CATEGORY_NAME, RUNNING_TOTAL_DR, RUNNING_TOTAL_CR,
    RUNNING_TOTAL_ACCOUNTED_DR, RUNNING_TOTAL_ACCOUNTED_CR,
    LEDGER_NAME, LEGAL_ENTITY_NAME, CREATED_BY
  ) VALUES (
    v_je_header_id, v_je_batch_id, v_header_name, v_description,
    v_period, v_eff_date, v_currency,
    v_category, v_total_dr, v_total_cr, v_total_dr, v_total_cr,
    v_ledger,
    NVL(v_header.get_string('legalEntityName'), NULL),
    v_created_by
  );

  -- ── Lines ─────────────────────────────────────────────────────────────────
  FOR i IN 0 .. v_lines.get_size - 1 LOOP
    v_line     := TREAT(v_lines.get(i) AS JSON_OBJECT_T);
    v_line_num := v_line_num + 1;

    INSERT INTO RR_GL_LINES_ALL (
      JE_HEADER_ID, JE_LINE_NUMBER, BATCH_ID,
      ENTERED_DR, ENTERED_CR, ACCOUNTED_DR, ACCOUNTED_CR,
      DESCRIPTION, CURRENCY_CODE, ACCOUNT_COMBINATION,
      CHART_OF_ACCOUNTS_NAME,
      REFERENCE1, REFERENCE2, REFERENCE3, REFERENCE4, REFERENCE5,
      CREATED_BY
    ) VALUES (
      v_je_header_id, v_line_num, v_je_batch_id,
      v_line.get_number('enteredDr'),
      v_line.get_number('enteredCr'),
      NVL(v_line.get_number('accountedDr'), v_line.get_number('enteredDr')),
      NVL(v_line.get_number('accountedCr'), v_line.get_number('enteredCr')),
      v_line.get_string('description'),
      NVL(v_line.get_string('currencyCode'), v_currency),
      v_line.get_string('accountCombination'),
      NVL(v_line.get_string('chartOfAccountsName'), 'Chart of Accounts'),
      v_line.get_string('reference1'),
      NVL(v_line.get_string('reference2'), v_batch_name),
      v_line.get_string('reference3'),
      v_line.get_string('reference4'),
      v_line.get_string('reference5'),
      NVL(v_line.get_string('createdBy'), v_created_by)
    );
  END LOOP;

  COMMIT;

  :status_code := 201;
  APEX_JSON.OPEN_OBJECT;
  APEX_JSON.WRITE('success',       TRUE);
  APEX_JSON.WRITE('jeBatchId',     v_je_batch_id);
  APEX_JSON.WRITE('jeHeaderId',    v_je_header_id);
  APEX_JSON.WRITE('linesInserted', v_line_num);
  APEX_JSON.WRITE('batchName',     v_batch_name);
  APEX_JSON.CLOSE_OBJECT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('error',   SQLERRM);
    APEX_JSON.WRITE('detail',  DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    APEX_JSON.CLOSE_OBJECT;
END;
]'
  );
  COMMIT;
END;
/


-- =============================================================================
-- STEP 5 — Backfill check
-- Find any existing local journals whose JE_HEADER_ID collides with a
-- Fusion-synced journal in RR_GL_JE_HEADERS (or RR_GL_JE_LINES_ALL).
-- Run this to see if old data needs cleanup.
-- =============================================================================
SELECT
  h.JE_HEADER_ID,
  h.JOURNAL_NAME,
  h.PERIOD_NAME,
  h.CREATED_BY,
  h.CREATION_DATE,
  'LOCAL journal ID collides with Fusion-synced data' AS issue
FROM RR_GL_HEADERS h
WHERE h.JE_HEADER_ID <= 999999999          -- below the new sequence floor
  AND h.FUSION_CREATED_BY IS NULL          -- locally created (not synced from Fusion)
ORDER BY h.JE_HEADER_ID;
