-- ============================================================
-- Fix: V_GL_JOURNAL_LINES_SEGMENTS — add TRIM to all segment
-- extractions so that company/account filters work correctly
-- even when account combinations have spaces around dashes.
--
-- Root cause: REGEXP_SUBSTR('[^-]+') without TRIM would capture
-- trailing spaces (e.g. "04 " instead of "04") if the stored
-- combination is "04 - 01 - ...".  RR_V_STANDARD_TB already
-- uses TRIM — this brings the journal-lines view in line.
--
-- Also fixes the LEFT JOIN condition on ACCOUNT so that account
-- descriptions resolve correctly for all accounts.
--
-- Run in APEX SQL Workshop.
-- ============================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_GL_JOURNAL_LINES_SEGMENTS"
    ("BATCH_ID","JE_HEADER_ID","JE_LINE_NUMBER","CURRENCY_CODE",
     "ACCOUNT_COMBINATION","COMPANY","LOB","DEPARTMENT","ACCOUNT",
     "ACCOUNT_DESCRIPTION","SUB_ACCOUNT","ANALYSIS","INTERCOMPANY",
     "FUTURE1","FUTURE2","ENTERED_DR","ENTERED_CR","ACCOUNTED_DR",
     "ACCOUNTED_CR","CHART_OF_ACCOUNTS_NAME","DEFAULT_PERIOD_NAME",
     "BATCH_NAME","ACTUAL_FLAG_MEANING","APPROVAL_STATUS_MEANING",
     "USER_PERIOD_SET_NAME","USER_JE_SOURCE_NAME","LEDGER_NAME",
     "LEGAL_ENTITY_NAME","USER_JE_CATEGORY_NAME","ACCOUNTING_DATE") AS
SELECT
    L.BATCH_ID,
    L.JE_HEADER_ID,
    L.JE_LINE_NUMBER,
    L.CURRENCY_CODE,
    L.ACCOUNT_COMBINATION,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 1)) AS COMPANY,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 2)) AS LOB,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 3)) AS DEPARTMENT,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 4)) AS ACCOUNT,
    V.DESCRIPTION AS ACCOUNT_DESCRIPTION,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 5)) AS SUB_ACCOUNT,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 6)) AS ANALYSIS,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 7)) AS INTERCOMPANY,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 8)) AS FUTURE1,
    TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 9)) AS FUTURE2,
    L.ENTERED_DR,
    L.ENTERED_CR,
    L.ACCOUNTED_DR,
    L.ACCOUNTED_CR,
    L.CHART_OF_ACCOUNTS_NAME,
    B.DEFAULT_PERIOD_NAME,
    B.BATCH_NAME,
    B.ACTUAL_FLAG_MEANING,
    B.APPROVAL_STATUS_MEANING,
    B.USER_PERIOD_SET_NAME,
    B.USER_JE_SOURCE_NAME,
    H.LEDGER_NAME,
    H.LEGAL_ENTITY_NAME,
    H.USER_JE_CATEGORY_NAME,
    H.DEFAULT_EFFECTIVE_DATE AS ACCOUNTING_DATE
FROM RR_GL_JE_LINES_ALL L
JOIN RR_GL_JE_HEADERS H ON L.JE_HEADER_ID = H.JE_HEADER_ID
JOIN RR_GL_JOURNAL_BATCHES B ON B.JE_BATCH_ID = L.BATCH_ID
LEFT JOIN RR_VALUE_SET_VALUES V
    ON V.VALUE         = TRIM(REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 4))
   AND V.VALUE_SET_CODE = 'BUIMERC_FIN_GLB_COA_ACCOUNT';
/
