-- ============================================================
-- RR_GL_CATEGORIES table
-- Synced from Oracle Fusion journalCategoriesLOV
-- ============================================================

CREATE TABLE RR_GL_CATEGORIES (
    CATEGORY_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JE_CATEGORY_NAME        VARCHAR2(25)   NOT NULL,
    USER_JE_CATEGORY_NAME   VARCHAR2(80),
    DESCRIPTION             VARCHAR2(240),
    DISALLOW_MJE_FLAG       VARCHAR2(1),

    -- Sync tracking
    LAST_SYNC_DATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
    SYNC_COUNT              NUMBER    DEFAULT 1,

    CONSTRAINT UK_RR_GL_CATEGORIES UNIQUE (JE_CATEGORY_NAME)
);

CREATE INDEX IDX_RR_GL_CAT_USER_NAME ON RR_GL_CATEGORIES(USER_JE_CATEGORY_NAME);

COMMENT ON TABLE RR_GL_CATEGORIES IS 'GL Journal Categories synced from Oracle Fusion journalCategoriesLOV';
