-- =============================================================================
-- PATCH 83: Create sequence + trigger for RR_VALUE_SET_VALUES.VALUE_ID
--
-- PROBLEM:
--   IDX_RR_VSV_UK is on (VALUE_SET_CODE, VALUE_ID). VALUE_ID was being
--   generated by a MAX()+1 trigger (or had no generator at all), causing
--   ORA-00001 when bulk-sync rows from Fusion occupied IDs the trigger
--   hadn't accounted for.
--
-- FIX:
--   1. Create sequence RR_VSV_VALUE_ID_SEQ starting above current MAX.
--   2. Create BEFORE INSERT trigger that assigns NEXTVAL when VALUE_ID
--      is not supplied — so existing bulk-sync inserts that pass their
--      own VALUE_ID still work, and new single-row creates always get a
--      guaranteed-unique ID.
--   3. Re-register the POST handler to use the sequence explicitly
--      (belt-and-suspenders, in case the trigger is bypassed by ORDS).
--
-- HOW TO RUN:
--   APEX SQL Workshop → SQL Commands — run each block separately.
-- =============================================================================

-- ── 1. Create sequence starting above current MAX VALUE_ID ───────────────────
DECLARE
    v_max   NUMBER;
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(VALUE_ID), 0) + 1 INTO v_max FROM RR_VALUE_SET_VALUES;
    v_start := GREATEST(v_max, 1);

    BEGIN
        EXECUTE IMMEDIATE
            'CREATE SEQUENCE RR_VSV_VALUE_ID_SEQ ' ||
            'START WITH ' || v_start || ' ' ||
            'INCREMENT BY 1 NOCACHE NOCYCLE';
        DBMS_OUTPUT.PUT_LINE('Sequence RR_VSV_VALUE_ID_SEQ created, START WITH ' || v_start);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -955 THEN
                -- Already exists — advance it if needed
                DECLARE
                    v_curr NUMBER;
                BEGIN
                    SELECT last_number INTO v_curr
                    FROM   USER_SEQUENCES
                    WHERE  sequence_name = 'RR_VSV_VALUE_ID_SEQ';

                    IF v_curr < v_start THEN
                        EXECUTE IMMEDIATE
                            'ALTER SEQUENCE RR_VSV_VALUE_ID_SEQ ' ||
                            'INCREMENT BY ' || (v_start - v_curr);
                        EXECUTE IMMEDIATE
                            'SELECT RR_VSV_VALUE_ID_SEQ.NEXTVAL FROM DUAL';
                        EXECUTE IMMEDIATE
                            'ALTER SEQUENCE RR_VSV_VALUE_ID_SEQ INCREMENT BY 1';
                        DBMS_OUTPUT.PUT_LINE('Sequence advanced to ' || v_start);
                    ELSE
                        DBMS_OUTPUT.PUT_LINE('Sequence already at ' || v_curr || ', no change needed.');
                    END IF;
                END;
            ELSE
                RAISE;
            END IF;
    END;
END;
/

-- ── 2. Create BEFORE INSERT trigger using the sequence ───────────────────────
CREATE OR REPLACE TRIGGER RR_VSV_VALUE_ID_BI
BEFORE INSERT ON RR_VALUE_SET_VALUES
FOR EACH ROW
BEGIN
    IF :NEW.VALUE_ID IS NULL THEN
        :NEW.VALUE_ID := RR_VSV_VALUE_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- ── 3. Re-register POST valuesets/values using the sequence explicitly ───────
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'valuesets/values',
            p_method      => 'POST'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'valuesets/values',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_body          CLOB         := :body_text;
    v_vset_code     VARCHAR2(150):= TRIM(JSON_VALUE(v_body, '$.valueSetCode'));
    v_value         VARCHAR2(150):= TRIM(JSON_VALUE(v_body, '$.value'));
    v_description   VARCHAR2(500):= JSON_VALUE(v_body, '$.description');
    v_enabled       VARCHAR2(1)  := NVL(JSON_VALUE(v_body, '$.enabledFlag'), 'Y');
    v_acct_type     VARCHAR2(50) := JSON_VALUE(v_body, '$.accountType');
    v_start_date    VARCHAR2(30) := JSON_VALUE(v_body, '$.startDateActive');
    v_end_date      VARCHAR2(30) := JSON_VALUE(v_body, '$.endDateActive');
    v_summary       VARCHAR2(1)  := NVL(JSON_VALUE(v_body, '$.summaryFlag'), 'N');
    v_posting       VARCHAR2(1)  := NVL(JSON_VALUE(v_body, '$.detailPostingAllowed'), 'Y');
    v_budgeting     VARCHAR2(1)  := NVL(JSON_VALUE(v_body, '$.detailBudgetingAllowed'), 'Y');
    v_new_id        NUMBER;
    v_exists        NUMBER;
BEGIN
    IF v_vset_code IS NULL OR v_value IS NULL THEN
        :status_code := 400;
        HTP.P('{"status":"ERROR","message":"valueSetCode and value are required."}');
        RETURN;
    END IF;

    -- Business-level duplicate check: same value code in same value set
    SELECT COUNT(*) INTO v_exists
    FROM   RR_VALUE_SET_VALUES
    WHERE  VALUE_SET_CODE = v_vset_code
      AND  VALUE          = v_value;

    IF v_exists > 0 THEN
        :status_code := 409;
        HTP.P('{"status":"ERROR","message":"Value ' || v_value || ' already exists in value set ' || v_vset_code || '."}');
        RETURN;
    END IF;

    -- Explicit sequence to guarantee unique VALUE_ID
    SELECT RR_VSV_VALUE_ID_SEQ.NEXTVAL INTO v_new_id FROM DUAL;

    INSERT INTO RR_VALUE_SET_VALUES (
        VALUE_ID,
        VALUE_SET_CODE, VALUE, DESCRIPTION,
        ENABLED_FLAG, ACCOUNT_TYPE,
        START_DATE_ACTIVE, END_DATE_ACTIVE,
        SUMMARY_FLAG, DETAIL_POSTING_ALLOWED, DETAIL_BUDGETING_ALLOWED
    ) VALUES (
        v_new_id,
        v_vset_code, v_value, v_description,
        v_enabled, v_acct_type,
        CASE WHEN v_start_date IS NOT NULL THEN TO_DATE(v_start_date, 'YYYY-MM-DD') ELSE NULL END,
        CASE WHEN v_end_date   IS NOT NULL THEN TO_DATE(v_end_date,   'YYYY-MM-DD') ELSE NULL END,
        v_summary, v_posting, v_budgeting
    );

    COMMIT;
    :status_code := 201;
    HTP.P('{"status":"SUCCESS","valueId":' || v_new_id || '}');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        :status_code := 409;
        HTP.P('{"status":"ERROR","message":"Value ' || v_value || ' already exists in value set ' || v_vset_code || '."}');
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P('{"status":"ERROR","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('POST valuesets/values updated to use RR_VSV_VALUE_ID_SEQ.');
END;
/
