-- =============================================================================
-- PATCH 92: Fix V_GL_JOURNAL_LINES_SEGMENTS — add local RR_GL_LINES_ALL branch
--
-- PROBLEM:
--   The view only reads from RR_GL_JE_LINES_ALL / RR_GL_JE_HEADERS
--   (Fusion-synced tables). Journals created locally via the ReactERP
--   SLA posting flow are stored in RR_GL_LINES_ALL / RR_GL_HEADERS
--   and are invisible to gl/accountanalysis until Fusion syncs them back.
--
-- FIX:
--   UNION ALL the local tables into the view so both sources appear.
--   Column mapping for the local branch:
--     h.PERIOD_NAME           → DEFAULT_PERIOD_NAME
--     h.JOURNAL_NAME          → (used for BATCH_NAME fallback)
--     h.DEFAULT_EFFECTIVE_DATE → ACCOUNTING_DATE
--     h.USER_JE_CATEGORY_NAME → USER_JE_CATEGORY_NAME
--     h.USER_JE_SOURCE_NAME   → USER_JE_SOURCE_NAME (from batch)
--     b.BATCH_NAME            → BATCH_NAME
--     b.ACTUAL_FLAG_MEANING   → ACTUAL_FLAG_MEANING
--     b.APPROVAL_STATUS_MEANING → APPROVAL_STATUS_MEANING
--     b.USER_PERIOD_SET_NAME  → USER_PERIOD_SET_NAME
--
-- HOW TO RUN:
--   APEX SQL Workshop → SQL Commands  (run the CREATE OR REPLACE block)
-- =============================================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_GL_JOURNAL_LINES_SEGMENTS"
    ("BATCH_ID","JE_HEADER_ID","JE_LINE_NUMBER","CURRENCY_CODE",
     "ACCOUNT_COMBINATION","COMPANY","LOB","DEPARTMENT","ACCOUNT",
     "ACCOUNT_DESCRIPTION","SUB_ACCOUNT","ANALYSIS","INTERCOMPANY",
     "FUTURE1","FUTURE2","ENTERED_DR","ENTERED_CR","ACCOUNTED_DR",
     "ACCOUNTED_CR","CHART_OF_ACCOUNTS_NAME","DEFAULT_PERIOD_NAME",
     "BATCH_NAME","ACTUAL_FLAG_MEANING","APPROVAL_STATUS_MEANING",
     "USER_PERIOD_SET_NAME","USER_JE_SOURCE_NAME","LEDGER_NAME",
     "LEGAL_ENTITY_NAME","USER_JE_CATEGORY_NAME","ACCOUNTING_DATE") AS

-- ── Branch 1: Fusion-synced journals (RR_GL_JE_LINES_ALL) ────────────────────
SELECT
    L.BATCH_ID,
    L.JE_HEADER_ID,
    L.JE_LINE_NUMBER,
    L.CURRENCY_CODE,
    L.ACCOUNT_COMBINATION,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 1) AS COMPANY,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 2) AS LOB,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 3) AS DEPARTMENT,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 4) AS ACCOUNT,
    V.DESCRIPTION AS ACCOUNT_DESCRIPTION,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 5) AS SUB_ACCOUNT,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 6) AS ANALYSIS,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 7) AS INTERCOMPANY,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 8) AS FUTURE1,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 9) AS FUTURE2,
    L.ENTERED_DR,
    L.ENTERED_CR,
    L.ACCOUNTED_DR,
    L.ACCOUNTED_CR,
    L.CHART_OF_ACCOUNTS_NAME,
    B.DEFAULT_PERIOD_NAME,
    B.BATCH_NAME,
    B.ACTUAL_FLAG_MEANING,
    B.APPROVAL_STATUS_MEANING,
    B.USER_PERIOD_SET_NAME,
    B.USER_JE_SOURCE_NAME,
    H.LEDGER_NAME,
    H.LEGAL_ENTITY_NAME,
    H.USER_JE_CATEGORY_NAME,
    H.DEFAULT_EFFECTIVE_DATE AS ACCOUNTING_DATE
FROM RR_GL_JE_LINES_ALL L
JOIN RR_GL_JE_HEADERS H ON L.JE_HEADER_ID = H.JE_HEADER_ID
JOIN RR_GL_JOURNAL_BATCHES B ON B.JE_BATCH_ID = L.BATCH_ID
LEFT JOIN RR_VALUE_SET_VALUES V
    ON V.VALUE = REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 4)
   AND V.VALUE_SET_CODE = 'BUIMERC_FIN_GLB_COA_ACCOUNT'

UNION ALL

-- ── Branch 2: Locally-created journals (RR_GL_LINES_ALL) ─────────────────────
SELECT
    L.BATCH_ID,
    L.JE_HEADER_ID,
    L.JE_LINE_NUMBER,
    L.CURRENCY_CODE,
    L.ACCOUNT_COMBINATION,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 1) AS COMPANY,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 2) AS LOB,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 3) AS DEPARTMENT,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 4) AS ACCOUNT,
    V.DESCRIPTION AS ACCOUNT_DESCRIPTION,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 5) AS SUB_ACCOUNT,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 6) AS ANALYSIS,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 7) AS INTERCOMPANY,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 8) AS FUTURE1,
    REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 9) AS FUTURE2,
    L.ENTERED_DR,
    L.ENTERED_CR,
    L.ACCOUNTED_DR,
    L.ACCOUNTED_CR,
    L.CHART_OF_ACCOUNTS_NAME,
    H.PERIOD_NAME                                        AS DEFAULT_PERIOD_NAME,
    NVL(B.BATCH_NAME, H.JOURNAL_NAME)                   AS BATCH_NAME,
    NVL(B.ACTUAL_FLAG_MEANING,     'Actual')             AS ACTUAL_FLAG_MEANING,
    NVL(B.APPROVAL_STATUS_MEANING, 'Posted')             AS APPROVAL_STATUS_MEANING,
    B.USER_PERIOD_SET_NAME,
    NVL(B.USER_JE_SOURCE_NAME, H.USER_JE_SOURCE_NAME)   AS USER_JE_SOURCE_NAME,
    H.LEDGER_NAME,
    H.LEGAL_ENTITY_NAME,
    H.USER_JE_CATEGORY_NAME,
    H.DEFAULT_EFFECTIVE_DATE                             AS ACCOUNTING_DATE
FROM RR_GL_LINES_ALL L
JOIN RR_GL_HEADERS H ON H.JE_HEADER_ID = L.JE_HEADER_ID
LEFT JOIN RR_GL_JOURNAL_BATCHES B ON B.JE_BATCH_ID = L.BATCH_ID
LEFT JOIN RR_VALUE_SET_VALUES V
    ON V.VALUE = REGEXP_SUBSTR(L.ACCOUNT_COMBINATION, '[^-]+', 1, 4)
   AND V.VALUE_SET_CODE = 'BUIMERC_FIN_GLB_COA_ACCOUNT'
/
