-- ============================================================
-- Currency Module — Table Definitions
-- Tables: RR_CURRENCY_LIST, RR_CURRENCY_RATE_TYPES,
--         RR_CURRENCY_DAILY_RATES
-- ============================================================

-- ── Currency Master ──────────────────────────────────────────
CREATE TABLE RR_CURRENCY_LIST (
    CURRENCY_CODE          VARCHAR2(10)   NOT NULL,
    NAME                   VARCHAR2(100),
    DESCRIPTION            VARCHAR2(200),
    ENABLED_FLAG           VARCHAR2(1)    DEFAULT 'Y',
    START_DATE_ACTIVE      DATE,
    END_DATE_ACTIVE        DATE,
    SYMBOL                 VARCHAR2(20),
    PRECISION              NUMBER(2)      DEFAULT 2,
    EXTENDED_PRECISION     NUMBER(2)      DEFAULT 5,
    CURRENCY_FORMAT        VARCHAR2(200),
    CURRENCY_FORMAT_SYMBOL VARCHAR2(400),
    CURRENCY_FORMAT_CODE   VARCHAR2(400),
    ISSUING_TERRITORY_CODE VARCHAR2(10),
    CURRENCY_FLAG          VARCHAR2(1)    DEFAULT 'Y',
    LAST_SYNC_DATE         DATE           DEFAULT SYSDATE,
    CREATED_BY             VARCHAR2(100)  DEFAULT USER,
    CREATION_DATE          DATE           DEFAULT SYSDATE,
    CONSTRAINT RR_CURR_LIST_PK PRIMARY KEY (CURRENCY_CODE)
);

-- ── Rate Types ───────────────────────────────────────────────
CREATE SEQUENCE RR_CURR_RATE_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE RR_CURRENCY_RATE_TYPES (
    RATE_TYPE_ID                  NUMBER         NOT NULL,
    NAME                          VARCHAR2(50)   NOT NULL,
    DESCRIPTION                   VARCHAR2(200),
    DEFAULT_RATE_TYPE             VARCHAR2(1)    DEFAULT 'N',
    ENFORCE_INVERSE_RELATIONSHIP  VARCHAR2(1)    DEFAULT 'N',
    ENABLE_CROSS_RATES            VARCHAR2(1)    DEFAULT 'N',
    ALLOW_CROSS_RATES_OVERRIDE    VARCHAR2(1)    DEFAULT 'N',
    CROSS_RATE_PIVOT_CURRENCY     VARCHAR2(10),
    CREATED_BY                    VARCHAR2(100)  DEFAULT USER,
    CREATION_DATE                 DATE           DEFAULT SYSDATE,
    LAST_UPDATED_BY               VARCHAR2(100)  DEFAULT USER,
    LAST_UPDATE_DATE              DATE           DEFAULT SYSDATE,
    CONSTRAINT RR_CURR_RT_PK      PRIMARY KEY (RATE_TYPE_ID),
    CONSTRAINT RR_CURR_RT_NAME_UQ UNIQUE (NAME)
);

CREATE OR REPLACE TRIGGER RR_CURR_RT_BIR
BEFORE INSERT ON RR_CURRENCY_RATE_TYPES
FOR EACH ROW
BEGIN
    IF :NEW.RATE_TYPE_ID IS NULL THEN
        :NEW.RATE_TYPE_ID := RR_CURR_RATE_TYPE_SEQ.NEXTVAL;
    END IF;
END;
/

-- Seed default rate types
INSERT INTO RR_CURRENCY_RATE_TYPES (NAME, DESCRIPTION, DEFAULT_RATE_TYPE, ENFORCE_INVERSE_RELATIONSHIP, ENABLE_CROSS_RATES, ALLOW_CROSS_RATES_OVERRIDE)
VALUES ('Corporate', 'Corporate Exchange Rate', 'Y', 'Y', 'Y', 'N');
INSERT INTO RR_CURRENCY_RATE_TYPES (NAME, DESCRIPTION, DEFAULT_RATE_TYPE, ENFORCE_INVERSE_RELATIONSHIP, ENABLE_CROSS_RATES)
VALUES ('Fixed', 'Fixed Rate', 'N', 'Y', 'N');
INSERT INTO RR_CURRENCY_RATE_TYPES (NAME, DESCRIPTION, DEFAULT_RATE_TYPE, ENFORCE_INVERSE_RELATIONSHIP, ENABLE_CROSS_RATES)
VALUES ('Spot', 'Spot Exchange Rate', 'N', 'Y', 'N');
INSERT INTO RR_CURRENCY_RATE_TYPES (NAME, DESCRIPTION, DEFAULT_RATE_TYPE, ENFORCE_INVERSE_RELATIONSHIP, ENABLE_CROSS_RATES)
VALUES ('User', 'User Specified Rate', 'N', 'Y', 'N');
COMMIT;

-- ── Daily Rates ──────────────────────────────────────────────
CREATE SEQUENCE RR_CURR_DAILY_RATE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE RR_CURRENCY_DAILY_RATES (
    RATE_ID          NUMBER         NOT NULL,
    FROM_CURRENCY    VARCHAR2(10)   NOT NULL,
    TO_CURRENCY      VARCHAR2(10)   NOT NULL,
    RATE_DATE        DATE           NOT NULL,
    RATE_TYPE        VARCHAR2(50)   NOT NULL,
    RATE             NUMBER(20,10)  NOT NULL,
    INVERSE_RATE     NUMBER(20,10),
    SOURCE           VARCHAR2(20)   DEFAULT 'MANUAL',
    CREATED_BY       VARCHAR2(100)  DEFAULT USER,
    CREATION_DATE    DATE           DEFAULT SYSDATE,
    CONSTRAINT RR_CURR_DR_PK PRIMARY KEY (RATE_ID),
    CONSTRAINT RR_CURR_DR_UQ UNIQUE (FROM_CURRENCY, TO_CURRENCY, RATE_DATE, RATE_TYPE)
);

CREATE OR REPLACE TRIGGER RR_CURR_DR_BIR
BEFORE INSERT ON RR_CURRENCY_DAILY_RATES
FOR EACH ROW
BEGIN
    IF :NEW.RATE_ID IS NULL THEN
        :NEW.RATE_ID := RR_CURR_DAILY_RATE_SEQ.NEXTVAL;
    END IF;
    IF :NEW.INVERSE_RATE IS NULL AND :NEW.RATE IS NOT NULL AND :NEW.RATE != 0 THEN
        :NEW.INVERSE_RATE := ROUND(1 / :NEW.RATE, 10);
    END IF;
END;
/

CREATE INDEX RR_CURR_DR_DATE_IDX      ON RR_CURRENCY_DAILY_RATES (RATE_DATE DESC);
CREATE INDEX RR_CURR_DR_FROM_TO_IDX   ON RR_CURRENCY_DAILY_RATES (FROM_CURRENCY, TO_CURRENCY);
CREATE INDEX RR_CURR_DR_RATE_TYPE_IDX ON RR_CURRENCY_DAILY_RATES (RATE_TYPE);
