-- ============================================
-- Table: RR_GL_LEGAL_ENTITIES
-- Description: Legal Entity master data synced from Oracle Fusion
-- Source API : GET /fscmRestApi/resources/11.13.18.05/legalEntitiesLOV
-- ============================================

CREATE TABLE RR_GL_LEGAL_ENTITIES (
    ID                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LEGAL_ENTITY_ID          NUMBER          NOT NULL,
    NAME                     VARCHAR2(360)   NOT NULL,
    LEGAL_ENTITY_IDENTIFIER  VARCHAR2(60),
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    PARTY_ID                 NUMBER,
    -- Audit fields from Fusion
    CREATED_BY               VARCHAR2(150),
    CREATION_DATE            TIMESTAMP,
    LAST_UPDATE_DATE         TIMESTAMP,
    LAST_UPDATE_LOGIN        VARCHAR2(100),
    LAST_UPDATED_BY          VARCHAR2(150),
    -- Sync metadata
    SYNC_DATE                TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_RR_GL_LE_ID UNIQUE (LEGAL_ENTITY_ID)
);

-- Indexes
CREATE INDEX IDX_RR_GL_LE_NAME       ON RR_GL_LEGAL_ENTITIES(NAME);
CREATE INDEX IDX_RR_GL_LE_IDENTIFIER ON RR_GL_LEGAL_ENTITIES(LEGAL_ENTITY_IDENTIFIER);
CREATE INDEX IDX_RR_GL_LE_PARTY      ON RR_GL_LEGAL_ENTITIES(PARTY_ID);
CREATE INDEX IDX_RR_GL_LE_EFF        ON RR_GL_LEGAL_ENTITIES(EFFECTIVE_FROM, EFFECTIVE_TO);

-- Column comments
COMMENT ON TABLE  RR_GL_LEGAL_ENTITIES                         IS 'Legal Entity master data synced from Oracle Fusion legalEntitiesLOV';
COMMENT ON COLUMN RR_GL_LEGAL_ENTITIES.LEGAL_ENTITY_ID         IS 'Oracle Fusion LegalEntityId – unique identifier';
COMMENT ON COLUMN RR_GL_LEGAL_ENTITIES.NAME                    IS 'Legal entity display name (e.g. BUIMERC CORPORATION FZE)';
COMMENT ON COLUMN RR_GL_LEGAL_ENTITIES.LEGAL_ENTITY_IDENTIFIER IS 'Short identifier / code (e.g. 5314)';
COMMENT ON COLUMN RR_GL_LEGAL_ENTITIES.EFFECTIVE_FROM          IS 'Date from which the legal entity is active';
COMMENT ON COLUMN RR_GL_LEGAL_ENTITIES.EFFECTIVE_TO            IS 'Date to which the legal entity is active (NULL = no end date)';
COMMENT ON COLUMN RR_GL_LEGAL_ENTITIES.PARTY_ID                IS 'Oracle party ID linked to this legal entity';
COMMENT ON COLUMN RR_GL_LEGAL_ENTITIES.SYNC_DATE               IS 'Timestamp of last sync from Oracle Fusion';


-- ============================================
-- Procedure: RR_SYNC_GL_LEGAL_ENTITIES
-- Description: Upsert legal entities from JSON payload
--              Payload shape: {"items":[{...}, ...]}
-- ============================================

CREATE OR REPLACE PROCEDURE RR_SYNC_GL_LEGAL_ENTITIES (
    p_json  IN  CLOB,
    p_count OUT NUMBER,
    p_error OUT VARCHAR2
) AS
    v_legal_entity_id         NUMBER;
    v_name                    VARCHAR2(360);
    v_legal_entity_identifier VARCHAR2(60);
    v_effective_from          DATE;
    v_effective_to            DATE;
    v_party_id                NUMBER;
    v_created_by              VARCHAR2(150);
    v_creation_date           TIMESTAMP;
    v_last_update_date        TIMESTAMP;
    v_last_update_login       VARCHAR2(100);
    v_last_updated_by         VARCHAR2(150);
BEGIN
    p_count := 0;
    p_error := NULL;

    FOR rec IN (
        SELECT *
        FROM JSON_TABLE(p_json, '$.items[*]'
            COLUMNS (
                legal_entity_id          NUMBER          PATH '$.LegalEntityId',
                name                     VARCHAR2(360)   PATH '$.Name',
                legal_entity_identifier  VARCHAR2(60)    PATH '$.LegalEntityIdentifier',
                effective_from           DATE            PATH '$.EffectiveFrom',
                effective_to             DATE            PATH '$.EffectiveTo',
                party_id                 NUMBER          PATH '$.PartyId',
                created_by               VARCHAR2(150)   PATH '$.CreatedBy',
                creation_date            TIMESTAMP       PATH '$.CreationDate',
                last_update_date         TIMESTAMP       PATH '$.LastUpdateDate',
                last_update_login        VARCHAR2(100)   PATH '$.LastUpdateLogin',
                last_updated_by          VARCHAR2(150)   PATH '$.LastUpdatedBy'
            )
        )
    ) LOOP
        v_legal_entity_id         := rec.legal_entity_id;
        v_name                    := rec.name;
        v_legal_entity_identifier := rec.legal_entity_identifier;
        v_effective_from          := rec.effective_from;
        v_effective_to            := rec.effective_to;
        v_party_id                := rec.party_id;
        v_created_by              := rec.created_by;
        v_creation_date           := rec.creation_date;
        v_last_update_date        := rec.last_update_date;
        v_last_update_login       := rec.last_update_login;
        v_last_updated_by         := rec.last_updated_by;

        MERGE INTO RR_GL_LEGAL_ENTITIES tgt
        USING (SELECT v_legal_entity_id AS legal_entity_id FROM DUAL) src
        ON (tgt.LEGAL_ENTITY_ID = src.legal_entity_id)
        WHEN MATCHED THEN
            UPDATE SET
                tgt.NAME                    = v_name,
                tgt.LEGAL_ENTITY_IDENTIFIER = v_legal_entity_identifier,
                tgt.EFFECTIVE_FROM          = v_effective_from,
                tgt.EFFECTIVE_TO            = v_effective_to,
                tgt.PARTY_ID               = v_party_id,
                tgt.CREATED_BY             = v_created_by,
                tgt.CREATION_DATE          = v_creation_date,
                tgt.LAST_UPDATE_DATE       = v_last_update_date,
                tgt.LAST_UPDATE_LOGIN      = v_last_update_login,
                tgt.LAST_UPDATED_BY        = v_last_updated_by,
                tgt.SYNC_DATE              = SYSTIMESTAMP
        WHEN NOT MATCHED THEN
            INSERT (
                LEGAL_ENTITY_ID,
                NAME,
                LEGAL_ENTITY_IDENTIFIER,
                EFFECTIVE_FROM,
                EFFECTIVE_TO,
                PARTY_ID,
                CREATED_BY,
                CREATION_DATE,
                LAST_UPDATE_DATE,
                LAST_UPDATE_LOGIN,
                LAST_UPDATED_BY,
                SYNC_DATE
            ) VALUES (
                v_legal_entity_id,
                v_name,
                v_legal_entity_identifier,
                v_effective_from,
                v_effective_to,
                v_party_id,
                v_created_by,
                v_creation_date,
                v_last_update_date,
                v_last_update_login,
                v_last_updated_by,
                SYSTIMESTAMP
            );

        p_count := p_count + 1;
    END LOOP;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        p_error := SQLERRM;
        ROLLBACK;
END RR_SYNC_GL_LEGAL_ENTITIES;
/


-- ============================================
-- APEX REST Handler – POST + GET  gl/legalentities
-- Endpoint: /ords/bcldifc/reerp/gl/legalentities
-- ============================================

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'gl/legalentities',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'Legal Entities sync + query endpoint'
    );

    -- POST: receive JSON batch from sync service → upsert
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'gl/legalentities',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Sync Legal Entities from Oracle Fusion',
        p_source         => q'[
DECLARE
    l_json  CLOB;
    l_count NUMBER;
    l_error VARCHAR2(4000);
BEGIN
    l_json := :body_text;

    RR_SYNC_GL_LEGAL_ENTITIES(
        p_json  => l_json,
        p_count => l_count,
        p_error => l_error
    );

    IF l_error IS NOT NULL THEN
        :status_code := 500;
        HTP.P('{"status":"error","message":"' || REPLACE(l_error, '"', '''') || '"}');
    ELSE
        :status_code := 200;
        HTP.P('{"status":"success","count":' || l_count || '}');
    END IF;
END;
]'
    );

    -- GET: return active legal entities (no end date or end date in future)
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'gl/legalentities',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_items_per_page => 500,
        p_mimes_allowed  => NULL,
        p_comments       => 'Return active Legal Entities',
        p_source         => q'[
SELECT
    LEGAL_ENTITY_ID,
    NAME,
    LEGAL_ENTITY_IDENTIFIER,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    PARTY_ID,
    SYNC_DATE
FROM RR_GL_LEGAL_ENTITIES
WHERE EFFECTIVE_TO IS NULL
   OR EFFECTIVE_TO >= SYSDATE
ORDER BY NAME
]'
    );

    COMMIT;
END;
/


-- ============================================
-- APEX REST Handler – GET  gl/legalentities/all
-- Returns ALL records including expired (admin / sync review)
-- Endpoint: /ords/bcldifc/reerp/gl/legalentities/all
-- ============================================

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'gl/legalentities/all',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'Return all Legal Entities including expired'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'gl/legalentities/all',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_items_per_page => 500,
        p_mimes_allowed  => NULL,
        p_comments       => 'All Legal Entities (active + expired)',
        p_source         => q'[
SELECT
    LEGAL_ENTITY_ID,
    NAME,
    LEGAL_ENTITY_IDENTIFIER,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    PARTY_ID,
    SYNC_DATE
FROM RR_GL_LEGAL_ENTITIES
ORDER BY NAME
]'
    );

    COMMIT;
END;
/
