-- ============================================
-- Table: RR_GL_BUSINESS_UNITS
-- Description: Stores Business Unit master data synced from Oracle Fusion
-- Source API : GET /fscmRestApi/resources/11.13.18.05/finBusinessUnitsLOV
-- ============================================

CREATE TABLE RR_GL_BUSINESS_UNITS (
    ID                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BUSINESS_UNIT_ID        NUMBER          NOT NULL,
    BUSINESS_UNIT_NAME      VARCHAR2(360)   NOT NULL,
    ACTIVE_FLAG             VARCHAR2(1),            -- 'Y' / 'N'  (from boolean ActiveFlag)
    PRIMARY_LEDGER_ID       NUMBER,
    LOCATION_ID             NUMBER,
    MANAGER_ID              NUMBER,
    LEGAL_ENTITY_ID         NUMBER,
    PROFIT_CENTER_FLAG      VARCHAR2(1),            -- 'Y' / 'N'  (from boolean ProfitCenterFlag)
    COMPANY                 VARCHAR2(30),           -- COA Segment 1 company code for this BU
    -- Audit
    SYNC_DATE               TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_RR_GL_BU_ID UNIQUE (BUSINESS_UNIT_ID)
);

-- Add COMPANY column if the table already exists (safe re-run)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE RR_GL_BUSINESS_UNITS ADD (COMPANY VARCHAR2(30))';
EXCEPTION
    WHEN OTHERS THEN NULL; -- column already exists
END;
/

-- Indexes
CREATE INDEX IDX_RR_GL_BU_NAME        ON RR_GL_BUSINESS_UNITS(BUSINESS_UNIT_NAME);
CREATE INDEX IDX_RR_GL_BU_ACTIVE      ON RR_GL_BUSINESS_UNITS(ACTIVE_FLAG);
CREATE INDEX IDX_RR_GL_BU_LE          ON RR_GL_BUSINESS_UNITS(LEGAL_ENTITY_ID);
CREATE INDEX IDX_RR_GL_BU_LEDGER      ON RR_GL_BUSINESS_UNITS(PRIMARY_LEDGER_ID);

-- Column comments
COMMENT ON TABLE  RR_GL_BUSINESS_UNITS                    IS 'Business Unit master data synced from Oracle Fusion finBusinessUnitsLOV';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.BUSINESS_UNIT_ID   IS 'Oracle Fusion BusinessUnitId – unique identifier';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.BUSINESS_UNIT_NAME IS 'Business unit display name';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.ACTIVE_FLAG        IS 'Y = Active, N = Inactive  (maps to Oracle ActiveFlag boolean)';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.PRIMARY_LEDGER_ID  IS 'Primary ledger ID linked to this BU';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.LOCATION_ID        IS 'Physical location ID';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.MANAGER_ID         IS 'Manager person ID (nullable)';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.LEGAL_ENTITY_ID    IS 'Legal entity ID associated with this BU';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.PROFIT_CENTER_FLAG IS 'Y = Profit Center, N = Not  (maps to Oracle ProfitCenterFlag boolean)';
COMMENT ON COLUMN RR_GL_BUSINESS_UNITS.SYNC_DATE          IS 'Timestamp of last sync';


-- ============================================
-- Procedure: RR_SYNC_BUSINESS_UNITS
-- Description: Upsert business units from JSON payload
--              Payload shape:  {"items":[{...}, ...]}
-- ============================================

CREATE OR REPLACE PROCEDURE RR_SYNC_BUSINESS_UNITS (
    p_json  IN  CLOB,
    p_count OUT NUMBER,
    p_error OUT VARCHAR2
) AS
    v_business_unit_id   NUMBER;
    v_business_unit_name VARCHAR2(360);
    v_active_flag        VARCHAR2(1);
    v_primary_ledger_id  NUMBER;
    v_location_id        NUMBER;
    v_manager_id         NUMBER;
    v_legal_entity_id    NUMBER;
    v_profit_center_flag VARCHAR2(1);
    v_company            VARCHAR2(30);
BEGIN
    p_count := 0;
    p_error := NULL;

    FOR rec IN (
        SELECT *
        FROM JSON_TABLE(p_json, '$.items[*]'
            COLUMNS (
                business_unit_id    NUMBER        PATH '$.BusinessUnitId',
                business_unit_name  VARCHAR2(360) PATH '$.BusinessUnitName',
                -- Booleans arrive as true/false strings in JSON_TABLE
                active_flag_raw     VARCHAR2(10)  PATH '$.ActiveFlag',
                primary_ledger_id   NUMBER        PATH '$.PrimaryLedgerId',
                location_id         NUMBER        PATH '$.LocationId',
                manager_id          NUMBER        PATH '$.ManagerId',
                legal_entity_id     NUMBER        PATH '$.LegalEntityId',
                profit_center_raw   VARCHAR2(10)  PATH '$.ProfitCenterFlag',
                company             VARCHAR2(30)  PATH '$.Company'
            )
        )
    ) LOOP
        v_business_unit_id   := rec.business_unit_id;
        v_business_unit_name := rec.business_unit_name;
        v_active_flag        := CASE WHEN LOWER(rec.active_flag_raw) = 'true' THEN 'Y' ELSE 'N' END;
        v_primary_ledger_id  := rec.primary_ledger_id;
        v_location_id        := rec.location_id;
        v_manager_id         := rec.manager_id;
        v_legal_entity_id    := rec.legal_entity_id;
        v_profit_center_flag := CASE WHEN LOWER(rec.profit_center_raw) = 'true' THEN 'Y' ELSE 'N' END;
        v_company            := rec.company;

        MERGE INTO RR_GL_BUSINESS_UNITS tgt
        USING (SELECT v_business_unit_id AS business_unit_id FROM DUAL) src
        ON (tgt.BUSINESS_UNIT_ID = src.business_unit_id)
        WHEN MATCHED THEN
            UPDATE SET
                tgt.BUSINESS_UNIT_NAME  = v_business_unit_name,
                tgt.ACTIVE_FLAG         = v_active_flag,
                tgt.PRIMARY_LEDGER_ID   = v_primary_ledger_id,
                tgt.LOCATION_ID         = v_location_id,
                tgt.MANAGER_ID          = v_manager_id,
                tgt.LEGAL_ENTITY_ID     = v_legal_entity_id,
                tgt.PROFIT_CENTER_FLAG  = v_profit_center_flag,
                tgt.COMPANY             = NVL(v_company, tgt.COMPANY),
                tgt.SYNC_DATE           = SYSTIMESTAMP
        WHEN NOT MATCHED THEN
            INSERT (
                BUSINESS_UNIT_ID,
                BUSINESS_UNIT_NAME,
                ACTIVE_FLAG,
                PRIMARY_LEDGER_ID,
                LOCATION_ID,
                MANAGER_ID,
                LEGAL_ENTITY_ID,
                PROFIT_CENTER_FLAG,
                COMPANY,
                SYNC_DATE
            ) VALUES (
                v_business_unit_id,
                v_business_unit_name,
                v_active_flag,
                v_primary_ledger_id,
                v_location_id,
                v_manager_id,
                v_legal_entity_id,
                v_profit_center_flag,
                v_company,
                SYSTIMESTAMP
            );

        p_count := p_count + 1;
    END LOOP;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        p_error := SQLERRM;
        ROLLBACK;
END RR_SYNC_BUSINESS_UNITS;
/


-- ============================================
-- APEX REST Handler – POST  gl/businessunits
-- Endpoint: /ords/bcldifc/reerp/gl/businessunits
-- Used by: sync service batch inserts
-- ============================================

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'gl/businessunits',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'Business Units sync + query endpoint'
    );

    -- POST: receive JSON batch from sync service → upsert
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'gl/businessunits',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_items_per_page => 0,
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Sync Business Units from Oracle Fusion',
        p_source         => q'[
DECLARE
    l_json  CLOB;
    l_count NUMBER;
    l_error VARCHAR2(4000);
BEGIN
    l_json := :body_text;

    RR_SYNC_BUSINESS_UNITS(
        p_json  => l_json,
        p_count => l_count,
        p_error => l_error
    );

    IF l_error IS NOT NULL THEN
        :status_code := 500;
        HTP.P('{"status":"error","message":"' || REPLACE(l_error, '"', '''') || '"}');
    ELSE
        :status_code := 200;
        HTP.P('{"status":"success","count":' || l_count || '}');
    END IF;
END;
]'
    );

    -- GET: return all business units as JSON (ORDS auto-paginates)
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'gl/businessunits',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_items_per_page => 500,
        p_mimes_allowed  => NULL,
        p_comments       => 'Return all Business Units',
        p_source         => q'[
SELECT
    bu.BUSINESS_UNIT_ID,
    bu.BUSINESS_UNIT_NAME,
    bu.ACTIVE_FLAG,
    bu.PRIMARY_LEDGER_ID,
    bu.LOCATION_ID,
    bu.MANAGER_ID,
    bu.LEGAL_ENTITY_ID,
    bu.LEGAL_ENTITY_NAME,
    bu.PROFIT_CENTER_FLAG,
    -- COMPANY: use stored value if set, otherwise derive from first segment
    -- of LIABILITY_DISTRIBUTION on a site assignment for this BU
    NVL(
        bu.COMPANY,
        (SELECT REGEXP_SUBSTR(jl.account_combination, '[^-]+', 1, 1)
         FROM   RR_SLA_ACCOUNTING_HEADERS sh
         JOIN   RR_SLA_JOURNAL_LINES      jl ON jl.header_id = sh.header_id
         WHERE  sh.ledger_id              = bu.PRIMARY_LEDGER_ID
           AND  jl.account_combination   IS NOT NULL
           AND  ROWNUM                    = 1)
    ) AS COMPANY,
    bu.SYNC_DATE
FROM RR_GL_BUSINESS_UNITS bu
WHERE bu.ACTIVE_FLAG = 'Y'
ORDER BY bu.BUSINESS_UNIT_NAME
]'
    );

    COMMIT;
END;
/


-- ============================================
-- APEX REST Handler – GET  gl/businessunits/all
-- Returns ALL records including inactive (for admin / sync review)
-- Endpoint: /ords/bcldifc/reerp/gl/businessunits/all
-- ============================================

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'reerp',
        p_pattern     => 'gl/businessunits/all',
        p_priority    => 0,
        p_etag_type   => 'HASH',
        p_etag_query  => NULL,
        p_comments    => 'Return all Business Units including inactive'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'gl/businessunits/all',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_items_per_page => 500,
        p_mimes_allowed  => NULL,
        p_comments       => 'All Business Units (active + inactive)',
        p_source         => q'[
SELECT
    bu.BUSINESS_UNIT_ID,
    bu.BUSINESS_UNIT_NAME,
    bu.ACTIVE_FLAG,
    bu.PRIMARY_LEDGER_ID,
    bu.LOCATION_ID,
    bu.MANAGER_ID,
    bu.LEGAL_ENTITY_ID,
    bu.LEGAL_ENTITY_NAME,
    bu.PROFIT_CENTER_FLAG,
    NVL(
        bu.COMPANY,
        (SELECT REGEXP_SUBSTR(jl.account_combination, '[^-]+', 1, 1)
         FROM   RR_SLA_ACCOUNTING_HEADERS sh
         JOIN   RR_SLA_JOURNAL_LINES      jl ON jl.header_id = sh.header_id
         WHERE  sh.ledger_id              = bu.PRIMARY_LEDGER_ID
           AND  jl.account_combination   IS NOT NULL
           AND  ROWNUM                    = 1)
    ) AS COMPANY,
    bu.SYNC_DATE
FROM RR_GL_BUSINESS_UNITS bu
ORDER BY bu.BUSINESS_UNIT_NAME
]'
    );

    COMMIT;
END;
/
