-- ============================================================================
-- P&L Statement Template Tables
-- ============================================================================
-- Structure:
--   Template -> Groups -> Sections -> Accounts
--   With support for calculated totals and formulas
-- ============================================================================

-- ============================================================================
-- 1. RR_PL_TEMPLATES - Master table for P&L templates
-- ============================================================================
CREATE TABLE rr_pl_templates (
    template_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code       VARCHAR2(50) NOT NULL UNIQUE,
    template_name       VARCHAR2(200) NOT NULL,
    description         VARCHAR2(1000),
    template_type       VARCHAR2(50) DEFAULT 'STANDARD',  -- STANDARD, MANAGEMENT, REGULATORY, CUSTOM
    is_active           VARCHAR2(1) DEFAULT 'Y',
    is_default          VARCHAR2(1) DEFAULT 'N',
    ledger_id           NUMBER,
    currency_code       VARCHAR2(10),
    created_by          VARCHAR2(100),
    created_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR2(100),
    updated_date        TIMESTAMP,
    CONSTRAINT chk_pl_template_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_pl_template_default CHECK (is_default IN ('Y', 'N'))
);

COMMENT ON TABLE rr_pl_templates IS 'Master table for P&L statement templates';
COMMENT ON COLUMN rr_pl_templates.template_type IS 'STANDARD=Universal P&L, MANAGEMENT=Internal reporting, REGULATORY=Statutory, CUSTOM=User defined';

-- ============================================================================
-- 2. RR_PL_GROUPS - Groups within a template (Revenue, Expenses, etc.)
-- ============================================================================
CREATE TABLE rr_pl_groups (
    group_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id         NUMBER NOT NULL,
    group_code          VARCHAR2(50) NOT NULL,
    group_name          VARCHAR2(200) NOT NULL,
    group_label         VARCHAR2(200),           -- Display label (e.g., "Revenue", "Operating Expenses")
    group_type          VARCHAR2(50) NOT NULL,   -- REVENUE, EXPENSE, OTHER_INCOME, OTHER_EXPENSE, TAX, COMPREHENSIVE
    display_order       NUMBER NOT NULL,
    sign_convention     NUMBER DEFAULT 1,        -- 1 for positive (Revenue), -1 for negative (Expense)
    show_subtotal       VARCHAR2(1) DEFAULT 'Y',
    subtotal_label      VARCHAR2(200),           -- e.g., "Gross Profit", "Operating Profit"
    is_calculated       VARCHAR2(1) DEFAULT 'N', -- Y if this is a calculated row (sum of other groups)
    calculation_formula VARCHAR2(500),           -- e.g., "G1+G2" or "T1-T2"
    indent_level        NUMBER DEFAULT 0,
    font_style          VARCHAR2(50) DEFAULT 'NORMAL', -- NORMAL, BOLD, ITALIC, BOLD_ITALIC
    is_active           VARCHAR2(1) DEFAULT 'Y',
    created_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date        TIMESTAMP,
    CONSTRAINT fk_pl_group_template FOREIGN KEY (template_id) REFERENCES rr_pl_templates(template_id),
    CONSTRAINT chk_pl_group_type CHECK (group_type IN ('REVENUE', 'EXPENSE', 'OTHER_INCOME', 'OTHER_EXPENSE', 'TAX', 'COMPREHENSIVE', 'CALCULATED')),
    CONSTRAINT chk_pl_group_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT uk_pl_group UNIQUE (template_id, group_code)
);

COMMENT ON TABLE rr_pl_groups IS 'Groups within a P&L template (e.g., Revenue, Operating Expenses)';
COMMENT ON COLUMN rr_pl_groups.sign_convention IS '1 for income items (add), -1 for expense items (subtract)';
COMMENT ON COLUMN rr_pl_groups.calculation_formula IS 'Formula for calculated groups, e.g., G1-G2 or T1+T2';

-- ============================================================================
-- 3. RR_PL_SECTIONS - Sections within groups (sub-categories)
-- ============================================================================
CREATE TABLE rr_pl_sections (
    section_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id            NUMBER NOT NULL,
    section_code        VARCHAR2(50) NOT NULL,
    section_name        VARCHAR2(200) NOT NULL,
    section_label       VARCHAR2(200),           -- Display label
    display_order       NUMBER NOT NULL,
    show_subtotal       VARCHAR2(1) DEFAULT 'N',
    subtotal_label      VARCHAR2(200),
    indent_level        NUMBER DEFAULT 1,
    font_style          VARCHAR2(50) DEFAULT 'NORMAL',
    is_active           VARCHAR2(1) DEFAULT 'Y',
    created_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date        TIMESTAMP,
    CONSTRAINT fk_pl_section_group FOREIGN KEY (group_id) REFERENCES rr_pl_groups(group_id),
    CONSTRAINT chk_pl_section_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT uk_pl_section UNIQUE (group_id, section_code)
);

COMMENT ON TABLE rr_pl_sections IS 'Sections within groups (e.g., Interest Income, Dividend Income under Revenue)';

-- ============================================================================
-- 4. RR_PL_SECTION_ACCOUNTS - Accounts assigned to sections
-- ============================================================================
CREATE TABLE rr_pl_section_accounts (
    section_account_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id          NUMBER NOT NULL,
    account_code        VARCHAR2(50) NOT NULL,   -- Natural account code
    account_from        VARCHAR2(50),            -- For account range (optional)
    account_to          VARCHAR2(50),            -- For account range (optional)
    include_children    VARCHAR2(1) DEFAULT 'Y', -- Include child accounts
    display_order       NUMBER,
    is_active           VARCHAR2(1) DEFAULT 'Y',
    created_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date        TIMESTAMP,
    CONSTRAINT fk_pl_section_account FOREIGN KEY (section_id) REFERENCES rr_pl_sections(section_id),
    CONSTRAINT chk_pl_section_acct_active CHECK (is_active IN ('Y', 'N'))
);

COMMENT ON TABLE rr_pl_section_accounts IS 'Account assignments to sections - can be single account or range';
COMMENT ON COLUMN rr_pl_section_accounts.account_from IS 'Start of account range (if using range)';
COMMENT ON COLUMN rr_pl_section_accounts.account_to IS 'End of account range (if using range)';

-- ============================================================================
-- 5. RR_PL_TOTALS - Calculated total rows (Gross Profit, Net Income, etc.)
-- ============================================================================
CREATE TABLE rr_pl_totals (
    total_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id         NUMBER NOT NULL,
    total_code          VARCHAR2(50) NOT NULL,   -- e.g., T1, T2, T3
    total_name          VARCHAR2(200) NOT NULL,  -- e.g., "Gross Profit", "Net Income"
    total_label         VARCHAR2(200),
    calculation_formula VARCHAR2(500) NOT NULL,  -- e.g., "G1-G2" or "T1-G3"
    display_order       NUMBER NOT NULL,
    after_group_code    VARCHAR2(50),            -- Show this total after which group
    indent_level        NUMBER DEFAULT 0,
    font_style          VARCHAR2(50) DEFAULT 'BOLD',
    row_style           VARCHAR2(50) DEFAULT 'HIGHLIGHT', -- NORMAL, HIGHLIGHT, DOUBLE_LINE
    is_active           VARCHAR2(1) DEFAULT 'Y',
    created_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date        TIMESTAMP,
    CONSTRAINT fk_pl_total_template FOREIGN KEY (template_id) REFERENCES rr_pl_templates(template_id),
    CONSTRAINT chk_pl_total_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT uk_pl_total UNIQUE (template_id, total_code)
);

COMMENT ON TABLE rr_pl_totals IS 'Calculated totals in P&L (Gross Profit, Operating Profit, Net Income)';
COMMENT ON COLUMN rr_pl_totals.calculation_formula IS 'Formula using group codes (G1, G2) or total codes (T1, T2)';
COMMENT ON COLUMN rr_pl_totals.after_group_code IS 'Position this total after the specified group';

-- ============================================================================
-- 6. RR_PL_TEMPLATE_PERIODS - Periods configuration for templates
-- ============================================================================
CREATE TABLE rr_pl_template_periods (
    period_config_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id         NUMBER NOT NULL,
    period_type         VARCHAR2(50) NOT NULL,   -- CURRENT, PRIOR, YTD, PRIOR_YTD, BUDGET
    period_label        VARCHAR2(100),
    display_order       NUMBER NOT NULL,
    show_variance       VARCHAR2(1) DEFAULT 'N',
    show_percentage     VARCHAR2(1) DEFAULT 'N',
    is_active           VARCHAR2(1) DEFAULT 'Y',
    CONSTRAINT fk_pl_period_template FOREIGN KEY (template_id) REFERENCES rr_pl_templates(template_id)
);

COMMENT ON TABLE rr_pl_template_periods IS 'Configure which periods to show in the P&L report';

-- ============================================================================
-- Create Indexes for Performance
-- ============================================================================
CREATE INDEX idx_pl_groups_template ON rr_pl_groups(template_id);
CREATE INDEX idx_pl_sections_group ON rr_pl_sections(group_id);
CREATE INDEX idx_pl_section_accounts_section ON rr_pl_section_accounts(section_id);
CREATE INDEX idx_pl_totals_template ON rr_pl_totals(template_id);

-- ============================================================================
-- Insert Sample Standard P&L Template
-- ============================================================================

-- 1. Create the template
INSERT INTO rr_pl_templates (template_code, template_name, description, template_type, is_default)
VALUES ('STD_PL_01', 'Standard Profit & Loss Statement', 'Universal P&L format with Revenue, Expenses, and Comprehensive Income', 'STANDARD', 'Y');

-- 2. Create Groups
-- Group 1: Revenue
INSERT INTO rr_pl_groups (template_id, group_code, group_name, group_label, group_type, display_order, sign_convention, show_subtotal, subtotal_label, font_style)
SELECT template_id, 'G1', 'Revenue', 'Revenue', 'REVENUE', 10, 1, 'Y', 'Gross Profit', 'BOLD'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- Group 2: Operating Expense & Administrative Expense
INSERT INTO rr_pl_groups (template_id, group_code, group_name, group_label, group_type, display_order, sign_convention, show_subtotal, subtotal_label, font_style)
SELECT template_id, 'G2', 'Operating Expenses', 'Operating Expense & Administrative expense', 'EXPENSE', 20, -1, 'Y', 'Total Operating Expense & Administrative expense', 'BOLD'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- Group 3: Interest & Finance Charges
INSERT INTO rr_pl_groups (template_id, group_code, group_name, group_label, group_type, display_order, sign_convention, show_subtotal, subtotal_label, font_style)
SELECT template_id, 'G3', 'Interest & Finance Charges', 'Interest & finance Charges', 'EXPENSE', 40, -1, 'Y', 'Interest and Finance Charges (Total)', 'BOLD'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- Group 4: Other Comprehensive Income
INSERT INTO rr_pl_groups (template_id, group_code, group_name, group_label, group_type, display_order, sign_convention, show_subtotal, subtotal_label, font_style)
SELECT template_id, 'G4', 'Other Comprehensive Income', 'Other Comprehensive Income', 'COMPREHENSIVE', 60, 1, 'N', NULL, 'NORMAL'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- 3. Create Sections for Group 1 (Revenue)
INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G1S1', 'Income on Investment', 'Income on Investmet', 10
FROM rr_pl_groups WHERE group_code = 'G1' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G1S2', 'Interest on Deposit', 'Interest on Deposit', 20
FROM rr_pl_groups WHERE group_code = 'G1' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G1S3', 'Cost of Goods', 'Cost of Goods', 30
FROM rr_pl_groups WHERE group_code = 'G1' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

-- 4. Create Sections for Group 2 (Operating Expenses)
INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G2S1', 'Staff Cost', 'staff Cost', 10
FROM rr_pl_groups WHERE group_code = 'G2' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G2S2', 'Loss on Liquidation', 'Loss on Liquidation Subsidiary/Investment', 20
FROM rr_pl_groups WHERE group_code = 'G2' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G2S3', 'Depreciations', 'Depreciations', 30
FROM rr_pl_groups WHERE group_code = 'G2' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G2S4', 'Administrative Expenses', 'Administrative Expenses', 40
FROM rr_pl_groups WHERE group_code = 'G2' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

-- 5. Create Sections for Group 3 (Interest & Finance)
INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G3S1', 'Interest Expenses Bank', 'Interest Expenses (Bank)', 10
FROM rr_pl_groups WHERE group_code = 'G3' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G3S2', 'Interest Expenses Lease', 'Interest Expenses (lease liability)', 20
FROM rr_pl_groups WHERE group_code = 'G3' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G3S3', 'Fair Value Change', 'Fair Value change in investments', 30
FROM rr_pl_groups WHERE group_code = 'G3' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

-- 6. Create Sections for Group 4 (Other Comprehensive Income)
INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
SELECT group_id, 'G4S1', 'Other Comprehensive Income', 'other Comprehensive Income', 10
FROM rr_pl_groups WHERE group_code = 'G4' AND template_id = (SELECT template_id FROM rr_pl_templates WHERE template_code = 'STD_PL_01');

-- 7. Create Totals
-- T1: Gross Profit (after Revenue)
INSERT INTO rr_pl_totals (template_id, total_code, total_name, total_label, calculation_formula, display_order, after_group_code, font_style, row_style)
SELECT template_id, 'T1', 'Gross Profit', 'Gross Profit', 'G1', 15, 'G1', 'BOLD', 'HIGHLIGHT'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- T2: Profit/(Loss) from Operations (G1 - G2)
INSERT INTO rr_pl_totals (template_id, total_code, total_name, total_label, calculation_formula, display_order, after_group_code, font_style, row_style)
SELECT template_id, 'T2', 'Profit from Operations', 'Profit / (loss) from operations', 'G1+G2', 25, 'G2', 'BOLD', 'HIGHLIGHT'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- T3: Interest & Finance Total
INSERT INTO rr_pl_totals (template_id, total_code, total_name, total_label, calculation_formula, display_order, after_group_code, font_style, row_style)
SELECT template_id, 'T3', 'Interest and Finance Total', 'Interest and Finance Charges (Total)', 'G3', 45, 'G3', 'BOLD', 'NORMAL'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- T4: Profit/(Loss) for the Year (T2 + T3)
INSERT INTO rr_pl_totals (template_id, total_code, total_name, total_label, calculation_formula, display_order, after_group_code, font_style, row_style)
SELECT template_id, 'T4', 'Profit for the Year', 'Profit ( Loss) for theYear', 'T2+T3', 50, 'G3', 'BOLD', 'HIGHLIGHT'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- T5: Total Comprehensive Income (T4 + G4)
INSERT INTO rr_pl_totals (template_id, total_code, total_name, total_label, calculation_formula, display_order, after_group_code, font_style, row_style)
SELECT template_id, 'T5', 'Total Comprehensive Income', 'Total Comprehensive Income', 'T4+G4', 70, 'G4', 'BOLD', 'DOUBLE_LINE'
FROM rr_pl_templates WHERE template_code = 'STD_PL_01';

-- 8. Sample Account Assignments (you would populate these with actual account codes)
-- Example: Assign account 4100000 to Revenue > Income on Investment
-- INSERT INTO rr_pl_section_accounts (section_id, account_code, display_order)
-- SELECT section_id, '4100000', 10
-- FROM rr_pl_sections WHERE section_code = 'G1S1';

COMMIT;

-- ============================================================================
-- Package for P&L Template Management
-- ============================================================================
CREATE OR REPLACE PACKAGE rr_pl_template_pkg AS

    -- Get template structure as JSON
    FUNCTION get_template_structure(p_template_id NUMBER) RETURN CLOB;

    -- Get template list
    FUNCTION get_templates RETURN CLOB;

    -- Create new template
    PROCEDURE create_template(
        p_template_code VARCHAR2,
        p_template_name VARCHAR2,
        p_description VARCHAR2 DEFAULT NULL,
        p_template_type VARCHAR2 DEFAULT 'CUSTOM',
        p_template_id OUT NUMBER
    );

    -- Add group to template
    PROCEDURE add_group(
        p_template_id NUMBER,
        p_group_code VARCHAR2,
        p_group_name VARCHAR2,
        p_group_label VARCHAR2,
        p_group_type VARCHAR2,
        p_display_order NUMBER,
        p_sign_convention NUMBER DEFAULT 1,
        p_group_id OUT NUMBER
    );

    -- Add section to group
    PROCEDURE add_section(
        p_group_id NUMBER,
        p_section_code VARCHAR2,
        p_section_name VARCHAR2,
        p_section_label VARCHAR2,
        p_display_order NUMBER,
        p_section_id OUT NUMBER
    );

    -- Assign account to section
    PROCEDURE assign_account(
        p_section_id NUMBER,
        p_account_code VARCHAR2,
        p_account_from VARCHAR2 DEFAULT NULL,
        p_account_to VARCHAR2 DEFAULT NULL
    );

    -- Add total/calculated row
    PROCEDURE add_total(
        p_template_id NUMBER,
        p_total_code VARCHAR2,
        p_total_name VARCHAR2,
        p_calculation_formula VARCHAR2,
        p_display_order NUMBER,
        p_after_group_code VARCHAR2 DEFAULT NULL
    );

    -- Clone template
    PROCEDURE clone_template(
        p_source_template_id NUMBER,
        p_new_template_code VARCHAR2,
        p_new_template_name VARCHAR2,
        p_new_template_id OUT NUMBER
    );

END rr_pl_template_pkg;
/

CREATE OR REPLACE PACKAGE BODY rr_pl_template_pkg AS

    -- Helper function to escape JSON string values
    FUNCTION escape_json(p_str IN VARCHAR2) RETURN VARCHAR2
    IS
        v_result VARCHAR2(4000);
    BEGIN
        IF p_str IS NULL THEN
            RETURN 'null';
        END IF;
        v_result := p_str;
        v_result := REPLACE(v_result, CHR(92), CHR(92) || CHR(92));
        v_result := REPLACE(v_result, CHR(34), CHR(92) || CHR(34));
        v_result := REPLACE(v_result, CHR(10), CHR(92) || 'n');
        v_result := REPLACE(v_result, CHR(13), CHR(92) || 'r');
        v_result := REPLACE(v_result, CHR(9), CHR(92) || 't');
        RETURN CHR(34) || v_result || CHR(34);
    END escape_json;

    -- Get template structure as JSON
    FUNCTION get_template_structure(p_template_id IN NUMBER) RETURN CLOB
    IS
        v_result CLOB;
        v_groups CLOB;
        v_sections CLOB;
        v_accounts CLOB;
        v_totals CLOB;
        v_first_group BOOLEAN := TRUE;
        v_first_section BOOLEAN;
        v_first_account BOOLEAN;
        v_first_total BOOLEAN;
        v_template_code VARCHAR2(50);
        v_template_name VARCHAR2(200);
        v_description VARCHAR2(1000);
        v_template_type VARCHAR2(50);
        v_is_default VARCHAR2(1);
        v_count NUMBER;
    BEGIN
        -- Check if template exists
        SELECT COUNT(*) INTO v_count
        FROM rr_pl_templates
        WHERE template_id = p_template_id AND is_active = 'Y';

        IF v_count = 0 THEN
            RETURN '{"error":"Template not found","template_id":' || p_template_id || '}';
        END IF;

        -- Get template info
        SELECT template_code, template_name, description, template_type, is_default
        INTO v_template_code, v_template_name, v_description, v_template_type, v_is_default
        FROM rr_pl_templates
        WHERE template_id = p_template_id;

        -- Build groups array
        v_groups := '[';
        FOR grp IN (
            SELECT group_id, group_code, group_name, group_label, group_type,
                   display_order, sign_convention, show_subtotal, subtotal_label
            FROM rr_pl_groups
            WHERE template_id = p_template_id AND is_active = 'Y'
            ORDER BY display_order
        ) LOOP
            IF NOT v_first_group THEN
                v_groups := v_groups || ',';
            END IF;
            v_first_group := FALSE;

            -- Build sections for this group
            v_sections := '[';
            v_first_section := TRUE;
            FOR sec IN (
                SELECT section_id, section_code, section_name, section_label, display_order
                FROM rr_pl_sections
                WHERE group_id = grp.group_id AND is_active = 'Y'
                ORDER BY display_order
            ) LOOP
                IF NOT v_first_section THEN
                    v_sections := v_sections || ',';
                END IF;
                v_first_section := FALSE;

                -- Build accounts for this section
                v_accounts := '[';
                v_first_account := TRUE;
                FOR acct IN (
                    SELECT account_code, account_from, account_to
                    FROM rr_pl_section_accounts
                    WHERE section_id = sec.section_id AND is_active = 'Y'
                    ORDER BY display_order
                ) LOOP
                    IF NOT v_first_account THEN
                        v_accounts := v_accounts || ',';
                    END IF;
                    v_first_account := FALSE;

                    v_accounts := v_accounts || '{' ||
                        '"account_code":' || escape_json(acct.account_code) || ',' ||
                        '"account_from":' || escape_json(acct.account_from) || ',' ||
                        '"account_to":' || escape_json(acct.account_to) ||
                    '}';
                END LOOP;
                v_accounts := v_accounts || ']';

                v_sections := v_sections || '{' ||
                    '"section_id":' || sec.section_id || ',' ||
                    '"section_code":' || escape_json(sec.section_code) || ',' ||
                    '"section_name":' || escape_json(sec.section_name) || ',' ||
                    '"section_label":' || escape_json(sec.section_label) || ',' ||
                    '"display_order":' || sec.display_order || ',' ||
                    '"accounts":' || v_accounts ||
                '}';
            END LOOP;
            v_sections := v_sections || ']';

            v_groups := v_groups || '{' ||
                '"group_id":' || grp.group_id || ',' ||
                '"group_code":' || escape_json(grp.group_code) || ',' ||
                '"group_name":' || escape_json(grp.group_name) || ',' ||
                '"group_label":' || escape_json(grp.group_label) || ',' ||
                '"group_type":' || escape_json(grp.group_type) || ',' ||
                '"display_order":' || grp.display_order || ',' ||
                '"sign_convention":' || grp.sign_convention || ',' ||
                '"show_subtotal":' || escape_json(grp.show_subtotal) || ',' ||
                '"subtotal_label":' || escape_json(grp.subtotal_label) || ',' ||
                '"sections":' || v_sections ||
            '}';
        END LOOP;
        v_groups := v_groups || ']';

        -- Build totals array
        v_totals := '[';
        v_first_total := TRUE;
        FOR tot IN (
            SELECT total_id, total_code, total_name, total_label, calculation_formula,
                   display_order, after_group_code, font_style, row_style
            FROM rr_pl_totals
            WHERE template_id = p_template_id AND is_active = 'Y'
            ORDER BY display_order
        ) LOOP
            IF NOT v_first_total THEN
                v_totals := v_totals || ',';
            END IF;
            v_first_total := FALSE;

            v_totals := v_totals || '{' ||
                '"total_id":' || tot.total_id || ',' ||
                '"total_code":' || escape_json(tot.total_code) || ',' ||
                '"total_name":' || escape_json(tot.total_name) || ',' ||
                '"total_label":' || escape_json(tot.total_label) || ',' ||
                '"calculation_formula":' || escape_json(tot.calculation_formula) || ',' ||
                '"display_order":' || tot.display_order || ',' ||
                '"after_group_code":' || escape_json(tot.after_group_code) || ',' ||
                '"font_style":' || escape_json(tot.font_style) || ',' ||
                '"row_style":' || escape_json(tot.row_style) ||
            '}';
        END LOOP;
        v_totals := v_totals || ']';

        -- Build final result
        v_result := '{"template":{' ||
            '"template_id":' || p_template_id || ',' ||
            '"template_code":' || escape_json(v_template_code) || ',' ||
            '"template_name":' || escape_json(v_template_name) || ',' ||
            '"description":' || escape_json(v_description) || ',' ||
            '"template_type":' || escape_json(v_template_type) || ',' ||
            '"is_default":' || escape_json(v_is_default) || ',' ||
            '"groups":' || v_groups || ',' ||
            '"totals":' || v_totals ||
        '}}';

        RETURN v_result;
    END get_template_structure;

    -- Get template list
    FUNCTION get_templates RETURN CLOB
    IS
        v_result CLOB;
        v_first BOOLEAN := TRUE;
    BEGIN
        v_result := '{"templates":[';

        FOR t IN (
            SELECT template_id, template_code, template_name, description,
                   template_type, is_active, is_default, created_date
            FROM rr_pl_templates
            WHERE is_active = 'Y'
            ORDER BY template_name
        ) LOOP
            IF NOT v_first THEN
                v_result := v_result || ',';
            END IF;
            v_first := FALSE;

            v_result := v_result || '{' ||
                '"template_id":' || t.template_id || ',' ||
                '"template_code":' || escape_json(t.template_code) || ',' ||
                '"template_name":' || escape_json(t.template_name) || ',' ||
                '"description":' || escape_json(t.description) || ',' ||
                '"template_type":' || escape_json(t.template_type) || ',' ||
                '"is_active":' || escape_json(t.is_active) || ',' ||
                '"is_default":' || escape_json(t.is_default) || ',' ||
                '"created_date":' || escape_json(TO_CHAR(t.created_date, 'YYYY-MM-DD HH24:MI:SS')) ||
            '}';
        END LOOP;

        v_result := v_result || ']}';
        RETURN v_result;
    END get_templates;

    -- Create new template
    PROCEDURE create_template(
        p_template_code VARCHAR2,
        p_template_name VARCHAR2,
        p_description VARCHAR2 DEFAULT NULL,
        p_template_type VARCHAR2 DEFAULT 'CUSTOM',
        p_template_id OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO rr_pl_templates (template_code, template_name, description, template_type)
        VALUES (p_template_code, p_template_name, p_description, p_template_type)
        RETURNING template_id INTO p_template_id;

        COMMIT;
    END create_template;

    -- Add group to template
    PROCEDURE add_group(
        p_template_id NUMBER,
        p_group_code VARCHAR2,
        p_group_name VARCHAR2,
        p_group_label VARCHAR2,
        p_group_type VARCHAR2,
        p_display_order NUMBER,
        p_sign_convention NUMBER DEFAULT 1,
        p_group_id OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO rr_pl_groups (template_id, group_code, group_name, group_label, group_type, display_order, sign_convention)
        VALUES (p_template_id, p_group_code, p_group_name, p_group_label, p_group_type, p_display_order, p_sign_convention)
        RETURNING group_id INTO p_group_id;

        COMMIT;
    END add_group;

    -- Add section to group
    PROCEDURE add_section(
        p_group_id NUMBER,
        p_section_code VARCHAR2,
        p_section_name VARCHAR2,
        p_section_label VARCHAR2,
        p_display_order NUMBER,
        p_section_id OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order)
        VALUES (p_group_id, p_section_code, p_section_name, p_section_label, p_display_order)
        RETURNING section_id INTO p_section_id;

        COMMIT;
    END add_section;

    -- Assign account to section
    PROCEDURE assign_account(
        p_section_id NUMBER,
        p_account_code VARCHAR2,
        p_account_from VARCHAR2 DEFAULT NULL,
        p_account_to VARCHAR2 DEFAULT NULL
    ) IS
        v_max_order NUMBER;
    BEGIN
        SELECT NVL(MAX(display_order), 0) + 10 INTO v_max_order
        FROM rr_pl_section_accounts
        WHERE section_id = p_section_id;

        INSERT INTO rr_pl_section_accounts (section_id, account_code, account_from, account_to, display_order)
        VALUES (p_section_id, p_account_code, p_account_from, p_account_to, v_max_order);

        COMMIT;
    END assign_account;

    -- Add total/calculated row
    PROCEDURE add_total(
        p_template_id NUMBER,
        p_total_code VARCHAR2,
        p_total_name VARCHAR2,
        p_calculation_formula VARCHAR2,
        p_display_order NUMBER,
        p_after_group_code VARCHAR2 DEFAULT NULL
    ) IS
    BEGIN
        INSERT INTO rr_pl_totals (template_id, total_code, total_name, total_label, calculation_formula, display_order, after_group_code)
        VALUES (p_template_id, p_total_code, p_total_name, p_total_name, p_calculation_formula, p_display_order, p_after_group_code);

        COMMIT;
    END add_total;

    -- Clone template
    PROCEDURE clone_template(
        p_source_template_id NUMBER,
        p_new_template_code VARCHAR2,
        p_new_template_name VARCHAR2,
        p_new_template_id OUT NUMBER
    ) IS
        v_new_group_id NUMBER;
        v_new_section_id NUMBER;
        v_description VARCHAR2(1000);
        v_ledger_id NUMBER;
        v_currency_code VARCHAR2(10);
    BEGIN
        -- Get source template info
        SELECT description, ledger_id, currency_code
        INTO v_description, v_ledger_id, v_currency_code
        FROM rr_pl_templates
        WHERE template_id = p_source_template_id;

        -- Clone template
        INSERT INTO rr_pl_templates (template_code, template_name, description, template_type, ledger_id, currency_code)
        VALUES (p_new_template_code, p_new_template_name, v_description, 'CUSTOM', v_ledger_id, v_currency_code)
        RETURNING template_id INTO p_new_template_id;

        -- Clone groups
        FOR grp IN (SELECT * FROM rr_pl_groups WHERE template_id = p_source_template_id AND is_active = 'Y') LOOP
            INSERT INTO rr_pl_groups (template_id, group_code, group_name, group_label, group_type, display_order,
                sign_convention, show_subtotal, subtotal_label, is_calculated, calculation_formula, indent_level, font_style)
            VALUES (p_new_template_id, grp.group_code, grp.group_name, grp.group_label, grp.group_type, grp.display_order,
                grp.sign_convention, grp.show_subtotal, grp.subtotal_label, grp.is_calculated, grp.calculation_formula, grp.indent_level, grp.font_style)
            RETURNING group_id INTO v_new_group_id;

            -- Clone sections
            FOR sec IN (SELECT * FROM rr_pl_sections WHERE group_id = grp.group_id AND is_active = 'Y') LOOP
                INSERT INTO rr_pl_sections (group_id, section_code, section_name, section_label, display_order,
                    show_subtotal, subtotal_label, indent_level, font_style)
                VALUES (v_new_group_id, sec.section_code, sec.section_name, sec.section_label, sec.display_order,
                    sec.show_subtotal, sec.subtotal_label, sec.indent_level, sec.font_style)
                RETURNING section_id INTO v_new_section_id;

                -- Clone account assignments
                INSERT INTO rr_pl_section_accounts (section_id, account_code, account_from, account_to, include_children, display_order)
                SELECT v_new_section_id, account_code, account_from, account_to, include_children, display_order
                FROM rr_pl_section_accounts
                WHERE section_id = sec.section_id AND is_active = 'Y';
            END LOOP;
        END LOOP;

        -- Clone totals
        INSERT INTO rr_pl_totals (template_id, total_code, total_name, total_label, calculation_formula,
            display_order, after_group_code, indent_level, font_style, row_style)
        SELECT p_new_template_id, total_code, total_name, total_label, calculation_formula,
            display_order, after_group_code, indent_level, font_style, row_style
        FROM rr_pl_totals
        WHERE template_id = p_source_template_id AND is_active = 'Y';

        COMMIT;
    END clone_template;

END rr_pl_template_pkg;
/
