-- =============================================================================
-- PATCH 06: Email Reply Processing for Approval Engine
--
-- Flow:
--   1. ERP sends approval email → approver clicks APPROVE/REJECT (mailto: link)
--   2. Reply arrives at monitored inbox → Brevo Inbound webhook POSTs here
--   3. Handler parses action (APPROVE/REJECT) and stores in RR_APPROVAL_EMAIL_REPLIES
--   4. Frontend reads GET approvals/email-replies and processes them
--
-- HOW TO RUN:
--   APEX SQL Workshop → SQL Commands — run each BEGIN...END; block separately
-- =============================================================================

-- ── Step 1: Create RR_APPROVAL_EMAIL_REPLIES table ────────────────────────────
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE RR_APPROVAL_EMAIL_REPLIES (
            REPLY_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            FROM_EMAIL       VARCHAR2(500),
            FROM_NAME        VARCHAR2(300),
            SUBJECT          VARCHAR2(1000),
            BODY_TEXT        VARCHAR2(4000),
            ACTION_DETECTED  VARCHAR2(10)   DEFAULT 'UNKNOWN',
            REF_NUMBER       VARCHAR2(200),
            REQUEST_ID       NUMBER,
            STATUS           VARCHAR2(20)   DEFAULT 'PENDING',
            RECEIVED_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP,
            PROCESSED_DATE   TIMESTAMP,
            PROCESSED_BY     VARCHAR2(200),
            NOTES            VARCHAR2(1000)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF; -- ORA-00955: table already exists
END;
/

-- ── Step 2: POST approvals/email-reply  (Brevo Inbound webhook) ───────────────
-- Configure this URL in Brevo Dashboard → Inbound Email → Webhook URL:
--   https://g15d6279501ae08-buimerc.adb.me-dubai-1.oraclecloudapps.com/ords/bcldifc/reerp/approvals/email-reply
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'approvals/email-reply',
            p_method      => 'POST'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'approvals/email-reply',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_body      CLOB    := :body_text;
    v_from_email VARCHAR2(500);
    v_from_name  VARCHAR2(300);
    v_subject    VARCHAR2(1000);
    v_text       VARCHAR2(4000);
    v_action     VARCHAR2(10);
    v_ref        VARCHAR2(200);
    v_req_id     NUMBER;
BEGIN
    -- Brevo inbound JSON structure: {"From":{"Address":"...","Name":"..."},"Subject":"...","Text-part":"..."}
    SELECT jt.from_email, jt.from_name, jt.subject, SUBSTR(jt.body_text, 1, 4000)
    INTO   v_from_email, v_from_name, v_subject, v_text
    FROM   JSON_TABLE(v_body, '$'
             COLUMNS (
               from_email VARCHAR2(500)  PATH '$.From.Address',
               from_name  VARCHAR2(300)  PATH '$.From.Name',
               subject    VARCHAR2(1000) PATH '$.Subject',
               body_text  VARCHAR2(4000) PATH '$."Text-part"'
             )
           ) jt;

    -- Detect action from subject or body (first word)
    v_action := CASE
        WHEN UPPER(SUBSTR(TRIM(v_subject), 1, 7)) = 'APPROVE'
          OR UPPER(SUBSTR(TRIM(v_text),    1, 7)) = 'APPROVE' THEN 'APPROVE'
        WHEN UPPER(SUBSTR(TRIM(v_subject), 1, 6)) = 'REJECT'
          OR UPPER(SUBSTR(TRIM(v_text),    1, 6)) = 'REJECT'  THEN 'REJECT'
        ELSE 'UNKNOWN'
    END;

    -- Extract reference from subject  e.g. "APPROVE: INV-2024-001 [ERP]"
    BEGIN
        SELECT REGEXP_SUBSTR(v_subject, '[A-Z0-9]+-[A-Z0-9-]+', 1, 1)
        INTO   v_ref
        FROM   DUAL;
    EXCEPTION WHEN OTHERS THEN v_ref := NULL;
    END;

    -- Try to match to an open approval request by ref
    BEGIN
        SELECT REQUEST_ID INTO v_req_id
        FROM   RR_APPROVAL_REQUESTS
        WHERE  (TRANSACTION_REF = v_ref OR DESCRIPTION LIKE '%' || v_ref || '%')
        AND    STATUS = 'PENDING'
        FETCH  FIRST 1 ROWS ONLY;
    EXCEPTION WHEN OTHERS THEN v_req_id := NULL;
    END;

    INSERT INTO RR_APPROVAL_EMAIL_REPLIES (
        FROM_EMAIL, FROM_NAME, SUBJECT, BODY_TEXT,
        ACTION_DETECTED, REF_NUMBER, REQUEST_ID, STATUS
    ) VALUES (
        v_from_email, v_from_name, v_subject, v_text,
        v_action, v_ref, v_req_id, 'PENDING'
    );

    COMMIT;
    :status_code := 200;
    HTP.P('{"status":"SUCCESS","action":"' || v_action || '"}');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 200; -- always 200 to Brevo so it doesn't retry
        HTP.P('{"status":"ERROR","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── Step 3: GET approvals/email-replies  (frontend poll) ─────────────────────
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'approvals/email-replies',
            p_method      => 'GET'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'approvals/email-replies',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_clob  CLOB;
    v_first BOOLEAN := TRUE;
BEGIN
    DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
    DBMS_LOB.APPEND(v_clob, '{"items":[');

    FOR r IN (
        SELECT REPLY_ID, FROM_EMAIL, FROM_NAME, SUBJECT, BODY_TEXT,
               ACTION_DETECTED, REF_NUMBER, REQUEST_ID, STATUS,
               TO_CHAR(RECEIVED_DATE,  'YYYY-MM-DD"T"HH24:MI:SS') AS RECEIVED_DATE,
               TO_CHAR(PROCESSED_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS PROCESSED_DATE,
               PROCESSED_BY, NOTES
        FROM   RR_APPROVAL_EMAIL_REPLIES
        ORDER  BY RECEIVED_DATE DESC
        FETCH  FIRST 100 ROWS ONLY
    ) LOOP
        IF NOT v_first THEN DBMS_LOB.APPEND(v_clob, ','); END IF;
        v_first := FALSE;
        DBMS_LOB.APPEND(v_clob,
            '{"replyId":'          || r.REPLY_ID ||
            ',"fromEmail":'        || APEX_JSON.STRINGIFY(NVL(r.FROM_EMAIL,''))    ||
            ',"fromName":'         || APEX_JSON.STRINGIFY(NVL(r.FROM_NAME,''))     ||
            ',"subject":'          || APEX_JSON.STRINGIFY(NVL(r.SUBJECT,''))       ||
            ',"bodyText":'         || APEX_JSON.STRINGIFY(NVL(r.BODY_TEXT,''))     ||
            ',"actionDetected":'   || APEX_JSON.STRINGIFY(NVL(r.ACTION_DETECTED,'UNKNOWN')) ||
            ',"refNumber":'        || APEX_JSON.STRINGIFY(NVL(r.REF_NUMBER,''))    ||
            ',"requestId":'        || NVL(TO_CHAR(r.REQUEST_ID),'null')            ||
            ',"status":'           || APEX_JSON.STRINGIFY(NVL(r.STATUS,'PENDING')) ||
            ',"receivedDate":'     || APEX_JSON.STRINGIFY(NVL(r.RECEIVED_DATE,'')) ||
            ',"processedDate":'    || APEX_JSON.STRINGIFY(NVL(r.PROCESSED_DATE,'')) ||
            ',"processedBy":'      || APEX_JSON.STRINGIFY(NVL(r.PROCESSED_BY,''))  ||
            ',"notes":'            || APEX_JSON.STRINGIFY(NVL(r.NOTES,''))         ||
            '}'
        );
    END LOOP;

    DBMS_LOB.APPEND(v_clob, ']}');
    HTP.P(v_clob);
    DBMS_LOB.FREETEMPORARY(v_clob);
EXCEPTION
    WHEN OTHERS THEN
        HTP.P('{"items":[],"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── Step 4: PUT approvals/email-replies/:id/process  (mark processed) ─────────
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'approvals/email-replies/:id/process',
            p_method      => 'PUT'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'approvals/email-replies/:id/process',
        p_method         => 'PUT',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_body   CLOB    := :body_text;
    v_action VARCHAR2(10);
    v_notes  VARCHAR2(1000);
    v_req_id NUMBER;
    v_cnt    NUMBER;
BEGIN
    SELECT jt.action, jt.notes, jt.request_id
    INTO   v_action, v_notes, v_req_id
    FROM   JSON_TABLE(v_body, '$'
             COLUMNS (
               action     VARCHAR2(10)   PATH '$.action',
               notes      VARCHAR2(1000) PATH '$.notes',
               request_id NUMBER         PATH '$.requestId'
             )
           ) jt;

    UPDATE RR_APPROVAL_EMAIL_REPLIES
    SET    STATUS         = 'PROCESSED',
           PROCESSED_DATE = SYSTIMESTAMP,
           PROCESSED_BY   = SYS_CONTEXT('APEX$SESSION','APP_USER'),
           NOTES          = v_notes
    WHERE  REPLY_ID = :id;

    v_cnt := SQL%ROWCOUNT;

    -- [PLACEHOLDER] When AP approval webservice is ready, call it here:
    -- IF v_action = 'APPROVE' THEN
    --     AP_APPROVAL_PKG.APPROVE_INVOICE(p_request_id => v_req_id, p_notes => v_notes);
    -- ELSIF v_action = 'REJECT' THEN
    --     AP_APPROVAL_PKG.REJECT_INVOICE(p_request_id => v_req_id, p_notes => v_notes);
    -- END IF;

    COMMIT;

    IF v_cnt = 0 THEN
        :status_code := 404;
        HTP.P('{"status":"ERROR","message":"Reply not found"}');
    ELSE
        :status_code := 200;
        HTP.P('{"status":"SUCCESS","message":"Reply processed as ' || NVL(v_action,'') || '"}');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P('{"status":"ERROR","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── Step 5: POST approvals/email-replies/simulate  (test without real inbox) ──
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'approvals/email-replies/simulate',
            p_method      => 'POST'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'approvals/email-replies/simulate',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_body      CLOB    := :body_text;
    v_action    VARCHAR2(10);
    v_ref       VARCHAR2(200);
    v_from_email VARCHAR2(500);
    v_from_name  VARCHAR2(300);
    v_new_id    NUMBER;
BEGIN
    SELECT jt.action, jt.ref_number, jt.from_email, jt.from_name
    INTO   v_action, v_ref, v_from_email, v_from_name
    FROM   JSON_TABLE(v_body, '$'
             COLUMNS (
               action     VARCHAR2(10)  PATH '$.action',
               ref_number VARCHAR2(200) PATH '$.refNumber',
               from_email VARCHAR2(500) PATH '$.fromEmail',
               from_name  VARCHAR2(300) PATH '$.fromName'
             )
           ) jt;

    INSERT INTO RR_APPROVAL_EMAIL_REPLIES (
        FROM_EMAIL, FROM_NAME, SUBJECT, BODY_TEXT,
        ACTION_DETECTED, REF_NUMBER, STATUS
    ) VALUES (
        NVL(v_from_email, 'approver@test.com'),
        NVL(v_from_name,  'Test Approver'),
        v_action || ': ' || v_ref || ' [ERP]',
        v_action || CHR(10) || CHR(10) || 'Reference: ' || v_ref,
        v_action,
        v_ref,
        'PENDING'
    ) RETURNING REPLY_ID INTO v_new_id;

    COMMIT;
    :status_code := 201;
    HTP.P('{"status":"SUCCESS","replyId":' || v_new_id || '}');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P('{"status":"ERROR","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/
