-- =============================================================================
-- PATCH 07: One-time approval tokens — secure email approval links
--
-- Flow:
--   1. ERP sends email → generates 2 tokens (APPROVE + REJECT) in this table
--   2. Buttons in email → https://erp-approval.reerperp.workers.dev?token=TOKEN
--   3. Cloudflare Worker proxies to GET approvals/approve?token=TOKEN (this handler)
--   4. Handler validates token → marks USED → records in RR_APPROVAL_EMAIL_REPLIES
--   5. Returns branded HTML confirmation page to browser
--
-- HOW TO RUN:
--   APEX SQL Workshop → SQL Commands — run each block separately
-- =============================================================================

-- ── Step 1: Create RR_APPROVAL_TOKENS table ───────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE RR_APPROVAL_TOKENS (
            TOKEN_ID      NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TOKEN_VALUE   VARCHAR2(128)  NOT NULL UNIQUE,
            ACTION        VARCHAR2(10)   NOT NULL,
            REQUEST_REF   VARCHAR2(200),
            REQUEST_ID    NUMBER,
            TO_EMAIL      VARCHAR2(500),
            TO_NAME       VARCHAR2(300),
            STATUS        VARCHAR2(20)   DEFAULT 'PENDING',
            CREATED_DATE  TIMESTAMP      DEFAULT SYSTIMESTAMP,
            EXPIRES_DATE  TIMESTAMP,
            USED_DATE     TIMESTAMP
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── Step 2: POST approvals/tokens — generate APPROVE + REJECT token pair ──────
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'approvals/tokens',
            p_method      => 'POST'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'approvals/tokens',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_body       CLOB    := :body_text;
    v_ref        VARCHAR2(200);
    v_req_id     NUMBER;
    v_to_email   VARCHAR2(500);
    v_to_name    VARCHAR2(300);
    v_tok_app    VARCHAR2(128);
    v_tok_rej    VARCHAR2(128);
    v_expires    TIMESTAMP := SYSTIMESTAMP + INTERVAL '72' HOUR;
BEGIN
    SELECT jt.request_ref, jt.request_id, jt.to_email, jt.to_name
    INTO   v_ref, v_req_id, v_to_email, v_to_name
    FROM   JSON_TABLE(v_body, '$'
             COLUMNS (
               request_ref VARCHAR2(200) PATH '$.requestRef',
               request_id  NUMBER        PATH '$.requestId',
               to_email    VARCHAR2(500) PATH '$.toEmail',
               to_name     VARCHAR2(300) PATH '$.toName'
             )
           ) jt;

    -- Generate 64-char hex tokens (two SYS_GUIDs concatenated — no special grants needed)
    v_tok_app := LOWER(RAWTOHEX(SYS_GUID())) || LOWER(RAWTOHEX(SYS_GUID()));
    v_tok_rej := LOWER(RAWTOHEX(SYS_GUID())) || LOWER(RAWTOHEX(SYS_GUID()));

    INSERT INTO RR_APPROVAL_TOKENS
        (TOKEN_VALUE, ACTION, REQUEST_REF, REQUEST_ID, TO_EMAIL, TO_NAME, EXPIRES_DATE)
    VALUES
        (v_tok_app, 'APPROVE', v_ref, v_req_id, v_to_email, v_to_name, v_expires);

    INSERT INTO RR_APPROVAL_TOKENS
        (TOKEN_VALUE, ACTION, REQUEST_REF, REQUEST_ID, TO_EMAIL, TO_NAME, EXPIRES_DATE)
    VALUES
        (v_tok_rej, 'REJECT', v_ref, v_req_id, v_to_email, v_to_name, v_expires);

    COMMIT;
    :status_code := 201;
    HTP.P('{"status":"SUCCESS","approveToken":"' || v_tok_app || '","rejectToken":"' || v_tok_rej || '"}');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P('{"status":"ERROR","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- ── Step 3: GET approvals/approve — validate token, return HTML page ──────────
BEGIN
    BEGIN
        ORDS.DELETE_HANDLER(
            p_module_name => 'reerp',
            p_pattern     => 'approvals/approve',
            p_method      => 'GET'
        );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'reerp',
        p_pattern        => 'approvals/approve',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_source         => q'[
DECLARE
    v_token    VARCHAR2(128) := :token;
    v_action   VARCHAR2(10);
    v_ref      VARCHAR2(200);
    v_name     VARCHAR2(300);
    v_email    VARCHAR2(500);
    v_req_id   NUMBER;
    v_expires  TIMESTAMP;
    v_status   VARCHAR2(20);
    v_title    VARCHAR2(100);
    v_color    VARCHAR2(20);
    v_icon     VARCHAR2(10);
    v_msg      VARCHAR2(500);
BEGIN
    IF v_token IS NULL THEN
        :status_code := 400;
        HTP.P('<html><body style="font-family:Arial;text-align:center;padding:60px"><h2>Invalid Link</h2><p>This approval link is invalid.</p></body></html>');
        RETURN;
    END IF;

    -- Look up token
    BEGIN
        SELECT ACTION, REQUEST_REF, TO_NAME, TO_EMAIL, REQUEST_ID, EXPIRES_DATE, STATUS
        INTO   v_action, v_ref, v_name, v_email, v_req_id, v_expires, v_status
        FROM   RR_APPROVAL_TOKENS
        WHERE  TOKEN_VALUE = v_token;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            :status_code := 200;
            HTP.P('<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invalid Link</title></head>'
               || '<body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;">'
               || '<div style="background:#fff;border-radius:12px;padding:48px 40px;text-align:center;max-width:440px;box-shadow:0 4px 20px rgba(0,0,0,0.10);">'
               || '<div style="font-size:48px;margin-bottom:16px;">&#10060;</div>'
               || '<h2 style="margin:0 0 12px;color:#1a1a1a;font-size:22px;">Invalid Link</h2>'
               || '<p style="color:#666;font-size:14px;line-height:1.6;">This approval link does not exist or has already been removed.</p>'
               || '</div></body></html>');
            RETURN;
    END;

    -- Already used?
    IF v_status = 'USED' THEN
        :status_code := 200;
        HTP.P('<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Already Used</title></head>'
           || '<body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;">'
           || '<div style="background:#fff;border-radius:12px;padding:48px 40px;text-align:center;max-width:440px;box-shadow:0 4px 20px rgba(0,0,0,0.10);">'
           || '<div style="font-size:48px;margin-bottom:16px;">&#9888;&#65039;</div>'
           || '<h2 style="margin:0 0 12px;color:#1a1a1a;font-size:22px;">Link Already Used</h2>'
           || '<p style="color:#666;font-size:14px;line-height:1.6;">This approval link has already been used.<br>Your action was recorded.</p>'
           || '<p style="color:#aaa;font-size:12px;margin-top:24px;">You may close this tab.</p>'
           || '</div></body></html>');
        RETURN;
    END IF;

    -- Expired?
    IF SYSTIMESTAMP > v_expires THEN
        UPDATE RR_APPROVAL_TOKENS SET STATUS = 'EXPIRED' WHERE TOKEN_VALUE = v_token;
        COMMIT;
        :status_code := 200;
        HTP.P('<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Link Expired</title></head>'
           || '<body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;">'
           || '<div style="background:#fff;border-radius:12px;padding:48px 40px;text-align:center;max-width:440px;box-shadow:0 4px 20px rgba(0,0,0,0.10);">'
           || '<div style="font-size:48px;margin-bottom:16px;">&#8987;</div>'
           || '<h2 style="margin:0 0 12px;color:#1a1a1a;font-size:22px;">Link Expired</h2>'
           || '<p style="color:#666;font-size:14px;line-height:1.6;">This approval link expired 72 hours after it was sent.<br>Please contact the requester for a new link.</p>'
           || '<p style="color:#aaa;font-size:12px;margin-top:24px;">You may close this tab.</p>'
           || '</div></body></html>');
        RETURN;
    END IF;

    -- ── Valid token — mark USED and record action ─────────────────────────────
    UPDATE RR_APPROVAL_TOKENS
    SET    STATUS    = 'USED',
           USED_DATE = SYSTIMESTAMP
    WHERE  TOKEN_VALUE = v_token;

    -- Record in email replies table so frontend can see it
    INSERT INTO RR_APPROVAL_EMAIL_REPLIES (
        FROM_EMAIL, FROM_NAME, SUBJECT, BODY_TEXT,
        ACTION_DETECTED, REF_NUMBER, REQUEST_ID, STATUS
    ) VALUES (
        v_email, v_name,
        v_action || ': ' || v_ref || ' [via approval link]',
        v_action || ' — clicked approval button in email',
        v_action, v_ref, v_req_id, 'PENDING'
    );

    COMMIT;

    -- Build confirmation page
    v_color := CASE v_action WHEN 'APPROVE' THEN '#16a34a' ELSE '#dc2626' END;
    v_icon  := CASE v_action WHEN 'APPROVE' THEN '&#9989;' ELSE '&#10060;' END;
    v_title := CASE v_action WHEN 'APPROVE' THEN 'Approved!' ELSE 'Rejected' END;
    v_msg   := CASE v_action
                   WHEN 'APPROVE' THEN 'Your approval has been recorded. The requester will be notified.'
                   ELSE 'Your rejection has been recorded. The requester will be notified.'
               END;

    :status_code := 200;
    HTP.P('<!DOCTYPE html><html><head><meta charset="UTF-8">'
       || '<meta name="viewport" content="width=device-width,initial-scale=1">'
       || '<title>' || v_title || '</title></head>'
       || '<body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,sans-serif;'
       || 'display:flex;align-items:center;justify-content:center;min-height:100vh;">');

    HTP.P('<div style="background:#fff;border-radius:12px;padding:48px 40px;text-align:center;'
       || 'max-width:480px;width:90%;box-shadow:0 4px 24px rgba(0,0,0,0.10);">');

    HTP.P('<div style="font-size:56px;margin-bottom:16px;">' || v_icon || '</div>');

    HTP.P('<h2 style="margin:0 0 8px;color:' || v_color || ';font-size:26px;font-weight:700;">'
       || v_title || '</h2>');

    HTP.P('<div style="background:#f8f9fa;border-radius:8px;padding:16px 20px;'
       || 'margin:20px 0;text-align:left;border-left:4px solid ' || v_color || ';">');
    HTP.P('<div style="font-size:12px;color:#888;margin-bottom:4px;text-transform:uppercase;letter-spacing:0.5px;">Reference</div>');
    HTP.P('<div style="font-size:16px;font-weight:700;color:#1a1a1a;">' || NVL(v_ref,'—') || '</div>');
    HTP.P('<div style="font-size:12px;color:#888;margin-top:10px;margin-bottom:4px;text-transform:uppercase;letter-spacing:0.5px;">Actioned by</div>');
    HTP.P('<div style="font-size:14px;color:#333;">' || NVL(v_name, v_email) || '</div>');
    HTP.P('<div style="font-size:12px;color:#888;margin-top:10px;margin-bottom:4px;text-transform:uppercase;letter-spacing:0.5px;">Date &amp; Time</div>');
    HTP.P('<div style="font-size:13px;color:#333;">' || TO_CHAR(SYSDATE,'DD Mon YYYY HH24:MI') || ' (UTC)</div>');
    HTP.P('</div>');

    HTP.P('<p style="color:#555;font-size:14px;line-height:1.6;margin:0 0 24px;">' || v_msg || '</p>');

    HTP.P('<p style="color:#bbb;font-size:12px;margin:0;">You may close this tab.</p>');

    HTP.P('<div style="margin-top:32px;padding-top:20px;border-top:1px solid #f0f0f0;">'
       || '<div style="font-size:10px;color:#ddd;letter-spacing:1px;text-transform:uppercase;">'
       || 'Bumeric Business Solutions — ERP Approval System</div>'
       || '</div>');

    HTP.P('</div></body></html>');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 500;
        HTP.P('<html><body style="font-family:Arial;text-align:center;padding:60px">'
           || '<h2>Error</h2><p>' || APEX_ESCAPE.HTML(SQLERRM) || '</p></body></html>');
END;
]'
    );
    COMMIT;
END;
/
