-- =====================================================
-- AR Invoice DFF (Descriptive Flexfield — Rental Details)
-- Table  : RR_AR_INVOICES_DFF
-- Module : ar  (already defined)
-- Base   : /ar/invoices/:customerTrxId/dff
-- =====================================================

-- =====================================================
-- 1. Table
-- =====================================================
CREATE TABLE RR_AR_INVOICES_DFF (
    -- PK
    DFF_ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- FK to AR Invoice
    CUSTOMER_TRX_ID         NUMBER NOT NULL,

    -- Flex context
    FLEX_CONTEXT            VARCHAR2(100),
    FLEX_CONTEXT_DISPLAY    VARCHAR2(100),

    -- Rental Details segments
    UNIT                    VARCHAR2(100),
    LOCATION                VARCHAR2(240),
    PROPERTY_TYPE           VARCHAR2(100),
    NAME_OF_TENANT          VARCHAR2(360),
    NATIONALITY             VARCHAR2(100),
    OCCUPANT_STATUS         VARCHAR2(100),
    NO_OF_OCCUPANT          NUMBER,
    EJARI                   VARCHAR2(100),
    CONTRACT_START_DATE     DATE,
    CONTRACT_END_DATE       DATE,
    RENT                    NUMBER,
    MODE_OF_PAY             VARCHAR2(50),
    NO_OF_CHEQUES           NUMBER,
    PMGT_FEE                NUMBER,
    CHQS_WITH               VARCHAR2(100),

    -- Extra DFF segments (future-proof)
    ATTRIBUTE1              VARCHAR2(1000),
    ATTRIBUTE2              VARCHAR2(1000),
    ATTRIBUTE3              VARCHAR2(1000),
    ATTRIBUTE4              VARCHAR2(1000),
    ATTRIBUTE5              VARCHAR2(1000),

    -- Audit
    SYNC_DATE               TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_UPDATED_BY         VARCHAR2(240),
    LAST_UPDATE_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT UQ_AR_DFF_TRX UNIQUE (CUSTOMER_TRX_ID)
);

CREATE INDEX IDX_RR_ARDFF_TRX ON RR_AR_INVOICES_DFF (CUSTOMER_TRX_ID);

COMMENT ON TABLE RR_AR_INVOICES_DFF IS 'AR Invoice Descriptive Flexfield — Rental Details context synced from Fusion receivablesInvoiceDFF';

-- =====================================================
-- 2. Template: ar/invoices/:customerTrxId/dff
-- =====================================================
BEGIN
    ORDS.DELETE_TEMPLATE(p_module_name => 'ar', p_pattern => 'invoices/:customerTrxId/dff');
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'ar',
        p_pattern     => 'invoices/:customerTrxId/dff',
        p_comments    => 'AR Invoice DFF — Rental Details'
    );
    COMMIT;
END;
/

-- =====================================================
-- 3. GET /ar/invoices/:customerTrxId/dff
-- =====================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'ar',
        p_pattern        => 'invoices/:customerTrxId/dff',
        p_method         => 'GET',
        p_source_type    => 'json/collection',
        p_items_per_page => 1,
        p_comments       => 'Fetch DFF for a single AR invoice',
        p_source         => '
SELECT
    d.DFF_ID,
    d.CUSTOMER_TRX_ID,
    d.FLEX_CONTEXT,
    d.FLEX_CONTEXT_DISPLAY,
    d.UNIT,
    d.LOCATION,
    d.PROPERTY_TYPE,
    d.NAME_OF_TENANT,
    d.NATIONALITY,
    d.OCCUPANT_STATUS,
    d.NO_OF_OCCUPANT,
    d.EJARI,
    d.CONTRACT_START_DATE,
    d.CONTRACT_END_DATE,
    d.RENT,
    d.MODE_OF_PAY,
    d.NO_OF_CHEQUES,
    d.PMGT_FEE,
    d.CHQS_WITH,
    d.ATTRIBUTE1,
    d.ATTRIBUTE2,
    d.ATTRIBUTE3,
    d.ATTRIBUTE4,
    d.ATTRIBUTE5,
    d.SYNC_DATE,
    d.LAST_UPDATED_BY,
    d.LAST_UPDATE_DATE
FROM RR_AR_INVOICES_DFF d
WHERE d.CUSTOMER_TRX_ID = :customerTrxId'
    );
    COMMIT;
END;
/

-- =====================================================
-- 4. Template: ar/invoices/dff/bulk
-- =====================================================
BEGIN
    ORDS.DELETE_TEMPLATE(p_module_name => 'ar', p_pattern => 'invoices/dff/bulk');
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'ar',
        p_pattern     => 'invoices/dff/bulk',
        p_comments    => 'Bulk upsert AR Invoice DFF records'
    );
    COMMIT;
END;
/

-- =====================================================
-- 5. POST /ar/invoices/dff/bulk
--    Body: { "items": [ { "CustomerTrxId": N, "__FLEX_Context": "...", ... } ] }
-- =====================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'ar',
        p_pattern        => 'invoices/dff/bulk',
        p_method         => 'POST',
        p_source_type    => 'plsql/block',
        p_mimes_allowed  => 'application/json',
        p_comments       => 'Bulk upsert AR Invoice DFF from Fusion receivablesInvoiceDFF',
        p_source         => q'[
DECLARE
    l_body       CLOB;
    l_items      JSON_ARRAY_T;
    l_item       JSON_OBJECT_T;
    l_inserted   NUMBER := 0;
    l_updated    NUMBER := 0;
    l_errors     NUMBER := 0;
    l_error_msgs VARCHAR2(4000) := '';
    v_dest_off   INTEGER := 1;
    v_src_off    INTEGER := 1;
    v_lang_ctx   INTEGER := DBMS_LOB.DEFAULT_LANG_CTX;
    v_warning    INTEGER;

    FUNCTION safe_str(p_obj JSON_OBJECT_T, p_key VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        IF p_obj.has(p_key) AND NOT p_obj.get(p_key).is_null THEN
            RETURN p_obj.get_string(p_key);
        END IF;
        RETURN NULL;
    END;

    FUNCTION safe_num(p_obj JSON_OBJECT_T, p_key VARCHAR2) RETURN NUMBER IS
    BEGIN
        IF p_obj.has(p_key) AND NOT p_obj.get(p_key).is_null THEN
            RETURN p_obj.get_number(p_key);
        END IF;
        RETURN NULL;
    END;

    FUNCTION safe_date(p_obj JSON_OBJECT_T, p_key VARCHAR2) RETURN DATE IS
        v_str VARCHAR2(30);
    BEGIN
        IF p_obj.has(p_key) AND NOT p_obj.get(p_key).is_null THEN
            v_str := p_obj.get_string(p_key);
            IF v_str IS NOT NULL THEN
                RETURN TO_DATE(SUBSTR(v_str, 1, 10), 'YYYY-MM-DD');
            END IF;
        END IF;
        RETURN NULL;
    END;

BEGIN
    DBMS_LOB.CREATETEMPORARY(l_body, TRUE);
    DBMS_LOB.CONVERTTOCLOB(
        l_body, :body, DBMS_LOB.LOBMAXSIZE,
        v_dest_off, v_src_off,
        NLS_CHARSET_ID('AL32UTF8'), v_lang_ctx, v_warning
    );

    l_items := JSON_ARRAY_T(JSON_OBJECT_T.PARSE(l_body).get_array('items'));

    FOR i IN 0 .. l_items.get_size() - 1 LOOP
        BEGIN
            l_item := JSON_OBJECT_T(l_items.get(i));

            MERGE INTO RR_AR_INVOICES_DFF d
            USING (SELECT safe_num(l_item, 'CustomerTrxId') AS trx_id FROM DUAL) s
            ON (d.CUSTOMER_TRX_ID = s.trx_id)
            WHEN MATCHED THEN UPDATE SET
                FLEX_CONTEXT         = safe_str(l_item, '__FLEX_Context'),
                FLEX_CONTEXT_DISPLAY = safe_str(l_item, '__FLEX_Context_DisplayValue'),
                UNIT                 = safe_str(l_item, 'unit'),
                LOCATION             = safe_str(l_item, 'location'),
                PROPERTY_TYPE        = safe_str(l_item, 'propertyType'),
                NAME_OF_TENANT       = safe_str(l_item, 'nameOfTenant'),
                NATIONALITY          = safe_str(l_item, 'nationality'),
                OCCUPANT_STATUS      = safe_str(l_item, 'occupantStatus'),
                NO_OF_OCCUPANT       = safe_num(l_item, 'noOfOccupant'),
                EJARI                = safe_str(l_item, 'ejari'),
                CONTRACT_START_DATE  = safe_date(l_item, 'contractStartDate'),
                CONTRACT_END_DATE    = safe_date(l_item, 'contractEndDate'),
                RENT                 = safe_num(l_item, 'rent'),
                MODE_OF_PAY          = safe_str(l_item, 'modeOfPay'),
                NO_OF_CHEQUES        = safe_num(l_item, 'noOfChques'),
                PMGT_FEE             = safe_num(l_item, 'pmgtFee'),
                CHQS_WITH            = safe_str(l_item, 'chqsWith'),
                ATTRIBUTE1           = safe_str(l_item, 'attribute1'),
                ATTRIBUTE2           = safe_str(l_item, 'attribute2'),
                ATTRIBUTE3           = safe_str(l_item, 'attribute3'),
                ATTRIBUTE4           = safe_str(l_item, 'attribute4'),
                ATTRIBUTE5           = safe_str(l_item, 'attribute5'),
                LAST_UPDATED_BY      = USER,
                LAST_UPDATE_DATE     = SYSTIMESTAMP,
                SYNC_DATE            = SYSTIMESTAMP
            WHEN NOT MATCHED THEN INSERT (
                CUSTOMER_TRX_ID, FLEX_CONTEXT, FLEX_CONTEXT_DISPLAY,
                UNIT, LOCATION, PROPERTY_TYPE, NAME_OF_TENANT, NATIONALITY,
                OCCUPANT_STATUS, NO_OF_OCCUPANT, EJARI,
                CONTRACT_START_DATE, CONTRACT_END_DATE,
                RENT, MODE_OF_PAY, NO_OF_CHEQUES, PMGT_FEE, CHQS_WITH,
                ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5,
                LAST_UPDATED_BY, LAST_UPDATE_DATE, SYNC_DATE
            ) VALUES (
                safe_num(l_item, 'CustomerTrxId'),
                safe_str(l_item, '__FLEX_Context'),
                safe_str(l_item, '__FLEX_Context_DisplayValue'),
                safe_str(l_item, 'unit'),
                safe_str(l_item, 'location'),
                safe_str(l_item, 'propertyType'),
                safe_str(l_item, 'nameOfTenant'),
                safe_str(l_item, 'nationality'),
                safe_str(l_item, 'occupantStatus'),
                safe_num(l_item, 'noOfOccupant'),
                safe_str(l_item, 'ejari'),
                safe_date(l_item, 'contractStartDate'),
                safe_date(l_item, 'contractEndDate'),
                safe_num(l_item, 'rent'),
                safe_str(l_item, 'modeOfPay'),
                safe_num(l_item, 'noOfChques'),
                safe_num(l_item, 'pmgtFee'),
                safe_str(l_item, 'chqsWith'),
                safe_str(l_item, 'attribute1'),
                safe_str(l_item, 'attribute2'),
                safe_str(l_item, 'attribute3'),
                safe_str(l_item, 'attribute4'),
                safe_str(l_item, 'attribute5'),
                USER, SYSTIMESTAMP, SYSTIMESTAMP
            );

            IF SQL%ROWCOUNT > 0 THEN
                -- MERGE doesn't distinguish insert vs update via SQL%ROWCOUNT alone;
                -- track by checking if row existed before (approximation: count updated rows separately)
                l_inserted := l_inserted + 1;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            l_errors := l_errors + 1;
            IF LENGTH(l_error_msgs) < 3500 THEN
                l_error_msgs := l_error_msgs || 'Row ' || i || ': ' || SUBSTR(SQLERRM,1,200) || '; ';
            END IF;
        END;
    END LOOP;

    COMMIT;
    :status_code := CASE WHEN l_errors = 0 THEN 201 ELSE 207 END;
    HTP.P('{"status":"' || CASE WHEN l_errors = 0 THEN 'SUCCESS' ELSE 'PARTIAL' END || '"' ||
          ',"inserted":' || l_inserted ||
          ',"updated":'  || l_updated  ||
          ',"errors":'   || l_errors   ||
          CASE WHEN l_error_msgs IS NOT NULL
               THEN ',"errorDetail":"' || REPLACE(l_error_msgs, '"', '\"') || '"'
               ELSE '' END || '}');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.P('{"status":"ERROR","message":"' || REPLACE(SQLERRM, '"', '\"') || '"}');
END;]'
    );
    COMMIT;
END;
/

-- =====================================================
-- ENDPOINTS SUMMARY
-- =====================================================
-- GET  {base}/ar/invoices/:customerTrxId/dff    Fetch DFF for one invoice
-- POST {base}/ar/invoices/dff/bulk              Bulk upsert DFF records
-- =====================================================
