-- =====================================================
-- AR Receipts Attachments
-- Table  : RR_AR_RECEIPTS_ATTACHMENTS
-- Module : ar  (already defined)
-- Base   : /ar/receipts/:receiptId/attachments
-- =====================================================

-- =====================================================
-- 1. Table
-- =====================================================
CREATE TABLE RR_AR_RECEIPTS_ATTACHMENTS (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STANDARD_RECEIPT_ID NUMBER NOT NULL,
    FILE_NAME           VARCHAR2(500) NOT NULL,
    FILE_TYPE           VARCHAR2(100),
    FILE_SIZE           NUMBER,
    FILE_CONTENT        CLOB,   -- Base64-encoded content
    CREATED_BY          VARCHAR2(150),
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_AR_RCPT_ATT FOREIGN KEY (STANDARD_RECEIPT_ID)
        REFERENCES RR_AR_RECEIPTS(STANDARD_RECEIPT_ID)
);

CREATE INDEX IDX_RR_ARATT_RCPT ON RR_AR_RECEIPTS_ATTACHMENTS(STANDARD_RECEIPT_ID);

-- =====================================================
-- 2. Template: ar/receipts/:receiptId/attachments
-- =====================================================
BEGIN
    ORDS.DELETE_TEMPLATE(p_module_name => 'ar', p_pattern => 'receipts/:receiptId/attachments');
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'ar',
        p_pattern     => 'receipts/:receiptId/attachments',
        p_comments    => 'Attachments for an AR receipt'
    );
    COMMIT;
END;
/

-- =====================================================
-- 3. GET /ar/receipts/:receiptId/attachments
-- =====================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'ar',
        p_pattern        => 'receipts/:receiptId/attachments',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'List attachments for an AR receipt (no content)',
        p_source         => q'[
DECLARE
    l_json  CLOB    := '{"items":[';
    l_first BOOLEAN := TRUE;
BEGIN
    FOR r IN (
        SELECT ID, FILE_NAME, FILE_TYPE, FILE_SIZE, CREATED_BY,
               TO_CHAR(CREATED_DATE, 'YYYY-MM-DD"T"HH24:MI:SS') AS CREATED_DATE
          FROM RR_AR_RECEIPTS_ATTACHMENTS
         WHERE STANDARD_RECEIPT_ID = :receiptId
         ORDER BY CREATED_DATE DESC
    ) LOOP
        IF NOT l_first THEN l_json := l_json || ','; END IF;
        l_first := FALSE;
        l_json := l_json
            || '{"id":'         || r.ID
            || ',"fileName":'   || APEX_JSON.STRINGIFY(r.FILE_NAME)
            || ',"fileType":'   || APEX_JSON.STRINGIFY(NVL(r.FILE_TYPE,''))
            || ',"fileSize":'   || NVL(TO_CHAR(r.FILE_SIZE),'null')
            || ',"createdBy":'  || APEX_JSON.STRINGIFY(NVL(r.CREATED_BY,''))
            || ',"createdDate":' || APEX_JSON.STRINGIFY(NVL(r.CREATED_DATE,''))
            || '}';
    END LOOP;
    l_json := l_json || ']}';
    HTP.P(l_json);
EXCEPTION WHEN OTHERS THEN
    HTP.P('{"items":[],"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- =====================================================
-- 4. POST /ar/receipts/:receiptId/attachments
--    Body: { "fileName":"...", "fileType":"...", "fileSize":N, "content":"base64..." }
-- =====================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'ar',
        p_pattern        => 'receipts/:receiptId/attachments',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_mimes_allowed  => 'application/json',
        p_items_per_page => 0,
        p_comments       => 'Upload attachment for an AR receipt — JSON body',
        p_source         => q'[
DECLARE
    v_file_name  VARCHAR2(500);
    v_file_type  VARCHAR2(100);
    v_file_size  NUMBER;
    v_content    CLOB;
    v_new_id     NUMBER;
    v_body       CLOB;
    v_dest_off   INTEGER := 1;
    v_src_off    INTEGER := 1;
    v_lang_ctx   INTEGER := DBMS_LOB.DEFAULT_LANG_CTX;
    v_warning    INTEGER;
BEGIN
    DBMS_LOB.CREATETEMPORARY(v_body, TRUE);
    DBMS_LOB.CONVERTTOCLOB(
        v_body, :body, DBMS_LOB.LOBMAXSIZE,
        v_dest_off, v_src_off,
        NLS_CHARSET_ID('AL32UTF8'), v_lang_ctx, v_warning
    );

    APEX_JSON.PARSE(v_body);
    v_file_name := APEX_JSON.GET_VARCHAR2(p_path => 'fileName');
    v_file_type := APEX_JSON.GET_VARCHAR2(p_path => 'fileType');
    v_file_size := APEX_JSON.GET_NUMBER(p_path  => 'fileSize');
    v_content   := APEX_JSON.GET_CLOB(p_path    => 'content');

    INSERT INTO RR_AR_RECEIPTS_ATTACHMENTS
        (STANDARD_RECEIPT_ID, FILE_NAME, FILE_TYPE, FILE_SIZE, FILE_CONTENT, CREATED_BY)
    VALUES
        (:receiptId, v_file_name, v_file_type, v_file_size, v_content, USER)
    RETURNING ID INTO v_new_id;
    COMMIT;

    :status_code := 201;
    HTP.P('{"status":"success","id":' || v_new_id
        || ',"fileName":'  || APEX_JSON.STRINGIFY(v_file_name)
        || ',"receiptId":' || TO_CHAR(:receiptId)
        || '}');
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- =====================================================
-- 5. Template: ar/receipts/:receiptId/attachments/:attachmentId
-- =====================================================
BEGIN
    ORDS.DELETE_TEMPLATE(p_module_name => 'ar', p_pattern => 'receipts/:receiptId/attachments/:attachmentId');
    COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    ORDS.DEFINE_TEMPLATE(
        p_module_name => 'ar',
        p_pattern     => 'receipts/:receiptId/attachments/:attachmentId',
        p_comments    => 'Single AR receipt attachment'
    );
    COMMIT;
END;
/

-- =====================================================
-- 6. GET /ar/receipts/:receiptId/attachments/:attachmentId
--    Returns full content for preview/download
-- =====================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'ar',
        p_pattern        => 'receipts/:receiptId/attachments/:attachmentId',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'Fetch single attachment with base64 content',
        p_source         => q'[
DECLARE
    r RR_AR_RECEIPTS_ATTACHMENTS%ROWTYPE;
BEGIN
    SELECT * INTO r
      FROM RR_AR_RECEIPTS_ATTACHMENTS
     WHERE ID = :attachmentId
       AND STANDARD_RECEIPT_ID = :receiptId;

    HTP.P('{"id":'        || r.ID
        || ',"fileName":' || APEX_JSON.STRINGIFY(r.FILE_NAME)
        || ',"fileType":' || APEX_JSON.STRINGIFY(NVL(r.FILE_TYPE,''))
        || ',"fileSize":' || NVL(TO_CHAR(r.FILE_SIZE),'null')
        || ',"content":'  || APEX_JSON.STRINGIFY(NVL(r.FILE_CONTENT,''))
        || '}');
EXCEPTION WHEN NO_DATA_FOUND THEN
    :status_code := 404;
    HTP.P('{"error":"Not found"}');
WHEN OTHERS THEN
    :status_code := 500;
    HTP.P('{"error":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- =====================================================
-- 7. DELETE /ar/receipts/:receiptId/attachments/:attachmentId
-- =====================================================
BEGIN
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'ar',
        p_pattern        => 'receipts/:receiptId/attachments/:attachmentId',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_items_per_page => 0,
        p_comments       => 'Delete an AR receipt attachment',
        p_source         => q'[
BEGIN
    DELETE FROM RR_AR_RECEIPTS_ATTACHMENTS
     WHERE ID = :attachmentId
       AND STANDARD_RECEIPT_ID = :receiptId;

    IF SQL%ROWCOUNT = 0 THEN
        :status_code := 404;
        HTP.P('{"status":"error","message":"Attachment not found"}');
    ELSE
        COMMIT;
        :status_code := 200;
        HTP.P('{"status":"success"}');
    END IF;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    :status_code := 500;
    HTP.P('{"status":"error","message":' || APEX_JSON.STRINGIFY(SQLERRM) || '}');
END;
]'
    );
    COMMIT;
END;
/

-- =====================================================
-- ENDPOINTS SUMMARY
-- =====================================================
-- GET    {base}/ar/receipts/:receiptId/attachments                 List attachments (no content)
-- POST   {base}/ar/receipts/:receiptId/attachments                 Upload attachment (JSON body)
-- GET    {base}/ar/receipts/:receiptId/attachments/:attachmentId   Fetch with content
-- DELETE {base}/ar/receipts/:receiptId/attachments/:attachmentId   Delete attachment
-- =====================================================
