-- =============================================================================
-- RR_AR_REVENUE.SQL   — Revenue Recognition (Receivables)
--
-- Contract source table (already exists):  RR_AR_REVENUE_CONTRACT
--   (ID, TRX_NUMBER, UNIT, LOCATION, TENANT, CONTRACT_START_DATE,
--    CONTRACT_END_DATE, STATUS, RENT_TOTAL)
--
-- New schedules table (created below): RR_AR_REVENUE_SCHDULES
--
-- Webservices:
--   GET  reerp/ar/revenue-contracts                 -> list contracts
--   POST reerp/ar/revenue-schedules/generate        -> { contractIds:[...] }
--   GET  reerp/ar/revenue-schedules?contractId=&trxNumber=
--
-- HOW TO RUN: APEX SQL Workshop -> SQL Commands -> run the whole block.
-- =============================================================================

-- ── New table for the generated monthly revenue schedules ────────────────────
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'RR_AR_REVENUE_SCHDULES';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE RR_AR_REVENUE_SCHDULES (
        ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 INCREMENT BY 1 START WITH 1 NOT NULL,
        CONTRACT_ID     NUMBER,
        TRX_NUMBER      NUMBER,
        UNIT            VARCHAR2(255),
        LOCATION        VARCHAR2(255),
        TENANT          VARCHAR2(255),
        SCHEDULE_NUM    NUMBER,
        PERIOD_NAME     VARCHAR2(20),
        PERIOD_DATE     DATE,
        AMOUNT          NUMBER,
        INVOICE_NUMBER  VARCHAR2(100),
        STATUS          VARCHAR2(30),
        ACCOUNT_STATUS  VARCHAR2(30),
        CREATION_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATED_BY      VARCHAR2(240),
        PRIMARY KEY (ID)
      )
    ]';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_RR_AR_REV_SCH_CONTRACT ON RR_AR_REVENUE_SCHDULES(CONTRACT_ID)';
  END IF;
END;
/

CREATE OR REPLACE PACKAGE RR_AR_REVENUE_PKG AS
  -- Monthly split: RENT_TOTAL / inclusive-month-count, equal per period.
  PROCEDURE GENERATE_SCHEDULES(p_body IN CLOB, p_status OUT NUMBER, p_result OUT CLOB);
  -- Daily (prorated) split: each period = daily rate * days of that period that
  -- fall inside [start,end]. Handles partial first/last months correctly.
  PROCEDURE GENERATE_SCHEDULES_DAILY(p_body IN CLOB, p_status OUT NUMBER, p_result OUT CLOB);
END RR_AR_REVENUE_PKG;
/

CREATE OR REPLACE PACKAGE BODY RR_AR_REVENUE_PKG AS

  -- Parse a VARCHAR2 date stored in the contract table (several formats seen).
  FUNCTION to_dt(p_s VARCHAR2) RETURN DATE IS
    v DATE;
  BEGIN
    IF p_s IS NULL THEN RETURN NULL; END IF;
    BEGIN v := TO_DATE(SUBSTR(p_s,1,10), 'YYYY-MM-DD'); RETURN v; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN v := TO_DATE(p_s, 'DD-MON-YYYY');              RETURN v; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN v := TO_DATE(p_s, 'DD-MON-RR');                RETURN v; EXCEPTION WHEN OTHERS THEN NULL; END;
    -- Contract dates are entered US-style (MM/DD/YYYY), matching the frontend's
    -- parseFlexDate. Try MM/DD/YYYY BEFORE DD/MM/YYYY: for an ambiguous value
    -- like "10/1/2025" (Oct 1) DD/MM would wrongly parse it as Jan 10, which
    -- stretched the schedule span (e.g. 12 months read as 21).
    BEGIN v := TO_DATE(p_s, 'MM/DD/YYYY');               RETURN v; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN v := TO_DATE(p_s, 'DD/MM/YYYY');               RETURN v; EXCEPTION WHEN OTHERS THEN NULL; END;
    RETURN NULL;
  END to_dt;

  PROCEDURE GENERATE_SCHEDULES(p_body IN CLOB, p_status OUT NUMBER, p_result OUT CLOB) IS
    v_cnt        NUMBER;
    v_by         VARCHAR2(240);
    v_id         NUMBER;
    v_sdt        VARCHAR2(50);
    v_edt        VARCHAR2(50);
    v_start      DATE;
    v_end        DATE;
    v_months     NUMBER;
    v_total      NUMBER;
    v_monthly    NUMBER;
    v_running    NUMBER;
    v_amt        NUMBER;
    v_pdate      DATE;
    v_contracts  NUMBER := 0;
    v_rows       NUMBER := 0;
  BEGIN
    APEX_JSON.PARSE(p_body);
    v_by  := NVL(APEX_JSON.GET_VARCHAR2(p_path => 'createdBy'), 'REACTERP');
    v_cnt := NVL(APEX_JSON.GET_COUNT(p_path => 'contractIds'), 0);
    IF v_cnt = 0 THEN
      p_status := 400; p_result := '{"success":false,"error":"contractIds is required"}'; RETURN;
    END IF;

    FOR i IN 1 .. v_cnt LOOP
      v_id := APEX_JSON.GET_NUMBER(p_path => 'contractIds[%d]', p0 => i);

      BEGIN
        -- Select raw VARCHAR dates, then convert in PL/SQL (to_dt is a private
        -- package function and cannot be used inside a SQL statement).
        SELECT CONTRACT_START_DATE, CONTRACT_END_DATE, NVL(RENT_TOTAL,0)
          INTO v_sdt, v_edt, v_total
          FROM RR_AR_REVENUE_CONTRACT
         WHERE ID = v_id;
      EXCEPTION WHEN NO_DATA_FOUND THEN
        CONTINUE;
      END;

      v_start := to_dt(v_sdt);
      v_end   := to_dt(v_edt);
      IF v_start IS NULL OR v_end IS NULL THEN CONTINUE; END IF;

      -- Inclusive month count (Jan 1 – Dec 31 = 12).
      v_months := GREATEST(1, CEIL(MONTHS_BETWEEN(v_end + 1, v_start)));
      v_monthly := ROUND(v_total / v_months, 2);
      v_running := 0;

      -- Regenerate: clear any previous schedule for this contract.
      DELETE FROM RR_AR_REVENUE_SCHDULES WHERE CONTRACT_ID = v_id;

      FOR m IN 1 .. v_months LOOP
        v_pdate := ADD_MONTHS(TRUNC(v_start, 'MM'), m - 1);
        -- last month absorbs the rounding remainder so the sum ties to RENT_TOTAL
        IF m = v_months THEN v_amt := v_total - v_running;
        ELSE                 v_amt := v_monthly; v_running := v_running + v_monthly;
        END IF;

        INSERT INTO RR_AR_REVENUE_SCHDULES (
          CONTRACT_ID, TRX_NUMBER, UNIT, LOCATION, TENANT,
          SCHEDULE_NUM, PERIOD_NAME, PERIOD_DATE, AMOUNT,
          INVOICE_NUMBER, STATUS, ACCOUNT_STATUS, CREATION_DATE, CREATED_BY
        )
        SELECT c.ID, c.TRX_NUMBER, c.UNIT, c.LOCATION, c.TENANT,
               m, TO_CHAR(v_pdate, 'Mon-RR'), v_pdate, v_amt,
               NULL, 'PENDING', 'UNACCOUNTED', SYSTIMESTAMP, v_by
          FROM RR_AR_REVENUE_CONTRACT c
         WHERE c.ID = v_id;
        v_rows := v_rows + 1;
      END LOOP;

      v_contracts := v_contracts + 1;
    END LOOP;

    COMMIT;
    p_status := 200;
    p_result := '{"success":true,"contracts":' || v_contracts || ',"schedules":' || v_rows || '}';
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_status := 500;
      p_result := '{"success":false,"error":"' || REPLACE(SQLERRM,'"','\"') || '"}';
  END GENERATE_SCHEDULES;

  -- Day-wise (prorated) revenue schedules. The contract's RENT_TOTAL is spread
  -- over the inclusive day span [start,end]; each calendar month's schedule gets
  -- daily_rate * (days of that month that fall inside the span), so partial
  -- first/last months are prorated. The final period absorbs the rounding
  -- remainder so the schedule sum ties exactly to RENT_TOTAL.
  PROCEDURE GENERATE_SCHEDULES_DAILY(p_body IN CLOB, p_status OUT NUMBER, p_result OUT CLOB) IS
    v_cnt        NUMBER;
    v_by         VARCHAR2(240);
    v_id         NUMBER;
    v_sdt        VARCHAR2(50);
    v_edt        VARCHAR2(50);
    v_start      DATE;
    v_end        DATE;
    v_total      NUMBER;
    v_days       NUMBER;
    v_daily      NUMBER;
    v_running    NUMBER;
    v_amt        NUMBER;
    v_pdate      DATE;   -- first-of-month bucket (period_date)
    v_seg_start  DATE;
    v_seg_end    DATE;
    v_seg_days   NUMBER;
    v_seq        NUMBER;
    v_contracts  NUMBER := 0;
    v_rows       NUMBER := 0;
  BEGIN
    APEX_JSON.PARSE(p_body);
    v_by  := NVL(APEX_JSON.GET_VARCHAR2(p_path => 'createdBy'), 'REACTERP');
    v_cnt := NVL(APEX_JSON.GET_COUNT(p_path => 'contractIds'), 0);
    IF v_cnt = 0 THEN
      p_status := 400; p_result := '{"success":false,"error":"contractIds is required"}'; RETURN;
    END IF;

    FOR i IN 1 .. v_cnt LOOP
      v_id := APEX_JSON.GET_NUMBER(p_path => 'contractIds[%d]', p0 => i);

      BEGIN
        SELECT CONTRACT_START_DATE, CONTRACT_END_DATE, NVL(RENT_TOTAL,0)
          INTO v_sdt, v_edt, v_total
          FROM RR_AR_REVENUE_CONTRACT
         WHERE ID = v_id;
      EXCEPTION WHEN NO_DATA_FOUND THEN
        CONTINUE;
      END;

      v_start := to_dt(v_sdt);
      v_end   := to_dt(v_edt);
      IF v_start IS NULL OR v_end IS NULL OR v_end < v_start THEN CONTINUE; END IF;

      -- Inclusive day span and daily rate.
      v_days  := (v_end - v_start) + 1;
      v_daily := v_total / v_days;
      v_running := 0;
      v_seq := 0;

      -- Regenerate: clear any previous schedule for this contract.
      DELETE FROM RR_AR_REVENUE_SCHDULES WHERE CONTRACT_ID = v_id;

      -- Walk each month bucket from the start month to the end month.
      v_pdate := TRUNC(v_start, 'MM');
      WHILE v_pdate <= v_end LOOP
        v_seq := v_seq + 1;
        v_seg_start := GREATEST(v_pdate, v_start);
        v_seg_end   := LEAST(LAST_DAY(v_pdate), v_end);
        v_seg_days  := (v_seg_end - v_seg_start) + 1;

        IF v_end <= LAST_DAY(v_pdate) THEN
          -- final period → absorb the remainder so the sum ties to RENT_TOTAL
          v_amt := ROUND(v_total - v_running, 2);
        ELSE
          v_amt := ROUND(v_daily * v_seg_days, 2);
          v_running := v_running + v_amt;
        END IF;

        INSERT INTO RR_AR_REVENUE_SCHDULES (
          CONTRACT_ID, TRX_NUMBER, UNIT, LOCATION, TENANT,
          SCHEDULE_NUM, PERIOD_NAME, PERIOD_DATE, AMOUNT,
          INVOICE_NUMBER, STATUS, ACCOUNT_STATUS, CREATION_DATE, CREATED_BY
        )
        SELECT c.ID, c.TRX_NUMBER, c.UNIT, c.LOCATION, c.TENANT,
               v_seq, TO_CHAR(v_pdate, 'Mon-RR'), v_pdate, v_amt,
               NULL, 'PENDING', 'UNACCOUNTED', SYSTIMESTAMP, v_by
          FROM RR_AR_REVENUE_CONTRACT c
         WHERE c.ID = v_id;
        v_rows := v_rows + 1;

        v_pdate := ADD_MONTHS(v_pdate, 1);
      END LOOP;

      v_contracts := v_contracts + 1;
    END LOOP;

    COMMIT;
    p_status := 200;
    p_result := '{"success":true,"contracts":' || v_contracts || ',"schedules":' || v_rows || '}';
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_status := 500;
      p_result := '{"success":false,"error":"' || REPLACE(SQLERRM,'"','\"') || '"}';
  END GENERATE_SCHEDULES_DAILY;

END RR_AR_REVENUE_PKG;
/

-- ── GET reerp/ar/revenue-contracts ───────────────────────────────────────────
BEGIN ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'ar/revenue-contracts', p_method => 'GET'); COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/revenue-contracts', p_priority => 0, p_etag_type => 'HASH');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name    => 'reerp',
    p_pattern        => 'ar/revenue-contracts',
    p_method         => 'GET',
    p_source_type    => 'json/collection',
    p_items_per_page => 0,
    p_source         => q'[
SELECT ID              AS "id",
       TRX_NUMBER      AS "trxNumber",
       UNIT            AS "unit",
       LOCATION        AS "location",
       TENANT          AS "tenant",
       CONTRACT_START_DATE AS "contractStartDate",
       CONTRACT_END_DATE   AS "contractEndDate",
       STATUS          AS "status",
       RENT_TOTAL      AS "rentTotal",
       (SELECT COUNT(*) FROM RR_AR_REVENUE_SCHDULES s WHERE s.CONTRACT_ID = c.ID) AS "scheduleCount"
FROM RR_AR_REVENUE_CONTRACT c
ORDER BY TRX_NUMBER, ID
]'
  );
  COMMIT;
END;
/

-- ── POST reerp/ar/revenue-schedules/generate ─────────────────────────────────
BEGIN ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'ar/revenue-schedules/generate', p_method => 'POST'); COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/revenue-schedules/generate', p_priority => 0, p_etag_type => 'HASH');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name    => 'reerp',
    p_pattern        => 'ar/revenue-schedules/generate',
    p_method         => 'POST',
    p_source_type    => 'plsql/block',
    p_items_per_page => 0,
    p_mimes_allowed  => 'application/json',
    p_source         => q'[
DECLARE
  v_status NUMBER; v_result CLOB;
BEGIN
  RR_AR_REVENUE_PKG.GENERATE_SCHEDULES(:body_text, v_status, v_result);
  :status_code := v_status;
  HTP.P(v_result);
END;
]'
  );
  COMMIT;
END;
/

-- ── POST reerp/ar/revenue-schedules/generate-daily (day-wise proration) ──────
BEGIN ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'ar/revenue-schedules/generate-daily', p_method => 'POST'); COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/revenue-schedules/generate-daily', p_priority => 0, p_etag_type => 'HASH');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name    => 'reerp',
    p_pattern        => 'ar/revenue-schedules/generate-daily',
    p_method         => 'POST',
    p_source_type    => 'plsql/block',
    p_items_per_page => 0,
    p_mimes_allowed  => 'application/json',
    p_source         => q'[
DECLARE
  v_status NUMBER; v_result CLOB;
BEGIN
  RR_AR_REVENUE_PKG.GENERATE_SCHEDULES_DAILY(:body_text, v_status, v_result);
  :status_code := v_status;
  HTP.P(v_result);
END;
]'
  );
  COMMIT;
END;
/

-- ── GET reerp/ar/revenue-schedules ───────────────────────────────────────────
BEGIN ORDS.DELETE_HANDLER(p_module_name => 'reerp', p_pattern => 'ar/revenue-schedules', p_method => 'GET'); COMMIT; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  ORDS.DEFINE_TEMPLATE(p_module_name => 'reerp', p_pattern => 'ar/revenue-schedules', p_priority => 0, p_etag_type => 'HASH');
  COMMIT;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  ORDS.DEFINE_HANDLER(
    p_module_name    => 'reerp',
    p_pattern        => 'ar/revenue-schedules',
    p_method         => 'GET',
    p_source_type    => 'json/collection',
    p_items_per_page => 0,
    p_source         => q'[
SELECT s.ID              AS "id",
       s.CONTRACT_ID     AS "contractId",
       s.TRX_NUMBER      AS "trxNumber",
       s.UNIT            AS "unit",
       s.LOCATION        AS "location",
       s.TENANT          AS "tenant",
       s.SCHEDULE_NUM    AS "scheduleNum",
       s.PERIOD_NAME     AS "periodName",
       TO_CHAR(s.PERIOD_DATE, 'YYYY-MM-DD') AS "periodDate",
       s.AMOUNT          AS "amount",
       s.INVOICE_NUMBER  AS "invoiceNumber",
       s.STATUS          AS "status",
       s.ACCOUNT_STATUS  AS "accountStatus"
FROM RR_AR_REVENUE_SCHDULES s
WHERE (:contractId IS NULL OR s.CONTRACT_ID = :contractId)
  AND (:trxNumber  IS NULL OR s.TRX_NUMBER  = :trxNumber)
ORDER BY s.TRX_NUMBER, s.CONTRACT_ID, s.SCHEDULE_NUM
]'
  );
  COMMIT;
END;
/

-- ── Verify the package compiled (returns no rows on success) ─────────────────
ALTER PACKAGE RR_AR_REVENUE_PKG COMPILE BODY;
SELECT name, type, line, position, text FROM USER_ERRORS
 WHERE name = 'RR_AR_REVENUE_PKG' ORDER BY sequence;
