-- Table: RR_RAW_CUSTOMER_SITE_ACTIVITIES
-- Stores synced data from Oracle Fusion receivablesCustomerAccountSiteActivities

CREATE TABLE RR_RAW_CUSTOMER_SITE_ACTIVITIES (
  ID                              NUMBER GENERATED ALWAYS AS IDENTITY,
  BILL_TO_SITE_USE_ID             NUMBER             NOT NULL,
  BILL_TO_SITE_NUMBER             VARCHAR2(100),
  BILL_TO_SITE_ADDRESS            VARCHAR2(500),
  ACCOUNT_NUMBER                  VARCHAR2(100),
  CUSTOMER_NAME                   VARCHAR2(500),
  TAX_REGISTRATION_NUMBER         VARCHAR2(100),
  TOTAL_OPEN_RECEIVABLES_FOR_SITE NUMBER,
  TOTAL_TRANSACTIONS_DUE_FOR_SITE NUMBER,
  SYNC_DATE                       DATE DEFAULT SYSDATE,
  CONSTRAINT RR_RAW_CUST_SITE_ACT_PK PRIMARY KEY (ID),
  CONSTRAINT RR_RAW_CUST_SITE_ACT_UQ UNIQUE (BILL_TO_SITE_USE_ID)
);

CREATE INDEX RR_RAW_CUST_SITE_ACT_CN_IDX ON RR_RAW_CUSTOMER_SITE_ACTIVITIES (CUSTOMER_NAME);
CREATE INDEX RR_RAW_CUST_SITE_ACT_AN_IDX ON RR_RAW_CUSTOMER_SITE_ACTIVITIES (ACCOUNT_NUMBER);
